using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Threading;using KianaPet;
class MusicReactionTests {
 static readonly List<string> checks=new List<string>();static void Check(bool value,string name){if(!value)throw new Exception(name);checks.Add(name);}static object Field(object o,string n){return o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}static object Call(object o,string n,params object[] a){return o.GetType().GetMethod(n,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(o,a);}static void Set(object o,string n,object v){o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).SetValue(o,v);}
 static void Save(BitmapSource bitmap,string name){var e=new PngBitmapEncoder();e.Frames.Add(BitmapFrame.Create(bitmap));using(var f=File.Create(Path.Combine(Store.Root,name+".png")))e.Save(f);}
 static BitmapImage Read(string path){var b=new BitmapImage();b.BeginInit();b.CacheOption=BitmapCacheOption.OnLoad;b.UriSource=new Uri(path);b.EndInit();b.Freeze();return b;}
 static void ContactSheet(){string[] skins={"kiana-winter-wish-round","kiana-fiery-wishing-star-round","time-runner-kiana-round"};var visual=new DrawingVisual();using(var dc=visual.RenderOpen()){dc.DrawRectangle(Brushes.White,null,new Rect(0,0,768,624));for(int row=0;row<3;row++){var atlas=Read(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets",skins[row]+".png"));dc.DrawImage(new CroppedBitmap(atlas,new Int32Rect(0,0,192,208)),new Rect(0,row*208,192,208));var frames=MusicSprites.Load(skins[row]);for(int col=1;col<4;col++)dc.DrawImage(frames[(col-1)*2],new Rect(col*192,row*208,192,208));}}var output=new RenderTargetBitmap(1536,1248,192,192,PixelFormats.Pbgra32);output.Render(visual);Save(output,"music-actions-comparison");}
 [STAThread]static int Main(string[] args){Store.Root=args[0];Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false,NoticeSound=false});var app=new Application{ShutdownMode=ShutdownMode.OnLastWindowClose};var pet=new PetWindow(true);bool passed=false;
 pet.Loaded+=async delegate{try{await Task.Delay(1100);((DispatcherTimer)Field(pet,"animation")).Stop();var w=app.Windows.OfType<SettingsWindow>().Single();
 var config=new Config();Check(config.MusicReactionMode=="quiet"&&config.MusicChorusEnabled,"默认安静听歌且副歌查询可关闭");var ranges=ChorusLibrary.Parse("{\"code\":200,\"chorus\":[{\"id\":123,\"startTime\":30000,\"endTime\":60000},{\"id\":999,\"startTime\":1,\"endTime\":2}]}","123");Check(ranges.Length==1&&ranges[0].Start==30&&ranges[0].End==60,"解析实测格式并过滤其他歌曲与毫秒单位");Check(ChorusLibrary.Parse("{\"code\":200,\"data\":[{\"id\":123,\"startTime\":-1,\"endTime\":60000}]}","123").Length==0,"拒绝无效副歌区间");bool rejected=false;try{ChorusLibrary.Parse("{\"code\":500}","123");}catch{rejected=true;}Check(rejected,"异常响应不会当作已成功识别");
 var utc=DateTime.UtcNow;var state=new MusicState{Connected=true,Playing=true,Id="123",Title="示例抒情歌曲",Position=35,Duration=180,At=utc};var planner=new MusicReactionPlanner();Check(planner.Choose(state,config,ranges,0,utc,true)==null,"连续播放门槛抑制切歌闪动");Check(planner.Choose(state,config,ranges,9,utc,true)=="music-quiet","安静模式在副歌仍保持耳机");config.MusicReactionMode="gentle";Check(planner.Choose(state,config,ranges,10,utc,true)=="music-gentle","副歌轻柔挥棒");config.MusicSongPreferences=new[]{new SongMusicPreference{Id="123",Mode="lively",Start=40,End=50}};Check(planner.Choose(state,config,ranges,11,utc,true)=="music-quiet","手动副歌区间优先于远程数据");state.Position=45;Check(planner.Choose(state,config,ranges,12,utc,true)=="music-lively","本曲活力偏好优先于整体轻柔");state.Position=80;Check(planner.Choose(state,config,ranges,13,utc,true)=="music-quiet","拖动到副歌外立即回到倾听");state.Position=42;Check(planner.Choose(state,config,ranges,14,utc,true)=="music-lively","回拖进入副歌可重新应援");Check(planner.Choose(state,config,ranges,15,utc,false)==null,"任务与互动优先级可中断");state.Playing=false;Check(planner.Choose(state,config,ranges,16,utc,true)=="music-quiet"&&planner.Choose(state,config,ranges,20,utc,true)==null,"短暂停顿收棒，超过三秒停止音乐动作");state.Playing=true;Check(planner.Choose(state,config,ranges,21,utc,true)==null,"恢复播放重新等待稳定门槛");Check(planner.Choose(state,config,ranges,30,utc.AddSeconds(10),true)==null,"过期连接不能维持音乐状态");
 config.MusicSongPreferences=new[]{new SongMusicPreference{Id="123",Mode="lively"},new SongMusicPreference{Id="123",Mode="quiet"},new SongMusicPreference{Id="bad",Mode="lively"}};config.Validate();Check(config.MusicSongPreferences.Length==1&&config.MusicSongPreferences[0].Mode=="quiet","偏好去重并校验歌曲 ID");var transferred=PreferenceTransfer.Import(PreferenceTransfer.Export(config,false));Check(transferred.MusicSongPreferences[0].Mode=="quiet","按歌曲偏好可以迁移");
 foreach(string skin in new[]{"kiana-winter-wish-round","kiana-fiery-wishing-star-round","time-runner-kiana-round"}){var frames=MusicSprites.Load(skin);Check(frames!=null&&frames.Length==6&&frames.All(f=>f.PixelWidth==768&&f.PixelHeight==832),"六关键帧与比例归一化："+skin);foreach(var frame in frames){var bgra=new FormatConvertedBitmap(frame,PixelFormats.Bgra32,null,0);byte[] pixels=new byte[frame.PixelWidth*frame.PixelHeight*4];bgra.CopyPixels(pixels,frame.PixelWidth*4,0);Check(pixels[3]==0&&pixels[(frame.PixelWidth-1)*4+3]==0,"图集角落保持实际透明");}pet.SelectSkin(skin);Set(pet,"state","music-lively");Set(pet,"lastFrame",-1);Call(pet,"DrawAnimation",0d);Check(ReferenceEquals(((Image)Field(pet,"sprite")).Source,frames[4])&&Field(pet,"activeAlignment")==null,"新动作不套用旧动作缩放："+skin);}
 ContactSheet();pet.Music.Current=state;state.Playing=true;state.Position=20;state.At=DateTime.UtcNow;pet.SetSongMusicMode("gentle");pet.MarkMusicChorus(false);state.Position=55;pet.MarkMusicChorus(true);var saved=MusicReactions.Preference(Store.Load(),"123");Check(saved.Mode=="gentle"&&saved.Start>=20&&saved.End>=55,"真实设置入口保存本曲模式和区间");pet.ClearMusicChorus();Check(MusicReactions.Preference(pet.Settings,"123").Start==-1,"可清除手动区间并恢复远程时间");
 w.NavigateCategory("音乐","听歌互动");w.UpdateStatus();w.Capture(Path.Combine(Store.Root,"music-reaction-settings.png"));Check(w.ActiveCategory=="音乐"&&((TextBlock)Field(w,"musicReactionStatus")).Text.Contains("轻柔应援"),"设置展示当前模式与来源");string before=File.ReadAllText(Path.Combine(Store.Root,"settings.json"));pet.PreviewMusicAnimation("gentle");await Task.Delay(180);var preview=app.Windows.OfType<MusicAnimationPreview>().Single();Check(preview.Sprite.Source!=null,"动作预览显示实际素材");preview.Close();Check(before==File.ReadAllText(Path.Combine(Store.Root,"settings.json")),"预览不修改偏好");var music=new MusicWindow(pet);music.Show();pet.OpenMusicReactionMenu(music);await Task.Delay(100);var menu=(ContextMenu)Field(pet,"toolbarMenu");Check(menu.IsOpen&&((MenuItem)menu.Items[0]).IsEnabled,"音乐栏菜单真实打开且可设置本曲");var songMenu=(MenuItem)menu.Items[0];((MenuItem)songMenu.Items[3]).RaiseEvent(new RoutedEventArgs(MenuItem.ClickEvent));Check(MusicReactions.Preference(pet.Settings,"123").Mode=="lively","菜单活力应援选项保存本曲偏好");Call(pet,"ClosePetMenu");music.Close();passed=true;
 }catch(Exception e){Store.Atomic("error.json",new{error=e.ToString()});}finally{Store.Atomic("music-reaction-tests.json",new{passed,checks});foreach(var window in app.Windows.Cast<Window>().Where(window=>window!=pet).ToArray())window.Close();pet.Close();}};app.Run(pet);return passed?0:1;
 }
}
