using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Threading;using KianaPet;
class MusicReactionTests {
 static readonly List<string> checks=new List<string>();static void Check(bool value,string name){if(!value)throw new Exception(name);checks.Add(name);}static object Field(object o,string n){return o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}static object Call(object o,string n,params object[] a){return o.GetType().GetMethod(n,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(o,a);}static void Set(object o,string n,object v){o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).SetValue(o,v);}
 static void Save(BitmapSource bitmap,string name){var e=new PngBitmapEncoder();e.Frames.Add(BitmapFrame.Create(bitmap));using(var f=File.Create(Path.Combine(Store.Root,name+".png")))e.Save(f);}
 static BitmapImage Read(string path){var b=new BitmapImage();b.BeginInit();b.CacheOption=BitmapCacheOption.OnLoad;b.UriSource=new Uri(path);b.EndInit();b.Freeze();return b;}
 static void ContactSheet(){string[] skins={"kiana-winter-wish-round","kiana-fiery-wishing-star-round","time-runner-kiana-round"};var visual=new DrawingVisual();using(var dc=visual.RenderOpen()){dc.DrawRectangle(Brushes.White,null,new Rect(0,0,768,624));for(int row=0;row<3;row++){var atlas=Read(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets",skins[row]+".png"));dc.DrawImage(new CroppedBitmap(atlas,new Int32Rect(0,0,192,208)),new Rect(0,row*208,192,208));var frames=MusicSprites.Load(skins[row]);for(int col=1;col<4;col++)dc.DrawImage(frames[(col-1)*6],new Rect(col*192,row*208,192,208));}}var output=new RenderTargetBitmap(1536,1248,192,192,PixelFormats.Pbgra32);output.Render(visual);Save(output,"music-actions-comparison");}
 static void SeatedFrameTests(){
   var styleConfig=new Config();Check(styleConfig.MusicSeatedStyle=="classic","existing seated style remains default");styleConfig.MusicSeatedStyle="invalid";styleConfig.Validate();Check(styleConfig.MusicSeatedStyle=="classic","unknown seated style safely falls back");styleConfig.MusicSeatedStyle="sway";Check(PreferenceTransfer.Import(PreferenceTransfer.Export(styleConfig,false)).MusicSeatedStyle=="sway","seated style migrates with common preferences");
   foreach(string skin in new[]{"kiana-winter-wish-round","kiana-fiery-wishing-star-round","time-runner-kiana-round"}){
    var classic=MusicSeatedFrames.Load(skin);var sway=MusicSeatedFrames.Load(skin,"sway");Check(sway.Length==12&&!ReferenceEquals(classic,sway),"distinct accepted sway frames: "+skin);foreach(var frame in sway)VerifyFrameEdges(frame);
    int styleKey;Check(ReferenceEquals(MusicSprites.Playback(skin,"music-quiet",MusicReactions.SitTransitionMs+1200,false,false,out styleKey,"sway"),sway[11])&&styleKey==2011,"selected sway is used live with distinct redraw key");
    var choice=AnimationGallery.Catalog.Single(a=>a.Id=="music-quiet");var pose=new AnimationPreviewSource(skin,"sway").Frame(choice,1200);Check(pose.SourceLabel.Contains("头部轻晃"),"gallery identifies selected seated variant");
    Check(!ReferenceEquals(MusicSeatedFrames.Load(skin),MusicSeatedFrames.Load(skin,"sway")),"switching back cannot reuse wrong style cache");
    var sheet=new DrawingVisual();using(var dc=sheet.RenderOpen())for(int i=0;i<12;i++)dc.DrawImage(sway[i],new Rect(i%4*192,i/4*208,192,208));var packed=new RenderTargetBitmap(1536,1248,192,192,PixelFormats.Pbgra32);packed.Render(sheet);Save(packed,"music-seated-sway-"+skin);
   }
   styleConfig.MusicSeatedStyle="nod";Check(PreferenceTransfer.Import(PreferenceTransfer.Export(styleConfig,false)).MusicSeatedStyle=="nod","accepted side nod survives preference validation and transfer");
   foreach(string skin in new[]{"kiana-winter-wish-round","kiana-fiery-wishing-star-round","time-runner-kiana-round"}){
    var nod=MusicSeatedFrames.Load(skin,"nod");Check(nod.Length==12,"twelve accepted nod frames: "+skin);foreach(var f in nod)VerifyFrameEdges(f);int key;Check(ReferenceEquals(MusicSprites.Playback(skin,"music-quiet",1920,false,false,out key,"nod"),nod[11])&&key==3011,"side nod live source and key differ from other styles");
    var sheet=new DrawingVisual();using(var dc=sheet.RenderOpen())for(int i=0;i<12;i++)dc.DrawImage(nod[i],new Rect(i%4*192,i/4*208,192,208));var packed=new RenderTargetBitmap(1536,1248,192,192,PixelFormats.Pbgra32);packed.Render(sheet);Save(packed,"music-seated-nod-"+skin);
   }
   Check(MusicSeatedFrames.FrameIndex(double.NaN)==0&&MusicSeatedFrames.FrameIndex(-1)==0,"invalid time is stable");
   Check(MusicSeatedFrames.FrameIndex(1200)==11&&MusicSeatedFrames.FrameIndex(2400)==0,"opposite extremum and closed cycle");
   for(int i=0;i<22;i++)Check(Math.Abs(MusicSeatedFrames.Sequence[i]-MusicSeatedFrames.Sequence[(i+1)%22])==1,"only adjacent painted frames, including loop seam");
   foreach(string skin in new[]{"kiana-winter-wish-round","kiana-fiery-wishing-star-round","time-runner-kiana-round"}){
    var f=MusicSeatedFrames.Load(skin);Check(f.Length==12,"twelve whole-character drawings: "+skin);
    foreach(var frame in f)VerifyFrameEdges(frame);
    int key;Check(ReferenceEquals(MusicSprites.Playback(skin,"music-quiet",MusicReactions.SitTransitionMs+1200,false,false,out key),f[11])&&key==1011,"live playback uses opposite painted key pose");
    Check(ReferenceEquals(MusicSprites.Playback(skin,"music-quiet",9999,true,false,out key),f[0]),"reduced motion stays on a whole pose");
    var v=new DrawingVisual();using(var dc=v.RenderOpen())for(int i=0;i<12;i++)dc.DrawImage(f[i],new Rect(i%4*192,i/4*208,192,208));var atlas=new RenderTargetBitmap(1536,1248,192,192,PixelFormats.Pbgra32);atlas.Render(v);Save(atlas,"music-seated-"+skin);
    foreach(bool dark in new[]{false,true}){
     v=new DrawingVisual();using(var dc=v.RenderOpen()){dc.DrawRectangle(dark?new SolidColorBrush(Color.FromRgb(30,32,40)):Brushes.White,null,new Rect(0,0,768,624));for(int i=0;i<4;i++)dc.DrawImage(f[new[]{0,3,7,11}[i]],new Rect(i*192,0,192,208));for(int i=0;i<4;i++){dc.PushClip(new RectangleGeometry(new Rect(i*192,208,192,208)));dc.DrawImage(f[new[]{0,3,7,11}[i]],new Rect(i*192-20,208-265,384,416));dc.Pop();}var original=Read(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets",skin+".png"));dc.DrawImage(new CroppedBitmap(original,new Int32Rect(0,0,192,208)),new Rect(0,416,192,208));dc.DrawImage(f[2],new Rect(192,416,192,208));var poses=MusicSprites.Load(skin);dc.DrawImage(poses[6],new Rect(384,416,192,208));dc.DrawImage(poses[10],new Rect(576,416,192,208));}var check=new RenderTargetBitmap(1536,1248,192,192,PixelFormats.Pbgra32);check.Render(v);Save(check,"music-legs-"+skin+(dark?"-dark":"-light"));
    }
   }
  }
  static void SessionTests(){
  var c=new Config();c.Validate();Check(c.MusicEntryDelaySeconds==3&&c.MusicPlaybackGraceSeconds==5&&c.MusicChorusImmediate&&c.MusicContinueAcrossTracks,"默认三秒进入、副歌立即、五秒保留并连续切歌");
  var legacy=Store.Json.Deserialize<Config>("{}");legacy.Validate();Check(legacy.MusicEntryDelaySeconds==3&&legacy.MusicPlaybackGraceSeconds==5&&legacy.MusicContinueAcrossTracks&&legacy.MusicChorusImmediate,"旧 JSON 未包含新字段时取得默认值");
  c.MusicEntryDelaySeconds=99;c.MusicPlaybackGraceSeconds=-1;c.Validate();Check(c.MusicEntryDelaySeconds==30&&c.MusicPlaybackGraceSeconds==0,"音乐时长输入有上下限");
  c.MusicEntryDelaySeconds=-2;c.MusicPlaybackGraceSeconds=99;c.Validate();Check(c.MusicEntryDelaySeconds==0&&c.MusicPlaybackGraceSeconds==15,"时长另一侧边界校验");
  c.MusicEntryDelaySeconds=8;c.MusicPlaybackGraceSeconds=7;c.MusicChorusImmediate=false;c.MusicContinueAcrossTracks=false;var copy=PreferenceTransfer.Import(PreferenceTransfer.Export(c,false));Check(copy.MusicEntryDelaySeconds==8&&copy.MusicPlaybackGraceSeconds==7&&!copy.MusicChorusImmediate&&!copy.MusicContinueAcrossTracks,"四项设置随通用偏好迁移");
  c=new Config{MusicNormalAction="quiet",MusicChorusAction="lively"};var t=DateTime.UtcNow;var s=new MusicState{Connected=true,Playing=true,Id="1",Duration=180,At=t};var p=new MusicReactionPlanner();var empty=new ChorusRange[0];
  Check(p.Choose(s,c,empty,0,t,true)==null&&p.Choose(s,c,empty,2.99,t,true)==null&&p.Choose(s,c,empty,3,t,true)=="music-quiet","精确三秒门槛");
  s.Id="2";Check(p.Choose(s,c,empty,4,t,true)=="music-quiet","手动切歌不重置进入门槛");s.Id="3";s.Position=0;Check(p.Choose(s,c,empty,5,t,true)=="music-quiet","自动下一首不中断坐姿");
  s.Playing=false;Check(p.Choose(s,c,empty,7,t,true)=="music-quiet","短暂停播保留实际上一动作");s.Connected=false;s.Id="";s.Title="";Check(p.Choose(s,c,empty,9,t,true)=="music-quiet","切歌空白元数据和短暂断开仍保留");s.Connected=s.Playing=true;s.Id="4";Check(p.Choose(s,c,empty,9.5,t,true)=="music-quiet","宽限内恢复不再次等待");
  s.Playing=false;Check(p.Choose(s,c,empty,14.6,t,true)==null,"超过自定义保留时间恢复日常状态");s.Playing=true;Check(p.Choose(s,c,empty,15,t,true)==null&&p.Choose(s,c,empty,18,t,true)=="music-quiet","真正暂停后恢复重新执行进入门槛");
  c.MusicPlaybackGraceSeconds=0;s.Playing=false;Check(p.Choose(s,c,empty,18.1,t,true)==null,"零秒保留立即退出");
  c.MusicEntryDelaySeconds=0;s.Playing=true;p=new MusicReactionPlanner();Check(p.Choose(s,c,empty,0,t,true)=="music-quiet","零秒进入立即生效");c.MusicContinueAcrossTracks=false;c.MusicEntryDelaySeconds=8;s.Id="5";Check(p.Choose(s,c,empty,1,t,true)==null&&p.Choose(s,c,empty,8.9,t,true)==null&&p.Choose(s,c,empty,9,t,true)=="music-quiet","可关闭连续切歌并自定义八秒等待");
  var ranges=new[]{new ChorusRange{Start=30,End=60}};c=new Config{MusicNormalAction="quiet",MusicChorusAction="lively",MusicEntryDelaySeconds=30};s.Position=40;p=new MusicReactionPlanner();Check(p.Choose(s,c,ranges,0,t,true)=="music-lively","已知副歌绕过首次三十秒等待");c.MusicChorusImmediate=false;p=new MusicReactionPlanner();Check(p.Choose(s,c,ranges,0,t,true)==null&&p.Choose(s,c,ranges,30,t,true)=="music-lively","关闭立即响应时尊重自定义等待");c.MusicChorusImmediate=true;p=new MusicReactionPlanner();s.Position=20;Check(p.Choose(s,c,ranges,0,t,true)==null,"副歌外仍等待");s.Position=40;Check(p.Choose(s,c,ranges,.2,t,true)=="music-lively","等待中进入副歌即时响应");s.Playing=false;Check(p.Choose(s,c,ranges,1,t,true)=="music-lively","短暂停顿不从应援突然变坐姿");
  s.Playing=true;s.Id="6";c.MusicSongPreferences=new[]{new SongMusicPreference{Id="6",NormalAction="off",ChorusAction="off"}};Check(p.Choose(s,c,ranges,2,t,true)==null,"连续切歌仍尊重新歌曲禁用规则");s.Id="7";Check(p.Choose(s,c,ranges,3,t,true)=="music-lively","下一首已知副歌立即按新规则响应");
  Check(p.Choose(s,c,ranges,4,t,false)==null,"高优先级互动不会被副歌覆盖");c.ReduceMotion=true;Check(p.Choose(s,c,ranges,5,t,true)==null,"减少动态效果禁用自动音乐动作");c.ReduceMotion=false;c.MusicEnabled=false;Check(p.Choose(s,c,ranges,6,t,true)==null,"关闭音乐时无宽限残留");
  c=new Config{MusicEntryDelaySeconds=0,MusicNormalAction="quiet"};p=new MusicReactionPlanner();s.Position=0;s.At=t;Check(p.Choose(s,c,empty,0,t,true)=="music-quiet","新鲜播放样本进入");Check(p.Choose(s,c,empty,7,t.AddSeconds(7),true)==null&&p.Choose(s,c,empty,9,t.AddSeconds(9),true)==null,"重复读取过期 Playing 样本不能无限续期");
  c=new Config{MusicEntryDelaySeconds=3};p=new MusicReactionPlanner();s.At=t;s.Playing=true;Check(p.Choose(s,c,empty,0,t,true)==null,"首次等待开始");s.Playing=false;p.Choose(s,c,empty,2,t,true);s.Playing=true;Check(p.Choose(s,c,empty,4,t,true)==null&&p.Choose(s,c,empty,6.9,t,true)==null&&p.Choose(s,c,empty,7,t,true)=="music-quiet","尚未进入听歌时暂停不能累计进等待时长");
  c=new Config{MusicNormalAction="mixed",MusicEntryDelaySeconds=0};p=new MusicReactionPlanner();s.At=t;s.Id="";s.Title="元数据标题";Check(p.Choose(s,c,empty,0,t,true)=="music-quiet","仅元数据也可以开始会话");s.Id="8";Check(p.Choose(s,c,empty,45,t,true)=="music-gentle","歌曲 ID 后到不重置混合动作周期");s.Id="9";Check(p.Choose(s,c,empty,46,t,true)=="music-gentle","连续下一首保留混合阶段");Check(p.Choose(s,c,empty,60,t,true)=="music-quiet","混合方案继续自身交替周期");
 }
 static void SessionUiTests(PetWindow pet,SettingsWindow w){
  var tabs=(TabControl)Field(w,"settingsTabs");var page=(StackPanel)((ScrollViewer)tabs.Items.Cast<TabItem>().Single(x=>(string)x.Header=="音乐").Content).Content;
  var delay=SettingsWindow.Descendants<Slider>(page).Single(x=>System.Windows.Automation.AutomationProperties.GetName(x)=="开始听歌前等待（秒，0 为立即）");var grace=SettingsWindow.Descendants<Slider>(page).Single(x=>System.Windows.Automation.AutomationProperties.GetName(x)=="切歌或短暂停顿保留动作（秒）");var chorus=SettingsWindow.Descendants<CheckBox>(page).Single(x=>(string)x.Content=="已识别到副歌时立即进入对应动作");var continuous=SettingsWindow.Descendants<CheckBox>(page).Single(x=>(string)x.Content=="连续切歌时保持听歌状态");
  delay.Value=9;grace.Value=7;chorus.IsChecked=false;continuous.IsChecked=false;var saved=Store.Load();Check(saved.MusicEntryDelaySeconds==9&&saved.MusicPlaybackGraceSeconds==7&&!saved.MusicChorusImmediate&&!saved.MusicContinueAcrossTracks,"真实四项设置写入偏好");pet.Settings.MusicEntryDelaySeconds=3;pet.Settings.MusicPlaybackGraceSeconds=5;pet.Settings.MusicChorusImmediate=true;pet.Settings.MusicContinueAcrossTracks=true;pet.Save();w.UpdateStatus();Check(delay.Value==3&&grace.Value==5&&chorus.IsChecked==true&&continuous.IsChecked==true,"撤销或恢复偏好后四项控件同步且不写回旧值");
  var original=pet.Music.Current;pet.Settings.MusicEnabled=true;pet.Settings.MusicEntryDelaySeconds=0;pet.Settings.MusicNormalAction="quiet";pet.Settings.MusicChorusAction="same";pet.Settings.Walking=true;Set(pet,"quietActive",false);Set(pet,"interaction",null);Set(pet,"interactionUntil",0d);Set(pet,"menuLayerYielding",false);Set(pet,"displayPending",false);Set(pet,"lastSlow",double.MaxValue);
  pet.Music.Current=new MusicState{Connected=true,Playing=true,Id="100",Title="切歌测试",Duration=180,At=DateTime.UtcNow};Call(pet,"Tick",null,EventArgs.Empty);Check((string)Field(pet,"state")=="music-quiet","实际桌宠进入坐姿音乐状态");double age=((System.Diagnostics.Stopwatch)Field(pet,"clock")).Elapsed.TotalSeconds-5;Set(pet,"stateAt",age);Set(pet,"walkUntil",9999d);double left=pet.Left,top=pet.Top;
  pet.Music.Current=new MusicState{Connected=true,Playing=false,Id="",At=DateTime.UtcNow};Call(pet,"Tick",null,EventArgs.Empty);pet.Music.Current=new MusicState{Connected=true,Playing=true,Id="101",Title="下一首测试",Duration=180,At=DateTime.UtcNow};Call(pet,"Tick",null,EventArgs.Empty);
  Check((string)Field(pet,"state")=="music-quiet"&&(double)Field(pet,"stateAt")==age&&(double)Field(pet,"walkUntil")==0&&pet.Left==left&&pet.Top==top,"真实切歌与短暂停顿保留坐姿时间轴、取消走动、不重复坐下");
  pet.Settings.MusicEnabled=false;pet.Settings.Walking=false;pet.Settings.MusicEntryDelaySeconds=3;pet.Music.Current=original;pet.Save();
 }

 static void PhaseTests(){
  SessionTests();
  ChorusDisplayTests();
  foreach(string legacy in MusicReactions.Modes){var c=new Config{MusicReactionMode=legacy};c.Validate();Check(MusicReactions.Action(c,"",false)==(legacy=="off"?"off":"quiet")&&MusicReactions.Action(c,"",true)==legacy,"旧版出现规则迁移："+legacy);}
  var mixed=new Config{MusicNormalAction="mixed",MusicChorusAction="lively"};mixed.Validate();Check(MusicReactions.ChooseAction(mixed,"",false,0)=="music-quiet"&&MusicReactions.ChooseAction(mixed,"",false,45)=="music-gentle"&&MusicReactions.ChooseAction(mixed,"",false,60)=="music-quiet","平时坐姿与轻微应援按稳定周期交替");Check(MusicReactions.ChooseAction(mixed,"",true,2)=="music-lively","副歌动作独立于平时动作");mixed.MusicChorusAction="same";Check(MusicReactions.ChooseAction(mixed,"",true,50)=="music-gentle","副歌保持平时动作可继续交替");mixed.MusicSongPreferences=new[]{new SongMusicPreference{Id="12",NormalAction="gentle",ChorusAction="quiet"}};Check(MusicReactions.ChooseAction(mixed,"12",false)=="music-gentle"&&MusicReactions.ChooseAction(mixed,"12",true)=="music-quiet","单曲可分别覆盖两个阶段");mixed.MusicSongPreferences[0].ChorusAction="same";Check(MusicReactions.ChooseAction(mixed,"12",true)=="music-gentle","单曲副歌保持该曲的平时设置");var copy=PreferenceTransfer.Import(PreferenceTransfer.Export(mixed,false));Check(copy.MusicNormalAction=="mixed"&&copy.MusicChorusAction=="same"&&copy.MusicSongPreferences[0].NormalAction=="gentle","两个阶段及交替偏好可迁移");
  foreach(string state in new[]{"music-quiet","music-gentle","music-lively"}){int first=MusicReactions.Frame(state,0,false);var seen=new HashSet<int>();for(int ms=0;ms<6000;ms+=30){int f=MusicReactions.Frame(state,ms,false);Check(f>=first&&f<first+6,"时间线帧索引合法");seen.Add(f);}Check(seen.Count==6,"每个动作实际播放六张姿势："+state);Check(MusicReactions.Frame(state,double.NaN,false)==first&&MusicReactions.Frame(state,10000,true)==first,"异常时间与减少动态效果稳定");}
  Check(MusicReactions.PlaybackFrame("music-quiet",0,false,false)==18&&MusicReactions.PlaybackFrame("music-quiet",719,false,false)==23&&MusicReactions.PlaybackFrame("music-quiet",720,false,false)==0,"先坐下再进入坐姿循环");Check(MusicReactions.PlaybackFrame("music-gentle",0,false,true)==23&&MusicReactions.PlaybackFrame("music-gentle",719,false,true)==18&&MusicReactions.PlaybackFrame("music-gentle",720,false,true)==6,"从坐姿到应援先起身");
  byte[] data=new byte[40*40*4];for(int y=5;y<30;y++)for(int x=5;x<25;x++){int p=(y*40+x)*4;data[p+2]=data[p+3]=255;}data[(6*40+33)*4+3]=255;data[(6*40+33)*4]=255;int fringe=(15*40+4)*4;data[fringe+2]=data[fringe+3]=64;var atlas=BitmapSource.Create(40,40,96,96,PixelFormats.Pbgra32,null,data,160);var crop=MusicSpriteCrop.Extract(atlas,new Int32Rect(0,0,40,40));byte[] actual=new byte[data.Length];crop.CopyPixels(actual,160,0);Check(actual[(6*40+33)*4+3]==0&&actual[fringe+3]==64&&actual[(15*40+15)*4+3]==255,"裁切排除邻格碎片并保留原始抗锯齿透明边缘");
 }

 static void ChorusDisplayTests(){
  var config=new Config();var state=new MusicState{Connected=true,Id="123",Duration=180};var ranges=new[]{new ChorusRange{Start=90,End=110},new ChorusRange{Start=30,End=60},new ChorusRange{Start=175,End=195}};
  string text=ChorusDisplay.Describe(config,state,ranges,"已取得副歌时间",DateTime.UtcNow);
  Check(text.Contains("第 1 段  00:30–01:00")&&text.Contains("第 2 段  01:30–01:50")&&!text.Contains("第 3 段")&&text.Contains("获取时间"),"副歌区间按时间排序并过滤超出歌曲长度的区间");
  config.MusicChorusEnabled=false;text=ChorusDisplay.Describe(config,state,ranges,"",null);Check(text.Contains("未启用")&&text.Contains("00:30"),"关闭查询仍可查看缓存且不会误称生效");
  config.MusicSongPreferences=new[]{new SongMusicPreference{Id="123",Start=40,End=50}};text=ChorusDisplay.Describe(config,state,ranges,"",null);Check(text.Contains("当前生效：手动标记 00:40–00:50")&&text.Contains("手动标记优先"),"手动时间和接口来源分别显示");
  config.MusicSongPreferences[0].End=-1;text=ChorusDisplay.Describe(config,state,ranges,"",null);Check(text.Contains("等待标记终点")&&!text.Contains("当前生效：手动"),"不完整手动标记不覆盖接口区间");
  config.MusicChorusEnabled=true;text=ChorusDisplay.Describe(config,state,new ChorusRange[0],"正在查询副歌时间…",null);Check(text.Contains("正在查询"),"暂无区间时展示实际查询状态");
  Check(ChorusDisplay.Time(62.056)=="01:02"&&ChorusDisplay.Time(3661)=="61:01"&&ChorusDisplay.Time(double.NaN)=="00:00","时间格式支持毫秒舍入和长音轨");
  state.Id="456";using(var library=new ChorusLibrary()){library.Status="旧歌曲的状态";Set(library,"statusSong","123");Check(!library.StatusFor(state.Id).Contains("旧歌曲"),"切歌不泄露上一首查询状态");library.Update(state,false).GetAwaiter().GetResult();Check(library.StatusFor("456").Contains("已关闭")&&library.AcquiredAt("456")==null,"关闭查询按当前歌曲展示状态");}
  state.Connected=false;Check(ChorusDisplay.Describe(config,state,ranges,"",null).Contains("连接并播放"),"断开时不显示为当前歌曲的有效副歌");
 }
 static void ChorusUiTests(PetWindow pet,SettingsWindow w){
  var seatedChoice=(ComboBox)Field(w,"musicSeatedStyle");seatedChoice.SelectedIndex=1;Check(pet.Settings.MusicSeatedStyle=="sway"&&Store.Load().MusicSeatedStyle=="sway","real settings choice persists accepted sway");Set(pet,"state","music-quiet");Set(pet,"drawnMusicState","music-quiet");Call(pet,"DrawAnimation",5520d);Check((int)Field(pet,"lastFrame")==2411,"switching style immediately redraws live seated pose");seatedChoice.SelectedIndex=2;Call(pet,"DrawAnimation",5520d);Check((int)Field(pet,"lastFrame")==3411&&Store.Load().MusicSeatedStyle=="nod","third settings option saves and redraws side nod");seatedChoice.SelectedIndex=0;Call(pet,"DrawAnimation",5520d);Check((int)Field(pet,"lastFrame")==1411,"switching back immediately redraws original pose");
  var state=pet.Music.Current;string id=state.Id;bool enabled=pet.Settings.MusicChorusEnabled;state.Id="123";pet.Settings.MusicChorusEnabled=true;
  var cache=(Dictionary<string,ChorusCacheEntry>)Field(Field(pet,"chorusLibrary"),"cache");cache["123"]=new ChorusCacheEntry{Id="123",At=DateTime.UtcNow,Ranges=new[]{new ChorusRange{Start=30,End=60},new ChorusRange{Start=90,End=110}}};
  w.UpdateStatus();var text=(TextBlock)Field(w,"musicChorusTimes");Check(text.Text.Contains("第 2 段  01:30–01:50"),"真实设置页显示接口获取的多个区间");pet.Settings.MusicChorusEnabled=false;w.UpdateStatus();Check(text.Text.Contains("未启用"),"真实设置页关闭查询立即更新来源说明");
  state.Id="456";w.UpdateStatus();Check(!text.Text.Contains("00:30")&&!text.Text.Contains("01:50"),"设置页切歌立即移除上一首副歌时间");state.Id=id;pet.Settings.MusicChorusEnabled=enabled;w.UpdateStatus();text.BringIntoView();w.UpdateLayout();w.Capture(Path.Combine(Store.Root,"chorus-time-settings.png"));
 }
 static void QualitySheets(){foreach(string skin in new[]{"kiana-winter-wish-round","kiana-fiery-wishing-star-round","time-runner-kiana-round"}){var frames=MusicSprites.Load(skin);var packed=new DrawingVisual();using(var dc=packed.RenderOpen()){for(int i=0;i<24;i++)dc.DrawImage(frames[i],new Rect(i%6*192,i/6*208,192,208));}var atlas=new RenderTargetBitmap(2304,1664,192,192,PixelFormats.Pbgra32);atlas.Render(packed);Save(atlas,"music-frames-"+skin);foreach(bool dark in new[]{false,true}){var v=new DrawingVisual();using(var dc=v.RenderOpen()){dc.DrawRectangle(dark?new SolidColorBrush(Color.FromRgb(30,32,40)):Brushes.White,null,new Rect(0,0,1152,832));dc.DrawImage(atlas,new Rect(0,0,1152,832));}var output=new RenderTargetBitmap(1152,832,96,96,PixelFormats.Pbgra32);output.Render(v);Save(output,"music-qa-"+skin+(dark?"-dark":"-light"));}}}
 static void VerifyFrameEdges(BitmapSource frame){var bgra=new FormatConvertedBitmap(frame,PixelFormats.Bgra32,null,0);int width=frame.PixelWidth,height=frame.PixelHeight;var pixels=new byte[width*height*4];bgra.CopyPixels(pixels,width*4,0);bool clear=true;for(int x=0;x<width;x++)if(pixels[x*4+3]>8||pixels[((height-1)*width+x)*4+3]>8)clear=false;for(int y=0;y<height;y++)if(pixels[(y*width)*4+3]>8||pixels[(y*width+width-1)*4+3]>8)clear=false;Check(clear,"完整轮廓在输出画布内，四边无裁切");}

 [STAThread]static int Main(string[] args){Store.Root=args[0];Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false,NoticeSound=false});var app=new Application{ShutdownMode=ShutdownMode.OnLastWindowClose};var pet=new PetWindow(true);bool passed=false;
 pet.Loaded+=async delegate{try{await Task.Delay(1100);((DispatcherTimer)Field(pet,"animation")).Stop();var w=app.Windows.OfType<SettingsWindow>().Single();
 PhaseTests();var config=new Config();Check(config.MusicReactionMode=="quiet"&&config.MusicChorusEnabled,"默认安静听歌且副歌查询可关闭");var ranges=ChorusLibrary.Parse("{\"code\":200,\"chorus\":[{\"id\":123,\"startTime\":30000,\"endTime\":60000},{\"id\":999,\"startTime\":1,\"endTime\":2}]}","123");Check(ranges.Length==1&&ranges[0].Start==30&&ranges[0].End==60,"解析实测格式并过滤其他歌曲与毫秒单位");Check(ChorusLibrary.Parse("{\"code\":200,\"data\":[{\"id\":123,\"startTime\":-1,\"endTime\":60000}]}","123").Length==0,"拒绝无效副歌区间");bool rejected=false;try{ChorusLibrary.Parse("{\"code\":500}","123");}catch{rejected=true;}Check(rejected,"异常响应不会当作已成功识别");
 var utc=DateTime.UtcNow;var state=new MusicState{Connected=true,Playing=true,Id="123",Title="示例抒情歌曲",Position=35,Duration=180,At=utc};var planner=new MusicReactionPlanner();config.MusicChorusImmediate=false;Check(planner.Choose(state,config,ranges,0,utc,true)==null,"连续播放门槛抑制切歌闪动");Check(planner.Choose(state,config,ranges,9,utc,true)=="music-quiet","安静模式在副歌仍保持耳机");config.MusicReactionMode="gentle";Check(planner.Choose(state,config,ranges,10,utc,true)=="music-gentle","副歌轻柔挥棒");config.MusicSongPreferences=new[]{new SongMusicPreference{Id="123",Mode="lively",Start=40,End=50}};Check(planner.Choose(state,config,ranges,11,utc,true)=="music-quiet","手动副歌区间优先于远程数据");state.Position=45;Check(planner.Choose(state,config,ranges,12,utc,true)=="music-lively","本曲活力偏好优先于整体轻柔");state.Position=80;Check(planner.Choose(state,config,ranges,13,utc,true)=="music-quiet","拖动到副歌外立即回到倾听");state.Position=42;Check(planner.Choose(state,config,ranges,14,utc,true)=="music-lively","回拖进入副歌可重新应援");Check(planner.Choose(state,config,ranges,15,utc,false)==null,"任务与互动优先级可中断");state.Playing=false;Check(planner.Choose(state,config,ranges,16,utc,true)=="music-lively"&&planner.Choose(state,config,ranges,20.1,utc,true)==null,"短暂停顿保留原动作，超过五秒停止音乐动作");state.Playing=true;Check(planner.Choose(state,config,ranges,21,utc,true)==null,"恢复播放重新等待稳定门槛");Check(planner.Choose(state,config,ranges,30,utc.AddSeconds(10),true)==null,"过期连接不能维持音乐状态");
 config.MusicSongPreferences=new[]{new SongMusicPreference{Id="123",Mode="lively"},new SongMusicPreference{Id="123",Mode="quiet"},new SongMusicPreference{Id="bad",Mode="lively"}};config.Validate();Check(config.MusicSongPreferences.Length==1&&config.MusicSongPreferences[0].Mode=="quiet","偏好去重并校验歌曲 ID");var transferred=PreferenceTransfer.Import(PreferenceTransfer.Export(config,false));Check(transferred.MusicSongPreferences[0].Mode=="quiet","按歌曲偏好可以迁移");
 foreach(string skin in new[]{"kiana-winter-wish-round","kiana-fiery-wishing-star-round","time-runner-kiana-round"}){var frames=MusicSprites.Load(skin);Check(frames!=null&&frames.Length==24&&frames.All(f=>f.PixelWidth==768&&f.PixelHeight==832),"24 帧与脸宽归一化："+skin);foreach(var frame in frames){VerifyFrameEdges(frame);var bgra=new FormatConvertedBitmap(frame,PixelFormats.Bgra32,null,0);byte[] pixels=new byte[frame.PixelWidth*frame.PixelHeight*4];bgra.CopyPixels(pixels,frame.PixelWidth*4,0);Check(pixels[3]==0&&pixels[(frame.PixelWidth-1)*4+3]==0,"图集角落保持实际透明");}pet.SelectSkin(skin);Set(pet,"state","music-lively");Set(pet,"lastFrame",-1);Call(pet,"DrawAnimation",0d);Check(ReferenceEquals(((Image)Field(pet,"sprite")).Source,frames[12])&&Field(pet,"activeAlignment")==null,"新动作不套用旧动作缩放："+skin);}
 SeatedFrameTests();ContactSheet();QualitySheets();var otherSkinPreview=new MusicAnimationPreview("kiana-winter-wish-round","quiet");otherSkinPreview.Show();var liveSkin=MusicSprites.Load("time-runner-kiana-round");await Task.Delay(160);Check(ReferenceEquals(liveSkin,MusicSprites.Load("time-runner-kiana-round")),"Different skin preview retains its cache without evicting live pet frames");otherSkinPreview.Close();pet.Music.Current=state;state.Playing=true;state.Position=20;state.At=DateTime.UtcNow;pet.SetSongMusicMode("gentle");pet.MarkMusicChorus(false);state.Position=55;pet.MarkMusicChorus(true);var saved=MusicReactions.Preference(Store.Load(),"123");Check(saved.Mode=="gentle"&&saved.Start>=20&&saved.End>=55,"真实设置入口保存本曲模式和区间");pet.ClearMusicChorus();Check(MusicReactions.Preference(pet.Settings,"123").Start==-1,"可清除手动区间并恢复远程时间");
 w.NavigateCategory("音乐","音乐动作");w.UpdateStatus();w.Capture(Path.Combine(Store.Root,"music-reaction-settings.png"));Check(w.ActiveCategory=="音乐"&&((TextBlock)Field(w,"musicReactionStatus")).Text.Contains("轻微挥棒"),"设置展示当前模式与来源");ChorusUiTests(pet,w);SessionUiTests(pet,w);string before=File.ReadAllText(Path.Combine(Store.Root,"settings.json"));pet.PreviewMusicAnimation("gentle");await Task.Delay(180);var preview=app.Windows.OfType<MusicAnimationPreview>().Single();Check(preview.Sprite.Source!=null,"动作预览显示实际素材");preview.Close();Check(before==File.ReadAllText(Path.Combine(Store.Root,"settings.json")),"预览不修改偏好");var music=new MusicWindow(pet);music.Show();pet.OpenMusicReactionMenu(music);await Task.Delay(100);var menu=(ContextMenu)Field(pet,"toolbarMenu");Check(menu.IsOpen&&((MenuItem)menu.Items[0]).IsEnabled,"音乐栏菜单真实打开且可设置本曲");var songMenu=(MenuItem)menu.Items[0];((MenuItem)((MenuItem)songMenu.Items[1]).Items[4]).RaiseEvent(new RoutedEventArgs(MenuItem.ClickEvent));Check(MusicReactions.Preference(pet.Settings,"123").ChorusAction=="lively","菜单活力应援选项保存本曲偏好");Call(pet,"ClosePetMenu");music.Close();passed=true;
 }catch(Exception e){Store.Atomic("error.json",new{error=e.ToString()});}finally{Store.Atomic("music-reaction-tests.json",new{passed,checks});foreach(var window in app.Windows.Cast<Window>().Where(window=>window!=pet).ToArray())window.Close();pet.Close();}};app.Run(pet);return passed?0:1;
 }
}
