using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Threading;using KianaPet;
class MusicReactionTests {
 static readonly List<string> checks=new List<string>();static void Check(bool value,string name){if(!value)throw new Exception(name);checks.Add(name);}static object Field(object o,string n){return o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}static object Call(object o,string n,params object[] a){return o.GetType().GetMethod(n,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(o,a);}static void Set(object o,string n,object v){o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).SetValue(o,v);}
 static void Save(BitmapSource bitmap,string name){var e=new PngBitmapEncoder();e.Frames.Add(BitmapFrame.Create(bitmap));using(var f=File.Create(Path.Combine(Store.Root,name+".png")))e.Save(f);}
 static BitmapImage Read(string path){var b=new BitmapImage();b.BeginInit();b.CacheOption=BitmapCacheOption.OnLoad;b.UriSource=new Uri(path);b.EndInit();b.Freeze();return b;}
 static void ContactSheet(){string[] skins={"kiana-winter-wish-round","kiana-fiery-wishing-star-round","time-runner-kiana-round"};var visual=new DrawingVisual();using(var dc=visual.RenderOpen()){dc.DrawRectangle(Brushes.White,null,new Rect(0,0,768,624));for(int row=0;row<3;row++){var atlas=Read(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets",skins[row]+".png"));dc.DrawImage(new CroppedBitmap(atlas,new Int32Rect(0,0,192,208)),new Rect(0,row*208,192,208));var frames=MusicSprites.Load(skins[row]);for(int col=1;col<4;col++)dc.DrawImage(frames[(col-1)*6],new Rect(col*192,row*208,192,208));}}var output=new RenderTargetBitmap(1536,1248,192,192,PixelFormats.Pbgra32);output.Render(visual);Save(output,"music-actions-comparison");}
 static void RigTests(){
  foreach(string skin in new[]{"kiana-winter-wish-round","kiana-fiery-wishing-star-round","time-runner-kiana-round"}){
   var c=MusicSeatedRig.Calibration(skin);var f=MusicSeatedRig.Load(skin);Check(f.Length==48,"坐姿48个连续相位："+skin);
   foreach(var frame in f)VerifyFrameEdges(frame);
   var farA=MusicSeatedRig.Ankle(c.FarLeg,false,Math.PI/2);var nearA=MusicSeatedRig.Ankle(c.NearLeg,true,Math.PI/2);
   var farB=MusicSeatedRig.Ankle(c.FarLeg,false,Math.PI*1.5);var nearB=MusicSeatedRig.Ankle(c.NearLeg,true,Math.PI*1.5);
   Check(farA.X<nearA.X-4 && nearB.X<farB.X-4,"两个半周期真正交换前脚，而非始终同一脚在前："+skin);
   Check(Math.Abs(MusicSeatedRig.LegAngle(false,0)-MusicSeatedRig.LegAngle(false,Math.PI*2))<.001,"循环接缝角度连续");
   var poses=MusicSprites.Load(skin);for(int i=0;i<6;i++)foreach(double angle in new[]{-1.1,1.1}){var edgeVisual=new DrawingVisual();using(var dc=edgeVisual.RenderOpen()){dc.PushTransform(new RotateTransform(angle,384*.46,384*1.03));dc.DrawImage(poses[6+i],new Rect(0,0,384,416));dc.Pop();}var rotated=new RenderTargetBitmap(768,832,192,192,PixelFormats.Pbgra32);rotated.Render(edgeVisual);VerifyFrameEdges(rotated);}
   Check(Math.Abs(MusicReactions.GentleAngle(0)-MusicReactions.GentleAngle(1440))<.0001&&MusicReactions.GentleAngle(360)>.5&&MusicReactions.GentleAngle(1080)<-.5,"连续轻摆完整往返且循环无角度跳变");
   int key;Check(ReferenceEquals(MusicSprites.Playback(skin,"music-quiet",MusicReactions.SitTransitionMs+600,false,false,out key),f[12]),"实际桌宠坐姿播放使用独立腿相位");
   var v=new DrawingVisual();using(var dc=v.RenderOpen())for(int i=0;i<48;i++)dc.DrawImage(f[i],new Rect(i%8*192,i/8*208,192,208));var atlas=new RenderTargetBitmap(3072,2496,192,192,PixelFormats.Pbgra32);atlas.Render(v);Save(atlas,"music-seated-"+skin);
   v=new DrawingVisual();using(var dc=v.RenderOpen()){dc.DrawRectangle(Brushes.White,null,new Rect(0,0,768,416));for(int i=0;i<4;i++)dc.DrawImage(f[6+i*12],new Rect(i*192,0,192,208));for(int i=0;i<4;i++){dc.PushClip(new RectangleGeometry(new Rect(i*192,208,192,208)));dc.DrawImage(f[6+i*12],new Rect(i*192-68,208-280,384,416));dc.Pop();}}var check=new RenderTargetBitmap(1536,832,192,192,PixelFormats.Pbgra32);check.Render(v);Save(check,"music-legs-"+skin);
  }
 }
 static void PhaseTests(){
  foreach(string legacy in MusicReactions.Modes){var c=new Config{MusicReactionMode=legacy};c.Validate();Check(MusicReactions.Action(c,"",false)==(legacy=="off"?"off":"quiet")&&MusicReactions.Action(c,"",true)==legacy,"旧版出现规则迁移："+legacy);}
  var mixed=new Config{MusicNormalAction="mixed",MusicChorusAction="lively"};mixed.Validate();Check(MusicReactions.ChooseAction(mixed,"",false,0)=="music-quiet"&&MusicReactions.ChooseAction(mixed,"",false,45)=="music-gentle"&&MusicReactions.ChooseAction(mixed,"",false,60)=="music-quiet","平时坐姿与轻微应援按稳定周期交替");Check(MusicReactions.ChooseAction(mixed,"",true,2)=="music-lively","副歌动作独立于平时动作");mixed.MusicChorusAction="same";Check(MusicReactions.ChooseAction(mixed,"",true,50)=="music-gentle","副歌保持平时动作可继续交替");mixed.MusicSongPreferences=new[]{new SongMusicPreference{Id="12",NormalAction="gentle",ChorusAction="quiet"}};Check(MusicReactions.ChooseAction(mixed,"12",false)=="music-gentle"&&MusicReactions.ChooseAction(mixed,"12",true)=="music-quiet","单曲可分别覆盖两个阶段");mixed.MusicSongPreferences[0].ChorusAction="same";Check(MusicReactions.ChooseAction(mixed,"12",true)=="music-gentle","单曲副歌保持该曲的平时设置");var copy=PreferenceTransfer.Import(PreferenceTransfer.Export(mixed,false));Check(copy.MusicNormalAction=="mixed"&&copy.MusicChorusAction=="same"&&copy.MusicSongPreferences[0].NormalAction=="gentle","两个阶段及交替偏好可迁移");
  foreach(string state in new[]{"music-quiet","music-gentle","music-lively"}){int first=MusicReactions.Frame(state,0,false);var seen=new HashSet<int>();for(int ms=0;ms<6000;ms+=30){int f=MusicReactions.Frame(state,ms,false);Check(f>=first&&f<first+6,"时间线帧索引合法");seen.Add(f);}Check(seen.Count==6,"每个动作实际播放六张姿势："+state);Check(MusicReactions.Frame(state,double.NaN,false)==first&&MusicReactions.Frame(state,10000,true)==first,"异常时间与减少动态效果稳定");}
  Check(MusicReactions.PlaybackFrame("music-quiet",0,false,false)==18&&MusicReactions.PlaybackFrame("music-quiet",719,false,false)==23&&MusicReactions.PlaybackFrame("music-quiet",720,false,false)==0,"先坐下再进入坐姿循环");Check(MusicReactions.PlaybackFrame("music-gentle",0,false,true)==23&&MusicReactions.PlaybackFrame("music-gentle",719,false,true)==18&&MusicReactions.PlaybackFrame("music-gentle",720,false,true)==6,"从坐姿到应援先起身");
  byte[] data=new byte[40*40*4];for(int y=5;y<30;y++)for(int x=5;x<25;x++){int p=(y*40+x)*4;data[p+2]=data[p+3]=255;}data[(6*40+33)*4+3]=255;data[(6*40+33)*4]=255;int fringe=(15*40+4)*4;data[fringe+2]=data[fringe+3]=64;var atlas=BitmapSource.Create(40,40,96,96,PixelFormats.Pbgra32,null,data,160);var crop=MusicSpriteCrop.Extract(atlas,new Int32Rect(0,0,40,40));byte[] actual=new byte[data.Length];crop.CopyPixels(actual,160,0);Check(actual[(6*40+33)*4+3]==0&&actual[fringe+3]==64&&actual[(15*40+15)*4+3]==255,"裁切排除邻格碎片并保留原始抗锯齿透明边缘");
 }

 static void QualitySheets(){foreach(string skin in new[]{"kiana-winter-wish-round","kiana-fiery-wishing-star-round","time-runner-kiana-round"}){var frames=MusicSprites.Load(skin);var packed=new DrawingVisual();using(var dc=packed.RenderOpen()){for(int i=0;i<24;i++)dc.DrawImage(frames[i],new Rect(i%6*192,i/6*208,192,208));}var atlas=new RenderTargetBitmap(2304,1664,192,192,PixelFormats.Pbgra32);atlas.Render(packed);Save(atlas,"music-frames-"+skin);foreach(bool dark in new[]{false,true}){var v=new DrawingVisual();using(var dc=v.RenderOpen()){dc.DrawRectangle(dark?new SolidColorBrush(Color.FromRgb(30,32,40)):Brushes.White,null,new Rect(0,0,1152,832));dc.DrawImage(atlas,new Rect(0,0,1152,832));}var output=new RenderTargetBitmap(1152,832,96,96,PixelFormats.Pbgra32);output.Render(v);Save(output,"music-qa-"+skin+(dark?"-dark":"-light"));}}}
 static void VerifyFrameEdges(BitmapSource frame){var bgra=new FormatConvertedBitmap(frame,PixelFormats.Bgra32,null,0);int width=frame.PixelWidth,height=frame.PixelHeight;var pixels=new byte[width*height*4];bgra.CopyPixels(pixels,width*4,0);bool clear=true;for(int x=0;x<width;x++)if(pixels[x*4+3]>8||pixels[((height-1)*width+x)*4+3]>8)clear=false;for(int y=0;y<height;y++)if(pixels[(y*width)*4+3]>8||pixels[(y*width+width-1)*4+3]>8)clear=false;Check(clear,"完整轮廓在输出画布内，四边无裁切");}

 [STAThread]static int Main(string[] args){Store.Root=args[0];Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false,NoticeSound=false});var app=new Application{ShutdownMode=ShutdownMode.OnLastWindowClose};var pet=new PetWindow(true);bool passed=false;
 pet.Loaded+=async delegate{try{await Task.Delay(1100);((DispatcherTimer)Field(pet,"animation")).Stop();var w=app.Windows.OfType<SettingsWindow>().Single();
 PhaseTests();var config=new Config();Check(config.MusicReactionMode=="quiet"&&config.MusicChorusEnabled,"默认安静听歌且副歌查询可关闭");var ranges=ChorusLibrary.Parse("{\"code\":200,\"chorus\":[{\"id\":123,\"startTime\":30000,\"endTime\":60000},{\"id\":999,\"startTime\":1,\"endTime\":2}]}","123");Check(ranges.Length==1&&ranges[0].Start==30&&ranges[0].End==60,"解析实测格式并过滤其他歌曲与毫秒单位");Check(ChorusLibrary.Parse("{\"code\":200,\"data\":[{\"id\":123,\"startTime\":-1,\"endTime\":60000}]}","123").Length==0,"拒绝无效副歌区间");bool rejected=false;try{ChorusLibrary.Parse("{\"code\":500}","123");}catch{rejected=true;}Check(rejected,"异常响应不会当作已成功识别");
 var utc=DateTime.UtcNow;var state=new MusicState{Connected=true,Playing=true,Id="123",Title="示例抒情歌曲",Position=35,Duration=180,At=utc};var planner=new MusicReactionPlanner();Check(planner.Choose(state,config,ranges,0,utc,true)==null,"连续播放门槛抑制切歌闪动");Check(planner.Choose(state,config,ranges,9,utc,true)=="music-quiet","安静模式在副歌仍保持耳机");config.MusicReactionMode="gentle";Check(planner.Choose(state,config,ranges,10,utc,true)=="music-gentle","副歌轻柔挥棒");config.MusicSongPreferences=new[]{new SongMusicPreference{Id="123",Mode="lively",Start=40,End=50}};Check(planner.Choose(state,config,ranges,11,utc,true)=="music-quiet","手动副歌区间优先于远程数据");state.Position=45;Check(planner.Choose(state,config,ranges,12,utc,true)=="music-lively","本曲活力偏好优先于整体轻柔");state.Position=80;Check(planner.Choose(state,config,ranges,13,utc,true)=="music-quiet","拖动到副歌外立即回到倾听");state.Position=42;Check(planner.Choose(state,config,ranges,14,utc,true)=="music-lively","回拖进入副歌可重新应援");Check(planner.Choose(state,config,ranges,15,utc,false)==null,"任务与互动优先级可中断");state.Playing=false;Check(planner.Choose(state,config,ranges,16,utc,true)=="music-quiet"&&planner.Choose(state,config,ranges,20,utc,true)==null,"短暂停顿收棒，超过三秒停止音乐动作");state.Playing=true;Check(planner.Choose(state,config,ranges,21,utc,true)==null,"恢复播放重新等待稳定门槛");Check(planner.Choose(state,config,ranges,30,utc.AddSeconds(10),true)==null,"过期连接不能维持音乐状态");
 config.MusicSongPreferences=new[]{new SongMusicPreference{Id="123",Mode="lively"},new SongMusicPreference{Id="123",Mode="quiet"},new SongMusicPreference{Id="bad",Mode="lively"}};config.Validate();Check(config.MusicSongPreferences.Length==1&&config.MusicSongPreferences[0].Mode=="quiet","偏好去重并校验歌曲 ID");var transferred=PreferenceTransfer.Import(PreferenceTransfer.Export(config,false));Check(transferred.MusicSongPreferences[0].Mode=="quiet","按歌曲偏好可以迁移");
 foreach(string skin in new[]{"kiana-winter-wish-round","kiana-fiery-wishing-star-round","time-runner-kiana-round"}){var frames=MusicSprites.Load(skin);Check(frames!=null&&frames.Length==24&&frames.All(f=>f.PixelWidth==768&&f.PixelHeight==832),"24 帧与脸宽归一化："+skin);foreach(var frame in frames){VerifyFrameEdges(frame);var bgra=new FormatConvertedBitmap(frame,PixelFormats.Bgra32,null,0);byte[] pixels=new byte[frame.PixelWidth*frame.PixelHeight*4];bgra.CopyPixels(pixels,frame.PixelWidth*4,0);Check(pixels[3]==0&&pixels[(frame.PixelWidth-1)*4+3]==0,"图集角落保持实际透明");}pet.SelectSkin(skin);Set(pet,"state","music-lively");Set(pet,"lastFrame",-1);Call(pet,"DrawAnimation",0d);Check(ReferenceEquals(((Image)Field(pet,"sprite")).Source,frames[12])&&Field(pet,"activeAlignment")==null,"新动作不套用旧动作缩放："+skin);}
 RigTests();ContactSheet();QualitySheets();var otherSkinPreview=new MusicAnimationPreview("kiana-winter-wish-round","quiet");otherSkinPreview.Show();var liveSkin=MusicSprites.Load("time-runner-kiana-round");await Task.Delay(160);Check(ReferenceEquals(liveSkin,MusicSprites.Load("time-runner-kiana-round")),"Different skin preview retains its cache without evicting live pet frames");otherSkinPreview.Close();pet.Music.Current=state;state.Playing=true;state.Position=20;state.At=DateTime.UtcNow;pet.SetSongMusicMode("gentle");pet.MarkMusicChorus(false);state.Position=55;pet.MarkMusicChorus(true);var saved=MusicReactions.Preference(Store.Load(),"123");Check(saved.Mode=="gentle"&&saved.Start>=20&&saved.End>=55,"真实设置入口保存本曲模式和区间");pet.ClearMusicChorus();Check(MusicReactions.Preference(pet.Settings,"123").Start==-1,"可清除手动区间并恢复远程时间");
 w.NavigateCategory("音乐","音乐动作");w.UpdateStatus();w.Capture(Path.Combine(Store.Root,"music-reaction-settings.png"));Check(w.ActiveCategory=="音乐"&&((TextBlock)Field(w,"musicReactionStatus")).Text.Contains("轻微挥棒"),"设置展示当前模式与来源");string before=File.ReadAllText(Path.Combine(Store.Root,"settings.json"));pet.PreviewMusicAnimation("gentle");await Task.Delay(180);var preview=app.Windows.OfType<MusicAnimationPreview>().Single();Check(preview.Sprite.Source!=null,"动作预览显示实际素材");preview.Close();Check(before==File.ReadAllText(Path.Combine(Store.Root,"settings.json")),"预览不修改偏好");var music=new MusicWindow(pet);music.Show();pet.OpenMusicReactionMenu(music);await Task.Delay(100);var menu=(ContextMenu)Field(pet,"toolbarMenu");Check(menu.IsOpen&&((MenuItem)menu.Items[0]).IsEnabled,"音乐栏菜单真实打开且可设置本曲");var songMenu=(MenuItem)menu.Items[0];((MenuItem)((MenuItem)songMenu.Items[1]).Items[4]).RaiseEvent(new RoutedEventArgs(MenuItem.ClickEvent));Check(MusicReactions.Preference(pet.Settings,"123").ChorusAction=="lively","菜单活力应援选项保存本曲偏好");Call(pet,"ClosePetMenu");music.Close();passed=true;
 }catch(Exception e){Store.Atomic("error.json",new{error=e.ToString()});}finally{Store.Atomic("music-reaction-tests.json",new{passed,checks});foreach(var window in app.Windows.Cast<Window>().Where(window=>window!=pet).ToArray())window.Close();pet.Close();}};app.Run(pet);return passed?0:1;
 }
}
