using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Controls.Primitives;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Threading;using KianaPet;
class NotificationCenterTests {
 static readonly List<string> checks=new List<string>();static void Check(bool value,string name){if(!value)throw new Exception(name);checks.Add(name);}static object Field(object o,string n){return o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}static void Refresh(NoticeCenter c){c.GetType().GetMethod("Refresh",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(c,new object[]{false});}
 static void Capture(FrameworkElement element,string name,int dpi){element.UpdateLayout();var b=new RenderTargetBitmap((int)Math.Ceiling(element.ActualWidth*dpi/96d),(int)Math.Ceiling(element.ActualHeight*dpi/96d),dpi,dpi,PixelFormats.Pbgra32);var drawing=new DrawingVisual();using(var dc=drawing.RenderOpen()){var window=Window.GetWindow(element);dc.DrawRectangle(window==null?PetPalette.Brush(PetPalette.Background):window.Background,null,new Rect(0,0,element.ActualWidth,element.ActualHeight));dc.DrawRectangle(new VisualBrush(element),null,new Rect(0,0,element.ActualWidth,element.ActualHeight));}b.Render(drawing);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(b));using(var f=File.Create(Path.Combine(Store.Root,name+".png")))encoder.Save(f);}
 [STAThread]static int Main(string[] args){Store.Root=args[0];Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false,NoticeSound=false});var app=new Application{ShutdownMode=ShutdownMode.OnLastWindowClose};var pet=new PetWindow(true);bool passed=false;
 pet.Loaded+=async delegate{try{await Task.Delay(1100);((DispatcherTimer)Field(pet,"animation")).Stop();app.Windows.OfType<SettingsWindow>().Single().Close();var now=DateTime.UtcNow;pet.Settings.LinkChatGPT=true;pet.Link.Current=new BridgeState{Connected=true,AppOpen=true,NotificationSource="mini",Label="ChatGPT 已连接",CanNotifications=true,NotificationCount=3,At=now,LastSuccessAt=now,Notices=new[]{new BridgeNotice{Id="review",Title="确认桌宠通知界面的更新方案",State="waiting",UpdatedAt=now},new BridgeNotice{Id="running",Title="整理本周工作与接下来的安排",State="running",UpdatedAt=now},new BridgeNotice{Id="done",Title="桌宠配色与图标方案已准备好",State="review",UpdatedAt=now}}};
 int opens=0;pet.TaskNotices.RegisterAction("本机构建","open",delegate{opens++;});pet.TaskNotices.Publish(new TaskNotice{Source="本机构建",TaskId="build",Title="源码构建完成，可以查看结果",Status="succeeded",ActionId="open"});pet.OpenNoticeCenter();await Task.Delay(100);var center=app.Windows.OfType<NoticeCenter>().Single();((DispatcherTimer)Field(center,"timer")).Stop();var cards=(Dictionary<string,NoticeCard>)Field(center,"cards");var card=cards["gpt:running"];var root=(FrameworkElement)center.Content;
 foreach(var style in NoticeSourceIcons.Styles){pet.Settings.NoticeSourceStyle=style;Refresh(center);Check(((Image)Field(card,"inlineIcon")).Visibility==((style=="icon-name"||style=="icon-only")?Visibility.Visible:Visibility.Collapsed),"行内图标布局："+style);Check(((Image)Field(card,"leadingIcon")).Visibility==(style=="leading-icon"?Visibility.Visible:Visibility.Collapsed),"左侧图标布局："+style);Check(((TextBlock)Field(card,"label")).Text.Contains("ChatGPT")== (style=="icon-name"||style=="name-only"),"来源名显示："+style);Check(((Image)Field(card,"leadingIcon")).ToolTip.ToString()=="ChatGPT","隐藏名称仍可查看来源");Capture(root,"center-"+style,144);}
 Check(card.ToolTip.ToString().Contains("更新于"),"更新时间保留在悬浮提示");Check(card.Read.Visibility==Visibility.Collapsed,"不提供未经支持的 ChatGPT 已读操作");
 pet.Settings.NoticeSourceStyle="leading-icon";PetPalette.Dark=true;Refresh(center);Capture(root,"center-dark",144);var source=(ComboBox)Field(center,"source");source.IsDropDownOpen=true;await Task.Delay(80);var popup=(Popup)source.Template.FindName("PART_Popup",source);Check(popup.IsOpen&&source.ItemContainerGenerator.ContainerFromIndex(0)!=null,"新下拉样式显示真实来源选项");Capture((FrameworkElement)popup.Child,"center-dropdown-dark",144);source.IsDropDownOpen=false;PetPalette.Dark=false;
 center.Width=460;center.Height=500;pet.Link.Current.Notices[1].Title=new string('长',140);Refresh(center);center.UpdateLayout();var title=(TextBlock)Field(card,"title");Check(title.ActualHeight>40&&title.ActualWidth>100,"窄窗口长标题换行且留出操作空间");Check(card.Open.TranslatePoint(new Point(card.Open.ActualWidth,0),root).X<=root.ActualWidth,"窄窗口操作不越界");Capture(root,"center-narrow",144);
 center.Width=660;center.Height=740;pet.Link.Current.Notices[1].Title="整理本周工作与接下来的安排";pet.Settings.NoticeSourceStyle="icon-name";Refresh(center);foreach(int dpi in new[]{96,144,192})Capture(root,"center-scale-"+dpi,dpi);
 MotionSettings.Reduced=true;pet.Settings.MusicEnabled=true;pet.Settings.NoticePreviewFollowMusic=true;pet.Settings.MusicTintMode="cover-gradient";pet.Settings.MusicTintStrength=100;pet.Music.Current=new MusicState{Connected=true,Id="fixture",Cover="fixture-cover",At=DateTime.UtcNow};var library=Field(pet,"musicLibrary");library.GetType().GetField("id",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(library,"id:fixture");library.GetType().GetField("coverUrl",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(library,"fixture-cover");var art=BitmapSource.Create(2,1,96,96,PixelFormats.Bgra32,null,new byte[]{80,120,240,255,230,160,90,255},8);art.Freeze();library.GetType().GetProperty("Cover").SetValue(library,art,null);Refresh(center);var expected=new Border();new MusicSurfaceAppearance().Apply(expected,art,pet.Settings,true);Check(card.Background is LinearGradientBrush&&((LinearGradientBrush)card.Background).GradientStops[0].Color==((LinearGradientBrush)expected.Background).GradientStops[0].Color,"通知中心沿用音乐渐变及浓度");Capture(root,"center-music",144);pet.Music.Current.At=now.AddMinutes(-1);Refresh(center);Check(card.Background is SolidColorBrush,"音乐状态过期恢复主题配色");
 var local=cards.Values.Single(c=>!c.Row.ChatGPT);local.Mute.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(local.Row.TaskMuted&&((TextBlock)Field(local,"label")).Text.Contains("已静音"),"任务静音生效并在卡片标记");local.Mute.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));local.Read.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(!local.Row.Unread&&!local.Read.IsEnabled,"已读操作更新任务与按钮");local.Open.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(opens==1,"紧凑打开按钮仍执行注册动作");source.SelectedItem="本机构建";Check(center.VisibleTaskCount==1,"来源筛选准确");((CheckBox)Field(center,"unread")).IsChecked=true;Refresh(center);Check(center.VisibleTaskCount==0&&((TextBlock)Field(center,"empty")).Text.Contains("筛选条件"),"筛选空状态说明原因");passed=true;
 }catch(Exception e){Store.Atomic("error.json",new{error=e.ToString()});}finally{Store.Atomic("notification-center-tests.json",new{passed,checks});foreach(var w in app.Windows.Cast<Window>().Where(w=>w!=pet).ToArray())w.Close();pet.Close();}};app.Run(pet);return passed?0:1;
 }
}
