using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using KianaPet;
class ReliabilityTests {
 static List<string> checks=new List<string>();static void Check(bool b,string name){if(!b)throw new Exception(name);checks.Add(name);}static BridgeState State(DateTime at,bool fallback){return new BridgeState{At=at,AppOpen=true,Connected=true,CanChat=true,CanVoice=true,MainReady=true,MiniStatus="ready",NotificationSource=fallback?"main":"mini",Code=fallback?"fallback":"connected"};}
 static int Main(string[] args){Store.Root=args[0];try{
  DateTime now=DateTime.UtcNow;var s=State(now,false);var h=LinkHealth.Read(s,true,now);Check(h.Chat&&h.Voice&&h.Notifications&&!h.Degraded,"零通知时仍确认通知来源正常，不把无角标当断线");s.CanVoice=false;h=LinkHealth.Read(s,true,now);Check(h.Chat&&!h.Voice&&h.Notifications&&h.Degraded,"聊天语音通知分别判断");s=State(now,true);Check(LinkHealth.Read(s,true,now).NotificationText.Contains("备用")&&LinkHealth.Read(s,true,now).Degraded,"备用来源明确标记为降级");s.Stale=true;Check(!LinkHealth.Read(s,true,now).Notifications,"缓存状态不冒充通知已同步");s=State(now,false);Check(!LinkHealth.Read(s,true,now.AddSeconds(11)).Chat,"过期入口不显示可用");Check(!LinkHealth.Read(s,false,now).Degraded,"主动关闭联动不告警");
  var tracker=new LinkIncidentTracker();Check(!tracker.Update(State(now,true),true,now,true),"短异常不打扰");Check(!tracker.Update(State(now.AddSeconds(29),true),true,now.AddSeconds(29),true),"持续三十秒前不提示");Check(tracker.Update(State(now.AddSeconds(31),true),true,now.AddSeconds(31),true),"持续异常只提示一次");var timeout=State(now.AddSeconds(90),true);timeout.Code="timeout";timeout.Connected=false;Check(!tracker.Update(timeout,true,now.AddSeconds(90),true),"异常代码变化不反复提示");tracker.Update(State(now.AddSeconds(100),false),true,now.AddSeconds(100),true);tracker.Update(State(now.AddSeconds(110),true),true,now.AddSeconds(110),true);Check(!tracker.Update(State(now.AddSeconds(160),true),true,now.AddSeconds(160),true),"短暂假恢复不重置提醒");tracker.Update(State(now.AddSeconds(170),false),true,now.AddSeconds(170),true);tracker.Update(State(now.AddSeconds(191),false),true,now.AddSeconds(191),true);tracker.Update(State(now.AddSeconds(200),true),true,now.AddSeconds(200),true);Check(tracker.Update(State(now.AddSeconds(231),true),true,now.AddSeconds(231),true),"持续恢复后二次独立异常可提醒");var quiet=new LinkIncidentTracker();quiet.Update(State(now,true),true,now,false);Check(!quiet.Update(State(now.AddSeconds(31),true),true,now.AddSeconds(31),false)&&!quiet.Update(State(now.AddSeconds(60),true),true,now.AddSeconds(60),true),"静默期间不提示，结束后不补播旧异常");
  using(var bridge=new Bridge()){var publish=typeof(Bridge).GetMethod("PublishState",BindingFlags.NonPublic|BindingFlags.Instance);publish.Invoke(bridge,new object[]{State(now,false)});var last=bridge.Current.LastVoiceAt;Check(last.HasValue&&bridge.Current.LastNotificationsAt.HasValue,"真实发布记录各入口有效时间");publish.Invoke(bridge,new object[]{new BridgeState{AppOpen=true,Code="timeout"}});Check(bridge.Current.LastVoiceAt==last&&!bridge.Current.Connected,"失败轮询不会刷新成功时间");}
  var current=new Config{Theme="light",LaunchChatGPTOnStart=false,LaunchMusicOnStart=false,X=-900,Y=120,HasPosition=true,MusicPosition="free",MusicX=-800,MusicY=400,MusicHasPosition=true,RecoverHotkeyEnabled=false,QuietApps=new[]{"code"},CompletionNoticeSeconds=12};var remote=new Config{Theme="dark",LaunchChatGPTOnStart=true,LaunchMusicOnStart=true,X=2000,Y=500,HasPosition=true,MusicPosition="below",RecoverHotkeyEnabled=true,QuietApps=new[]{"word"},CompletionNoticeSeconds=8};var full=PreferenceReview.Parse(PreferenceTransfer.Export(remote,true));Check(full.Version==Maintenance.Version&&full.ExportedAt.HasValue,"偏好包记录程序版本和导出时间");var merged=PreferenceReview.Merge(current,full,false,false);Check(merged.Theme=="dark"&&merged.CompletionNoticeSeconds==8,"通用偏好正常合并");Check(!merged.LaunchChatGPTOnStart&&!merged.LaunchMusicOnStart&&!merged.RecoverHotkeyEnabled&&merged.X==-900&&merged.MusicPosition=="free"&&merged.QuietApps[0]=="code","默认保护启动快捷键软件名单与位置");Check(PreferenceReview.Differences(current,merged).All(d=>!PreferenceReview.Local(d.Key)),"预览差异仅包含实际允许改变的项");var local=PreferenceReview.Merge(current,full,true,false);Check(local.LaunchChatGPTOnStart&&local.RecoverHotkeyEnabled&&local.X==-900&&local.MusicPosition=="free","本机配置与位置可独立导入");var position=PreferenceReview.Merge(current,full,false,true);Check(position.X==2000&&!position.LaunchChatGPTOnStart,"只导入位置不隐含打开其他应用");var commonText=PreferenceTransfer.Export(remote,false);var common=PreferenceReview.Parse(commonText);Check(common.Scope=="common"&&!common.PresentKeys.Any(PreferenceReview.Local)&&!commonText.Contains("word"),"通用导出不携带本机应用名单及选项");Check(!PreferenceReview.Merge(current,common,true,true).LaunchChatGPTOnStart,"通用包无法借勾选导入不存在的本机配置");
  var legacy=PreferenceReview.Parse("{\"Schema\":1,\"Skin\":\"kiana-fiery-wishing-star-round\",\"Size\":160,\"Theme\":\"dark\"}");Check(PreferenceReview.Merge(current,legacy,true,true).CompletionNoticeSeconds==12,"旧包缺失字段保留本机值");Check(PreferenceReview.Merge(current,legacy,true,true).X==-900,"缺失坐标不被默认坐标覆盖");var unknown=PreferenceReview.Parse("{\"Schema\":1,\"Skin\":\"kiana-fiery-wishing-star-round\",\"Size\":176,\"FutureOption\":42}");Check(unknown.UnknownKeys.Length==1,"未知新选项单独提示并跳过");Check(PreferenceReview.Differences(current,PreferenceTransfer.Copy(current)).Length==0,"相同设置不产生虚假差异");merged.QuietApps[0]="changed";Check(current.QuietApps[0]=="code","合并快照与当前设置不共享可变数组");
  var partial=State(now,false);partial.NotificationCount=2;partial.CanNotifications=true;BridgeDiagnostics.Failure(partial,new Exception("Mini 接口执行失败"));Check(!partial.Connected&&!partial.CanVoice&&!partial.CanChat&&partial.NotificationCount==0,"读取中途失败不保留未确认的入口或角标");
  var defaults=new Config();Check(!EffectPreviewRules.Completion(defaults,false).Bubble&&!EffectPreviewRules.Completion(defaults,false).Sound,"默认完成静默在预览中如实反映");defaults.NoticeSilentSuccess=false;defaults.NoticeSound=true;defaults.CompletionNoticeSeconds=3;var preview=EffectPreviewRules.Completion(defaults,false);Check(preview.Bubble&&preview.Sound&&preview.Seconds==3,"预览使用当前时长与声音设置");defaults.NoticeQuiet=true;Check(!EffectPreviewRules.Completion(defaults,false).Sound&&!EffectPreviewRules.Completion(defaults,false).Bubble,"全静默抑制试播声音和气泡");defaults.NoticeQuiet=false;Check(!EffectPreviewRules.Completion(defaults,true).Sound,"免打扰抑制自动试播声音");
  Store.Atomic("reliability-tests.json",new{passed=true,checks});return 0;
 }catch(Exception e){Store.Atomic("reliability-tests.json",new{passed=false,checks,error=e.ToString()});return 1;}}
}
