using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Threading;using KianaPet;
class ReliabilityUiTests {
 static List<string> checks=new List<string>();static void Check(bool value,string name){if(!value)throw new Exception(name);checks.Add(name);}static object Field(object o,string n){return o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}static object Call(object o,string n,params object[] a){return o.GetType().GetMethod(n,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(o,a);}static void Capture(Window w,string label,int dpi=144){w.UpdateLayout();var b=new RenderTargetBitmap((int)Math.Ceiling(w.ActualWidth*dpi/96d),(int)Math.Ceiling(w.ActualHeight*dpi/96d),dpi,dpi,PixelFormats.Pbgra32);b.Render(w);var e=new PngBitmapEncoder();e.Frames.Add(BitmapFrame.Create(b));using(var f=File.Create(Path.Combine(Store.Root,label+".png")))e.Save(f);}
 [STAThread]static int Main(string[] args){Store.Root=args[0];Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false,NoticeSound=false});var app=new Application{ShutdownMode=ShutdownMode.OnLastWindowClose};var pet=new PetWindow(true);bool passed=false;
 pet.Loaded+=async delegate{try{await Task.Delay(1100);((DispatcherTimer)Field(pet,"animation")).Stop();var settings=app.Windows.OfType<SettingsWindow>().Single();settings.NavigateCategory("效果预览","");string saved=File.ReadAllText(Path.Combine(Store.Root,"settings.json"));var bridge=pet.Link.Current;int realNotices=pet.TaskNotices.Snapshot().Length;
 foreach(string state in new[]{"running","review","stale","waiting","idle"}){settings.PreviewEffect(state);Check(settings.PreviewState==state,"模拟状态可切换："+state);}Check(pet.Link.Current==bridge&&realNotices==pet.TaskNotices.Snapshot().Length,"预览不改变联动状态或真实任务列表");Check(saved==File.ReadAllText(Path.Combine(Store.Root,"settings.json")),"切换模拟状态不写偏好");pet.Settings.NoticeSilentSuccess=false;pet.Settings.CompletionNoticeSeconds=2;settings.PreviewCompletion();Check(((Border)Field(settings,"effectBubble")).Visibility==Visibility.Visible,"按当前偏好显示示例气泡");Capture(settings,"effect-preview");await Task.Delay(2250);Check(((Border)Field(settings,"effectBubble")).Visibility==Visibility.Hidden,"气泡按设定时长自动结束");settings.PreviewCompletion();settings.NavigateCategory("ChatGPT 联动","");await Task.Delay(60);Check(!((DispatcherTimer)Field(settings,"effectTimer")).IsEnabled,"离开预览页面释放计时器");settings.UpdateStatus();Capture(settings,"connection-details");settings.Close();
 var now=DateTime.UtcNow;pet.Settings.LinkChatGPT=true;pet.Link.Current=new BridgeState{AppOpen=true,Connected=true,MainReady=true,Code="fallback",NotificationSource="main",Label="备用来源 · 思考中",CanNotifications=true,NotificationCount=22,LastSuccessAt=now,At=now,Notices=Enumerable.Range(0,22).Select(i=>new BridgeNotice{Id="task-"+i,Title="示例任务 "+i,State=i==0?"waiting":i<18?"running":"review",UpdatedAt=now.AddSeconds(-i)}).ToArray()};pet.OpenNoticeCenter();await Task.Delay(150);var center=app.Windows.OfType<NoticeCenter>().Single();((DispatcherTimer)Field(center,"timer")).Stop();Check(center.VisibleTaskCount==22,"分组列表展示全部不同任务");var groups=(StackPanel[])Field(center,"groups");Check(groups[0].Visibility==Visibility.Visible&&groups[1].Visibility==Visibility.Visible&&groups[2].Visibility==Visibility.Visible,"需要处理、进行中、完成未读分别分组");Capture(center,"grouped-notices");
 var cards=(Dictionary<string,NoticeCard>)Field(center,"cards");var selected=cards["gpt:task-8"];selected.Open.Focus();selected.BringIntoView();await Task.Delay(100);var scroll=(ScrollViewer)Field(center,"scroll");scroll.ScrollToVerticalOffset(scroll.VerticalOffset+25);await Task.Delay(60);double y=selected.TranslatePoint(new Point(),scroll).Y;var focused=Keyboard.FocusedElement;pet.Link.Current.Notices[2].Title="另一任务的标题在后台变更，增加文字但不重建当前卡片";pet.Link.Current.Notices=pet.Link.Current.Notices.Concat(new[]{new BridgeNotice{Id="new",Title="新插入的任务",State="running",UpdatedAt=now.AddSeconds(1)}}).ToArray();pet.Link.Current.NotificationCount++;Call(center,"Refresh",false);await Task.Delay(100);Check(ReferenceEquals(selected,cards["gpt:task-8"]),"后台更新复用原任务卡片");Check(ReferenceEquals(Keyboard.FocusedElement,focused),"后台更新保留键盘焦点");Check(Math.Abs(selected.TranslatePoint(new Point(),scroll).Y-y)<3,"上方插入任务保持正在阅读的位置");
 pet.Link.Current.Notices.First(n=>n.Id=="task-8").State="review";Call(center,"Refresh",false);await Task.Delay(100);Check(ReferenceEquals(Keyboard.FocusedElement,focused)&&ReferenceEquals(selected,cards["gpt:task-8"]),"任务跨组移动保留卡片和焦点");var status=(ComboBox)Field(center,"status");status.SelectedIndex=2;Check(center.VisibleTaskCount==5,"已完成筛选准确且不会被刷新重置");Call(center,"Refresh",false);Check(status.SelectedIndex==2,"后台轮询保留筛选");status.SelectedIndex=0;
 pet.Link.Current=LinkResilience.KeepLast(new BridgeState{AppOpen=true,Code="timeout"},pet.Link.Current,DateTime.UtcNow,30);Call(center,"Refresh",false);Check(cards.Values.All(c=>!c.Open.IsEnabled)&&((TextBlock)Field(center,"connection")).Text.Contains("上次状态"),"断线保留卡片但暂停跳转");center.Close();
 pet.Settings.LinkChatGPT=false;pet.Settings.Theme="light";pet.Save();saved=File.ReadAllText(Path.Combine(Store.Root,"settings.json"));var remote=PreferenceTransfer.Copy(pet.Settings);remote.Theme="dark";remote.LaunchChatGPTOnStart=true;remote.LaunchMusicOnStart=true;remote.X=99999;remote.Y=-99999;var info=PreferenceReview.Parse(PreferenceTransfer.Export(remote,true));var review=new PreferenceReviewWindow(pet,info,false);review.Show();await Task.Delay(80);Capture(review,"import-differences");Check(!review.Proposed.LaunchChatGPTOnStart&&review.Proposed.X==pet.Settings.X&&review.Proposed.Theme=="dark","导入预览默认保护本机选项");review.Close();Check(saved==File.ReadAllText(Path.Combine(Store.Root,"settings.json")),"关闭导入预览不改偏好");
 review=new PreferenceReviewWindow(pet,info,false);review.Loaded+=delegate{review.Dispatcher.BeginInvoke(new Action(delegate{Call(review,"Apply");}),DispatcherPriority.ApplicationIdle);};Check(review.ShowDialog()==true,"确认应用完成导入");Check(pet.Settings.Theme=="dark"&&!pet.Settings.LaunchChatGPTOnStart&&!pet.Settings.LaunchMusicOnStart,"只应用预览允许的通用修改");Check(Directory.GetFiles(Path.Combine(Store.Root,"preference-backups"),"*.json").Length>0,"应用前自动备份旧偏好");Check(Store.Load().Theme=="dark","合并结果实际持久化");passed=true;
 }catch(Exception e){Store.Atomic("error.json",new{error=e.ToString()});}finally{Store.Atomic("reliability-ui-tests.json",new{passed,checks});foreach(var w in app.Windows.Cast<Window>().Where(w=>w!=pet).ToArray())w.Close();pet.Close();}};app.Run(pet);return passed?0:1;
 }
}
