using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Threading;using KianaPet;
class SettingsSidebarTests {
 static readonly List<string> checks=new List<string>();static void Check(bool value,string name){if(!value)throw new Exception(name);checks.Add(name);}static object Field(object o,string n){return o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}static void Set(object o,string n,object v){o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).SetValue(o,v);}static object Call(object o,string n,params object[] a){return o.GetType().GetMethod(n,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(o,a);}static string[] Names(SettingsWindow w){return ((ListBox)Field(w,"categoryList")).Items.Cast<ListBoxItem>().Select(i=>(string)((TabItem)i.Tag).Header).ToArray();}
 [STAThread]static int Main(string[] args){Store.Root=args[0];Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false,NoticeSound=false});var app=new Application{ShutdownMode=ShutdownMode.OnLastWindowClose};var pet=new PetWindow(true);bool passed=false;
 pet.Loaded+=async delegate{try{await Task.Delay(1100);((DispatcherTimer)Field(pet,"animation")).Stop();var w=app.Windows.OfType<SettingsWindow>().Single();var nav=(ListBox)Field(w,"categoryList");Check(Names(w).SequenceEqual(SettingsCategoryOrder.Recommended),"旧偏好获得完整推荐顺序且不遗漏分类");Check(w.ActiveCategory=="常用","打开设置仍默认常用页");w.Capture(Path.Combine(Store.Root,"sidebar-recommended.png"));var sort=(Button)Field(w,"sortCategories");sort.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check((bool)Field(w,"sortingCategories")&&((StackPanel)Field(w,"categorySortTools")).IsVisible,"排序按钮进入可拖动模式");w.NavigateCategory("音乐","");var tabs=(TabControl)Field(w,"settingsTabs");var current=tabs.SelectedItem;var page=(ScrollViewer)((TabItem)current).Content;page.ScrollToVerticalOffset(90);w.UpdateLayout();double offset=page.VerticalOffset;
 ((Button)Field(w,"moveCategoryUp")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(Names(w)[1]=="音乐"&&w.ActiveCategory=="音乐"&&ReferenceEquals(current,tabs.SelectedItem),"上移改变顺序并保留页面对象和选择");w.UpdateLayout();Check(Math.Abs(page.VerticalOffset-offset)<1,"排序保留内容滚动位置");Check(Store.Load().SettingsCategoryOrder[1]=="音乐","排序自动持久化");
 // Drive the actual WPF routed drop handler without moving the user's pointer.
 var target=nav.Items.Cast<ListBoxItem>().Single(i=>(string)((TabItem)i.Tag).Header=="常用");nav.ScrollIntoView(target);w.UpdateLayout();Set(w,"draggingCategory",true);Set(w,"categoryDragName","音乐");var constructor=typeof(DragEventArgs).GetConstructors(BindingFlags.NonPublic|BindingFlags.Instance).Single(c=>c.GetParameters().Length==5);var drop=(DragEventArgs)constructor.Invoke(new object[]{new DataObject("KianaPet.SettingsCategory","音乐"),DragDropKeyStates.LeftMouseButton,DragDropEffects.Move,target,new Point(3,1)});drop.RoutedEvent=DragDrop.DropEvent;target.RaiseEvent(drop);Set(w,"draggingCategory",false);Set(w,"categoryDragName",null);Check(drop.Effects==DragDropEffects.Move&&Names(w)[0]=="音乐","真实 Drop 路由将分类插入目标前方");// External drags must never change the settings order.
 string[] beforeExternal=Names(w);var external=(DragEventArgs)constructor.Invoke(new object[]{new DataObject("KianaPet.SettingsCategory","音乐"),DragDropKeyStates.LeftMouseButton,DragDropEffects.Move,nav.Items[1],new Point(3,1)});external.RoutedEvent=DragDrop.DropEvent;((ListBoxItem)nav.Items[1]).RaiseEvent(external);Check(external.Effects==DragDropEffects.None&&Names(w).SequenceEqual(beforeExternal),"忽略来自其他窗口的拖放数据");Check(pet.PendingUndo!=null&&pet.PendingUndo.Label=="设置分类顺序","顺序调整有中文撤销记录");w.Capture(Path.Combine(Store.Root,"sidebar-custom.png"));
 string[] custom=Names(w);string saved=File.ReadAllText(Path.Combine(Store.Root,"settings.json"));w.NavigateCategory("音乐","暂停");Check(!(bool)Field(w,"sortingCategories")&&!sort.IsEnabled,"搜索时退出排序并禁用入口");Call(w,"ReorderCategory","音乐","常用",true);Check(saved==File.ReadAllText(Path.Combine(Store.Root,"settings.json")),"过滤状态禁止隐式调整完整顺序");w.NavigateCategory("音乐","");Check(Names(w).SequenceEqual(custom),"清空搜索恢复自定义顺序");
 var exported=PreferenceTransfer.Import(PreferenceTransfer.Export(pet.Settings,false));Check(exported.SettingsCategoryOrder.SequenceEqual(custom),"分类顺序随通用偏好迁移");w.Close();pet.OpenSettings();w=app.Windows.OfType<SettingsWindow>().Single();Check(Names(w).SequenceEqual(custom)&&w.ActiveCategory=="常用","重新打开保持排序并默认常用页");sort=(Button)Field(w,"sortCategories");sort.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));w.NavigateCategory("音乐","");Check(!((Button)Field(w,"moveCategoryUp")).IsEnabled,"第一项不可继续上移");((Button)Field(w,"moveCategoryDown")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(Names(w)[1]=="音乐","下移可用");((Button)Field(w,"resetCategoryOrder")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(Names(w).SequenceEqual(SettingsCategoryOrder.Recommended)&&Store.Load().SettingsCategoryOrder.Length==0&&w.ActiveCategory=="音乐","恢复推荐顺序保留当前页并清除覆盖偏好");
 pet.Settings.Theme="dark";w.RefreshTheme();w.Width=760;w.Height=520;w.UpdateLayout();w.Capture(Path.Combine(Store.Root,"sidebar-dark-small.png"));Check(((Button)Field(w,"sortCategories")).IsVisible,"小窗口排序入口始终可见");w.NavigateCategory("使用说明","");w.UpdateLayout();Check(w.ActiveCategory=="使用说明","最底部低频分类仍可达");
 var invalid=new Config{SettingsCategoryOrder=new[]{"音乐","音乐",null,"旧分类"}};invalid.Validate();Check(invalid.SettingsCategoryOrder.Length==SettingsCategoryOrder.Recommended.Length&&invalid.SettingsCategoryOrder[0]=="音乐","无效与重复条目被清理且补全新分类");Check(SettingsCategoryOrder.Resolve(new[]{"音乐"},new[]{"音乐","常用","未来分类"}).Last()=="未来分类","未来新增页面不会因自定义排序消失");passed=true;
 }catch(Exception e){Store.Atomic("error.json",new{error=e.ToString()});}finally{Store.Atomic("settings-sidebar-tests.json",new{passed,checks});foreach(var w in app.Windows.Cast<Window>().Where(w=>w!=pet).ToArray())w.Close();pet.Close();}};app.Run(pet);return passed?0:1;
 }
}
