using System;using System.IO;using System.Linq;using System.Drawing;using System.Collections.Generic;using System.Threading.Tasks;using KianaPet;
class ComfortTests {
 static List<string> checks=new List<string>();static void Check(bool v,string name){if(!v)throw new Exception(name);checks.Add(name);Console.WriteLine("PASS "+name);}
 static bool Reject(Action f){try{f();return false;}catch{return true;}}
 static double Motion(int fps,double scale){var m=new SmoothWalk();m.Begin(0,1000*scale);for(int i=0;i<fps*2;i++)m.Step(1.0/fps,38*scale,140*scale);return m.Position/scale;}
 static void Run(){
  var c=new Config();ComfortRules.Preset(c,"quiet");Check(c.WalkSpeed==22&&c.WalkPauseMin==90,"安静预设降低频率与速度");ComfortRules.Preset(c,"lively");Check(c.WalkSpeed==65&&c.WalkPauseMax==20,"活泼预设提高频率");ComfortRules.Preset(c,"occasional");Check(c.WalkSpeed==38&&c.WalkDistanceMax==235,"偶尔活动保留原有基础范围");
  c.WalkSpeed=-1;c.WalkDistanceMin=6000;c.WalkDistanceMax=-1;c.WalkPauseMin=90000;c.WalkPauseMax=-1;c.QuietApps=null;c.Validate();Check(c.WalkSpeed==10&&c.WalkDistanceMin==500&&c.WalkDistanceMax==500&&c.WalkPauseMin==600&&c.WalkPauseMax==600,"非法参数归入有限范围");
  var motion=new SmoothWalk();motion.Begin(0,200);double first=motion.Step(1.0/60,38,140);Check(first>0&&first<38.0/60,"起步逐渐加速");for(int i=0;i<800;i++)motion.Step(1.0/60,38,140);Check(Math.Abs(motion.Position-200)<.01&&motion.Speed==0,"到达终点不越过并停止");motion.Begin(100,0);for(int i=0;i<500;i++)motion.Step(1.0/30,38,140);Check(motion.Position==0,"反向运动正确到达终点");Check(Math.Abs(Motion(30,1)-Motion(120,1))<1,"30/120 FPS 两秒位移差小于一个逻辑像素");Check(Math.Abs(Motion(60,1)-Motion(60,1.5))<.01&&Math.Abs(Motion(60,1)-Motion(60,2))<.01,"100/150/200% 缩放保持一致逻辑速度");
  var planner=new WalkPlanner();var random=new Random(480);int last=0,streak=0;for(int i=0;i<10000;i++){double target=planner.Next(1000,0,2000,random,35,100);int d=Math.Sign(target-1000);streak=d==last?streak+1:1;last=d;if(streak>2||Math.Abs(target-1000)<35||Math.Abs(target-1000)>100)throw new Exception("walk invariant");}Check(true,"自定义距离保留同向两次后反向规则");
  var areas=new[]{new Rectangle(0,0,1920,1040),new Rectangle(-1600,-200,1600,900)};var left=new Rectangle(-1400,-100,176,300);Check(ScreenPlacement.Fit(left,areas)==left,"左上副屏负坐标保持原位");var disconnected=ScreenPlacement.Fit(left,new[]{areas[0]});Check(areas[0].Contains(disconnected),"拔掉副屏后完整移回可见区域");Check(areas[0].Contains(ScreenPlacement.Fit(new Rectangle(8000,9000,176,300),areas)),"远离显示区域的旧坐标恢复");Check(ScreenPlacement.Fit(new Rectangle(0,0,3000,3000),areas).Left==0,"窗口大于工作区时不会产生无效坐标");
  c=Store.Json.Deserialize<Config>("{\"X\":-1300,\"Y\":-100}");c.Validate();Check(c.HasPosition,"旧配置的负坐标迁移为有效保存位置");c=new Config();c.Validate();Check(!c.HasPosition,"默认 -1/-1 仍表示初次放置");c.X=double.NaN;c.HasPosition=true;c.Validate();Check(!c.HasPosition,"无效坐标不保留已保存标记");
  string[] apps=ComfortRules.NormalizeApps(new[]{"obs64.exe\nOBS64\nTeams.EXE\nC:\\bad.exe"});Check(apps.Length==2&&apps.Contains("obs64")&&apps.Contains("Teams"),"进程规则去重、移除扩展名且拒绝路径");
  c=new Config{QuietAppsEnabled=true,QuietApps=new[]{"obs64"}};c.Validate();Check(ComfortRules.Quiet(c,false,TimeSpan.Zero,"OBS64",new string[0]),"前台进程规则大小写无关");Check(!ComfortRules.Quiet(c,false,TimeSpan.Zero,"Code",new[]{"obs64"}),"仅前台规则不因后台 OBS 误触发");c.QuietForegroundOnly=false;Check(ComfortRules.Quiet(c,false,TimeSpan.Zero,"Code",new[]{"obs64"}),"可选择进程运行即触发");c.QuietAppsEnabled=false;c.QuietHoursEnabled=true;c.QuietStart="23:00";c.QuietEnd="07:00";Check(ComfortRules.Quiet(c,false,TimeSpan.FromHours(1),"",new string[0])&&!ComfortRules.Quiet(c,false,TimeSpan.FromHours(12),"",new string[0]),"跨午夜免打扰时段");c.QuietStart=c.QuietEnd;Check(!ComfortRules.Quiet(c,false,TimeSpan.Zero,"",new string[0]),"相同起止时刻不全天触发");Check(ComfortRules.Quiet(c,true,TimeSpan.Zero,"",new string[0]),"手动免打扰独立生效");
  c=new Config{X=-1000,Y=30,HasPosition=true,MusicPosition="free",MusicHasPosition=true,MusicX=100,MusicY=200,LockPetPosition=true,LockMusicPosition=true};var restored=PreferenceTransfer.Import(PreferenceTransfer.Export(c,true));Check(restored.X==-1000&&restored.HasPosition&&restored.LockPetPosition&&restored.LockMusicPosition,"导出导入保留负坐标与位置锁定偏好");var portable=PreferenceTransfer.Import(PreferenceTransfer.Export(c,false));Check(!portable.HasPosition&&!portable.MusicHasPosition&&portable.MusicPosition=="below","默认导出排除设备坐标");Check(c.X==-1000&&c.MusicPosition=="free","导出不修改运行中的设置");Check(Reject(()=>PreferenceTransfer.Import("{}"))&&Reject(()=>PreferenceTransfer.Import("{\"Schema\":2,\"Product\":\"KianaDesktopPet\",\"Preferences\":{}}"))&&Reject(()=>PreferenceTransfer.Import(new string('x',70000))),"拒绝无关文件、新版未知格式和超大文件");Store.Save(c);string backup=PreferenceTransfer.Backup();Check(File.Exists(backup)&&PreferenceTransfer.Import(File.ReadAllText(backup)).X==-1000,"恢复前备份可再次导入");
  var hub=new TaskNoticeHub();var notice=new TaskNotice{Source="test",TaskId="1",Title="Compile",Status="running"};hub.Publish(notice);notice.Title="mutated";Check(hub.Unread==1&&hub.Snapshot()[0].Title=="Compile","任务接口复制输入，不受调用方后续修改影响");hub.Read("test","1");hub.Publish(new TaskNotice{Source="test",TaskId="1",Title="Compile",Status="running"});Check(hub.Unread==0,"重复状态不重复提醒");hub.Publish(new TaskNotice{Source="test",TaskId="1",Title="Compile",Status="succeeded"});Check(hub.Unread==1&&hub.Snapshot().Length==1,"状态更新替换同一任务并恢复未读");var snapshot=hub.Snapshot();snapshot[0].Title="wrong";Check(hub.Snapshot()[0].Title=="Compile","通知快照不暴露内部可变引用");Check(Reject(()=>hub.Publish(new TaskNotice{Source="test",TaskId="a",Title="bad",Status="execute"})),"任务接口拒绝未知状态，没有执行命令能力");Parallel.For(0,200,i=>hub.Publish(new TaskNotice{Source="test",TaskId=i.ToString(),Title="Task",Status="succeeded"}));Check(hub.Snapshot().Length==50,"并发通知保留最近 50 项");hub.ReadAll();Check(hub.Unread==0,"本地全部已读仅操作本地通知");
  string[] errors={"请先使用 ChatGPT 平滑桌宠启动器。","Browser changed","Endpoint unavailable: no-listener","Mini 后台未就绪","Mini 接口执行失败","Untrusted page"};string[] codes={"launcher-missing","session-stale","endpoint-unavailable","mini-missing","interface-changed","endpoint-rejected"};for(int i=0;i<errors.Length;i++){var state=new BridgeState{AppOpen=true};BridgeDiagnostics.Failure(state,new Exception(errors[i]));Check(state.Code==codes[i]&&state.Hint.Length>0,"联动故障分级："+codes[i]);}var closed=new BridgeState();BridgeDiagnostics.Failure(closed,new Exception());Check(closed.Code=="app-closed","ChatGPT 关闭与接口失败分开提示");
 }
 static int Main(string[] args){Store.Root=args[0];try{Run();Store.Atomic("comfort-tests.json",new{version="0.6.0",passed=true,checks=checks});return 0;}catch(Exception e){Store.Atomic("comfort-tests.json",new{passed=false,error=e.ToString(),checks=checks});Console.WriteLine(e);return 1;}}
}
