using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Interop;using KianaPet;
class ComfortUiTests {
 static List<string> checks=new List<string>();static void Check(bool v,string n){if(!v)throw new Exception(n);checks.Add(n);Console.WriteLine("PASS "+n);}
 static object Field(object o,string name){return o.GetType().GetField(name,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}static void Set(object o,string name,object v){o.GetType().GetField(name,BindingFlags.NonPublic|BindingFlags.Instance).SetValue(o,v);}static object Call(object o,string n,params object[] args){return o.GetType().GetMethod(n,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(o,args);}
 static Native.Rect Bounds(PetWindow p){Native.Rect r;Native.GetWindowRect(new WindowInteropHelper(p).Handle,out r);return r;}
 [STAThread]static int Main(string[] args){Store.Root=args[0];Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false});var app=new Application{ShutdownMode=ShutdownMode.OnExplicitShutdown};var pet=new PetWindow(true);bool passed=false;
 pet.Loaded+=async delegate{try{await Task.Delay(450);var settings=app.Windows.OfType<SettingsWindow>().Single();var tabs=(TabControl)Field(settings,"settingsTabs");var experience=tabs.Items.OfType<TabItem>().Single(t=>(string)t.Header=="体验");tabs.SelectedItem=experience;var page=(StackPanel)((ScrollViewer)experience.Content).Content;var profile=page.Children.OfType<ComboBox>().Single();profile.SelectedIndex=0;page.Children.OfType<Button>().Single(b=>(string)b.Content=="保存走动节奏").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(pet.Settings.WalkProfile=="quiet"&&pet.Settings.WalkSpeed==22,"设置页安静预设保存到实际配置");
 var locks=page.Children.OfType<CheckBox>().ToArray();locks[0].IsChecked=true;locks[1].IsChecked=true;Check(pet.Settings.LockPetPosition&&pet.Settings.LockMusicPosition,"设置页两个锁定开关生效");await Task.Delay(100);settings.Capture(Path.Combine(Store.Root,"comfort-preview.png"));tabs.SelectedItem=tabs.Items.OfType<TabItem>().Single(t=>(string)t.Header=="免打扰");await Task.Delay(100);settings.Capture(Path.Combine(Store.Root,"quiet-preview.png"));tabs.SelectedItem=tabs.Items.OfType<TabItem>().Single(t=>(string)t.Header=="使用说明");((ScrollViewer)((TabItem)tabs.SelectedItem).Content).ScrollToEnd();await Task.Delay(100);settings.Capture(Path.Combine(Store.Root,"transfer-preview.png"));settings.Close();
 pet.Settings.Walking=true;pet.Settings.Gravity=true;pet.ApplySettings();Set(pet,"nextWalk",0.0);var before=Bounds(pet);await Task.Delay(450);var after=Bounds(pet);Check(before.Left==after.Left&&before.Top==after.Top,"位置锁定阻止自动走动与重力");Set(pet,"pressed",true);Call(pet,"PointerMove",null,new MouseEventArgs(Mouse.PrimaryDevice,Environment.TickCount));Check(!(bool)Field(pet,"dragging"),"位置锁定阻止拖动进入");Set(pet,"pressed",false);
 var music=new MusicWindow(pet);music.Show();music.Refresh(new MusicState{Title="控件测试",Artist="无实际播放",CanToggle=true,CanNext=true,CanPrevious=true},"",null,false);var surface=(UIElement)Field(music,"dragSurface");surface.RaiseEvent(new MouseButtonEventArgs(Mouse.PrimaryDevice,Environment.TickCount,MouseButton.Left){RoutedEvent=UIElement.MouseLeftButtonDownEvent});Check(!(bool)Field(music,"pointerPressed"),"音乐栏锁定阻止拖动捕获");Check(((Button)Field(music,"toggle")).IsEnabled,"锁定音乐栏不禁用播放按钮");music.Close();
 pet.Settings.LockPetPosition=false;pet.Settings.Gravity=false;pet.Settings.AvoidCursor=false;Set(pet,"interactionHoldUntil",0d);pet.Settings.WalkSpeed=38;pet.Settings.WalkDistanceMin=120;pet.Settings.WalkDistanceMax=200;pet.ApplySettings();Set(pet,"nextWalk",0.0);Set(pet,"hover",false);Set(pet,"toolbarUntil",0.0);before=Bounds(pet);await Task.Delay(1300);after=Bounds(pet);Check(Math.Abs(after.Left-before.Left)>8,"实际窗口使用平滑走动推进");
 pet.ToggleQuiet();before=Bounds(pet);pet.Say("不应显示",2);await Task.Delay(300);after=Bounds(pet);Check(after.Left==before.Left&&((Border)Field(pet,"bubble")).Visibility!=Visibility.Visible,"安静模式暂停位移并抑制气泡");pet.Settings.QuietMode="hide";pet.ApplySettings();await Task.Delay(1100);Check(!pet.IsVisible,"隐藏型免打扰隐藏宠物");pet.ToggleQuiet();await Task.Delay(1100);Check(pet.IsVisible,"取消临时免打扰自动恢复");pet.Settings.Walking=false;pet.ApplySettings();
 var hookArgs=new object[]{IntPtr.Zero,0x02b1,new IntPtr(7),IntPtr.Zero,false};Call(pet,"Hook",hookArgs);await Task.Delay(1100);Check(!pet.IsVisible,"模拟会话锁屏消息隐藏桌宠");hookArgs[2]=new IntPtr(8);Call(pet,"Hook",hookArgs);await Task.Delay(1100);Check(pet.IsVisible,"模拟解锁消息恢复桌宠");
 Native.SetWindowPos(new WindowInteropHelper(pet).Handle,IntPtr.Zero,99999,99999,0,0,0x1|0x4|0x10);Call(pet,"Hook",IntPtr.Zero,0x007e,IntPtr.Zero,IntPtr.Zero,false);await Task.Delay(1100);after=Bounds(pet);Check(System.Windows.Forms.Screen.AllScreens.Any(s=>s.WorkingArea.Contains(new System.Drawing.Rectangle(after.Left,after.Top,after.Width,after.Height))),"模拟显示器变更将丢失窗口找回可见区域");
 var import=PreferenceTransfer.Copy(pet.Settings);import.X=-1500;import.Y=-500;import.WalkSpeed=52;before=Bounds(pet);pet.ReplacePreferences(import,false);after=Bounds(pet);Check(after.Left==before.Left&&after.Top==before.Top&&pet.Settings.WalkSpeed==52,"导入偏好可保留本机位置");Check(Directory.GetFiles(Path.Combine(Store.Root,"preference-backups")).Length>0,"实际导入前生成可恢复备份");
 pet.TestTaskNotice();await Task.Delay(150);Set(pet,"hover",true);Call(pet,"UpdateToolbar",9999.0);Check(pet.LocalNoticeCount==1&&((Button)Field(pet,"notificationButton")).Visibility==Visibility.Visible,"示例任务出现在实际铃铛");Call(pet,"OpenToolbarNotifications");Check(((NoticeCenter)Field(pet,"noticeCenter")).IsVisible,"本地任务通知中心可以打开");((NoticeCenter)Field(pet,"noticeCenter")).Close();pet.Settings.LinkChatGPT=true;pet.Link.Current=new BridgeState{Connected=true,CanNotifications=true,NotificationCount=3,NotificationText="3",NotificationColor="#3a83f7"};Call(pet,"UpdateToolbar",10000.0);Check(((TextBlock)Field(pet,"notificationNumber")).Text=="4","本地与 ChatGPT 角标合并显示");pet.TaskNotices.ReadAll();Call(pet,"UpdateToolbar",10001.0);Check(((TextBlock)Field(pet,"notificationNumber")).Text=="3"&&pet.Link.Current.NotificationCount==3,"本地已读不清除 ChatGPT 原生通知");
 passed=true;
 }catch(Exception e){Console.WriteLine(e);Store.Atomic("comfort-ui-error.json",new{error=e.ToString()});}finally{Store.Atomic("comfort-ui-tests.json",new{version="0.6.0",passed=passed,checks=checks,physicalScreens=System.Windows.Forms.Screen.AllScreens.Length,displayChanges="simulated window messages; mixed DPI geometry tested separately"});File.AppendAllText(Path.Combine(Store.Root,"exit-trace.txt"),DateTime.Now.ToString("o")+" before close: quitting="+Field(pet,"quitting")+" visible="+pet.IsVisible+" windows="+app.Windows.Count+"\n");pet.Close();File.AppendAllText(Path.Combine(Store.Root,"exit-trace.txt"),DateTime.Now.ToString("o")+" after close: quitting="+Field(pet,"quitting")+" dispatcherShutdown="+pet.Dispatcher.HasShutdownStarted+" windows="+app.Windows.Count+"\n");}};app.Run(pet);File.AppendAllText(Path.Combine(Store.Root,"exit-trace.txt"),DateTime.Now.ToString("o")+" loop returned\n");return passed?0:1;
 }
}

