using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Interop;using KianaPet;
class PolishUiTests {
 static List<string> checks=new List<string>();static void Check(bool ok,string name){if(!ok)throw new Exception(name);checks.Add(name);}
 static object Field(object o,string n){return o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}static void Set(object o,string n,object v){o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).SetValue(o,v);}static object Call(object o,string n,params object[] a){return o.GetType().GetMethod(n,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(o,a);}
 static StackPanel Page(TabControl t,string name){var tab=t.Items.OfType<TabItem>().Single(x=>(string)x.Header==name);t.SelectedItem=tab;return (StackPanel)((ScrollViewer)tab.Content).Content;}
 [STAThread]static int Main(string[] args){Store.Root=args[0];Directory.CreateDirectory(Store.Root);Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false,RememberLayouts=true});var app=new Application{ShutdownMode=ShutdownMode.OnExplicitShutdown};var pet=new PetWindow(true);bool success=false;
 pet.Loaded+=async delegate{try{await Task.Delay(400);var settings=app.Windows.OfType<SettingsWindow>().Single();var tabs=(TabControl)Field(settings,"settingsTabs");Check(tabs.Items.OfType<TabItem>().Any(t=>(string)t.Header=="场景与维护"),"维护页面可打开");var appearance=Page(tabs,"外观与互动");var theme=appearance.Children.OfType<ComboBox>().Single();theme.SelectedIndex=1;await Task.Delay(180);Check(pet.Settings.Theme=="dark"&&PetPalette.Dark,"主题控件切换为深色");Check(((SolidColorBrush)appearance.Children.OfType<CheckBox>().First().Foreground).Color.R>200,"深色设置复选框文字保持可读");settings.Capture(Path.Combine(Store.Root,"settings-dark.png"));var sliders=appearance.Children.OfType<Slider>().ToArray();int originalSize=pet.Settings.Size;sliders.Last().Value=150;Check(pet.Settings.ToolbarPercent==150&&pet.Settings.Size==originalSize,"工具栏可独立调整到百分之一百五十");Check(Math.Abs(((Grid)pet.Content).RowDefinitions[2].Height.Value-60)<.1,"工具栏放大预留真实布局高度");
 var musicPage=Page(tabs,"音乐");var tint=musicPage.Children.OfType<CheckBox>().Single(c=>((string)c.Content).Contains("随封面"));tint.IsChecked=false;Check(!pet.Settings.MusicCoverTint,"封面配色开关保存");musicPage.Children.OfType<Slider>().Single(s=>System.Windows.Automation.AutomationProperties.GetName(s)=="配色程度").Value=70;Check(pet.Settings.MusicTintStrength==70,"封面配色强度保存");tint.IsChecked=true;
 var music=new MusicWindow(pet);music.Show();byte[] pixel={40,100,230,255};var cover=BitmapSource.Create(1,1,96,96,PixelFormats.Bgra32,null,pixel,4);cover.Freeze();var state=new MusicState{Connected=true,Title="晴空下的陪伴",Artist="配色预览 · 不控制播放器",CanToggle=true,CanPrevious=true,CanNext=true,Playing=true};music.Refresh(state,"",cover,false);await Task.Delay(420);music.Capture(Path.Combine(Store.Root,"music-dark.png"));var surface=(Border)Field(music,"surface");Check(((SolidColorBrush)surface.Background).Color.R<110,"深色音乐背景取色保持低亮度");var title=(TextBlock)Field(music,"title");Check(((SolidColorBrush)title.Foreground).Color.R>200,"深色音乐文字保持清晰高亮");theme.SelectedIndex=0;music.Refresh(state,"",cover,false);await Task.Delay(420);music.Capture(Path.Combine(Store.Root,"music-light.png"));Check(((SolidColorBrush)surface.Background).Color.G>200,"浅色音乐背景保持柔和");Check(((Button)Field(music,"toggle")).IsEnabled,"主题和配色不影响播放按钮");music.Close();
 Page(tabs,"场景与维护");settings.Capture(Path.Combine(Store.Root,"maintenance.png"));settings.Close();int size=pet.Settings.Size;string skin=pet.Settings.Skin;pet.ApplyScene(0);Check(!pet.Settings.Walking&&pet.Settings.Size==size&&pet.Settings.Skin==skin,"实际场景切换保留服装尺寸");Check(!app.Windows.OfType<SettingsWindow>().Any(),"右键应用场景不会额外弹设置窗口");pet.SaveScene("我自己的方案");Check(pet.Settings.Scenes.Any(s=>s.Name=="我自己的方案"),"保存自定义场景");pet.DeleteScene(pet.Settings.Scenes.Length-1);Check(!pet.Settings.Scenes.Any(s=>s.Name=="我自己的方案"),"删除自定义场景");
 foreach(var info in pet.Pets.Where(p=>p.Id.EndsWith("-round"))){pet.SelectSkin(info.Id);foreach(string action in new[]{"groom","stretch"}){pet.React(action,"",2.1);Set(pet,"state",action);Call(pet,"DrawAnimation",1000d);var bitmap=(BitmapSource)((Image)Field(pet,"sprite")).Source;Check(bitmap.PixelWidth==384&&bitmap.PixelHeight==416,info.Id+" "+action+" 使用高清绘制帧");}}pet.React("blink","",.5);Set(pet,"state","blink");Call(pet,"DrawAnimation",220d);Check(((Image)Field(pet,"sprite")).Source!=null,"眨眼复用既有闭眼帧");
 pet.Settings.HideFullscreen=false;pet.Settings.QuietMode="hide";pet.ToggleQuiet();await Task.Delay(1100);Check(!pet.IsVisible&&((System.Windows.Threading.DispatcherTimer)Field(pet,"animation")).Interval.TotalMilliseconds==500,"隐藏后实际动画定时器降频");pet.ToggleQuiet();for(int attempt=0;attempt<30&&!pet.IsVisible;attempt++)await Task.Delay(100);Check(pet.IsVisible,"恢复显示及时退出降频隐藏状态");
 Native.SetWindowPos(new WindowInteropHelper(pet).Handle,IntPtr.Zero,99999,99999,0,0,0x1|0x4|0x10);Call(pet,"RepairDisplay");await Task.Delay(1100);Native.Rect rect;Native.GetWindowRect(new WindowInteropHelper(pet).Handle,out rect);Check(System.Windows.Forms.Screen.AllScreens.Any(s=>s.WorkingArea.Contains(new System.Drawing.Rectangle(rect.Left,rect.Top,rect.Width,rect.Height))),"显示变动防抖后将窗口收回可见区域");Check(File.Exists(Path.Combine(Store.Root,"display-layouts.json")),"实际位置写入本机布局记忆");
 string report=Diagnostics.Report(pet,true,true);Check(Store.Json.DeserializeObject(report)!=null&&!report.Contains(Environment.UserName),"诊断报告可解析且隐藏个人路径");success=true;
 }catch(Exception e){Console.WriteLine(e);Store.Atomic("polish-ui-error.json",new{error=e.ToString()});}finally{Store.Atomic("polish-ui-tests.json",new{version="0.6.0",passed=success,checks=checks,physicalScreens=System.Windows.Forms.Screen.AllScreens.Length});pet.Close();}};app.Run(pet);Console.WriteLine((success?"PASS ":"FAIL ")+checks.Count);return success?0:1;}
}

