using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.IO.Compression;using System.Windows.Media;using KianaPet;
class PolishTests {
 static List<string> checks=new List<string>();static void Check(bool b,string n){if(!b)throw new Exception(n);checks.Add(n);}static void Reject(Action a,string n){bool rejected=false;try{a();}catch{rejected=true;}Check(rejected,n);}
 static void Main(string[] args){Store.Root=args[0];Directory.CreateDirectory(Store.Root);try{
 var c=new Config{MusicTintStrength=900,ToolbarPercent=1,NoticeBatchSeconds=-1,Theme="bad"};c.Validate();Check(c.MusicTintStrength==100&&c.ToolbarPercent==75&&c.NoticeBatchSeconds==2&&c.Theme=="light","新增配置边界和旧配置默认兼容");
 c=new Config{Skin="time-runner-kiana-round",X=-1250,Y=-100,Size=112,RecoverHotkeyEnabled=false};var scene=ScenePreset.Capture("测试",new Config{Walking=false,MusicLyrics=true,QuietHoursEnabled=true,WalkSpeed=60});scene.Apply(c);Check(!c.Walking&&c.MusicLyrics&&c.QuietHoursEnabled&&c.WalkSpeed==60,"场景应用活动音乐与免打扰开关");Check(c.X==-1250&&c.Size==112&&c.Skin=="time-runner-kiana-round"&&!c.RecoverHotkeyEnabled,"场景保留位置服装尺寸和快捷键");Check(PreferenceTransfer.Import(PreferenceTransfer.Export(c,false)).Scenes.Length==3,"场景随偏好导出导入");
 var m=new DisplayMemory();m.Remember("dual",c);c.X=200;c.Y=300;m.Remember("single",c);Check(m.Find("dual").X==-1250&&m.Find("single").X==200,"两套显示布局分别保存负坐标位置");m.Save();Check(DisplayMemory.Load().Find("dual").Y==-100,"布局记忆持久化");Check(DisplayMemory.Key(new[]{"b","a"})==DisplayMemory.Key(new[]{"a","b"}),"显示器枚举顺序不改变布局标识");for(int i=0;i<30;i++)m.Remember("screen"+i,c);Check(m.Items.Count==20&&m.Find("screen29")!=null,"最多保存二十套布局");Check(!PreferenceTransfer.Export(c,true).Contains("dual"),"本机布局记忆不进入偏好包");
 Check(PolishRules.FrameInterval(true,true,false,false,false)==500,"隐藏刷新降低到每秒两次");Check(PolishRules.FrameInterval(true,false,true,false,false)==180,"休息状态降低刷新");Check(PolishRules.FrameInterval(true,false,false,true,false)==33&&PolishRules.FrameInterval(true,false,false,false,true)==33,"互动和走动保留流畅刷新");Check(PolishRules.RetrySeconds(0,2)==2&&PolishRules.RetrySeconds(30,2)==30,"连接保持两秒续期且断线重试上限三十秒");
 var now=DateTime.UtcNow;var batch=new NoticeBatcher();batch.Add(new TaskNotice{Source="测试",TaskId="1",Title="完成",Status="succeeded"},now,5);Check(batch.Flush(now.AddSeconds(2),false,true,false)==null,"合并窗口到期前不提醒");Check(batch.Flush(now.AddSeconds(6),false,true,true)==null,"普通成功可静默");batch.Add(new TaskNotice{Source="测试",TaskId="1",Title="开始",Status="running"},now,2);batch.Add(new TaskNotice{Source="测试",TaskId="1",Title="失败",Status="failed"},now,2);Check(batch.Flush(now.AddSeconds(3),false,true,true).Contains("失败"),"同任务去重并保留最终失败状态");batch.Add(new TaskNotice{Source="测试",TaskId="1",Title="完成",Status="succeeded"},now,2);Check(batch.Flush(now.AddSeconds(3),true,true,true)==null,"免打扰期间积累而不弹出");Check(batch.Flush(now.AddSeconds(4),false,true,true)==null,"免打扰结束仍尊重完成静默");batch.Add(new TaskNotice{Source="测试",TaskId="1",Title="失败",Status="failed"},now,2);batch.Flush(now.AddSeconds(3),false,false,false);Check(batch.Flush(now.AddSeconds(4),false,true,false)==null,"关闭通知清理待提醒队列");
 var planner=new AmbientPlanner();Check(planner.Touch(1)&&!planner.Touch(1.2)&&planner.Touch(2),"连续触摸防抖");var random=new Random(73);string prior="";bool distinct=true;for(int i=1;i<100;i++){string action=planner.Next(i*100,true,random);distinct&=action!=prior;prior=action;}Check(distinct,"连续九十九次空闲动作不重复相邻动作");Check(planner.Next(20000,false,random)==null,"忙碌时不插入空闲动作");
 Check(PetPalette.MusicSurface(Colors.Red,false,false,100)==Colors.White,"关闭封面配色恢复中性色");Check(PetPalette.MusicSurface(Colors.Red,false,true,0)==Colors.White,"程度零等于中性背景");var light=PetPalette.MusicSurface(Colors.Red,false,true,100);Check(light.R==255&&light.G>=210&&light.B>=210,"最高配色程度仍为柔和浅色");var dark=PetPalette.MusicSurface(Colors.White,true,true,100);Check(dark.R<100&&dark.G<100&&dark.B<110,"深色最高程度仍保持深色底");Check(Diagnostics.Redact(@"path C:\Users\Someone\secret token=hello",true).IndexOf("Someone")<0,"诊断隐藏个人路径");Check(!Diagnostics.Redact("Bearer secret authorization=abc https://host/path?token=abc",false).Contains("secret"),"诊断脱敏令牌及链接");
 string safe=Path.Combine(Store.Root,"safe");Reject(()=>Maintenance.SafePath(safe,"../escape"),"更新拒绝目录穿越");Reject(()=>Maintenance.SafePath(safe,"C:/escape"),"更新拒绝绝对路径");Reject(()=>Maintenance.SafePath(safe,"assets/../escape"),"更新拒绝嵌套穿越");Reject(()=>Maintenance.SafePath(safe,"assets/file:stream"),"更新拒绝备用数据流");Check(Maintenance.RuntimeFile("assets/a.png")&&!Maintenance.RuntimeFile("source/run.ps1"),"更新仅安装限定运行文件");
 if(args.Length>1&&!string.IsNullOrWhiteSpace(args[1])){var p=Maintenance.PrepareZip(args[1],Path.Combine(Store.Root,"stage"));Check(p.Version=="0.6.0"&&p.Manifest.files.Length>10,"完整发布包校验和提取");Check(Maintenance.VerifyRuntime(p.Folder).version=="0.6.0","提取后再次校验运行文件");File.AppendAllText(Path.Combine(p.Folder,"README.md"),"changed");Reject(()=>Maintenance.VerifyRuntime(p.Folder),"损坏备份不可用于回退");}
 Store.Atomic("polish-tests.json",new{version="0.6.0",passed=true,checks=checks});Console.WriteLine("PASS "+checks.Count);
 }catch(Exception e){Store.Atomic("polish-tests.json",new{version="0.6.0",passed=false,checks=checks,error=e.ToString()});Console.WriteLine(e);Environment.ExitCode=1;}}
}

