using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using System.Windows.Media;using System.Windows.Media.Imaging;using KianaPet;
class UsabilityTests {
 static List<string> checks=new List<string>();static void Check(bool b,string n){if(!b)throw new Exception(n);checks.Add(n);}static void Reject(Action a,string n){bool fail=false;try{a();}catch{fail=true;}Check(fail,n);}
 static void Main(string[] args){Store.Root=args[0];Directory.CreateDirectory(Store.Root);try{
 var now=DateTime.UtcNow;var a=new Config();var b=PreferenceTransfer.Copy(a);b.X=99;b.Y=80;Check(EditHistory.Changed(a,b).Length==0,"自动移动不进入撤销记录");var h=new EditHistory();b.Size=160;h.Record(a,b,now);var c=PreferenceTransfer.Copy(b);c.Size=200;h.Record(b,c,now.AddMilliseconds(500));Check(h.Items.Count==1&&h.Peek(now).Before.Size==a.Size,"连续尺寸调整合并并保留最初值");c.Theme="dark";h.Record(b,c,now.AddSeconds(2));Check(h.Items.Count==2,"不同调整分别入栈");Check(h.Pop(now.AddSeconds(93))==null,"超过九十秒的撤销过期");bool restored=false;h.AddAction("清除布局","场景与维护",()=>restored=true,now);h.Pop(now).Restore();Check(restored,"布局清除可通过恢复动作撤销");for(int i=0;i<30;i++){b.Size=100+i;c.Size=101+i;h.Record(b,c,now.AddSeconds(i*2));}Check(h.Items.Count==20&&h.Recent.Count<=12,"撤销与最近记录有容量上限");
 var rect=new System.Drawing.Rectangle(-500,100,150,200);Check(CursorAvoidance.Near(rect,new System.Drawing.Point(-510,150),20),"负坐标显示器鼠标邻近避让");Check(!CursorAvoidance.Near(rect,new System.Drawing.Point(-510,350),20),"跨越纵向范围不误暂停");Check(CursorAvoidance.Crosses(rect,new System.Drawing.Point(-100,150),0,20),"路径会穿过鼠标时阻止前进");Check(!CursorAvoidance.Crosses(rect,new System.Drawing.Point(-100,500),0,20),"鼠标远离路径允许移动");var walk=new WalkPlanner();Check(walk.NextSafe(100,0,1000,new Random(3),65,235,24,x=>false)==100,"两方向都受阻时原地等待");double target=walk.NextSafe(100,0,1000,new Random(3),65,235,24,x=>x>100);Check(target>100,"选择唯一安全的方向");
 var hub=new TaskNoticeHub();hub.Publish(new TaskNotice{Source="测试",TaskId="a",Title="开始",Status="running",ActionId="open"});var n=hub.Snapshot()[0];Check(!hub.CanOpen(n)&&!hub.Open(n),"未注册动作不会执行任何跳转");int opened=0;hub.RegisterAction("测试","open",x=>opened++);Check(opened==0,"注册和收到通知不会自动跳转");Check(hub.Open(n)&&opened==1&&hub.Unread==0,"显式打开任务执行已注册动作并已读");hub.Mute("测试","a",true);Check(hub.IsMuted(n)&&hub.Snapshot().Length==1,"任务静音保留历史");hub.Publish(new TaskNotice{Source="测试",TaskId="a",Title="完成",Status="succeeded",ActionId="open"});Check(hub.IsMuted(hub.Snapshot()[0]),"状态变化仍保留任务静音");hub.RegisterAction("测试","open",x=>hub.Publish(new TaskNotice{Source="测试",TaskId="a",Title="打开过程中到来的新状态",Status="failed",ActionId="open"}));hub.Open(hub.Snapshot()[0]);Check(hub.Unread==1,"打开过程中更新的任务保持未读");hub.UnregisterAction("测试","open");Check(!hub.CanOpen(n),"取消适配器注册后入口失效");Reject(()=>hub.Publish(new TaskNotice{Source="bad\nsource",TaskId="a",Title="x",Status="running"}),"来源身份拒绝控制字符");hub.Publish(new TaskNotice{Source="另一个",TaskId="b",Title="失败",Status="failed"});Check(NoticeCenter.Filter(hub.Snapshot(),"另一个",3,true).Length==1,"通知来源状态和未读联合筛选");Check(NoticeCenter.Filter(hub.Snapshot(),"测试",2,false).Length==0,"不匹配状态不混入结果");var batch=new NoticeBatcher();batch.Add(n,now,2);batch.RemoveWhere(x=>true);Check(batch.Flush(now.AddSeconds(3),false,true,false)==null,"读过或静音的排队提醒可撤回");
 using(var lib=new MusicLibrary()){var first=new MusicState{Connected=true,Id="1",Title="A",Artist="a",Cover=""};lib.Update(first,false);var image=BitmapSource.Create(1,1,96,96,PixelFormats.Bgra32,null,new byte[]{0,0,255,255},4);typeof(MusicLibrary).GetProperty("Cover").GetSetMethod(true).Invoke(lib,new object[]{image});Check(lib.CoverFor(first)==image,"歌曲身份匹配时显示封面");var second=new MusicState{Connected=true,Id="2",Title="B",Artist="b",Cover=""};Check(lib.CoverFor(second)==null,"切歌轮询先到时不混用上一首封面");lib.Update(second,false);Check(lib.CoverFor(second)==null,"新歌曲立即清除旧封面");Check(MusicLibrary.Identity(new MusicState{Title="A",Artist="one"})!=MusicLibrary.Identity(new MusicState{Title="A",Artist="two"}),"无歌曲ID时以标题与歌手隔离");}
 Check(TransitionSequence.Frame(0)==-1&&TransitionSequence.Frame(200)==0&&TransitionSequence.Frame(300)==1&&TransitionSequence.Frame(1000)==3&&TransitionSequence.Frame(2050)==-1,"动作从站立经两张过渡到关键帧并返回");var config=new Config{BackupKeepCount=100,MutedNoticeSources=new[]{"abc","abc",""}};config.Validate();Check(config.BackupKeepCount==10&&config.MutedNoticeSources.Length==1,"备份数量和静音来源校验");Check(SettingsWindow.Matches("网易云音乐","音乐")&&!SettingsWindow.Matches("音乐","快捷键"),"设置搜索匹配与空结果");
 Check(StorageManagement.Size(1572864)=="1.5 MB","占用大小正确保留一位小数");
string root=Path.Combine(Store.Root,"storage-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);foreach(string name in new[]{"20260101","20260201","20260301"}){string d=Path.Combine(root,"managed-backups",name);Directory.CreateDirectory(d);File.WriteAllText(Path.Combine(d,"data"),name);}File.WriteAllText(Path.Combine(root,"stable-backup.txt"),"managed-backups/20260101");string cache=Path.Combine(root,"update-cache","old");Directory.CreateDirectory(cache);File.WriteAllText(Path.Combine(cache,"a"),"cache");File.SetLastWriteTimeUtc(Path.Combine(cache,"a"),now.AddDays(-2));Directory.SetLastWriteTimeUtc(cache,now.AddDays(-2));string fresh=Path.Combine(root,"update-cache","fresh");Directory.CreateDirectory(fresh);File.WriteAllText(Path.Combine(fresh,"x"),"fresh");var rows=StorageManagement.Scan(root,1,now);Check(!rows.Single(x=>x.Name=="20260101").CanDelete,"稳定版始终保护");Check(!rows.Single(x=>x.Name=="20260301").CanDelete&&rows.Single(x=>x.Name=="20260201").CanDelete,"保留最新一份备份，旧版列为候选");Check(rows.Single(x=>x.Name=="old").CanDelete&&!rows.Single(x=>x.Name=="fresh").CanDelete,"新缓存保护二十四小时");Reject(()=>StorageManagement.Child(root,"../escape"),"清理路径拒绝越界");var old=rows.Single(x=>x.Name=="old");File.AppendAllText(Path.Combine(cache,"a"),"changed");var changed=StorageManagement.DeleteSelected(root,new[]{old},1);Check(changed.Skipped.Count==1&&Directory.Exists(cache),"预览后发生变化的目录不删除");using(var gate=new FileStream(Path.Combine(root,"maintenance.lock"),FileMode.OpenOrCreate,FileAccess.ReadWrite,FileShare.None)){Reject(()=>StorageManagement.DeleteSelected(root,new[]{rows[0]},1),"更新维护锁占用时清理拒绝执行");}var deleted=StorageManagement.DeleteSelected(root,new[]{rows.Single(x=>x.Name=="20260201"),rows.Single(x=>x.Name=="20260101")},1);Check(deleted.Deleted.Count==1&&deleted.Skipped.Count==1&&Directory.Exists(Path.Combine(root,"managed-backups","20260101")),"只删除选定且未受保护的测试备份");
 string stableRoot=Path.Combine(root,"managed-backups","20260401"),runtime=Path.Combine(stableRoot,"app");Directory.CreateDirectory(Path.Combine(runtime,"assets"));File.WriteAllText(Path.Combine(runtime,"KianaDesktopPet.exe"),"test only");File.WriteAllText(Path.Combine(runtime,"assets","pets.json"),"[]");var entries=new[]{"KianaDesktopPet.exe","assets/pets.json"}.Select(x=>new PackageEntry{path=x,size=new FileInfo(Path.Combine(runtime,x)).Length,sha256=Maintenance.Hash(Path.Combine(runtime,x))}).ToArray();Maintenance.Write(Path.Combine(runtime,"runtime-manifest.json"),new PackageManifest{schema=1,product="Kiana Desktop Pet",version="0.6.0",files=entries});StorageManagement.MarkStable(root,new StorageItem{Path=stableRoot});Check(StorageManagement.Stable(root)=="managed-backups/20260401","稳定版标记先验证完整运行清单");File.AppendAllText(Path.Combine(runtime,"assets","pets.json"),"tampered");Reject(()=>StorageManagement.MarkStable(root,new StorageItem{Path=stableRoot}),"损坏备份不能标记为稳定版");
 Store.Atomic("usability-tests.json",new{version="0.6.0",passed=true,checks=checks});Console.WriteLine("PASS "+checks.Count);
 }catch(Exception e){Store.Atomic("usability-tests.json",new{version="0.6.0",passed=false,checks=checks,error=e.ToString()});Console.WriteLine(e);Environment.ExitCode=1;}}
}
