using System;using System.IO;using System.Linq;using System.Reflection;using System.Diagnostics;using System.Collections.Generic;using System.Runtime.InteropServices;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Controls.Primitives;using System.Windows.Interop;using System.Windows.Media;using System.Windows.Threading;using KianaPet;using Forms=System.Windows.Forms;
class MenuLayerTests {
static void IpcWrite(string path,string value){string temp=path+"."+Guid.NewGuid().ToString("N");File.WriteAllText(temp,value);if(File.Exists(path))File.Replace(temp,path,null);else File.Move(temp,path);}static string IpcRead(string path){using(var f=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete))using(var r=new StreamReader(f))return r.ReadToEnd();}
 static readonly List<string> checks=new List<string>();static void Check(bool ok,string name){if(!ok)throw new Exception(name);checks.Add(name);}static object Field(object o,string n){return o.GetType().GetField(n,BindingFlags.Instance|BindingFlags.NonPublic).GetValue(o);}static void Set(object o,string n,object v){o.GetType().GetField(n,BindingFlags.Instance|BindingFlags.NonPublic).SetValue(o,v);}static object Call(object o,string n,params object[] args){return o.GetType().GetMethod(n,BindingFlags.Instance|BindingFlags.NonPublic).Invoke(o,args);}static Native.Rect Bounds(Window w){Native.Rect r;Native.GetWindowRect(new WindowInteropHelper(w).Handle,out r);return r;}
 static async Task Until(Func<bool> predicate,string name){for(int i=0;i<60;i++){if(predicate()){checks.Add(name);return;}await Task.Delay(50);}throw new Exception("Timeout: "+name);}
 [DllImport("user32.dll")]static extern IntPtr CreatePopupMenu();[DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern bool AppendMenu(IntPtr menu,uint flags,IntPtr id,string text);[DllImport("user32.dll")]static extern bool TrackPopupMenuEx(IntPtr menu,uint flags,int x,int y,IntPtr owner,IntPtr unused);[DllImport("user32.dll")]static extern bool DestroyMenu(IntPtr menu);[DllImport("user32.dll")]static extern bool EndMenu();[DllImport("user32.dll")]static extern bool PostMessage(IntPtr h,uint m,IntPtr a,IntPtr b);

 delegate IntPtr PanelProc(IntPtr h,uint m,IntPtr w,IntPtr l);static readonly PanelProc panelProc=DefWindowProc;
 [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]struct PanelClass {public uint Style;public IntPtr Proc;public int ClsExtra,WndExtra;public IntPtr Instance,Icon,Cursor,Background;public string Menu,Name;}
 [DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern IntPtr DefWindowProc(IntPtr h,uint m,IntPtr w,IntPtr l);
 [DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern ushort RegisterClass(ref PanelClass cls);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode)]static extern IntPtr GetModuleHandle(string name);
 [DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern IntPtr CreateWindowEx(uint ex,string cls,string name,uint style,int x,int y,int width,int height,IntPtr parent,IntPtr menu,IntPtr instance,IntPtr param);
 [DllImport("user32.dll")]static extern bool ShowWindow(IntPtr h,int show);[DllImport("user32.dll")]static extern bool DestroyWindow(IntPtr h);
 static IntPtr CreatePanel(){var instance=GetModuleHandle(null);var cls=new PanelClass{Proc=Marshal.GetFunctionPointerForDelegate(panelProc),Instance=instance,Background=new IntPtr(6),Name="TopLevelWindowForOverflowXamlIsland"};RegisterClass(ref cls);var area=Forms.Screen.PrimaryScreen.WorkingArea;var panel=CreateWindowEx(0x08000080,cls.Name,"Tray panel fixture",0x80000000,area.Right-340,area.Bottom-260,320,240,IntPtr.Zero,IntPtr.Zero,instance,IntPtr.Zero);if(panel==IntPtr.Zero)throw new Exception("Cannot create panel fixture");return panel;}
 static int Fixture(string folder){var app=new Application();var owner=new Window{Title="Menu priority fixture",Width=360,Height=200,Left=80,Top=80,ShowInTaskbar=false};var handle=IntPtr.Zero;IntPtr trayPanel=IntPtr.Zero;var popup=new Popup{StaysOpen=true,AllowsTransparency=true,Placement=PlacementMode.Absolute};var child=new Popup{StaysOpen=true,AllowsTransparency=true,Placement=PlacementMode.Absolute};popup.Child=new Border{Width=180,Height=160,Background=Brushes.White,Child=new TextBlock{Text="Custom tray menu fixture"}};child.Child=new Border{Width=130,Height=110,Background=Brushes.White,Child=new TextBlock{Text="Submenu fixture"}};string last="";var timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(40)};
 owner.Loaded+=delegate{handle=new WindowInteropHelper(owner).Handle;IpcWrite(Path.Combine(folder,"fixture-hwnd"),handle.ToInt64().ToString());timer.Start();};
 timer.Tick+=delegate{string file=Path.Combine(folder,"command");if(!File.Exists(file))return;string cmd=IpcRead(file);if(cmd==last)return;last=cmd;var area=Forms.Screen.PrimaryScreen.WorkingArea;double dpi=PresentationSource.FromVisual(owner).CompositionTarget.TransformToDevice.M11;
  if(cmd=="tray-panel"){if(trayPanel==IntPtr.Zero)trayPanel=CreatePanel();ShowWindow(trayPanel,4);}
  if(cmd=="quit"){if(trayPanel!=IntPtr.Zero)DestroyWindow(trayPanel);EndMenu();popup.IsOpen=false;child.IsOpen=false;owner.Close();return;}
  if(cmd=="native"){owner.Activate();IntPtr menu=CreatePopupMenu(),sub=CreatePopupMenu();AppendMenu(sub,0,new IntPtr(2),"Fixture item");AppendMenu(menu,0x10,sub,"Fixture submenu");AppendMenu(menu,0,new IntPtr(1),"Fixture no-op");IpcWrite(Path.Combine(folder,"ready"),cmd);TrackPopupMenuEx(menu,0x100|0x2,area.Right-220,area.Bottom-180,handle,IntPtr.Zero);DestroyMenu(menu);return;}
  if(cmd=="custom"){popup.HorizontalOffset=(area.Right-300)/dpi;popup.VerticalOffset=(area.Bottom-200)/dpi;popup.IsOpen=true;}
  if(cmd=="child"){child.HorizontalOffset=(area.Right-120)/dpi;child.VerticalOffset=(area.Bottom-200)/dpi;child.IsOpen=true;}
  if(cmd=="close-child")child.IsOpen=false;
  if(cmd=="close"){if(trayPanel!=IntPtr.Zero)ShowWindow(trayPanel,0);EndMenu();child.IsOpen=false;popup.IsOpen=false;}
  IpcWrite(Path.Combine(folder,"ready"),cmd);
 };app.Run(owner);return 0;}
 [STAThread]static int Main(string[] args){if(args[0]=="--fixture")return Fixture(args[1]);Store.Root=args[0];Directory.CreateDirectory(Store.Root);Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=true,MusicHoverOnly=false,ToolbarPinned=true,SleepSchedule=false,IdleSleep=false,HideFullscreen=false,ReduceMotion=true});var app=new Application{ShutdownMode=ShutdownMode.OnExplicitShutdown};var pet=new PetWindow(true);bool passed=false;ExternalMenuMonitor monitor=null;Process fixture=null;IntPtr oldForeground=Native.GetForegroundWindow(),fixtureHandle=IntPtr.Zero;
 pet.Loaded+=async delegate{try{await Task.Delay(250);((DispatcherTimer)Field(pet,"animation")).Stop();foreach(var s in app.Windows.OfType<SettingsWindow>().ToArray())s.Close();
  Check(MenuPriorityRules.TrayPanel("NotifyIconOverflowWindow")&&MenuPriorityRules.TrayPanel("TopLevelWindowForOverflowXamlIsland"),"Windows 10 and 11 hidden-icon panels are recognized");Check(!MenuPriorityRules.TrayPanel("Shell_TrayWnd"),"ordinary taskbar does not permanently lower pet");Check(new Config().YieldToMenus,"menu priority defaults on");var copy=PreferenceTransfer.Import(PreferenceTransfer.Export(new Config{YieldToMenus=false},false));Check(!copy.YieldToMenus,"menu priority switch transfers");Check(MenuPriorityRules.StandardPopup("#32768",0),"native menu class recognized");Check(MenuPriorityRules.StandardPopup("WindowsForms10.Window.8.app.fixture",0x80000000),"WinForms dropdown recognized");Check(!MenuPriorityRules.StandardPopup("WindowsForms10.Window.8.app.fixture",0x80C40000),"regular WinForms window is not a menu");
  var screen=new System.Drawing.Rectangle(-1920,0,1920,1080);var anchor=new Native.Point{X=-150,Y=1020};var info=new MenuWindowInfo{ClassName="QtFixturePopup",Style=0x80000000,Bounds=new Native.Rect{Left=-400,Top=800,Right=-130,Bottom=1020}};Check(MenuPriorityRules.TrayPopup(info,anchor,screen),"custom popup supports negative monitor coordinates");info.ClassName="tooltips_class32";Check(!MenuPriorityRules.TrayPopup(info,anchor,screen),"tooltip does not trigger menu hiding");info.ClassName="QtFixturePopup";info.Style=0x80C40000;Check(!MenuPriorityRules.TrayPopup(info,anchor,screen),"decorated window near tray is not a menu");
  foreach(string reason in new[]{"locked","manual","fullscreen","quiet"})Check(MenuPriorityRules.HiddenReason(reason=="locked",reason=="manual",reason=="fullscreen",reason=="quiet",true)==reason,reason+" takes priority over menus");
  pet.Music.Current=new MusicState{Connected=true,Id="fixture",Title="Menu test",Artist="No real playback",Playing=true,CanToggle=true,At=DateTime.UtcNow};Call(pet,"UpdateMusic");var music=(MusicWindow)Field(pet,"musicWindow");var before=Bounds(pet);Check(music.IsVisible,"pinned music starts visible");
  monitor=new ExternalMenuMonitor(pet.Dispatcher,b=>Call(pet,"UpdateMenuPriority",b));Set(pet,"externalMenus",monitor);await Until(()=>!monitor.Active,"no menus at baseline");Call(pet,"OpenMenu");await Task.Delay(250);Check(!monitor.Active&&pet.IsVisible,"own pet context menu remains usable");Call(pet,"ClosePetMenu");
  fixture=Process.Start(new ProcessStartInfo{FileName=Assembly.GetExecutingAssembly().Location,Arguments="--fixture \""+Store.Root+"\"",UseShellExecute=false,CreateNoWindow=true});await Until(()=>File.Exists(Path.Combine(Store.Root,"fixture-hwnd")),"external fixture ready");fixtureHandle=new IntPtr(long.Parse(IpcRead(Path.Combine(Store.Root,"fixture-hwnd"))));
  IpcWrite(Path.Combine(Store.Root,"command"),"native");await Until(()=>monitor.Active&&pet.IsVisible&&!pet.Topmost,"native menu lowers visible pet promptly");Check(music.IsVisible&&pet.ToolbarVisible&&!music.Topmost,"music and toolbar stay visible without topmost");Check(!Native.IsTopmost(new WindowInteropHelper(pet).Handle)&&!Native.IsTopmost(new WindowInteropHelper(music).Handle),"native topmost flags cleared for both windows");Check(monitor.PriorityWindows.All(h=>!Native.IsAbove(new WindowInteropHelper(pet).Handle,h)&&!Native.IsAbove(new WindowInteropHelper(music).Handle,h)),"both windows are below every detected menu");Check((string)Field(pet,"lastHidden")==""&&pet.MenuLayerYielding,"layer priority does not set a hidden reason");var foreground=Native.GetForegroundWindow();Call(pet,"MaintainWindowStack");Check(pet.IsVisible&&!pet.Topmost&&Native.GetForegroundWindow()==foreground,"stack repair does not compete with menu or steal focus");
  pet.Settings.YieldToMenus=false;pet.ApplySettings();Check(pet.IsVisible&&pet.Topmost&&music.Topmost,"turning menu priority off restores topmost immediately");pet.Settings.YieldToMenus=true;pet.ApplySettings();Check(pet.IsVisible&&!pet.Topmost,"turning preference back on lowers rather than hides pet");
  PostMessage(fixtureHandle,0x1F,IntPtr.Zero,IntPtr.Zero);IpcWrite(Path.Combine(Store.Root,"command"),"close");await Until(()=>!monitor.Active&&pet.IsVisible,"closing native menu restores pet");Check(Bounds(pet).Equals(before),"restoration preserves pet position");Check(pet.Topmost&&music.Topmost&&Native.IsTopmost(new WindowInteropHelper(pet).Handle),"menu closure restores native topmost");pet.Music.Current.At=DateTime.UtcNow;Call(pet,"UpdateMusic");Check(music.IsVisible,"pinned music returns after menu closes");
  monitor.Scan();var area=Forms.Screen.PrimaryScreen.WorkingArea;Call(monitor,"ArmTray",new Native.Point{X=area.Right-200,Y=area.Bottom-20});IpcWrite(Path.Combine(Store.Root,"command"),"custom");await Until(()=>monitor.Active&&pet.IsVisible&&!pet.Topmost,"custom WPF tray popup lowers pet");IpcWrite(Path.Combine(Store.Root,"command"),"child");await Until(()=>File.Exists(Path.Combine(Store.Root,"ready"))&&IpcRead(Path.Combine(Store.Root,"ready"))=="child","custom submenu opens");IpcWrite(Path.Combine(Store.Root,"command"),"close-child");await Task.Delay(500);Check(monitor.Active&&pet.IsVisible&&!pet.Topmost,"closing child keeps pet non-topmost below parent");
  Set(pet,"manualHidden",true);Call(pet,"RefreshPetVisibility");IpcWrite(Path.Combine(Store.Root,"command"),"close");await Until(()=>!monitor.Active,"custom popup closure reconciles");Check(!pet.IsVisible&&(string)Field(pet,"lastHidden")=="manual","menu closure preserves manual hide");Set(pet,"manualHidden",false);Call(pet,"RefreshPetVisibility");Check(pet.IsVisible,"manual recovery still works");
  IpcWrite(Path.Combine(Store.Root,"command"),"custom");await Until(()=>IpcRead(Path.Combine(Store.Root,"ready"))=="custom","unarmed custom popup opens");await Task.Delay(500);Check(!monitor.Active&&pet.IsVisible,"unarmed custom popup is not mistaken for tray menu");IpcWrite(Path.Combine(Store.Root,"command"),"close");await Until(()=>IpcRead(Path.Combine(Store.Root,"ready"))=="close","unarmed popup closes");await Task.Delay(250);
  pet.Music.Current.At=DateTime.UtcNow;Call(pet,"UpdateMusic");IpcWrite(Path.Combine(Store.Root,"command"),"tray-panel");await Until(()=>monitor.Active&&pet.IsVisible&&!pet.Topmost,"opening hidden-icon panel lowers pet without a right click");Check(music.IsVisible&&!music.Topmost,"hidden-icon panel also lowers visible music card");Check(monitor.PriorityWindows.All(h=>!Native.IsAbove(new WindowInteropHelper(pet).Handle,h)),"pet is below actual panel window");IpcWrite(Path.Combine(Store.Root,"command"),"close");await Until(()=>!monitor.Active&&pet.Topmost&&music.Topmost,"closing hidden-icon panel restores both topmost flags");
  monitor.Scan();Call(monitor,"ArmTray",new Native.Point{X=area.Right-200,Y=area.Bottom-20});IpcWrite(Path.Combine(Store.Root,"command"),"custom");await Until(()=>monitor.Active,"second custom popup detected");fixture.Kill();await Until(()=>!monitor.Active&&pet.IsVisible,"crashed menu process restores normal topmost");
  Check(pet.Topmost&&music.Topmost,"topmost restored after menu process exit");monitor.Dispose();Check(monitor.Disposed,"event and mouse hooks disposed");passed=true;
 }catch(Exception e){Store.Atomic("menu-layer-error.json",new{error=e.ToString()});}finally{if(monitor!=null)monitor.Dispose();if(fixture!=null&&!fixture.HasExited){PostMessage(fixtureHandle,0x1F,IntPtr.Zero,IntPtr.Zero);IpcWrite(Path.Combine(Store.Root,"command"),"quit");if(!fixture.WaitForExit(1500))fixture.Kill();}if(oldForeground!=IntPtr.Zero)Native.FocusPetForMenu(oldForeground);Store.Atomic("menu-layer-tests.json",new{version="0.6.5",passed=passed,checks=checks});pet.Close();}};app.Run(pet);return passed?0:1;}
}
