using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Interop;using System.Windows.Threading;using System.Runtime.InteropServices;using KianaPet;
class DockingTests {
 [DllImport("user32.dll")]static extern bool SetCursorPos(int x,int y);
 static List<string> checks=new List<string>();static void Check(bool b,string n){if(!b)throw new Exception(n);checks.Add(n);}static object Field(object o,string n){return o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}static void Set(object o,string n,object v){o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).SetValue(o,v);}static object Call(object o,string n,params object[] args){return o.GetType().GetMethod(n,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(o,args);}static Native.Rect Bounds(Window w){Native.Rect r;Native.GetWindowRect(new WindowInteropHelper(w).Handle,out r);return r;}
 static void Capture(PetWindow p,MusicWindow m,string file){p.UpdateLayout();m.UpdateLayout();var pb=Bounds(p);var mb=Bounds(m);double dpi=PresentationSource.FromVisual(p).CompositionTarget.TransformToDevice.M11;double left=Math.Min(pb.Left,mb.Left)/dpi,top=Math.Min(pb.Top,mb.Top)/dpi,right=Math.Max(pb.Right,mb.Right)/dpi,bottom=Math.Max(pb.Bottom,mb.Bottom)/dpi;var visual=new DrawingVisual();using(var draw=visual.RenderOpen()){draw.DrawRectangle(Brushes.White,null,new Rect(0,0,right-left+20,bottom-top+20));foreach(var w in new Window[]{p,m}){var b=Bounds(w);var image=new RenderTargetBitmap((int)Math.Ceiling(w.ActualWidth),(int)Math.Ceiling(w.ActualHeight),96,96,PixelFormats.Pbgra32);image.Render(w);draw.DrawImage(image,new Rect(b.Left/dpi-left+10,b.Top/dpi-top+10,w.ActualWidth,w.ActualHeight));}}var bitmap=new RenderTargetBitmap((int)Math.Ceiling(right-left+20),(int)Math.Ceiling(bottom-top+20),96,96,PixelFormats.Pbgra32);bitmap.Render(visual);var png=new PngBitmapEncoder();png.Frames.Add(BitmapFrame.Create(bitmap));using(var stream=File.Create(Path.Combine(Store.Root,file)))png.Save(stream);}
 [STAThread]static int Main(string[] args){Store.Root=args[0];Directory.CreateDirectory(Store.Root);Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=true,MusicHoverOnly=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false,AmbientActions=false,Size=176});var app=new Application{ShutdownMode=ShutdownMode.OnExplicitShutdown};var pet=new PetWindow(true);bool passed=false;Native.Point original;Native.GetCursorPos(out original);
 pet.Loaded+=async delegate{try{await Task.Delay(300);foreach(var w in app.Windows.OfType<SettingsWindow>().ToArray())w.Close();((DispatcherTimer)Field(pet,"animation")).Stop();SetCursorPos(0,0);Set(pet,"hover",false);Set(pet,"toolbarUntil",-1d);Set(pet,"musicUntil",0d);var area=System.Windows.Forms.Screen.PrimaryScreen.WorkingArea;Call(pet,"MoveTo",area.Left+400d,area.Top+150d);pet.UpdateLayout();Call(pet,"SetToolbarVisible",false,true);pet.Music.Current=new MusicState{Connected=true,Id="fixture",Title="常驻布局演示",Artist="模拟信息 · 不控制播放器",Playing=true,CanToggle=true,CanPrevious=true,CanNext=true,At=DateTime.UtcNow};Call(pet,"UpdateMusic");await Task.Delay(240);var music=(MusicWindow)Field(pet,"musicWindow");var compact=Bounds(music);var full=Bounds(pet);var shortBounds=pet.MusicFootprint(full);Check(music.IsVisible&&!pet.ToolbarVisible,"音乐常驻且工具栏独立隐藏");Check(compact.Top>=shortBounds.Bottom&&compact.Top<full.Bottom,"隐藏工具栏时音乐栏收起预留空白");Capture(pet,music,"music-pinned-compact.png");
 pet.SetToolbarPinned(true);Check(music.DockMoving,"工具栏出现触发真实位置过渡");await Task.Delay(70);var moving=Bounds(music);Check(moving.Top>compact.Top&&moving.Top<full.Bottom+20,"让位途中位置连续变化");await Task.Delay(350);Check(pet.ToolbarVisible&&!music.DockMoving&&Bounds(music).Top>=full.Bottom,"工具栏常驻完成后音乐栏位于其下方");Capture(pet,music,"both-pinned.png");Set(pet,"musicUntil",0d);Set(pet,"toolbarUntil",-1d);Check(!(bool)pet.GetType().GetProperty("ToolbarActive",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(pet,null),"常驻但未操作的工具栏不锁住自动走动");
 pet.SetToolbarPinned(false);await Task.Delay(180);Call(pet,"UpdateMusic");Check(music.DockMoving,"工具栏淡出后音乐栏平滑贴回");await Task.Delay(240);Check(Bounds(music).Top==compact.Top,"工具栏隐藏恢复紧凑位置");
 pet.Settings.MusicPosition="free";pet.Settings.MusicHasPosition=true;pet.Settings.MusicX=compact.Left;pet.Settings.MusicY=compact.Top;pet.ApplySettings();pet.PositionMusic();double savedX=pet.Settings.MusicX,savedY=pet.Settings.MusicY;pet.SetToolbarPinned(true);await Task.Delay(400);Check(Bounds(music).Top>=full.Bottom||Bounds(music).Right<=full.Left||Bounds(music).Left>=full.Right,"自由位置与新出现工具栏冲突时自动让位");Check(pet.Settings.MusicX==savedX&&pet.Settings.MusicY==savedY,"自动让位不覆盖用户拖动位置");pet.SetToolbarPinned(false);await Task.Delay(180);Call(pet,"UpdateMusic");await Task.Delay(240);Check(Bounds(music).Left==(int)savedX&&Bounds(music).Top==(int)savedY,"工具栏收起后恢复记住的自由位置");
 pet.Settings.MusicX=area.Left+30;pet.Settings.MusicY=area.Top+30;pet.PositionMusic();var separate=Bounds(music);pet.SetToolbarPinned(true);await Task.Delay(400);Check(Bounds(music).Left==separate.Left&&Bounds(music).Top==separate.Top,"远离工具栏的自由位置保持不动");pet.SetToolbarPinned(false);await Task.Delay(180);pet.SetMusicPinned(false);Set(pet,"hover",false);Set(pet,"toolbarUntil",-1d);Set(pet,"musicUntil",0d);Call(pet,"UpdateMusic");await Task.Delay(180);Check(!music.IsVisible,"关闭常驻恢复原来的悬停显示模式");Set(pet,"hover",true);Call(pet,"UpdateToolbar",10d);Call(pet,"UpdateMusic");await Task.Delay(240);Check(music.IsVisible&&pet.ToolbarVisible,"非常驻悬停仍显示音乐与工具栏");Check(pet.MusicFootprint(Bounds(pet)).Height==Bounds(pet).Height,"非持续模式保留原有完整避让范围");
 pet.SetMusicPinned(true);pet.SetToolbarPinned(true);var loaded=Store.Load();Check(!loaded.MusicHoverOnly&&loaded.ToolbarPinned,"两个常驻偏好分别持久保存");var imported=PreferenceTransfer.Import(PreferenceTransfer.Export(loaded,false));Check(imported.ToolbarPinned&&!imported.MusicHoverOnly,"常驻偏好可迁移");pet.Settings.ReduceMotion=true;pet.ApplySettings();pet.SetToolbarPinned(false);Set(pet,"hover",false);Set(pet,"toolbarUntil",-1d);Call(pet,"UpdateToolbar",100d);await Task.Delay(30);Call(pet,"UpdateMusic");Check(!music.DockMoving,"减少动态时位置直接对齐而不播放过渡");
 foreach(double dpi in new[]{1d,1.5,2d}){var f=new System.Drawing.Rectangle(-1600,100,(int)(176*dpi),(int)(289*dpi));var r=DockingRules.Footprint(f,(int)(40*dpi),false,false);Check(r.Bottom==f.Bottom-(int)(40*dpi)&&r.Left==f.Left,"DPI "+dpi+" 保留负坐标并正确减去工具栏高度");}Check(DockingRules.Ease(0)==0&&DockingRules.Ease(1)==1&&DockingRules.Ease(.5)>.5,"让位动画有明确起点终点与减速");
 var align=Store.Json.Deserialize<SkinAlignment[]>(File.ReadAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets","sprite-alignment.json")));Check(align.Length==3&&align.All(x=>x.Extra.Length==6&&x.Ambient.Length==4&&x.Transition.Length==4),"三套Q版42张后补姿态都有比例校准");foreach(var skin in align){pet.SelectSkin(skin.Skin);Set(pet,"state","pat");Call(pet,"DrawAnimation",0d);var image=(Image)Field(pet,"sprite");var matrix=((MatrixTransform)image.RenderTransform).Matrix;Check(Math.Abs(matrix.M11-skin.Extra[0].Scale)<.00001&&matrix.M11<1,skin.Skin+" 摸头帧按原站姿缩放");pet.Settings.Size=256;pet.ResizePet();Check(Math.Abs(((MatrixTransform)image.RenderTransform).Matrix.OffsetY-skin.Extra[0].OffsetY*256/384)<.0001,skin.Skin+" 宠物大小改变时校准同步缩放");Call(pet,"SetFrame",0,0);Check(((MatrixTransform)image.RenderTransform).Matrix.IsIdentity,skin.Skin+" 切回原图恢复恒等变换");}pet.SelectSkin("time-runner-kiana");Call(pet,"SetFrame",0,0);Check(((MatrixTransform)((Image)Field(pet,"sprite")).RenderTransform).Matrix.IsIdentity,"普通三套原图不误用Q版校准");
 passed=true;}catch(Exception e){Store.Atomic("docking-error.json",new{error=e.ToString()});}finally{SetCursorPos(original.X,original.Y);Store.Atomic("docking-tests.json",new{version="0.6.1",passed=passed,checks=checks});pet.Close();}};app.Run(pet);return passed?0:1;}
}
