using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Threading;using System.Windows.Interop;using KianaPet;using Forms=System.Windows.Forms;
class ExperienceUiTests {
 static List<string> checks=new List<string>();static void Check(bool v,string n){if(!v)throw new Exception(n);checks.Add(n);}static object Field(object o,string n){return o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}static void Set(object o,string n,object v){o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).SetValue(o,v);}static object Call(object o,string n,params object[] a){return o.GetType().GetMethod(n,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(o,a);}
 static void Capture(Window w,string label,int dpi){w.UpdateLayout();var bitmap=new RenderTargetBitmap((int)Math.Ceiling(w.ActualWidth*dpi/96d),(int)Math.Ceiling(w.ActualHeight*dpi/96d),dpi,dpi,PixelFormats.Pbgra32);bitmap.Render(w);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(bitmap));using(var f=File.Create(Path.Combine(Store.Root,label+"-"+dpi+"dpi.png")))encoder.Save(f);}
 [STAThread]static int Main(string[] args){Store.Root=args[0];Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false});var app=new Application{ShutdownMode=ShutdownMode.OnLastWindowClose};var pet=new PetWindow(true);bool passed=false;
 pet.Loaded+=async delegate{try{await Task.Delay(1200);((DispatcherTimer)Field(pet,"animation")).Stop();var settings=app.Windows.OfType<SettingsWindow>().First();settings.NavigateCategory("启动与联动","");Check(settings.ActiveCategory=="启动与联动","启动选项有独立设置分类");foreach(int dpi in new[]{96,120,144,192})Capture(settings,"startup",dpi);settings.NavigateCategory("通知中心","");Check(settings.ActiveCategory=="通知中心","提醒方式在通知设置中可达");Capture(settings,"notifications-settings",144);Check(settings.UseLayoutRounding&&settings.SnapsToDevicePixels,"设置使用布局取整和像素对齐");settings.Close();
 pet.Settings.LinkChatGPT=true;var now=DateTime.UtcNow;pet.Link.Current=new BridgeState{Connected=true,AppOpen=true,Code="fallback",NotificationSource="main",Label="备用状态 · 思考中 / 处理中",CanNotifications=true,NotificationCount=3,NotificationColor="#3a83f7",LastSuccessAt=now,Notices=new[]{new BridgeNotice{Id="a",Title="检查多显示器布局",State="running",UpdatedAt=now},new BridgeNotice{Id="b",Title="音乐栏样式已经更新",State="review",UpdatedAt=now.AddMinutes(-1)},new BridgeNotice{Id="c",Title="等待确认本次构建",State="waiting",UpdatedAt=now.AddMinutes(-2)}}};Call(pet,"UpdateToolbar",10000d);Check(((Button)Field(pet,"notificationButton")).Visibility==Visibility.Visible,"多任务铃铛正常显示");Call(pet,"OpenToolbarNotifications");await Task.Delay(100);var center=app.Windows.OfType<NoticeCenter>().Single();Check(center.VisibleTaskCount==3,"铃铛打开统一多任务列表");foreach(int dpi in new[]{96,120,144,192})Capture(center,"task-list",dpi);
 ((ComboBox)Field(center,"status")).SelectedIndex=2;Check(center.VisibleTaskCount==1,"任务状态过滤准确");((ComboBox)Field(center,"status")).SelectedIndex=0;
 var last=pet.Link.Current;last.At=DateTime.UtcNow.AddSeconds(-15);pet.Link.Current=LinkResilience.KeepLast(new BridgeState{AppOpen=true,Code="timeout",At=DateTime.UtcNow.AddSeconds(-12)},last,DateTime.UtcNow,30);Call(pet,"UpdateToolbar",10001d);Check(pet.NotificationsAvailable&&((Button)Field(pet,"notificationButton")).Visibility==Visibility.Visible,"重试间隔超过十秒仍保留有效缓存角标");Call(center,"Refresh",true);Check(((TextBlock)Field(center,"connection")).Text.Contains("上次状态"),"列表标出断线保留和最后同步");Capture(center,"stale-task-list",144);center.Close();
 pet.Link.Current=new BridgeState{Connected=true,AppOpen=true};Call(pet,"UpdateToolbar",10002d);Check(((Button)Field(pet,"notificationButton")).Visibility==Visibility.Collapsed,"新鲜空闲状态隐藏铃铛");pet.Settings.LinkChatGPT=false;pet.Settings.MusicPosition="free";pet.Settings.MusicHasPosition=true;pet.Settings.MusicX=99999;pet.Settings.MusicY=-99999;Call(pet,"MoveTo",99999d,-99999d);Call(pet,"ScheduleDisplayRecovery",false);Set(pet,"displayDue",-1d);Call(pet,"CheckDisplay",100000d);Set(pet,"displayDue",-1d);Call(pet,"CheckDisplay",100002d);Native.Rect r;Native.GetWindowRect(new WindowInteropHelper(pet).Handle,out r);Check(Forms.Screen.AllScreens.Any(s=>s.WorkingArea.Contains(new System.Drawing.Rectangle(r.Left,r.Top,r.Width,r.Height))),"显示恢复将离屏宠物完整移入可见工作区");Check(Forms.Screen.AllScreens.Any(s=>s.WorkingArea.Contains((int)pet.Settings.MusicX,(int)pet.Settings.MusicY)),"显示恢复修复自由音乐栏坐标");Check(!(bool)Field(pet,"displayPending"),"分阶段复核完成后不遗留恢复状态");Check(!pet.Settings.LaunchChatGPTOnStart&&!pet.Settings.LaunchMusicOnStart,"显示恢复不改启动开关");
 Set(pet,"manualHidden",true);Call(pet,"ScheduleDisplayRecovery",true);Check((bool)Field(pet,"manualHidden"),"唤醒恢复尊重手动隐藏");Check((int)Field(pet,"displayRechecks")==3,"唤醒后进行三阶段显示布局复核");passed=true;
 }catch(Exception e){Store.Atomic("error.json",new{error=e.ToString()});}finally{Store.Atomic("experience-ui-tests.json",new{passed,checks});foreach(var w in app.Windows.Cast<Window>().Where(w=>w!=pet).ToArray())w.Close();pet.Close();}};app.Run(pet);return passed?0:1;
 }
}
