using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Drawing;using KianaPet;
class ExperienceTests {
 static List<string> checks=new List<string>();static void Check(bool value,string name){if(!value)throw new Exception(name);checks.Add(name);}static void Publish(Bridge b,BridgeState s){typeof(Bridge).GetMethod("PublishState",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(b,new object[]{s});}
 static BridgeState Active(string state){return new BridgeState{AppOpen=true,Connected=true,Code="connected",State=state,NotificationCount=1,Notices=new[]{new BridgeNotice{Id="task-1",Title="测试任务",State=state,UpdatedAt=DateTime.UtcNow}}};}
 static int Main(string[] args){Store.Root=args[0];try{
 var c=new Config();Check(!c.LaunchChatGPTOnStart&&!c.LaunchMusicOnStart&&!c.NoticeSound&&!c.NoticeQuiet,"默认不启动其他应用、不播放声音");Check(StartupRules.ShouldLaunch(true,false,false)&&!StartupRules.ShouldLaunch(true,true,false)&&!StartupRules.ShouldLaunch(false,false,false)&&!StartupRules.ShouldLaunch(true,false,true),"启动只执行用户启用且未运行的应用，预览不启动");
 c.LaunchChatGPTOnStart=true;c.LaunchMusicOnStart=true;c.NoticeQuiet=true;c.NoticeSound=true;c.CompletionNoticeSeconds=12;c.NotificationGraceSeconds=60;var copy=PreferenceTransfer.Import(PreferenceTransfer.Export(c,true));Check(copy.LaunchChatGPTOnStart&&copy.LaunchMusicOnStart&&copy.NoticeQuiet&&copy.NoticeSound&&copy.CompletionNoticeSeconds==12&&copy.NotificationGraceSeconds==60,"新偏好完整迁移");c.CompletionNoticeSeconds=999;c.NotificationGraceSeconds=-2;c.Validate();Check(c.CompletionNoticeSeconds==30&&c.NotificationGraceSeconds==10,"提醒时长配置边界校验");Check(!Store.Json.Deserialize<Config>("{\"Schema\":1}").LaunchChatGPTOnStart,"旧设置升级默认关闭启动联动");
 foreach(string code in new[]{"app-closed","launcher-missing","session-stale","endpoint-unavailable"})Check(StartupRules.RepairAction(code)=="launcher","定向修复启动会话："+code);foreach(string code in new[]{"connected","fallback","mini-missing","timeout","endpoint-rejected"})Check(StartupRules.RepairAction(code)=="recheck","不启动无关应用："+code);
 var now=DateTime.UtcNow;var last=Active("running");last.At=now.AddSeconds(-12);var stale=LinkResilience.KeepLast(new BridgeState{AppOpen=true,Code="timeout"},last,now,30);Check(stale.Stale&&!stale.Connected&&stale.NotificationCount==1&&stale.Notices.Length==1&&!stale.CanVoice&&stale.NotificationColor=="#8b8790","断线保留灰色任务状态并禁用远程动作");Check(!LinkResilience.KeepLast(new BridgeState{AppOpen=true,Code="timeout"},last,now.AddSeconds(20),30).Stale,"保留状态到期清理");Check(!LinkResilience.KeepLast(new BridgeState{AppOpen=false,Code="app-closed"},last,now,30).Stale,"主动关闭应用不留下幽灵通知");Check(!LinkResilience.KeepLast(new BridgeState{AppOpen=true,Code="endpoint-rejected"},last,now,30).Stale,"校验失败不使用缓存冒充有效连接");
 using(var b=new Bridge()){Publish(b,Active("running"));Publish(b,new BridgeState{AppOpen=true,Code="timeout"});Check(b.Current.Stale,"真实发布路径保留状态");Publish(b,new BridgeState{AppOpen=true,Connected=true,Code="connected"});Publish(b,new BridgeState{AppOpen=true,Code="timeout"});Check(!b.Current.Stale&&b.Current.NotificationCount==0,"成功空闲快照替代旧缓存，不复活已读任务");}
 var fallback=new BridgeState{AppOpen=true};Bridge.MergeMainNotifications(fallback,"{\"ready\":true,\"notices\":[{\"id\":\"task-1\",\"state\":\"running\",\"title\":\"测试标题\",\"updatedAt\":1780000000000}]}");Check(fallback.NotificationSource=="main"&&fallback.MainReady&&fallback.Label.Contains("备用状态")&&fallback.Notices[0].UpdatedAt.Year==2026,"备用来源明确标记并保留任务更新时间");Check(!Store.Json.Serialize(fallback).Contains("测试标题"),"诊断文件不写入任务标题");var empty=new BridgeState{AppOpen=true};Bridge.MergeMainNotifications(empty,"{\"ready\":true,\"notices\":[]}");Check(empty.NotificationSource=="main"&&empty.State=="idle"&&empty.NotificationCount==0,"主窗口确认空闲时不继续显示过期状态");
 var transitions=new NotificationTransitions();Check(transitions.Update(Active("review")).Length==0,"初次连接不重播旧完成通知");Check(transitions.Update(Active("running")).Length==0,"运行态不产生完成提醒");Check(transitions.Update(Active("review")).Length==1&&transitions.Update(Active("review")).Length==0,"完成提醒一次，不因轮询重复");Check(transitions.Update(stale).Length==0&&transitions.Update(Active("review")).Length==0,"短断线恢复不重复提醒");var many=Active("running");many.Notices=new[]{new BridgeNotice{Id="a",State="review"},new BridgeNotice{Id="b",State="failed"},new BridgeNotice{Id="c",State="waiting"}};Check(transitions.Update(many).Length==3,"不同任务的完成失败等待分别识别");
 var batch=new NoticeBatcher();batch.Add(new TaskNotice{Source="ChatGPT",TaskId="1",Title="完成",Status="succeeded"},now,2);Check(batch.Flush(now.AddSeconds(3),true,true,true)==null&&batch.Flush(now.AddSeconds(4),false,true,true)==null,"免打扰结束仍尊重普通完成静默");batch.Add(new TaskNotice{Source="ChatGPT",TaskId="2",Title="失败",Status="failed"},now,2);Check(batch.Flush(now.AddSeconds(3),false,true,true)!=null,"仅完成静默仍允许失败提醒");batch.Add(new TaskNotice{Source="ChatGPT",TaskId="3",Title="等待",Status="waiting"},now,2);Check(batch.Flush(now.AddSeconds(3),false,false,false)==null&&batch.Flush(now.AddSeconds(4),false,true,false)==null,"全静默清空提醒队列，不延后补播");
 var left=new Rectangle(-1920,0,1920,1040);var primary=new Rectangle(0,0,2560,1400);Check(ScreenPlacement.Fit(new Rectangle(-1800,200,200,300),new[]{left,primary}).X==-1800,"保留副屏负坐标");var fit=ScreenPlacement.Fit(new Rectangle(-1800,200,200,300),new[]{primary});Check(primary.Contains(fit),"拔除副屏后位置落入现有屏幕");Check(primary.Contains(ScreenPlacement.Fit(new Rectangle(99999,-99999,420,120),new[]{primary})),"自由音乐栏离屏后安全归位");
 Store.Atomic("experience-tests.json",new{passed=true,checks});return 0;
 }catch(Exception e){Store.Atomic("experience-tests.json",new{passed=false,checks,error=e.ToString()});return 1;}}
}
