using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Diagnostics;using System.Threading.Tasks;using System.Runtime.InteropServices;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Interop;using System.Windows.Threading;using KianaPet;using Forms=System.Windows.Forms;
class LayoutTests {
 static List<string> checks=new List<string>();static void Check(bool ok,string name){if(!ok)throw new Exception(name);checks.Add(name);}
 static object Field(object o,string n){return o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}static void Set(object o,string n,object v){o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).SetValue(o,v);}static object Call(object o,string n,params object[] args){return o.GetType().GetMethod(n,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(o,args);}
 static Native.Rect R(int l,int t,int r,int b){return new Native.Rect{Left=l,Top=t,Right=r,Bottom=b};}
 static Native.Rect Bounds(Window w){Native.Rect r;Native.GetWindowRect(new WindowInteropHelper(w).Handle,out r);return r;}
 static StackPanel Page(SettingsWindow s,string name){s.NavigateCategory(name,"");var tabs=(TabControl)Field(s,"settingsTabs");return (StackPanel)((ScrollViewer)((TabItem)tabs.SelectedItem).Content).Content;}
 static Color[] ColorsOf(Brush b){var solid=b as SolidColorBrush;return solid!=null?new[]{solid.Color,solid.Color}:((LinearGradientBrush)b).GradientStops.Select(s=>s.Color).ToArray();}
 static BitmapSource Cover(){byte[] px={230,100,40,255,80,80,235,255};var b=BitmapSource.Create(2,1,96,96,PixelFormats.Bgra32,null,px,8);b.Freeze();return b;}
 static void Capture(FrameworkElement element,string name){element.UpdateLayout();var src=PresentationSource.FromVisual(element);double dpi=src==null?1:src.CompositionTarget.TransformToDevice.M11;var b=new RenderTargetBitmap((int)Math.Ceiling(element.ActualWidth*dpi),(int)Math.Ceiling(element.ActualHeight*dpi),96*dpi,96*dpi,PixelFormats.Pbgra32);var visual=new DrawingVisual();using(var draw=visual.RenderOpen()){draw.DrawRectangle(new VisualBrush(element){Stretch=Stretch.Fill},null,new Rect(0,0,element.ActualWidth,element.ActualHeight));}b.Render(visual);var png=new PngBitmapEncoder();png.Frames.Add(BitmapFrame.Create(b));using(var f=File.Create(Path.Combine(Store.Root,name)))png.Save(f);}
 [DllImport("user32.dll")]static extern bool SetCursorPos(int x,int y);
 static int Overlay(string root){var form=new Forms.Form{Text="Kiana test fixture",TopMost=true,ShowInTaskbar=false,StartPosition=Forms.FormStartPosition.Manual,Bounds=new System.Drawing.Rectangle(100,100,700,500)};string mode="";var timer=new Forms.Timer{Interval=50};timer.Tick+=delegate{if(File.Exists(Path.Combine(root,"quit-overlay"))){timer.Stop();form.Close();return;}string file=Path.Combine(root,"overlay-mode");string next=File.Exists(file)?File.ReadAllText(file):"maximized";if(next==mode)return;mode=next;if(next=="fullscreen"){form.WindowState=Forms.FormWindowState.Normal;form.FormBorderStyle=Forms.FormBorderStyle.None;form.Bounds=Forms.Screen.PrimaryScreen.Bounds;}else{form.FormBorderStyle=Forms.FormBorderStyle.Sizable;form.WindowState=Forms.FormWindowState.Maximized;}form.Activate();Native.RaiseWithoutActivation(form.Handle);File.WriteAllText(Path.Combine(root,"overlay-ready"),next);};form.Shown+=delegate{File.WriteAllText(Path.Combine(root,"overlay-hwnd"),form.Handle.ToInt64().ToString());timer.Start();};Forms.Application.Run(form);return 0;}
 static async Task WaitFile(string path,string text){for(int i=0;i<40;i++){if(File.Exists(path)&&(text==null||File.ReadAllText(path)==text))return;await Task.Delay(50);}throw new Exception("Timed out: "+path);}
 [STAThread]static int Main(string[] args){if(args[0]=="--overlay")return Overlay(args[1]);Store.Root=args[0];Directory.CreateDirectory(Store.Root);Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=true,MusicHoverOnly=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false,ReduceMotion=true});var app=new Application{ShutdownMode=ShutdownMode.OnExplicitShutdown};var pet=new PetWindow(true);bool passed=false;Process overlay=null;IntPtr original=Native.GetForegroundWindow();Native.Point cursor;Native.GetCursorPos(out cursor);
 pet.Loaded+=async delegate{try{await Task.Delay(300);((DispatcherTimer)Field(pet,"animation")).Stop();SetCursorPos(0,0);var settings=app.Windows.OfType<SettingsWindow>().Single();
  var old=Store.Json.Deserialize<Config>("{\"MusicEnabled\":true}");Check(old.MusicWidth==238&&old.MusicScalePercent==100&&!old.ToolbarFollowMusic,"old preferences preserve neutral toolbar and default size");var bad=new Config{MusicWidth=999,MusicScalePercent=-2};bad.Validate();Check(bad.MusicWidth==420&&bad.MusicScalePercent==80,"import clamps invalid dimensions");
  var appearance=Page(settings,"外观与互动");appearance.Children.OfType<CheckBox>().Single(c=>(string)c.Content=="工具栏跟随音乐栏配色").IsChecked=true;Check(pet.Settings.ToolbarFollowMusic,"appearance toggle is connected");var page=Page(settings,"音乐");page.Children.OfType<Slider>().Single(s=>System.Windows.Automation.AutomationProperties.GetName(s)=="整体大小（%）").Value=125;page.Children.OfType<Slider>().Single(s=>System.Windows.Automation.AutomationProperties.GetName(s).StartsWith("横向宽度")).Value=320;Check(pet.Settings.MusicWidth==320&&pet.Settings.MusicScalePercent==125,"music sliders independently save dimensions");var transfer=PreferenceTransfer.Import(PreferenceTransfer.Export(pet.Settings,false));Check(transfer.ToolbarFollowMusic&&transfer.MusicScalePercent==125&&transfer.MusicWidth==320,"all new preferences transfer");settings.NavigateCategory("音乐","音乐栏尺寸");settings.Capture(Path.Combine(Store.Root,"size-settings.png"));settings.Hide();
  var state=new MusicState{Connected=true,Id="fixture",Title="晴空中的约定 · 清晰缩放示意",Artist="琪亚娜的音乐时光",Playing=true,CanToggle=true,CanPrevious=true,CanNext=true,At=DateTime.UtcNow};pet.Music.Current=state;var library=(MusicLibrary)Field(pet,"musicLibrary");Set(library,"id",MusicLibrary.Identity(state));Set(library,"coverUrl",state.Cover);typeof(MusicLibrary).GetProperty("Cover").GetSetMethod(true).Invoke(library,new object[]{Cover()});Call(pet,"MoveTo",400d,150d);Call(pet,"SetToolbarVisible",true,false);Call(pet,"UpdateMusic");var music=(MusicWindow)Field(pet,"musicWindow");Check(music!=null&&music.IsVisible,"music card created");var toolbar=(Border)Field(pet,"hoverBar");var surface=(Border)Field(music,"surface");
  foreach(string mode in MusicGradient.Modes)foreach(string theme in new[]{"light","dark"}){pet.Settings.MusicTintMode=mode;pet.Settings.Theme=theme;pet.Settings.MusicTintStrength=100;pet.ApplySettings();Call(pet,"UpdateMusic");Check(ColorsOf(toolbar.Background).SequenceEqual(ColorsOf(surface.Background)),"shared toolbar colors: "+mode+" "+theme);}
  pet.Settings.Theme="light";pet.ApplySettings();pet.Settings.MusicHoverOnly=true;Set(pet,"hover",false);Set(pet,"musicUntil",0d);Call(pet,"SetToolbarVisible",false,true);Call(pet,"UpdateMusic");await Task.Delay(60);Check(!music.IsVisible&&ColorsOf(toolbar.Background).Any(c=>c!=PetPalette.Background),"toolbar keeps cover colors when music card is not hovered");
  pet.Settings.ToolbarFollowMusic=false;Call(pet,"UpdateMusic");Check(ColorsOf(toolbar.Background).All(c=>c==PetPalette.Background),"turning follow off restores neutral toolbar");pet.Settings.ToolbarFollowMusic=true;state.Connected=false;Call(pet,"UpdateMusic");Check(ColorsOf(toolbar.Background).All(c=>c==PetPalette.Background),"disconnect clears toolbar colors");state.Connected=true;state.At=DateTime.UtcNow;pet.Settings.MusicHoverOnly=false;pet.Settings.MusicTintMode="cover-gradient";Call(pet,"UpdateMusic");
  foreach(int scale in new[]{80,100,150})foreach(int width in new[]{200,420}){pet.Settings.MusicScalePercent=scale;pet.Settings.MusicWidth=width;pet.Settings.LargeTouchTargets=true;pet.Settings.MusicLyrics=true;pet.ApplySettings();Call(pet,"UpdateMusic");await Task.Delay(40);Check(Math.Abs(music.Width-width*scale/100d)<.01&&Math.Abs(music.Height-120*scale/100d)<.01,"scaled width and lyric height "+scale+" "+width);var next=(Button)Field(music,"next");var lyrics=(Button)Field(music,"lyrics");Point end=next.TranslatePoint(new Point(next.ActualWidth,0),music);Point start=lyrics.TranslatePoint(new Point(0,0),music);Check(end.X<=start.X+1,"buttons do not overlap at scale/width "+scale+" "+width);var mb=Bounds(music);var area=Forms.Screen.FromHandle(new WindowInteropHelper(pet).Handle).WorkingArea;Check(mb.Left>=area.Left&&mb.Right<=area.Right&&mb.Bottom<=area.Bottom,"resized card stays on screen "+scale+" "+width);}
  pet.Settings.MusicScalePercent=100;pet.Settings.MusicWidth=238;pet.Settings.LargeTouchTargets=false;pet.Settings.MusicLyrics=false;pet.ApplySettings();Call(pet,"SetToolbarVisible",true,false);Call(pet,"UpdateMusic");await Task.Delay(80);Check(toolbar.IsVisible&&toolbar.Opacity>.9,"colored toolbar is visibly revealed");Capture(toolbar,"toolbar-cover.png");music.Capture(Path.Combine(Store.Root,"music-default.png"));
  Call(pet,"OpenMenu");await Task.Delay(120);var menu=(ContextMenu)Field(pet,"toolbarMenu");var items=menu.Items.OfType<MenuItem>().ToArray();Check(items.Length==9,"right-click menu has nine primary entries");Check(!items.Any(i=>i.Header.ToString().Contains("键盘")||i.Header.ToString().Contains("撤销")),"keyboard and undo removed from context menu");Check(items.Count(i=>i.HasItems)==5,"five groups use submenus");Capture(menu,"context-menu.png");var group=items.Single(i=>(string)i.Header=="音乐与工具栏");group.IsSubmenuOpen=true;await Task.Delay(100);Check(group.IsSubmenuOpen,"music submenu opens");var pinned=group.Items.OfType<MenuItem>().Single(i=>i.Header.ToString().Contains("工具栏"));pinned.RaiseEvent(new RoutedEventArgs(MenuItem.ClickEvent));Check(pet.Settings.ToolbarPinned,"submenu action works");Call(pet,"ClosePetMenu");Check(Field(pet,"toolbarMenu")==null&&Field(pet,"menuOutsideClick")==null,"menu dismissal cleans outside-click hook");
  var screen=new System.Drawing.Rectangle(0,0,2560,1600);Check(!FullscreenRules.IsFullscreen(R(-11,-11,2571,1539),R(-1,-1,2561,1529),screen,true,0x15C70000),"actual ChatGPT maximum geometry is not fullscreen");Check(!FullscreenRules.IsFullscreen(R(-11,-11,2571,1611),R(-1,-1,2561,1601),screen,true,0x15C70000),"maximized on auto-hide taskbar is not fullscreen");Check(FullscreenRules.IsFullscreen(R(0,0,2560,1600),R(0,0,2560,1600),screen,false,0x90000000),"borderless fullscreen is detected");Check(!FullscreenRules.IsFullscreen(R(0,0,2560,1600),R(0,31,2560,1600),screen,false,0x90C00000),"decorated large window client is not fullscreen");Check(!FullscreenRules.IsFullscreen(R(-11,-11,2571,1539),R(-1,-1,2561,1529),new System.Drawing.Rectangle(2560,0,2560,1440),true,0x15C70000),"small overflow on second monitor does not hide pet");Check(FullscreenRules.IsFullscreen(R(-1920,0,0,1080),R(-1920,0,0,1080),new System.Drawing.Rectangle(-1920,0,1920,1080),false,0x90000000),"negative monitor coordinates support fullscreen");
  overlay=Process.Start(new ProcessStartInfo{FileName=Assembly.GetExecutingAssembly().Location,Arguments="--overlay \""+Store.Root+"\"",UseShellExecute=false,CreateNoWindow=true});await WaitFile(Path.Combine(Store.Root,"overlay-hwnd"),null);await WaitFile(Path.Combine(Store.Root,"overlay-ready"),"maximized");var overlayHandle=new IntPtr(long.Parse(File.ReadAllText(Path.Combine(Store.Root,"overlay-hwnd"))));Native.FocusPetForMenu(overlayHandle);await Task.Delay(80);var petHandle=new WindowInteropHelper(pet).Handle;Check(Native.GetForegroundWindow()==overlayHandle,"fixture is foreground");Check(!Native.IsFullscreen(petHandle)&&Native.FullscreenReason=="normal-maximized","native maximized fixture does not hide pet");Check(!Native.IsAbove(petHandle,overlayHandle),"topmost fixture reproduces coverage");Set(pet,"preview",false);Call(pet,"MaintainWindowStack");Check(Native.IsAbove(petHandle,overlayHandle),"foreground topmost coverage repaired");Check(Native.GetForegroundWindow()==overlayHandle,"repair does not steal keyboard focus");
  File.WriteAllText(Path.Combine(Store.Root,"overlay-mode"),"fullscreen");await WaitFile(Path.Combine(Store.Root,"overlay-ready"),"fullscreen");Native.FocusPetForMenu(overlayHandle);await Task.Delay(80);Check(Native.IsFullscreen(petHandle),"native borderless fixture still triggers fullscreen hiding");Set(pet,"fullscreenHidden",true);Set(pet,"lastHidden","fullscreen");pet.Hide();Call(pet,"MaintainWindowStack");Check(!pet.IsVisible,"stack repair respects fullscreen hidden state");Set(pet,"preview",true);passed=true;
 }catch(Exception e){Store.Atomic("layout-error.json",new{error=e.ToString()});}finally{if(overlay!=null){File.WriteAllText(Path.Combine(Store.Root,"quit-overlay"),"");overlay.WaitForExit(2000);}SetCursorPos(cursor.X,cursor.Y);if(original!=IntPtr.Zero)Native.FocusPetForMenu(original);Store.Atomic("layout-tests.json",new{version="0.6.3",passed=passed,checks=checks});pet.Close();}};app.Run(pet);return passed?0:1;}
}
