using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Interop;using System.Windows.Threading;using KianaPet;
class ToolbarThemeTests {
 [System.Runtime.InteropServices.DllImport("gdi32.dll")]static extern IntPtr CreateRectRgn(int x,int y,int r,int b);
 [System.Runtime.InteropServices.DllImport("user32.dll")]static extern int GetWindowRgn(IntPtr hwnd,IntPtr region);
 [System.Runtime.InteropServices.DllImport("gdi32.dll")]static extern bool PtInRegion(IntPtr region,int x,int y);
 [System.Runtime.InteropServices.DllImport("gdi32.dll")]static extern bool DeleteObject(IntPtr region);
 static List<string> checks=new List<string>();static void Check(bool b,string s){if(!b)throw new Exception(s);checks.Add(s);}static object F(object o,string n){return o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}static void Set(object o,string n,object v){o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).SetValue(o,v);}static object Call(object o,string n,params object[] a){return o.GetType().GetMethod(n,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(o,a);}
 static void Save(BitmapSource b,string name){var e=new PngBitmapEncoder();e.Frames.Add(BitmapFrame.Create(b));using(var s=File.Create(Path.Combine(Store.Root,name+".png")))e.Save(s);}
 static bool MusicColorReady(Border bar,string mode){var solid=bar.Background as SolidColorBrush;if(mode=="solid")return solid!=null&&solid.Color==PetPalette.Background&&!solid.HasAnimatedProperties;var gradient=bar.Background as LinearGradientBrush;return gradient!=null&&gradient.GradientStops.Count==2&&gradient.GradientStops.All(x=>x.Color==PetPalette.Background&&!x.HasAnimatedProperties);}
 static StackPanel Page(SettingsWindow w,string name){return (StackPanel)((ScrollViewer)((TabControl)F(w,"settingsTabs")).Items.Cast<TabItem>().Single(t=>(string)t.Header==name).Content).Content;}
 [STAThread]static int Main(string[] args){Store.Root=args[0];if(args.Length>1)RepositoryUpdate.Bind(args[1],Store.Root);var config=new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false,NoticeSound=false,ToolbarPinned=true};Store.Save(config);var app=new Application{ShutdownMode=ShutdownMode.OnLastWindowClose};var pet=new PetWindow(true);bool passed=false;Window backdrop=null;
 pet.Loaded+=async delegate{try{await Task.Delay(1200);((DispatcherTimer)F(pet,"animation")).Stop();var w=app.Windows.OfType<SettingsWindow>().Single();
 var legacy=Store.Json.Deserialize<Config>("{\"ToolbarFollowMusic\":true}");legacy.Validate();Check(legacy.ToolbarStyle=="legacy"&&legacy.ToolbarFollowMusic,"旧配置保留工具栏音乐跟随及外观");config.ToolbarStyle="invalid";config.ToolbarTint=900;config.ToolbarOpacity=-9;config.ToolbarColor1="bad";config.Validate();Check(config.ToolbarStyle=="legacy"&&config.ToolbarTint==100&&config.ToolbarOpacity==15&&ToolbarTheme.IsHex(config.ToolbarColor1),"材质、色号与参数校验");config.ToolbarStyle="glass";config.ToolbarColorSource="background";config.ToolbarFlow=true;config.ToolbarPreset=11;var copy=PreferenceTransfer.Import(PreferenceTransfer.Export(config,false));Check(copy.ToolbarStyle=="glass"&&copy.ToolbarColorSource=="background"&&copy.ToolbarFlow&&copy.ToolbarPreset==11,"样式设置随通用偏好迁移");
 var page=Page(w,"工具栏样式");var material=SettingsWindow.Descendants<ComboBox>(page).Single(x=>System.Windows.Automation.AutomationProperties.GetName(x)=="工具栏材质");material.SelectedIndex=3;Check(pet.Settings.ToolbarStyle=="tricolor"&&Store.Load().ToolbarStyle=="tricolor","真实材质选择保存并生效");var presets=SettingsWindow.Descendants<Button>(page).Where(x=>ToolbarTheme.PresetNames.Contains(Convert.ToString(x.Content))).ToArray();Check(presets.Length==12,"十二组可点选渐变预设");presets[4].RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(pet.Settings.ToolbarPreset==4&&pet.Settings.ToolbarColorSource=="preset","预设按钮保存颜色来源");
 var music=Page(w,"音乐");Check(music.Children[0] is StackPanel&&SettingsWindow.Descendants<Button>((DependencyObject)music.Children[0]).Any(x=>(string)x.Content=="打开 / 连接网易云音乐"),"音乐连接入口位于首组");var link=Page(w,"ChatGPT 联动");Check(link.Children[1] is WrapPanel&&SettingsWindow.Descendants<Button>((DependencyObject)link.Children[1]).Any(x=>(string)x.Content=="打开 ChatGPT"),"ChatGPT 启动与修复入口位于首组");
 var entry=SettingsWindow.Descendants<Expander>(music).Single(x=>(string)x.Header=="进入听歌状态与切歌衔接");Check(!entry.IsExpanded,"音乐细节默认折叠");w.NavigateCategory("音乐","开始听歌前等待");Check(entry.IsExpanded&&entry.IsVisible,"搜索自动展开隐藏设置");w.NavigateCategory("音乐","");Check(!entry.IsExpanded,"清除搜索恢复原折叠状态");entry.IsExpanded=true;w.NavigateCategory("音乐","开始听歌前等待");w.NavigateCategory("音乐","");Check(entry.IsExpanded,"搜索保留用户手动展开状态");entry.IsExpanded=false;w.Capture(Path.Combine(Store.Root,"music-layout.png"));w.NavigateCategory("ChatGPT 联动","");w.Capture(Path.Combine(Store.Root,"chatgpt-layout.png"));w.NavigateCategory("工具栏样式","");w.Capture(Path.Combine(Store.Root,"toolbar-settings.png"));
 var scenes=Page(w,"场景与维护");Check(EditHistory.Category("ToolbarFollowMusic")=="工具栏样式"&&EditHistory.Category("TaskNoticesEnabled")=="通知中心","最近调整导航跟随设置归类");Check(SettingsWindow.Descendants<Button>(scenes).Single(x=>(string)x.Content=="拉取 GitHub 更新并应用").IsEnabled,"绑定仓库后更新按钮可用");Check(((TextBlock)scenes.Children[0]).Text=="仓库更新"&&scenes.Children[1] is WrapPanel,"拉取更新与本机构建位于维护页首屏");Check(SettingsWindow.Descendants<Expander>(scenes).Any(x=>(string)x.Header=="双设备偏好与备份"),"偏好迁移归入维护分组");Check(!SettingsWindow.Descendants<CheckBox>(scenes).Any(x=>Convert.ToString(x.Content).Contains("普通任务完成静默")),"维护页移除重复通知开关");
 foreach(string name in new[]{"场景与维护","通知中心","启动与联动","外观与互动","活动与作息","体验","免打扰","快捷键","无障碍","使用说明"}){w.NavigateCategory(name,"");w.Capture(Path.Combine(Store.Root,name+".png"));}
 var quiet=Page(w,"免打扰");w.NavigateCategory("免打扰","保存应用列表");Check(SettingsWindow.Descendants<Button>(quiet).Single(x=>(string)x.Content=="保存应用列表").IsVisible,"搜索穿透免打扰规则折叠");w.NavigateCategory("场景与维护","导入并预览差异");Check(SettingsWindow.Descendants<Button>(scenes).Single(x=>(string)x.Content=="导入并预览差异…").IsVisible,"迁移入口搜索自动展开");w.NavigateCategory("体验","");var experience=Page(w,"体验");var profile=SettingsWindow.Descendants<ComboBox>(experience).First();profile.SelectedIndex=3;Check(SettingsWindow.Descendants<Expander>(experience).Single(x=>(string)x.Header=="自定义速度、距离与休息").IsExpanded,"选择自定义走动自动展开参数");
 w.Width=760;w.Height=520;w.NavigateCategory("场景与维护","");w.Capture(Path.Combine(Store.Root,"maintenance-small.png"));Check(SettingsWindow.Descendants<Button>(scenes).Single(x=>(string)x.Content=="拉取 GitHub 更新并应用").IsVisible,"小尺寸窗口更新入口仍可见");w.Width=920;w.Height=790;
 var sheet=new DrawingVisual();using(var dc=sheet.RenderOpen()){dc.DrawRectangle(Brushes.White,null,new Rect(0,0,680,ToolbarTheme.Styles.Length*75));for(int i=0;i<ToolbarTheme.Styles.Length;i++){var c=new Config{ToolbarStyle=ToolbarTheme.Styles[i],ToolbarPreset=i%12};var colors=ToolbarTheme.Tinted(c,ToolbarTheme.ColorsFor(c,null,null),false);var brush=ToolbarTheme.MakeBrush(c,colors,0);dc.DrawText(new FormattedText(ToolbarTheme.StyleNames[i],System.Globalization.CultureInfo.GetCultureInfo("zh-CN"),FlowDirection.LeftToRight,new Typeface("Microsoft YaHei UI"),16,Brushes.Black),new Point(18,i*75+20));dc.DrawRoundedRectangle(brush,new Pen(Brushes.LightGray,.7),new Rect(210,i*75+12,280,44),16,16);Check(brush.Opacity==.85,"保留独立底板透明度："+c.ToolbarStyle);}}
 var bitmap=new RenderTargetBitmap(1360,ToolbarTheme.Styles.Length*150,192,192,PixelFormats.Pbgra32);bitmap.Render(sheet);Save(bitmap,"toolbar-materials");
 var cflow=new Config{ToolbarStyle="tricolor",ToolbarFlow=true};var palette=ToolbarTheme.Tinted(cflow,ToolbarTheme.ColorsFor(cflow,null,null),false);var a=(LinearGradientBrush)ToolbarTheme.MakeBrush(cflow,palette,0);var b=(LinearGradientBrush)ToolbarTheme.MakeBrush(cflow,palette,4);Check(a.StartPoint!=b.StartPoint,"动态渐变随时间变化");cflow.ReduceMotion=true;Check(((LinearGradientBrush)ToolbarTheme.MakeBrush(cflow,palette,0)).StartPoint==((LinearGradientBrush)ToolbarTheme.MakeBrush(cflow,palette,4)).StartPoint,"减少动态效果停止流动");
 w.Hide();backdrop=new Window{Width=600,Height=500,Left=100,Top=100,WindowStyle=WindowStyle.None,ShowInTaskbar=false,Background=Brushes.White};var canvas=new Canvas();for(int i=0;i<20;i++){var stripe=new Border{Width=30,Height=500,Background=i%2==0?Brushes.LightSkyBlue:Brushes.PaleVioletRed};Canvas.SetLeft(stripe,i*30);canvas.Children.Add(stripe);}backdrop.Content=canvas;backdrop.Show();pet.Left=240;pet.Top=150;pet.Settings.ToolbarStyle="glass";pet.Settings.ToolbarOpacity=20;pet.Settings.ToolbarGlassFog=5;pet.Settings.ToolbarPinned=true;pet.Settings.ToolbarColorSource="preset";pet.ApplyAppearanceForSettings();IntPtr foreground=Native.GetForegroundWindow();Call(pet,"SetToolbarVisible",true,false);await Task.Delay(450);Call(pet,"UpdateMusic");await Task.Delay(300);
 Check(Native.GetForegroundWindow()==foreground,"玻璃层显示不抢焦点");var glass=(ToolbarGlass)F(pet,"toolbarGlass");Check(glass.Handle==IntPtr.Zero||Native.IsAbove(new WindowInteropHelper(pet).Handle,glass.Handle),"系统玻璃层位于按钮与宠物下方");IntPtr region=CreateRectRgn(0,0,1,1);int result=GetWindowRgn(glass.Handle,region);Store.Atomic("glass-status.json",new{available=glass.Available,handle=glass.Handle.ToInt64(),region=result,corner=PtInRegion(region,0,0),hint=pet.ToolbarMaterialStatus});DeleteObject(region);
 Native.Rect bounds;Native.GetWindowRect(new WindowInteropHelper(backdrop).Handle,out bounds);using(var image=new System.Drawing.Bitmap(bounds.Width,bounds.Height)){using(var g=System.Drawing.Graphics.FromImage(image))g.CopyFromScreen(bounds.Left,bounds.Top,0,0,image.Size);image.Save(Path.Combine(Store.Root,"native-glass.png"));}

 var menu=new Window{Width=110,Height=80,Left=250,Top=350,Topmost=true,ShowInTaskbar=false,WindowStyle=WindowStyle.None,Background=Brushes.Bisque};menu.Show();IntPtr mh=new WindowInteropHelper(menu).Handle;Set(pet,"fallbackMenu",mh);Call(pet,"UpdateMenuPriority",true);Call(pet,"UpdateMusic");Check(glass.Handle==IntPtr.Zero||Native.IsAbove(mh,glass.Handle)&&Native.IsAbove(mh,new WindowInteropHelper(pet).Handle),"外部菜单出现时玻璃与宠物均让出顶层");Set(pet,"fallbackMenu",IntPtr.Zero);menu.Close();Call(pet,"UpdateMenuPriority",false);Call(pet,"UpdateMusic");Check(glass.Handle==IntPtr.Zero||Native.IsTopmost(glass.Handle)&&Native.IsAbove(new WindowInteropHelper(pet).Handle,glass.Handle),"菜单关闭恢复玻璃顶层且保持按钮在上");
 pet.Hide();Check(glass.Handle==IntPtr.Zero||!Native.IsPresented(glass.Handle),"隐藏宠物同步隐藏玻璃，无悬空底板");pet.Show();
 pet.Settings.ToolbarStyle="legacy";Call(pet,"UpdateMusic");Check(glass.Handle==IntPtr.Zero||!Native.IsPresented(glass.Handle),"关闭玻璃样式立即收起独立底板");pet.Settings.ToolbarStyle="tricolor";Call(pet,"UpdateMusic");Check(((Border)F(pet,"hoverBar")).Background is LinearGradientBrush,"实际工具栏使用选择的渐变");var bar=(Border)F(pet,"hoverBar");pet.Settings.ToolbarFollowMusic=true;pet.Settings.MusicEnabled=true;pet.Settings.MusicHoverOnly=false;pet.Settings.MusicTintMode="cover-gradient";pet.Music.Current=new MusicState{Connected=true,Playing=true,Title="联动测试",At=DateTime.UtcNow};Call(pet,"UpdateMusic");Check(pet.ToolbarFollowingMusic&&((LinearGradientBrush)bar.Background).GradientStops.Count==2&&bar.Background.Opacity==1,"音乐栏显示时覆盖独立三色样式，使用音乐栏渐变与透明度");
 var card=(MusicWindow)F(pet,"musicWindow");card.HideSoft(false);Call(pet,"UpdateToolbarTheme",0d);Check(!pet.ToolbarFollowingMusic&&((LinearGradientBrush)bar.Background).GradientStops.Count==3,"音乐栏开始收起时平滑恢复独立三色样式");Call(pet,"UpdateMusic");Check(pet.ToolbarFollowingMusic&&((LinearGradientBrush)bar.Background).GradientStops.Count==2,"音乐栏重新出现正确刷新缓存");
 pet.Settings.ToolbarFollowMusic=false;Call(pet,"UpdateMusic");Check(!pet.ToolbarFollowingMusic&&((LinearGradientBrush)bar.Background).GradientStops.Count==3,"关闭跟随后音乐栏可见仍保留独立材质");pet.Settings.ToolbarFollowMusic=true;pet.Settings.MusicPausedCard=false;pet.Music.Current.Playing=false;Call(pet,"UpdateMusic");Check(!pet.ToolbarFollowingMusic&&!card.PresentationActive,"暂停且不保留卡片时恢复独立样式");pet.Settings.MusicPausedCard=true;Call(pet,"UpdateMusic");Check(pet.ToolbarFollowingMusic,"暂停保留卡片时仍跟随");pet.Music.Current.At=DateTime.UtcNow.AddSeconds(-8);Call(pet,"UpdateMusic");Check(!pet.ToolbarFollowingMusic,"连接过期立即回独立样式");
 pet.Music.Current.At=DateTime.UtcNow;pet.Settings.ToolbarStyle="glass";Call(pet,"UpdateMusic");Check(pet.ToolbarFollowingMusic&&(glass.Handle==IntPtr.Zero||!Native.IsPresented(glass.Handle)),"跟随音乐时收起独立玻璃层");pet.Settings.MusicEnabled=false;Call(pet,"UpdateMusic");Check(!pet.ToolbarFollowingMusic&&pet.Settings.ToolbarStyle=="glass"&&(glass.Handle==IntPtr.Zero||Native.IsPresented(glass.Handle)),"音乐栏关闭后恢复原玻璃材质且不改偏好");
 pet.Settings.ToolbarStyle="legacy";Call(pet,"UpdateMusic");Check(bar.Background is SolidColorBrush,"简洁独立样式兼容音乐栏收起");// Reproduce hover-only simultaneous reveal, including an unfinished hide/reveal.
 pet.Settings.ToolbarStyle="tricolor";pet.Settings.ToolbarColorSource="manual";pet.Settings.ToolbarColor1="#FF00FF";pet.Settings.ToolbarColor2="#FF0000";pet.Settings.ToolbarColor3="#FFFF00";pet.Settings.ToolbarTint=100;pet.Settings.ToolbarFollowMusic=true;pet.Settings.ToolbarPinned=false;pet.Settings.MusicHoverOnly=true;
 foreach(string mode in new[]{"solid","cover-gradient","background-gradient"}){
  pet.Settings.MusicEnabled=false;Call(pet,"SetToolbarVisible",false,true);Set(pet,"hover",false);Call(pet,"UpdateMusic");pet.Settings.MusicEnabled=true;pet.Settings.MusicTintMode=mode;pet.Music.Current=new MusicState{Connected=true,Playing=true,At=DateTime.UtcNow};Set(pet,"hover",true);
  bool correctAtReveal=false;DependencyPropertyChangedEventHandler onReveal=delegate{if(bar.IsVisible)correctAtReveal=MusicColorReady(bar,mode);};bar.IsVisibleChanged+=onReveal;Call(pet,"SetToolbarVisible",true,false);bar.IsVisibleChanged-=onReveal;
  Check(correctAtReveal&&pet.ToolbarFollowingMusic,"悬停显示第一帧已采用音乐色且没有跨色动画："+mode);Call(pet,"UpdateMusic");await Task.Delay(80);Check(MusicColorReady(bar,mode),"淡入期间保持音乐颜色："+mode);
  Call(pet,"SetToolbarVisible",false,false);await Task.Delay(20);Call(pet,"SetToolbarVisible",true,false);Check(MusicColorReady(bar,mode),"快速移出移入不闪独立配色："+mode);
 }
 // A persistent music card must also be resolved before toolbar reveal.
 pet.Settings.MusicHoverOnly=false;Set(pet,"hover",false);Call(pet,"SetToolbarVisible",false,true);Call(pet,"UpdateMusic");Call(pet,"SetToolbarVisible",true,false);Check(MusicColorReady(bar,pet.Settings.MusicTintMode),"常驻音乐栏时工具栏首帧同色");
 pet.Settings.ToolbarFollowMusic=false;Call(pet,"SetToolbarVisible",false,true);Call(pet,"SetToolbarVisible",true,false);Check(((GradientBrush)bar.Background).GradientStops.Count==3&&!((GradientBrush)bar.Background).GradientStops.Any(x=>x.HasAnimatedProperties),"关闭跟随后首帧使用独立配色");passed=true;
 }catch(Exception e){Store.Atomic("error.json",new{error=e.ToString()});}finally{Store.Atomic("toolbar-theme-tests.json",new{passed,checks});if(backdrop!=null)backdrop.Close();foreach(var win in app.Windows.Cast<Window>().Where(x=>x!=pet).ToArray())win.Close();pet.Close();}};app.Run(pet);return passed?0:1;}
}
