using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using KianaPet;
class PreviewGalleryTests {
 static readonly List<string> checks=new List<string>();static void Check(bool value,string message){if(!value)throw new Exception(message);checks.Add(message);}
 static IEnumerable<T> Find<T>(DependencyObject root) where T:DependencyObject {if(root is T)yield return (T)root;for(int i=0;i<VisualTreeHelper.GetChildrenCount(root);i++)foreach(var item in Find<T>(VisualTreeHelper.GetChild(root,i)))yield return item;}
 [STAThread]static int Main(string[] args){Store.Root=args[0];Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false});var app=new Application{ShutdownMode=ShutdownMode.OnLastWindowClose};var pet=new PetWindow(true);bool passed=false;
  pet.Loaded+=async delegate{try{await Task.Delay(800);var settings=app.Windows.OfType<SettingsWindow>().Single();settings.NavigateCategory("效果预览","");await Task.Delay(180);var gallery=Find<AnimationGallery>(settings).Single();Check(AnimationGallery.Catalog.Length==20,"20类现有动作可查阅");string before=Store.Json.Serialize(pet.Settings);foreach(var info in pet.Pets){var source=new AnimationPreviewSource(info.Id);foreach(var action in AnimationGallery.Catalog){if(action.Category=="音乐"&&!MusicSprites.Supported(info.Id)){Check(source.Frame(action,0)==null,"非Q版明确无音乐专用图集");continue;}var frame=source.Frame(action,0);Check(frame!=null&&frame.Source!=null,info.Id+" / "+action.Id);Check(source.Frame(action,action.Duration-.1)!=null,"循环末端可读");}}
   gallery.SelectAction("music-quiet");var initial=gallery.CurrentFrame;gallery.Step();Check(gallery.CurrentFrame!=null&&!ReferenceEquals(initial,gallery.CurrentFrame),"下一帧切换完整人物图片");Check(!gallery.IsPlaying,"逐帧查看自动暂停");gallery.SelectAction("stretch");Check(gallery.CurrentFrame!=null,"日常过渡可直接预览");Check(Store.Json.Serialize(pet.Settings)==before,"衣装和动作预览不写真实偏好");settings.Capture(Path.Combine(Store.Root,"animation-gallery.png"));settings.NavigateCategory("音乐","长歌词滚动");await Task.Delay(100);Check(!gallery.IsPlaying,"离开预览页停止计时器");settings.Capture(Path.Combine(Store.Root,"lyric-settings.png"));gallery.Dispose();Check(!gallery.IsPlaying,"关闭释放预览播放");passed=true;
  }catch(Exception e){Store.Atomic("error.json",new{error=e.ToString()});}finally{Store.Atomic("preview-gallery-tests.json",new{passed,checks});foreach(var window in app.Windows.Cast<Window>().Where(w=>w!=pet).ToArray())window.Close();pet.Close();}};app.Run(pet);return passed?0:1;
 }
}
