using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using KianaPet;
class PreviewGalleryTests {
 static readonly List<string> checks=new List<string>();static void Check(bool value,string message){if(!value)throw new Exception(message);checks.Add(message);}
 static object Field(object o,string n){return o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}static void Set(object o,string n,object v){o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).SetValue(o,v);}static void Draw(PetWindow p,double ms){p.GetType().GetMethod("DrawAnimation",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(p,new object[]{ms});}
 static void SpeedTests(PetWindow pet,AnimationGallery gallery){
  var c=Store.Json.Deserialize<Config>("{\"Schema\":1}");c.Validate();Check(AnimationTiming.Speed(c,"music-quiet")==.25&&AnimationTiming.Speed(c,"waving")==1,"旧配置缺少倍速时使用新默认值");
  Check(AnimationTiming.Actions.OrderBy(s=>s).SequenceEqual(AnimationGallery.Catalog.Select(a=>a.Id).OrderBy(s=>s)),"全部20类动画有独立速度项");
  c.AnimationSpeeds=null;c.Validate();c.AnimationSpeeds["idle"]=0;c.AnimationSpeeds["waving"]=double.NaN;c.AnimationSpeeds["invalid"]=2;c.Validate();Check(c.AnimationSpeeds.Count==0,"空配置、非有限值、越界和未知动作安全回退");
  c.AnimationSpeeds["idle"]=1.75;c.AnimationSpeeds["music-sit"]=.5;c.AnimationSpeeds["music-rise"]=2;c.AnimationSpeeds["music-gentle"]=1.5;
  Check(AnimationTiming.MusicElapsed(c,"music-quiet",1440+4800,false)==1920,"坐下0.5倍与坐姿0.25倍独立计时");Check(AnimationTiming.MusicElapsed(c,"music-gentle",360+1000,true)==2220,"起身2倍后进入1.5倍应援");
  var transferred=PreferenceTransfer.Import(PreferenceTransfer.Export(c,false));Check(AnimationTiming.Speed(transferred,"idle")==1.75&&AnimationTiming.Speed(transferred,"music-quiet")==.25,"速度随通用偏好导出导入");
  gallery.SelectAction("music-quiet");Check(gallery.CurrentSpeed==.25,"预览初始坐姿0.25倍");
  var input=Find<ComboBox>(gallery).Single(b=>b.IsEditable);input.Text="0.40";Find<Button>(gallery).Single(b=>Convert.ToString(b.Content)=="应用到桌宠").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(gallery.CurrentSpeed==.4&&AnimationTiming.Speed(Store.Load(),"music-quiet")==.4,"真实编辑框与按钮保存自定义倍速");
  input.Text="0";Find<Button>(gallery).Single(b=>Convert.ToString(b.Content)=="应用到桌宠").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(gallery.CurrentSpeed==.4,"非法输入不会覆盖已保存设置");
  gallery.SelectAction("waving");gallery.SetSelectedSpeed(2);Set(pet,"state","waving");Set(pet,"lastFrame",-1);Draw(pet,350);Check((int)Field(pet,"lastFrame")==Rules.Row("waving")*8+Rules.Frame("waving",700),"真实招手动画按2倍选择帧");
  gallery.SelectAction("groom");gallery.SetSelectedSpeed(.25);pet.React("groom","",2.1);double left=(double)Field(pet,"interactionUntil")-((System.Diagnostics.Stopwatch)Field(pet,"clock")).Elapsed.TotalSeconds;Check(left>8.2&&left<=8.4,"一次性慢动作时长同步延长，不被原时长截断");
  Set(pet,"interaction",null);gallery.ResetRates();Check(AnimationTiming.Speed(Store.Load(),"waving")==1&&AnimationTiming.Speed(Store.Load(),"music-quiet")==.25,"全部恢复默认且无互动时安全");
  Set(pet,"state","music-quiet");Set(pet,"drawnMusicState","");Set(pet,"lastFrame",-1);Draw(pet,720+4800);Check((int)Field(pet,"lastFrame")==1411,"实际坐姿在4.8秒到半循环，入座仍为720毫秒");
  var quietChoice=AnimationGallery.Catalog.Single(v=>v.Id=="music-quiet");Check(quietChoice.Duration/AnimationTiming.Speed(pet.Settings,quietChoice.Id)==9600,"预览与真实坐姿周期均为9.6秒");
  Set(pet,"state","idle");gallery.SelectAction("music-quiet");var originalPose=gallery.CurrentFrame;pet.Settings.MusicSeatedStyle="sway";gallery.SelectAction("music-quiet");Check(!ReferenceEquals(originalPose,gallery.CurrentFrame)&&((TextBlock)Field(gallery,"detail")).Text.Contains("头部轻晃"),"already-open gallery refreshes when seated style changes");pet.Settings.MusicSeatedStyle="classic";gallery.SelectAction("music-quiet");Check(((TextBlock)Field(gallery,"detail")).Text.Contains("原版坐姿"),"gallery can switch back without reopening");
 }
 static IEnumerable<T> Find<T>(DependencyObject root) where T:DependencyObject {if(root is T)yield return (T)root;for(int i=0;i<VisualTreeHelper.GetChildrenCount(root);i++)foreach(var item in Find<T>(VisualTreeHelper.GetChild(root,i)))yield return item;}
 [STAThread]static int Main(string[] args){Store.Root=args[0];Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false});var app=new Application{ShutdownMode=ShutdownMode.OnLastWindowClose};var pet=new PetWindow(true);bool passed=false;
  pet.Loaded+=async delegate{try{await Task.Delay(800);var settings=app.Windows.OfType<SettingsWindow>().Single();settings.NavigateCategory("效果预览","");await Task.Delay(180);var gallery=Find<AnimationGallery>(settings).Single();Check(AnimationGallery.Catalog.Length==20,"20类现有动作可查阅");string before=Store.Json.Serialize(pet.Settings);foreach(var info in pet.Pets){var source=new AnimationPreviewSource(info.Id);foreach(var action in AnimationGallery.Catalog){if(action.Category=="音乐"&&!MusicSprites.Supported(info.Id)){Check(source.Frame(action,0)==null,"非Q版明确无音乐专用图集");continue;}var frame=source.Frame(action,0);Check(frame!=null&&frame.Source!=null,info.Id+" / "+action.Id);Check(source.Frame(action,action.Duration-.1)!=null,"循环末端可读");}}
   gallery.SelectAction("music-quiet");var initial=gallery.CurrentFrame;gallery.Step();Check(gallery.CurrentFrame!=null&&!ReferenceEquals(initial,gallery.CurrentFrame),"下一帧切换完整人物图片");Check(!gallery.IsPlaying,"逐帧查看自动暂停");gallery.SelectAction("stretch");Check(gallery.CurrentFrame!=null,"日常过渡可直接预览");Check(Store.Json.Serialize(pet.Settings)==before,"衣装和动作预览不写真实偏好");SpeedTests(pet,gallery);settings.Capture(Path.Combine(Store.Root,"animation-gallery.png"));settings.NavigateCategory("音乐","长歌词滚动");await Task.Delay(100);Check(!gallery.IsPlaying,"离开预览页停止计时器");settings.Capture(Path.Combine(Store.Root,"lyric-settings.png"));gallery.Dispose();Check(!gallery.IsPlaying,"关闭释放预览播放");passed=true;
  }catch(Exception e){Store.Atomic("error.json",new{error=e.ToString()});}finally{Store.Atomic("preview-gallery-tests.json",new{passed,checks});foreach(var window in app.Windows.Cast<Window>().Where(w=>w!=pet).ToArray())window.Close();pet.Close();}};app.Run(pet);return passed?0:1;
 }
}
