using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Net.Http;using System.Threading;using System.Threading.Tasks;using System.Web.Script.Serialization;
namespace KianaPet {
 public sealed class ChorusCacheEntry {public string Id;public DateTime At;public ChorusRange[] Ranges=new ChorusRange[0];}
 public sealed class ChorusLibrary:IDisposable {
  readonly HttpClient http=new HttpClient(new HttpClientHandler{UseProxy=false,AllowAutoRedirect=false}){Timeout=TimeSpan.FromSeconds(7)};readonly CancellationTokenSource cancel=new CancellationTokenSource();readonly Dictionary<string,ChorusCacheEntry> cache=new Dictionary<string,ChorusCacheEntry>();readonly Dictionary<string,DateTime> retry=new Dictionary<string,DateTime>();bool busy,disposed;string requested="";public string Status="等待播放歌曲";
  public ChorusLibrary(){try{string path=Path.Combine(Store.Root,"chorus-cache.json");if(new FileInfo(path).Length>512000)return;foreach(var item in Store.Json.Deserialize<ChorusCacheEntry[]>(File.ReadAllText(path)).Where(e=>e!=null&&MusicReactions.SongId(e.Id)&&e.At<=DateTime.UtcNow.AddMinutes(5)).Take(300)){item.Ranges=Clean(item.Ranges);cache[item.Id]=item;}}catch{}}
  static ChorusRange[] Clean(ChorusRange[] ranges){return (ranges??new ChorusRange[0]).Where(r=>r!=null&&MusicReactions.ValidRange(r.Start,r.End,0)).OrderBy(r=>r.Start).Take(12).ToArray();}
  public static ChorusRange[] Parse(string text,string song){if(text==null||text.Length>128000)throw new InvalidDataException("副歌响应过大");var root=new JavaScriptSerializer{MaxJsonLength=128000}.DeserializeObject(text);if(Convert.ToInt32(MusicBridge.Get(root,"code"))!=200)throw new InvalidDataException("副歌接口暂不可用");var rows=MusicBridge.Get(root,"chorus") as object[]??MusicBridge.Get(root,"data") as object[];if(rows==null)throw new InvalidDataException("副歌响应格式改变");var list=new List<ChorusRange>();foreach(var row in rows){if(MusicBridge.Str(row,"id")!=song)continue;try{if(MusicBridge.Get(row,"startTime")==null||MusicBridge.Get(row,"endTime")==null)continue;list.Add(new ChorusRange{Start=Convert.ToDouble(MusicBridge.Get(row,"startTime"))/1000,End=Convert.ToDouble(MusicBridge.Get(row,"endTime"))/1000});}catch(FormatException){}catch(InvalidCastException){}}return Clean(list.ToArray());}
  public ChorusRange[] For(string song){ChorusCacheEntry entry;return cache.TryGetValue(song??"",out entry)?entry.Ranges:new ChorusRange[0];}
  public async Task Update(MusicState state,bool enabled){requested=state.Id??"";if(!enabled){Status="副歌联网查询已关闭";return;}if(!state.Connected||!MusicReactions.SongId(state.Id)){Status="没有可查询的网易云歌曲 ID";return;}ChorusCacheEntry existing;if(cache.TryGetValue(state.Id,out existing)&&DateTime.UtcNow-existing.At<TimeSpan.FromDays(existing.Ranges.Length>0?30:1)){Status=existing.Ranges.Length>0?"已取得副歌时间":"此曲暂无副歌数据，保持耳机听歌";return;}DateTime due;if(retry.TryGetValue(state.Id,out due)&&DateTime.UtcNow<due){Status=existing!=null&&existing.Ranges.Length>0?"查询暂不可用，使用已缓存的副歌时间":"查询暂不可用，保持耳机听歌";return;}if(busy)return;busy=true;string song=state.Id;Status="正在查询副歌时间…";
   try{string url="https://music.163.com/api/song/chorus?ids=%5B"+song+"%5D";string text;using(var response=await http.GetAsync(url,HttpCompletionOption.ResponseHeadersRead,cancel.Token)){response.EnsureSuccessStatusCode();if(response.Content.Headers.ContentLength>128000)throw new InvalidDataException();using(var stream=await response.Content.ReadAsStreamAsync())using(var memory=new MemoryStream()){byte[] buffer=new byte[4096];int n;while((n=await stream.ReadAsync(buffer,0,buffer.Length,cancel.Token))>0){memory.Write(buffer,0,n);if(memory.Length>128000)throw new InvalidDataException();}text=System.Text.Encoding.UTF8.GetString(memory.ToArray());}}
    var ranges=Parse(text,song);if(disposed)return;cache[song]=new ChorusCacheEntry{Id=song,At=DateTime.UtcNow,Ranges=ranges};while(cache.Count>300)cache.Remove(cache.Values.OrderBy(e=>e.At).First().Id);Store.Atomic("chorus-cache.json",cache.Values.ToArray());if(requested==song)Status=ranges.Length>0?"已取得副歌时间":"此曲暂无副歌数据，保持耳机听歌";
   }catch(Exception){if(!disposed){retry[song]=DateTime.UtcNow.AddMinutes(5);if(retry.Count>300)retry.Remove(retry.Keys.First());if(requested==song)Status="副歌查询暂不可用，保留耳机听歌";}}finally{busy=false;}
  }
  public void Dispose(){disposed=true;cancel.Cancel();http.Dispose();}
 }
}
