using System;using System.IO;using System.Linq;using System.Text.RegularExpressions;using System.Diagnostics;using System.Windows;using System.Windows.Controls;using Microsoft.Win32;
namespace KianaPet {
 public static class Diagnostics {
  public static string Redact(string text,bool paths){text=Regex.Replace(text??"",@"(?i)(bearer\s+)[^\s]+","$1[hidden]");text=Regex.Replace(text,@"(?i)(token|secret|authorization|password)\s*[:=]\s*[^\s,;]+","$1=[hidden]");text=Regex.Replace(text,@"https?://[^\s]+","[url]");if(paths){string profile=Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);if(profile.Length>0)text=Regex.Replace(text,Regex.Escape(profile),"[用户目录]",RegexOptions.IgnoreCase);text=Regex.Replace(text,@"[A-Za-z]:\\[^\r\n]*","[本地路径]");}return text;}
  public static string Report(PetWindow pet,bool paths,bool logs){var c=pet.Settings;var p=Process.GetCurrentProcess();string recent="未包含运行日志";if(logs){string file=Path.Combine(Store.Root,"desktop.log");if(File.Exists(file)){var info=new FileInfo(file);if(info.Length<=600000)recent=string.Join(Environment.NewLine,File.ReadAllLines(file).Reverse().Take(30).Reverse().Select(s=>s.Substring(0,Math.Min(s.Length,600))));}}recent=Redact(recent,paths);return Store.Json.Serialize(new{version=Maintenance.Version,at=DateTime.Now.ToString("o"),windows=Environment.OSVersion.Version.ToString(),is64Bit=Environment.Is64BitProcess,memoryMiB=Math.Round(p.WorkingSet64/1048576d,1),fullscreenReason=Native.FullscreenReason,stateRoot=paths?"[本地设置目录]":Store.Root,chatgpt=new{pet.Link.Current.Code,pet.Link.Current.Hint,pet.Link.Current.Connected,pet.Link.Current.Stale,pet.Link.Current.NotificationSource,pet.Link.Current.MiniStatus,pet.Link.Current.MainStatus,pet.Link.Current.NotificationCount,pet.Link.Current.LastSuccessAt,pet.Link.Current.LastChatAt,pet.Link.Current.LastVoiceAt,pet.Link.Current.LastNotificationsAt},music=new{pet.Music.Current.Connected,pet.Music.Current.Label},preferences=new{c.Skin,c.Size,c.Theme,c.ToolbarPercent,c.Walking,c.LockPetPosition,c.MusicEnabled,c.MusicPosition,c.ResourceSaving,c.RememberLayouts,c.RecoverHotkeyEnabled},screens=System.Windows.Forms.Screen.AllScreens.Select(s=>new{bounds=s.Bounds.ToString(),workingArea=s.WorkingArea.ToString(),primary=s.Primary}).ToArray(),recentLog=recent});}
 }
 public sealed partial class PetWindow {
  public void ShowDiagnostics(){var window=new Window{Title="诊断预览 · 不自动发送",Width=720,Height=650,Owner=settingsWindow,WindowStartupLocation=WindowStartupLocation.CenterOwner,Background=PetPalette.Brush(PetPalette.Background),Foreground=PetPalette.Brush(PetPalette.Ink)};var dock=new DockPanel{Margin=new Thickness(18)};var options=new StackPanel();var hide=new CheckBox{Foreground=PetPalette.Brush(PetPalette.Ink),Content="隐藏个人路径",IsChecked=true,Margin=new Thickness(0,4,0,8)};var logs=new CheckBox{Foreground=PetPalette.Brush(PetPalette.Ink),Content="包含最近 30 行运行日志（导出前请检查预览）",IsChecked=false,Margin=new Thickness(0,4,0,8)};options.Children.Add(hide);options.Children.Add(logs);DockPanel.SetDock(options,Dock.Top);dock.Children.Add(options);var actions=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};var save=new Button{Content="导出这份诊断",Padding=new Thickness(16,8,16,8),Margin=new Thickness(8)};actions.Children.Add(save);DockPanel.SetDock(actions,Dock.Bottom);dock.Children.Add(actions);var text=new TextBox{IsReadOnly=true,AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Background=PetPalette.Brush(PetPalette.Background),Foreground=PetPalette.Brush(PetPalette.Ink),Padding=new Thickness(10)};dock.Children.Add(text);Action refresh=delegate{text.Text=Diagnostics.Report(this,hide.IsChecked==true,logs.IsChecked==true);};hide.Click+=delegate{refresh();};logs.Click+=delegate{refresh();};save.Click+=delegate{var dialog=new SaveFileDialog{Filter="诊断报告 (*.json)|*.json",FileName="琪亚娜桌宠诊断.json"};if(dialog.ShowDialog(window)==true)try{File.WriteAllText(dialog.FileName,text.Text,new System.Text.UTF8Encoding(false));}catch(Exception e){MessageBox.Show(window,e.Message,"导出失败");}};window.Content=dock;refresh();window.ShowDialog();}
 }
}


