using System;using System.Diagnostics;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Animation;using System.Windows.Threading;using System.Media;
namespace KianaPet {
 public sealed class PreviewPlayback {public bool Bubble,Sound;public int Seconds;public string Reason;}
 public static class EffectPreviewRules {
  public static PreviewPlayback Completion(Config c,bool quiet){string reason=quiet?"当前处于免打扰或隐藏状态":c.NoticeQuiet?"已开启静默提醒":c.NoticeSilentSuccess?"已开启普通完成静默":"";return new PreviewPlayback{Bubble=reason==""&&c.Bubbles,Sound=reason==""&&c.NoticeSound,Seconds=c.CompletionNoticeSeconds,Reason=reason==""&&!c.Bubbles?"提示气泡已关闭":reason};}
 }
 public sealed partial class PetWindow {
  public ImageSource PreviewSprite{get{return sprite.Source;}}
  public bool NoticePlaybackBlocked{get{return quietActive||sessionLocked||manualHidden||fullscreenHidden||menuLayerYielding;}}
 }
 public sealed partial class SettingsWindow {
  readonly DispatcherTimer effectTimer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(100)};readonly Stopwatch effectClock=new Stopwatch();
  Border effectBadge,effectBubble,effectSeparator;Image effectSprite;StackPanel effectBell;TextBlock effectStatus,effectDetail,effectCountdown;int effectSeconds;public string PreviewState{get;private set;}
  void BuildEffectPreviewPage(TabControl tabs){var page=Page(tabs,"效果预览");TitleText(page,"看看通知会怎样显示");Note(page,"使用模拟状态，可直接检查角标、气泡和停留时间。预览只在本页显示，不写入真实任务列表，也不会打开 ChatGPT、改变已读状态或启动其他软件。");
   var choices=new WrapPanel();foreach(var pair in new[]{new[]{"running","蓝色 · 正在处理"},new[]{"review","绿色 · 完成未读"},new[]{"stale","灰色 · 暂时断线"},new[]{"waiting","橙色 · 等待回应"},new[]{"idle","空闲 · 隐藏铃铛"}}){var state=pair[0];choices.Children.Add(Button(pair[1],delegate{PreviewEffect(state);},false));}page.Children.Add(choices);
   var demo=new StackPanel{HorizontalAlignment=HorizontalAlignment.Center,Width=250};effectBubble=new Border{Background=PetPalette.Brush(PetPalette.Background),BorderBrush=PetPalette.Brush(PetPalette.Line),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(PetVisuals.SurfaceRadius),Padding=new Thickness(10,6,10,6),Margin=new Thickness(0,8,0,4),Visibility=Visibility.Hidden,Child=CompanionControls.Text("示例任务已完成，可以查看啦。",12)};demo.Children.Add(effectBubble);var spritePreview=new Image{Source=pet.PreviewSprite,Width=144,Height=156,Stretch=Stretch.Uniform};effectSprite=spritePreview;RenderOptions.SetBitmapScalingMode(spritePreview,BitmapScalingMode.HighQuality);demo.Children.Add(spritePreview);
   var toolbar=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Center,Margin=new Thickness(0,4,0,8)};foreach(string type in new[]{"chat","voice"}){var icon=ToolbarIcons.Create(type);icon.Margin=new Thickness(10,6,10,6);toolbar.Children.Add(icon);var separator=new Border{Width=1,Height=18,Background=PetPalette.Brush(PetPalette.Line)};toolbar.Children.Add(separator);if(type=="voice")effectSeparator=separator;}effectBell=new StackPanel{Orientation=Orientation.Horizontal};var bell=new Grid{Margin=new Thickness(10,6,10,6)};bell.Children.Add(ToolbarIcons.Create("bell"));effectBadge=new Border{CornerRadius=new CornerRadius(7),MinWidth=13,Height=13,Padding=new Thickness(2,0,2,0),HorizontalAlignment=HorizontalAlignment.Right,VerticalAlignment=VerticalAlignment.Top,Margin=new Thickness(0,-4,-5,0),Child=new TextBlock{Text="1",FontSize=9,Foreground=Brushes.White,TextAlignment=TextAlignment.Center}};bell.Children.Add(effectBadge);effectBell.Children.Add(bell);toolbar.Children.Add(effectBell);demo.Children.Add(toolbar);effectStatus=CompanionControls.Text("",13);effectStatus.TextAlignment=TextAlignment.Center;demo.Children.Add(effectStatus);
   var body=new Grid{Margin=new Thickness(0,10,8,8)};body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(280)});body.ColumnDefinitions.Add(new ColumnDefinition());body.Children.Add(new Border{CornerRadius=new CornerRadius(PetVisuals.SurfaceRadius),BorderBrush=PetPalette.Brush(PetPalette.Line),BorderThickness=new Thickness(1),Padding=new Thickness(10),Child=demo});var side=new StackPanel{Margin=new Thickness(14,0,0,0),VerticalAlignment=VerticalAlignment.Center};Grid.SetColumn(side,1);body.Children.Add(side);page.Children.Add(body);var actions=new StackPanel();actions.Children.Add(Button("按当前设置试播完成提醒",delegate{PreviewCompletion();},true));actions.Children.Add(Button("停止预览",StopEffectPreview,false));actions.Children.Add(Button("试听提示音（仅此一次）",delegate{SystemSounds.Asterisk.Play();effectDetail.Text="已试听系统轻提示音；没有修改提示音开关。";},false));side.Children.Add(actions);effectDetail=CompanionControls.Text("",12);effectCountdown=CompanionControls.Text("",12);side.Children.Add(effectDetail);side.Children.Add(effectCountdown);side.Children.Add(Button("调整提醒时长、声音和静默",delegate{NavigateCategory("通知中心","");},false));
   effectTimer.Tick+=delegate{double left=effectSeconds-effectClock.Elapsed.TotalSeconds;if(left<=0){StopEffectTimer();effectDetail.Text="气泡停留时间已结束；真实未读角标会保留到任务已读。";}else effectCountdown.Text="气泡还将显示 "+Math.Ceiling(left)+" 秒";};page.IsVisibleChanged+=delegate{if(!page.IsVisible)StopEffectTimer();else effectSprite.Source=pet.PreviewSprite;};Closed+=delegate{StopEffectTimer();};PreviewEffect("running");
  }
  public void PreviewEffect(string state){StopEffectTimer();PreviewState=state;effectSprite.Source=pet.PreviewSprite;effectSeparator.Visibility=state=="idle"?Visibility.Collapsed:Visibility.Visible;effectBell.Visibility=state=="idle"?Visibility.Collapsed:Visibility.Visible;effectBadge.Background=PetPalette.Brush(PetPalette.Hex(state=="running"?"#3a83f7":state=="review"?"#30c85a":state=="waiting"?"#ff9500":"#8b8790"));effectStatus.Text=state=="idle"?"空闲 · 没有待处理通知":state=="stale"?"暂时断线 · 保留上次状态":Bridge.Name(state);effectDetail.Text=state=="stale"?"真实断线状态按当前设置最多保留 "+pet.Settings.NotificationGraceSeconds+" 秒，并显示最后同步时间。":"模拟外观；点击“试播完成提醒”检查当前提醒设置。";}
  public PreviewPlayback PreviewCompletion(){PreviewEffect("review");var result=EffectPreviewRules.Completion(pet.Settings,pet.NoticePlaybackBlocked);effectDetail.Text=string.IsNullOrEmpty(result.Reason)?"按当前设置试播：气泡 "+result.Seconds+" 秒，提示音"+(result.Sound?"开启":"关闭")+"。":"当前只显示完成角标："+result.Reason+"。";if(result.Bubble){effectBubble.Visibility=Visibility.Visible;effectBubble.BeginAnimation(OpacityProperty,new DoubleAnimation(0,1,TimeSpan.FromMilliseconds(MotionSettings.Enabled?PetVisuals.ShowMs:0)));effectSeconds=result.Seconds;effectClock.Restart();effectTimer.Start();effectCountdown.Text="气泡还将显示 "+result.Seconds+" 秒";}if(result.Sound)SystemSounds.Asterisk.Play();return result;}
  void StopEffectTimer(){effectTimer.Stop();effectClock.Reset();if(effectBubble!=null){effectBubble.BeginAnimation(OpacityProperty,null);effectBubble.Visibility=Visibility.Hidden;}if(effectCountdown!=null)effectCountdown.Text="";}
  public void StopEffectPreview(){StopEffectTimer();PreviewEffect("idle");effectDetail.Text="预览已停止，真实通知不受影响。";}
 }
}
