using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.IO.Compression;using System.Security.Cryptography;using System.Diagnostics;using System.Text.RegularExpressions;
namespace KianaPet {
 public sealed class PackageEntry {public string path,sha256;public long size;}
 public sealed class PackageManifest {public int schema;public string product,version;public PackageEntry[] files;}
 public sealed class PreparedUpdate {public string Folder,Version,Notes;public PackageManifest Manifest;}
 public static class Maintenance {
  public const string Version="0.7.7";
  public static bool RuntimeFile(string path){return Regex.IsMatch(path,@"^(assets/|licenses/|docs/demo/|KianaDesktopPet\.exe(?:\.config)?$|README\.md$|CHANGELOG\.md$|ASSET_NOTICE\.md$|LICENSE$|update-worker\.ps1$)");}
  public static string SafePath(string root,string relative){if(string.IsNullOrWhiteSpace(relative)||relative.Contains(":")||relative.Contains("\\")||relative.StartsWith("/")||relative.Split('/').Any(p=>p==".."||p=="."||p.Length==0)||relative.Split('/').Any(p=>p.EndsWith(".")||p.EndsWith(" ")))throw new Exception("安装包包含无效路径。");string prefix=Path.GetFullPath(root).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar;string target=Path.GetFullPath(Path.Combine(root,relative));if(!target.StartsWith(prefix,StringComparison.OrdinalIgnoreCase))throw new Exception("文件超出安装范围。");return target;}
  public static string Hash(Stream stream){using(var sha=SHA256.Create())return BitConverter.ToString(sha.ComputeHash(stream)).Replace("-","").ToLowerInvariant();}
  public static string Hash(string file){using(var s=File.OpenRead(file))return Hash(s);}
  static void ValidateManifest(PackageManifest m){Version version;if(m==null||m.product!="Kiana Desktop Pet"||m.schema!=1||!System.Version.TryParse(m.version,out version)||m.files==null||m.files.Length<2||m.files.Length>2000)throw new Exception("不是受支持的完整桌宠安装包。");var seen=new HashSet<string>(StringComparer.OrdinalIgnoreCase);foreach(var f in m.files){if(f==null||!seen.Add(f.path??"")||f.size<0||f.size>100*1024*1024||!Regex.IsMatch(f.sha256??"","^[a-fA-F0-9]{64}$"))throw new Exception("安装清单内容无效。");SafePath(Path.GetTempPath(),f.path);}if(!seen.Contains("KianaDesktopPet.exe")||!seen.Contains("assets/pets.json"))throw new Exception("安装包缺少程序或素材。");}
  public static PreparedUpdate PrepareZip(string zip,string cache){var prepared=new PreparedUpdate{Folder=Path.Combine(cache,Guid.NewGuid().ToString("N"))};Directory.CreateDirectory(prepared.Folder);using(var archive=ZipFile.OpenRead(zip)){
    var seen=new HashSet<string>(StringComparer.OrdinalIgnoreCase);long total=0;foreach(var e in archive.Entries){if(e.FullName.EndsWith("/")){SafePath(prepared.Folder,e.FullName.TrimEnd('/'));continue;}SafePath(prepared.Folder,e.FullName);if(!seen.Add(e.FullName)||e.Length>100*1024*1024||(total+=e.Length)>512*1024*1024)throw new Exception("安装包重复、体积过大或路径无效。");}var entry=archive.GetEntry("package-manifest.json");if(entry==null||entry.Length>1024*1024)throw new Exception("缺少安装清单。");using(var reader=new StreamReader(entry.Open()))prepared.Manifest=Store.Json.Deserialize<PackageManifest>(reader.ReadToEnd());ValidateManifest(prepared.Manifest);if(seen.Count!=prepared.Manifest.files.Length+1)throw new Exception("安装包文件数量与清单不符。");
    foreach(var f in prepared.Manifest.files){var e=archive.GetEntry(f.path);if(e==null||e.Length!=f.size)throw new Exception("安装包缺少或损坏文件："+f.path);using(var input=e.Open())if(!string.Equals(Hash(input),f.sha256,StringComparison.OrdinalIgnoreCase))throw new Exception("文件校验失败："+f.path);if(RuntimeFile(f.path)){string target=SafePath(prepared.Folder,f.path);Directory.CreateDirectory(Path.GetDirectoryName(target));e.ExtractToFile(target);}}
   }prepared.Version=prepared.Manifest.version;prepared.Manifest.files=prepared.Manifest.files.Where(f=>RuntimeFile(f.path)).ToArray();Write(Path.Combine(prepared.Folder,"runtime-manifest.json"),prepared.Manifest);string notes=Path.Combine(prepared.Folder,"CHANGELOG.md");prepared.Notes=File.Exists(notes)?File.ReadAllText(notes):"安装包没有单独的版本说明，请参考随包 README。";return prepared;}
  public static void Write(string path,object value){File.WriteAllText(path,Store.Json.Serialize(value),new System.Text.UTF8Encoding(false));}
  public static PackageManifest VerifyRuntime(string folder){string file=Path.Combine(folder,"runtime-manifest.json");var manifest=Store.Json.Deserialize<PackageManifest>(File.ReadAllText(file));ValidateManifest(manifest);foreach(var entry in manifest.files){if(!RuntimeFile(entry.path))throw new Exception("备份中包含非运行文件。");string p=SafePath(folder,entry.path);if(!File.Exists(p)||new FileInfo(p).Length!=entry.size||!string.Equals(Hash(p),entry.sha256,StringComparison.OrdinalIgnoreCase))throw new Exception("备份文件校验失败："+entry.path);}return manifest;}
  public static string[] Backups(string root){string folder=Path.Combine(root,"managed-backups");if(!Directory.Exists(folder))return new string[0];return Directory.GetDirectories(folder).Where(p=>File.Exists(Path.Combine(p,"app","runtime-manifest.json"))).OrderByDescending(p=>p).Take(30).ToArray();}
  public static string BackupVersion(string folder){try{return Store.Json.Deserialize<PackageManifest>(File.ReadAllText(Path.Combine(folder,"app","runtime-manifest.json"))).version;}catch{return "需检查的备份";}}
  public static PreparedUpdate PrepareRollback(string backup,string root){string prefix=Path.GetFullPath(Path.Combine(root,"managed-backups"))+Path.DirectorySeparatorChar;if(!Path.GetFullPath(backup).StartsWith(prefix,StringComparison.OrdinalIgnoreCase))throw new Exception("不是本机管理的备份。");string source=Path.Combine(backup,"app");var m=VerifyRuntime(source);string stage=Path.Combine(root,"update-cache",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(stage);foreach(var entry in m.files){string dest=SafePath(stage,entry.path);Directory.CreateDirectory(Path.GetDirectoryName(dest));File.Copy(SafePath(source,entry.path),dest);}Write(Path.Combine(stage,"runtime-manifest.json"),m);return new PreparedUpdate{Folder=stage,Version=m.version,Manifest=m,Notes="恢复已校验的本机程序备份。偏好设置默认保留当前值。"};}
  public static bool Installed(){return string.Equals(Path.GetFullPath(AppDomain.CurrentDomain.BaseDirectory).TrimEnd('\\'),Path.GetFullPath(Path.Combine(Store.Root,"app")).TrimEnd('\\'),StringComparison.OrdinalIgnoreCase);}
  public static void Launch(PreparedUpdate prepared,string preferenceSource){if(!Installed())throw new Exception("请先使用安装器安装桌宠，再从已安装版本更新。");VerifyRuntime(prepared.Folder);string job=Path.Combine(Store.Root,"update-jobs",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(job);string worker=Path.Combine(job,"update-worker.ps1");File.Copy(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"update-worker.ps1"),worker);string config=Path.Combine(job,"job.json");Write(config,new{Root=Path.GetFullPath(Store.Root),Stage=prepared.Folder,ParentId=Process.GetCurrentProcess().Id,Version=prepared.Version,PreferenceSource=preferenceSource});Process.Start(new ProcessStartInfo{FileName=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System),@"WindowsPowerShell\v1.0\powershell.exe"),Arguments="-NoLogo -NoProfile -ExecutionPolicy Bypass -File \""+worker+"\" -JobFile \""+config+"\"",UseShellExecute=false,CreateNoWindow=true,WindowStyle=ProcessWindowStyle.Hidden});}
 }
}

