using System;using System.Collections.Generic;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Imaging;
namespace KianaPet {
 public static class MusicGradient {
  public static readonly string[] Modes={"solid","cover-gradient","background-gradient"};
  sealed class Pixel {public Color Color;public double Weight;}
  static double Distance(Color a,Color b){return Math.Pow(a.R-b.R,2)+Math.Pow(a.G-b.G,2)+Math.Pow(a.B-b.B,2);}
  public static Color[] SamplePair(BitmapSource image){Color fallback=PetPalette.Hex("#A28ABA");if(image==null)return new[]{fallback,fallback};var small=new TransformedBitmap(image,new ScaleTransform(16d/image.PixelWidth,16d/image.PixelHeight));var converted=new FormatConvertedBitmap(small,PixelFormats.Bgra32,null,0);byte[] bytes=new byte[converted.PixelWidth*converted.PixelHeight*4];converted.CopyPixels(bytes,converted.PixelWidth*4,0);var pixels=new List<Pixel>();double total=0,r=0,g=0,b=0;for(int i=0;i<bytes.Length;i+=4){double max=Math.Max(bytes[i],Math.Max(bytes[i+1],bytes[i+2])),min=Math.Min(bytes[i],Math.Min(bytes[i+1],bytes[i+2]));double weight=bytes[i+3]/255d*(.2+(max-min)/255d);if(max<25||min>240)weight*=.1;if(weight<=0)continue;var p=new Pixel{Color=Color.FromRgb(bytes[i+2],bytes[i+1],bytes[i]),Weight=weight};pixels.Add(p);total+=weight;r+=p.Color.R*weight;g+=p.Color.G*weight;b+=p.Color.B*weight;}if(total<=0)return new[]{fallback,fallback};Color mean=Color.FromRgb((byte)(r/total),(byte)(g/total),(byte)(b/total));Color first=mean,second=mean;double far=-1;foreach(var p in pixels){double score=Distance(mean,p.Color)*p.Weight;if(score>far){far=score;second=p.Color;}}double[] weights=new double[2];for(int step=0;step<8;step++){double[] rs=new double[2],gs=new double[2],bs=new double[2];weights=new double[2];foreach(var p in pixels){int c=Distance(p.Color,first)<=Distance(p.Color,second)?0:1;weights[c]+=p.Weight;rs[c]+=p.Color.R*p.Weight;gs[c]+=p.Color.G*p.Weight;bs[c]+=p.Color.B*p.Weight;}if(weights[0]>0)first=Color.FromRgb((byte)(rs[0]/weights[0]),(byte)(gs[0]/weights[0]),(byte)(bs[0]/weights[0]));if(weights[1]>0)second=Color.FromRgb((byte)(rs[1]/weights[1]),(byte)(gs[1]/weights[1]),(byte)(bs[1]/weights[1]));}if(Math.Min(weights[0],weights[1])<total*.08)return new[]{mean,mean};return weights[0]>=weights[1]?new[]{first,second}:new[]{second,first};}
  public static Color[] Stops(Color[] colors,bool hasCover,bool dark,bool enabled,int strength,string mode){Color background=PetPalette.Hex(dark?"#27262D":"#FFFFFF");double amount=enabled&&hasCover?Math.Max(0,Math.Min(100,strength))/100d*(dark?.25:.28):0;Color first=PetPalette.Mix(background,colors[0],amount),second=mode=="background-gradient"?background:PetPalette.Mix(background,colors[1],amount);return new[]{first,second};}
  public static LinearGradientBrush Brush(Color[] colors){return new LinearGradientBrush(colors[0],colors[1],new Point(0,0),new Point(1,1));}
 }
 public sealed partial class PetWindow {public BitmapSource MusicCoverForAppearance{get{return musicLibrary.CoverFor(Music.Current);}}}
 public sealed partial class SettingsWindow {
  Border musicColorPreview;TextBlock musicColorPreviewText;BitmapSource previewArt;string previewKey="";Color[] previewColors;Color previewAccent;
  void BuildMusicColorMode(Panel page){var mode=new ComboBox{ItemsSource=new[]{"柔和纯色（原有）","封面双色渐变","封面 → 主题背景渐变"},SelectedIndex=Array.IndexOf(MusicGradient.Modes,pet.Settings.MusicTintMode),Padding=new Thickness(8),Margin=new Thickness(0,6,0,6)};System.Windows.Automation.AutomationProperties.SetName(mode,"音乐栏配色样式");mode.SelectionChanged+=delegate{if(mode.SelectedIndex<0)return;pet.Settings.MusicTintMode=MusicGradient.Modes[mode.SelectedIndex];pet.ApplySettings();RefreshMusicColorPreview();};page.Children.Add(mode);musicColorPreviewText=new TextBlock{TextWrapping=TextWrapping.Wrap,FontSize=12};musicColorPreview=new Border{CornerRadius=new CornerRadius(10),BorderThickness=new Thickness(1),Padding=new Thickness(14),MinHeight=52,Margin=new Thickness(0,5,0,5),Child=musicColorPreviewText};page.Children.Add(musicColorPreview);Note(page,"双色渐变提取封面中的两种代表颜色；主题背景渐变从封面色过渡到浅色/深色卡片底色。配色程度控制浓淡，0 或关闭配色时恢复中性色。这里的背景指卡片主题，不读取桌面壁纸。");RefreshMusicColorPreview();}
  void RefreshMusicColorPreview(){if(musicColorPreview==null)return;var art=pet.MusicCoverForAppearance;bool dark=PetPalette.IsDark(pet.Settings.Theme);string key=pet.Settings.MusicTintMode+":"+pet.Settings.MusicCoverTint+":"+pet.Settings.MusicTintStrength+":"+dark;if(object.ReferenceEquals(previewArt,art)&&key==previewKey)return;bool resample=previewColors==null||!object.ReferenceEquals(previewArt,art);previewArt=art;previewKey=key;if(resample){previewColors=art==null?new[]{PetPalette.Hex("#719DD5"),PetPalette.Hex("#D696B4")}:MusicGradient.SamplePair(art);previewAccent=art==null?PetPalette.Hex("#A28ABA"):PetPalette.Sample(art);}musicColorPreview.Background=pet.Settings.MusicTintMode=="solid"?(Brush)PetPalette.Brush(PetPalette.MusicSurface(previewAccent,dark,pet.Settings.MusicCoverTint,pet.Settings.MusicTintStrength)):MusicGradient.Brush(MusicGradient.Stops(previewColors,true,dark,pet.Settings.MusicCoverTint,pet.Settings.MusicTintStrength,pet.Settings.MusicTintMode));musicColorPreview.BorderBrush=PetPalette.Brush(dark?PetPalette.Hex("#48434F"):PetPalette.Hex("#E9E7EC"));musicColorPreviewText.Foreground=PetPalette.Brush(dark?PetPalette.Hex("#F1EFF5"):PetPalette.Hex("#29272D"));musicColorPreviewText.Text=art==null?"示意配色 · 播放有封面的歌曲后，自动换成实际封面颜色":"当前封面配色预览 · 随歌曲自动更新";}
 }
}
