using System;using System.IO;using System.Collections.Generic;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Threading;
namespace KianaPet {
 public sealed class MusicSpriteCalibration {public string Skin;public double FaceWidth;public double[] SourceFaceWidths,Centers,Feet;public int[] RowEdges;}
 public static class MusicSprites {
  static readonly Dictionary<string,BitmapSource[]> loaded=new Dictionary<string,BitmapSource[]>();
  public static bool Supported(string skin){return skin=="kiana-winter-wish-round"||skin=="kiana-fiery-wishing-star-round"||skin=="time-runner-kiana-round";}
  public static BitmapSource[] Load(string skin){BitmapSource[] result;if(loaded.TryGetValue(skin,out result))return result;if(!Supported(skin))return null;
   try{var atlas=new BitmapImage();atlas.BeginInit();atlas.CacheOption=BitmapCacheOption.OnLoad;atlas.UriSource=new Uri(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets",skin+"-music.png"));atlas.EndInit();atlas.Freeze();if(atlas.PixelWidth%2!=0||atlas.PixelHeight%3!=0||atlas.PixelWidth<768||atlas.PixelWidth>4096||atlas.PixelHeight>4096)throw new InvalidDataException("音乐动作图集尺寸错误");var calibrations=Store.Json.Deserialize<MusicSpriteCalibration[]>(File.ReadAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets","music-sprite-calibration.json")));var calibration=Array.Find(calibrations,c=>c.Skin==skin);if(calibration==null||calibration.SourceFaceWidths.Length!=6||calibration.Centers.Length!=6||calibration.Feet.Length!=6)throw new InvalidDataException("音乐动作比例配置错误");
    result=new BitmapSource[6];int w=atlas.PixelWidth/2;var edges=calibration.RowEdges;if(edges==null||edges.Length!=4||edges[0]!=0||edges[3]!=atlas.PixelHeight)throw new InvalidDataException("音乐动作分行配置错误");for(int i=0;i<6;i++){int top=edges[i/2],h=edges[i/2+1]-top;var raw=new CroppedBitmap(atlas,new Int32Rect(i%2*w,top,w,h));raw.Freeze();double scale=calibration.FaceWidth/calibration.SourceFaceWidths[i];if(scale<.3||scale>1.3||!MusicReactions.Finite(scale))throw new InvalidDataException("音乐动作缩放无效");var drawing=new DrawingVisual();RenderOptions.SetBitmapScalingMode(drawing,BitmapScalingMode.HighQuality);using(var dc=drawing.RenderOpen())dc.DrawImage(raw,new Rect(192-calibration.Centers[i]*scale,398-calibration.Feet[i]*scale,w*scale,h*scale));var frame=new RenderTargetBitmap(768,832,192,192,PixelFormats.Pbgra32);frame.Render(drawing);frame.Freeze();result[i]=frame;}loaded[skin]=result;return result;
   }catch(Exception e){Store.Log("Music sprites: "+e.Message);loaded[skin]=null;return null;}
  }
 }
 public sealed class MusicAnimationPreview:Window {
  readonly DispatcherTimer timer=new DispatcherTimer();public readonly Image Sprite=new Image();readonly DateTime started=DateTime.UtcNow;
  public MusicAnimationPreview(string skin,string mode){Title="音乐动作预览 · "+MusicReactions.Label(mode);Width=370;Height=470;WindowStartupLocation=WindowStartupLocation.CenterScreen;PetVisuals.Apply(this,true);Background=PetPalette.Brush(PetPalette.Background);var root=new StackPanel{Margin=new Thickness(20)};var frames=MusicSprites.Load(skin);Sprite.Width=270;Sprite.Height=292.5;Sprite.Stretch=Stretch.Fill;RenderOptions.SetBitmapScalingMode(Sprite,BitmapScalingMode.HighQuality);root.Children.Add(Sprite);root.Children.Add(CompanionControls.Text("独立预览，不修改播放、任务或歌曲偏好。",12));root.Children.Add(CompanionControls.Button("关闭预览",Close));Content=root;string state=mode=="gentle"?"music-gentle":mode=="lively"?"music-lively":"music-quiet";Action draw=delegate{if(frames!=null)Sprite.Source=frames[MusicReactions.Frame(state,(DateTime.UtcNow-started).TotalMilliseconds,MotionSettings.Reduced)];};draw();timer.Interval=TimeSpan.FromMilliseconds(80);timer.Tick+=delegate{draw();};Loaded+=delegate{timer.Start();};Closed+=delegate{timer.Stop();};PreviewKeyDown+=delegate(object sender,System.Windows.Input.KeyEventArgs e){if(e.Key==System.Windows.Input.Key.Escape)Close();};}
 }
}
