using System;using System.Linq;using System.Collections.Generic;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;using System.Windows.Threading;
namespace KianaPet {
 public static class CompanionControls {
  public static Button Button(string text,Action action){var b=new Button{Content=text,Padding=new Thickness(12,7,12,7),Margin=new Thickness(0,4,8,4),MinHeight=32,Background=PetPalette.Brush(PetPalette.Background),Foreground=PetPalette.Brush(PetPalette.Ink),BorderBrush=PetPalette.Brush(PetPalette.Line),BorderThickness=new Thickness(1),Cursor=Cursors.Hand};PetVisuals.RoundButton(b);System.Windows.Automation.AutomationProperties.SetName(b,text);b.Click+=delegate{action();};return b;}
  public static TextBlock Text(string text,int size=13){return new TextBlock{FontFamily=PetVisuals.Font,Text=text,FontSize=size,TextWrapping=TextWrapping.Wrap,Foreground=PetPalette.Brush(PetPalette.Ink),Margin=new Thickness(0,5,0,5)};}
 }
 public sealed class NoticeRow {
  public string Key,Source,Id,Title,State;public DateTime UpdatedAt;public bool ChatGPT,Unread,Stale,CanOpen,Muted,TaskMuted;public TaskNotice Local;
  public int Group{get{return State=="failed"||State=="waiting"?0:State=="running"?1:Unread?2:3;}}
 }
 public sealed class NoticeCard:Border {
  public NoticeRow Row;public readonly Button Open,Read,Mute;readonly TextBlock label,title,time;readonly PetWindow pet;readonly Action refresh;
  public NoticeCard(PetWindow owner,Action onChange){pet=owner;refresh=onChange;CornerRadius=new CornerRadius(PetVisuals.SurfaceRadius);BorderThickness=new Thickness(1);Padding=new Thickness(14);Margin=new Thickness(0,6,6,6);var content=new StackPanel();label=CompanionControls.Text("",12);title=CompanionControls.Text("",15);time=CompanionControls.Text("",11);content.Children.Add(label);content.Children.Add(title);content.Children.Add(time);var controls=new WrapPanel();
   Open=CompanionControls.Button("打开任务",delegate{if(Row==null)return;if(Row.ChatGPT)pet.OpenChatGPTTask(Row.Id);else try{pet.TaskNotices.Open(Row.Local);refresh();}catch(Exception e){MessageBox.Show(e.Message,"无法打开任务");}});
   Read=CompanionControls.Button("标为已读",delegate{pet.TaskNotices.Read(Row.Source,Row.Id);refresh();});Mute=CompanionControls.Button("静音此任务",delegate{pet.TaskNotices.Mute(Row.Source,Row.Id,!pet.TaskNotices.IsMuted(Row.Local));refresh();});controls.Children.Add(Open);controls.Children.Add(Read);controls.Children.Add(Mute);content.Children.Add(controls);Child=content;
  }
  public void Update(NoticeRow row){Row=row;BorderBrush=PetPalette.Brush(PetPalette.Line);Background=PetPalette.Brush(PetPalette.Background);title.Foreground=time.Foreground=PetPalette.Brush(PetPalette.Ink);label.Text="● "+row.Source+" · "+TaskNoticeHub.StateName(row.State)+(row.Stale?" · 待同步":"")+(row.Muted?" · 已静音":"");label.Foreground=PetPalette.Brush(PetPalette.Hex(row.Stale?"#8b8790":row.State=="running"?"#3a83f7":row.State=="succeeded"?"#30a65a":row.State=="failed"?"#d95151":"#bd781c"));title.Text=row.Title;time.Text=row.UpdatedAt==DateTime.MinValue?"任务更新时间：来源未提供":"任务更新 "+row.UpdatedAt.ToLocalTime().ToString("MM-dd HH:mm:ss");Open.Content=row.ChatGPT?"在 ChatGPT 中打开":"打开任务";Open.IsEnabled=row.CanOpen;Open.ToolTip=row.Stale?"恢复连接后可打开":row.CanOpen?"打开对应任务":"该来源尚未提供可用跳转";Read.Visibility=Mute.Visibility=row.ChatGPT?Visibility.Collapsed:Visibility.Visible;Read.IsEnabled=row.Unread;Mute.Content=row.TaskMuted?"恢复此任务":"静音此任务";foreach(var b in new[]{Open,Read,Mute}){b.Background=Background;b.Foreground=title.Foreground;b.BorderBrush=BorderBrush;}}
 }
 public sealed class NoticeCenter:Window {
  readonly PetWindow pet;readonly StackPanel list=new StackPanel();readonly ComboBox source=new ComboBox(),status=new ComboBox();readonly CheckBox unread=new CheckBox();readonly TextBlock connection=new TextBlock(),extra=CompanionControls.Text("",12),empty=CompanionControls.Text("当前筛选下没有任务。");readonly DispatcherTimer timer=new DispatcherTimer();readonly ScrollViewer scroll;readonly Button native,muteSource;
  readonly Dictionary<string,NoticeCard> cards=new Dictionary<string,NoticeCard>();readonly StackPanel[] groups=new StackPanel[4],items=new StackPanel[4];readonly TextBlock[] headings=new TextBlock[4];bool rebuilding;
  public int VisibleTaskCount{get{return cards.Count;}}
  public NoticeCenter(PetWindow owner){pet=owner;Title="琪亚娜 · 通知中心";Width=660;Height=740;MinWidth=460;MinHeight=420;PetVisuals.Apply(this,true);PetVisuals.InstallTooltips(this);Background=PetPalette.Brush(PetPalette.Background);Foreground=PetPalette.Brush(PetPalette.Ink);WindowStartupLocation=WindowStartupLocation.CenterScreen;
   var root=new DockPanel{Margin=new Thickness(22)};var top=new StackPanel();top.Children.Add(CompanionControls.Text("任务通知",22));connection.TextWrapping=TextWrapping.Wrap;connection.FontSize=12;connection.Margin=new Thickness(0,5,0,10);top.Children.Add(connection);native=CompanionControls.Button("查看 ChatGPT 原生通知",pet.OpenOriginalNotifications);native.IsEnabled=false;top.Children.Add(native);
   source.MinWidth=150;source.Padding=new Thickness(6);source.Margin=new Thickness(0,4,8,4);status.ItemsSource=new[]{"全部状态","进行中","已完成","失败","等待处理"};status.SelectedIndex=0;status.Padding=new Thickness(6);status.Margin=new Thickness(0,4,8,4);var filters=new WrapPanel();filters.Children.Add(source);filters.Children.Add(status);unread.Content="仅未读";unread.VerticalAlignment=VerticalAlignment.Center;filters.Children.Add(unread);top.Children.Add(filters);
   var actions=new WrapPanel();actions.Children.Add(CompanionControls.Button("本地全部已读",delegate{pet.TaskNotices.ReadAll();Refresh(true);}));muteSource=CompanionControls.Button("静音 / 恢复所选来源",delegate{string selected=source.SelectedItem as string;if(selected==null||selected=="全部来源"||selected=="ChatGPT")return;pet.MuteSource(selected,!pet.Settings.MutedNoticeSources.Contains(selected));Refresh(true);});actions.Children.Add(muteSource);top.Children.Add(actions);DockPanel.SetDock(top,Dock.Top);root.Children.Add(top);
   for(int i=0;i<4;i++){groups[i]=new StackPanel();headings[i]=CompanionControls.Text("",14);headings[i].FontWeight=FontWeights.SemiBold;items[i]=new StackPanel();groups[i].Children.Add(headings[i]);groups[i].Children.Add(items[i]);list.Children.Add(groups[i]);}list.Children.Add(extra);list.Children.Add(empty);scroll=new ScrollViewer{Content=list,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};root.Children.Add(scroll);Content=root;
   source.SelectionChanged+=delegate{if(!rebuilding)Refresh(true);};status.SelectionChanged+=delegate{Refresh(true);};unread.Click+=delegate{Refresh(true);};timer.Interval=TimeSpan.FromSeconds(1);timer.Tick+=delegate{Refresh(false);};Loaded+=delegate{Refresh(true);timer.Start();};Closed+=delegate{timer.Stop();};PreviewKeyDown+=delegate(object sender,KeyEventArgs e){if(e.Key==Key.Escape){Close();e.Handled=true;}};
  }
  public static TaskNotice[] Filter(TaskNotice[] all,string source,int status,bool unread){string[] values={"","running","succeeded","failed","waiting"};return all.Where(n=>(source==null||source=="全部来源"||n.Source==source)&&(status<=0||status>=values.Length||n.Status==values[status])&&(!unread||n.Unread)).ToArray();}
  void Refresh(bool force){if(rebuilding)return;var all=pet.TaskNotices.Snapshot();var bridge=pet.Link.Current;bool available=pet.NotificationsAvailable;string selected=source.SelectedItem as string??"全部来源";var sources=new[]{"全部来源","ChatGPT"}.Concat(all.Select(n=>n.Source).Concat(pet.Settings.MutedNoticeSources).OrderBy(s=>s,StringComparer.Ordinal)).Concat(new[]{selected}).Distinct().ToArray();if(!source.IsDropDownOpen&&(source.ItemsSource==null||!source.ItemsSource.Cast<string>().SequenceEqual(sources))){rebuilding=true;source.ItemsSource=sources;source.SelectedItem=selected;rebuilding=false;}
   Background=PetPalette.Brush(PetPalette.Background);Foreground=PetPalette.Brush(PetPalette.Ink);connection.Foreground=PetPalette.Brush(PetPalette.Muted);unread.Foreground=Foreground;connection.Text=pet.StatusText+"\n最后有效同步 "+LinkHealth.Time(bridge.LastSuccessAt)+(bridge.Stale?" · 以下为上次状态":"");native.IsEnabled=available&&bridge.Connected&&!bridge.Stale&&bridge.NotificationSource=="mini"&&bridge.CanNotifications;muteSource.IsEnabled=selected!="全部来源"&&selected!="ChatGPT";
   var rows=new List<NoticeRow>();if((selected=="全部来源"||selected=="ChatGPT")&&available){string[] states={"","running","review","failed","waiting"};foreach(var n in bridge.Notices.Where(n=>status.SelectedIndex<=0||status.SelectedIndex>=states.Length||n.State==states[status.SelectedIndex]))rows.Add(new NoticeRow{Key="gpt:"+n.Id,Source="ChatGPT",Id=n.Id,Title=string.IsNullOrWhiteSpace(n.Title)?"ChatGPT 任务":n.Title,State=n.State=="review"?"succeeded":n.State,UpdatedAt=n.UpdatedAt,Unread=true,ChatGPT=true,Stale=bridge.Stale,CanOpen=bridge.Connected&&!bridge.Stale});}
   foreach(var n in Filter(all,selected,status.SelectedIndex,unread.IsChecked==true))rows.Add(new NoticeRow{Key="local:"+n.Source.Length+":"+n.Source+n.TaskId,Source=n.Source,Id=n.TaskId,Title=n.Title,State=n.Status,UpdatedAt=n.UpdatedAt,Unread=n.Unread,CanOpen=pet.TaskNotices.CanOpen(n),Muted=pet.NoticeMuted(n),TaskMuted=pet.TaskNotices.IsMuted(n),Local=n});
   UpdateLayout();var focused=Keyboard.FocusedElement as FrameworkElement;bool focusInList=focused!=null&&focused.IsDescendantOf(list);double offset=scroll.VerticalOffset;var anchor=items.SelectMany(p=>p.Children.OfType<NoticeCard>()).FirstOrDefault(c=>c.TranslatePoint(new Point(0,c.ActualHeight),scroll).Y>=0&&c.TranslatePoint(new Point(0,0),scroll).Y<scroll.ViewportHeight);string anchorKey=anchor==null?null:anchor.Row.Key;double anchorY=anchor==null?0:anchor.TranslatePoint(new Point(0,0),scroll).Y;
   var wanted=new HashSet<string>(rows.Select(r=>r.Key));foreach(var key in cards.Keys.Where(k=>!wanted.Contains(k)).ToArray()){var card=cards[key];((Panel)card.Parent).Children.Remove(card);cards.Remove(key);}
   string[] titles={"需要处理","正在进行","完成未读","已读记录"};for(int group=0;group<4;group++){var sorted=rows.Where(r=>r.Group==group).OrderByDescending(r=>r.UpdatedAt).ThenBy(r=>r.Key,StringComparer.Ordinal).GroupBy(r=>r.Key).Select(g=>g.First()).ToArray();headings[group].Text=titles[group]+" · "+sorted.Length;headings[group].Foreground=Foreground;groups[group].Visibility=sorted.Length>0?Visibility.Visible:Visibility.Collapsed;for(int index=0;index<sorted.Length;index++){var row=sorted[index];NoticeCard card;if(!cards.TryGetValue(row.Key,out card)){card=new NoticeCard(pet,delegate{Refresh(true);});cards.Add(row.Key,card);}card.Update(row);if(card.Parent!=items[group]||items[group].Children.IndexOf(card)!=index){var parent=card.Parent as Panel;if(parent!=null)parent.Children.Remove(card);items[group].Children.Insert(index,card);}}}
   int remaining=available&&(selected=="全部来源"||selected=="ChatGPT")?Math.Max(0,bridge.NotificationCount-bridge.Notices.Length):0;extra.Text="另有 "+remaining+" 项原生活动，可通过上方入口查看。";extra.Visibility=remaining>0?Visibility.Visible:Visibility.Collapsed;empty.Visibility=cards.Count==0&&remaining==0?Visibility.Visible:Visibility.Collapsed;extra.Foreground=empty.Foreground=Foreground;UpdateLayout();
   if(focusInList){if(focused.IsDescendantOf(list)&&focused.IsVisible&&focused.IsEnabled){if(Keyboard.FocusedElement!=focused)focused.Focus();}else status.Focus();}
   NoticeCard survivor;if(anchorKey!=null&&cards.TryGetValue(anchorKey,out survivor)){UpdateLayout();scroll.ScrollToVerticalOffset(scroll.VerticalOffset+survivor.TranslatePoint(new Point(0,0),scroll).Y-anchorY);}else scroll.ScrollToVerticalOffset(offset);
  }
 }
 public sealed partial class PetWindow {
  NoticeCenter noticeCenter;
  public bool NoticeMuted(TaskNotice n){return TaskNotices.IsMuted(n)||Settings.MutedNoticeSources.Contains(n.Source);}
  public TaskNotice[] VisibleNotices{get{return TaskNotices.Snapshot().Where(n=>!NoticeMuted(n)).ToArray();}}
  public void MuteSource(string name,bool muted){Settings.MutedNoticeSources=muted?Settings.MutedNoticeSources.Concat(new[]{name}).Distinct().Take(50).ToArray():Settings.MutedNoticeSources.Where(s=>s!=name).ToArray();ApplySettings();}
  public void OpenNoticeCenter(){CloseNoticePreview();if(noticeCenter!=null){noticeCenter.Activate();return;}noticeCenter=new NoticeCenter(this);noticeCenter.Closed+=delegate{noticeCenter=null;};noticeCenter.Show();}
  public void OpenNativeNotifications(){OpenNoticeCenter();}
  public void OpenOriginalNotifications(){RunToolbarAction("notifications");}
 }
}
