using System;using System.Linq;using System.Windows;using System.Windows.Controls;using System.Windows.Controls.Primitives;
namespace KianaPet {
 public sealed partial class PetWindow {
  readonly ChorusLibrary chorusLibrary=new ChorusLibrary();readonly MusicReactionPlanner musicReactionPlanner=new MusicReactionPlanner();
  public string MusicReactionStatus {get{var state=Music.Current;var pref=MusicReactions.Preference(Settings,state.Id);string range=pref!=null&&MusicReactions.ValidRange(pref.Start,pref.End,state.Duration)?"手动副歌 "+TimeText(pref.Start)+"–"+TimeText(pref.End):pref!=null&&pref.Start>=0&&pref.End<0?"起点已记下，等待标记终点":chorusLibrary.Status;return (state.Connected?state.Title:"尚未连接歌曲")+"\n"+MusicReactions.RuleText(Settings,state.Id)+"\n"+range+(MusicSprites.Supported(Settings.Skin)?"":"\n当前普通版保持原动作；换成三套 Q 版可体验音乐动作。");}}
  public static string TimeText(double seconds){return TimeSpan.FromSeconds(Math.Max(0,seconds)).ToString(@"mm\:ss");}
  SongMusicPreference SongPreference(){var state=Music.Current;if(!state.Connected||!MusicReactions.SongId(state.Id))return null;var existing=MusicReactions.Preference(Settings,state.Id);if(existing!=null)return existing;var added=new SongMusicPreference{Id=state.Id,Title=state.Title};Settings.MusicSongPreferences=Settings.MusicSongPreferences.Concat(new[]{added}).Reverse().Take(100).Reverse().ToArray();return added;}
  public void SetSongMusicMode(string mode){if(mode!="inherit"&&!MusicReactions.Modes.Contains(mode))return;var pref=SongPreference();if(pref==null){Say("播放一首有歌曲 ID 的网易云音乐后再设置。",4);return;}pref.Mode=mode;pref.NormalAction=mode=="inherit"?"inherit":mode=="off"?"off":"quiet";pref.ChorusAction=mode;Settings.Validate();Save();}
  public void MarkMusicChorus(bool end){var pref=SongPreference();if(pref==null){Say("请先连接并播放网易云歌曲。",4);return;}double position=MusicReactions.Position(Music.Current,DateTime.UtcNow);if(end){if(!MusicReactions.ValidRange(pref.Start,position,Music.Current.Duration)){Say("先标记起点，终点要晚于起点且相隔不超过十分钟。",5);return;}pref.End=position;}else{pref.Start=position;pref.End=-1;}Save();}
  public void ClearMusicChorus(){var pref=MusicReactions.Preference(Settings,Music.Current.Id);if(pref!=null){pref.Start=pref.End=-1;Save();}}
  public void PreviewMusicAnimation(string mode){if(!MusicSprites.Supported(Settings.Skin)){Say("请先换成三套 Q 版之一，再预览音乐动作。",4);return;}var window=new MusicAnimationPreview(Settings.Skin,mode);window.Show();}
  string ChooseMusicReaction(double now,bool allowed){return musicReactionPlanner.Choose(Music.Current,Settings,Settings.MusicChorusEnabled?chorusLibrary.For(Music.Current.Id):new ChorusRange[0],now,DateTime.UtcNow,allowed&&MusicSprites.Supported(Settings.Skin));}
  string drawnMusicState="";bool musicRising;
  bool DrawMusicReaction(double elapsed){if(!state.StartsWith("music-",StringComparison.Ordinal)){drawnMusicState="";musicRising=false;return false;}if(drawnMusicState!=state){musicRising=drawnMusicState=="music-quiet"&&state!="music-quiet";drawnMusicState=state;}var frames=MusicSprites.Load(Settings.Skin);if(frames==null){SetFrame(0,0);return true;}int frame;var image=MusicSprites.Playback(Settings.Skin,state,elapsed,Settings.ReduceMotion,musicRising,out frame);if(lastFrame!=400+frame){lastFrame=400+frame;ShowSprite(image,"music",frame);}sprite.RenderTransform=new System.Windows.Media.RotateTransform(state=="music-gentle"&&Settings.Skin!="time-runner-kiana-round"&&(!musicRising||elapsed>=MusicReactions.SitTransitionMs)&&!Settings.ReduceMotion?MusicReactions.GentleAngle(elapsed-(musicRising?MusicReactions.SitTransitionMs:0)):0,Settings.Size*.46,Settings.Size*1.03);return true;}
  public void SetSongMusicAction(bool chorus,string action){if(!MusicReactions.Modes.Contains(action)&&action!="inherit"&&!(!chorus&&action=="mixed")&&!(chorus&&action=="same"))return;var pref=SongPreference();if(pref==null){Say("播放网易云歌曲后再设置本曲动作。",4);return;}if(chorus)pref.ChorusAction=action;else pref.NormalAction=action;Settings.Validate();Save();}
  void AddSongMusicMenu(ItemsControl parent){var song=Submenu(parent,"这首歌的音乐动作");song.IsEnabled=Music.Current.Connected&&MusicReactions.SongId(Music.Current.Id);var current=MusicReactions.Preference(Settings,Music.Current.Id);foreach(bool chorus in new[]{false,true}){bool capturedPhase=chorus;var phase=Submenu(song,chorus?"进入副歌时":"平时播放时");foreach(string action in chorus?new[]{"inherit","same","quiet","gentle","lively","off"}:new[]{"inherit","mixed","quiet","gentle","lively","off"}){string captured=action;var item=new MenuItem{Header=MusicReactions.Label(action),IsCheckable=true,IsChecked=MusicReactions.SongActionSetting(current,chorus)==action};item.Click+=delegate{SetSongMusicAction(capturedPhase,captured);};phase.Items.Add(item);}}song.Items.Add(new Separator());Add(song,"标记副歌起点（当前位置）",delegate{MarkMusicChorus(false);});Add(song,"标记副歌终点（当前位置）",delegate{MarkMusicChorus(true);});Add(song,"清除本曲手动副歌",ClearMusicChorus);}
  public void OpenMusicReactionMenu(FrameworkElement anchor){var menu=PetMenus.Create();menu.PlacementTarget=anchor;menu.Placement=PlacementMode.MousePoint;AddSongMusicMenu(menu);var previewMenu=Submenu(menu,"预览音乐动作");foreach(string mode in new[]{"quiet","gentle","lively"}){string captured=mode;Add(previewMenu,MusicReactions.Label(mode),delegate{PreviewMusicAnimation(captured);});}ShowPetMenu(menu);}
 }
}
