using System;using System.IO;using System.Linq;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media.Imaging;
namespace KianaPet {
 public sealed partial class PetWindow {
  public readonly EditHistory Edits=new EditHistory();Config lastPreferences;bool restoringEdit;double interactionHoldUntil;bool keyboardToolbarMode;
  public PreferenceEdit PendingUndo{get{return Edits.Peek(DateTime.UtcNow);}}
  void StartUsability(){lastPreferences=PreferenceTransfer.Copy(Settings);try{var recent=Store.Json.Deserialize<RecentEdit[]>(File.ReadAllText(Path.Combine(Store.Root,"recent-settings.json")));Edits.Recent.AddRange(recent.Where(r=>r!=null&&r.Label!=null&&r.Label.Length<100&&r.Category!=null&&r.Category.Length<50).Take(12));}catch{}ApplyInputOptions();}
  void TrackPreferences(){if(lastPreferences==null){lastPreferences=PreferenceTransfer.Copy(Settings);return;}if(!restoringEdit){int prior=Edits.Revision;Edits.Record(lastPreferences,Settings,DateTime.UtcNow);if(prior!=Edits.Revision)Store.Atomic("recent-settings.json",Edits.Recent);}lastPreferences=PreferenceTransfer.Copy(Settings);}
  public void UndoLastEdit(){var entry=Edits.Pop(DateTime.UtcNow);if(entry==null)return;restoringEdit=true;try{if(entry.Restore!=null)entry.Restore();else{var before=PreferenceTransfer.Copy(entry.Before);string musicPosition=before.MusicPosition;string warning=ReplacePreferences(before,false);Settings.MusicPosition=musicPosition;ApplySettings();if(warning.Length>0)MessageBox.Show(warning,"撤销提示");}lastPreferences=PreferenceTransfer.Copy(Settings);Say("已撤销："+entry.Label,3);if(settingsWindow!=null)RefreshSettingsWindow();}finally{restoringEdit=false;}}
  bool CursorBlocksWalk(Native.Rect rect,double scale){if(!Settings.AvoidCursor)return false;Native.Point p;Native.GetCursorPos(out p);return CursorAvoidance.Near(new System.Drawing.Rectangle(rect.Left,rect.Top,rect.Width,rect.Height),new System.Drawing.Point(p.X,p.Y),28*scale);}
  double CursorSafeTarget(Native.Rect rect,System.Drawing.Rectangle area,double scale){Native.Point p;Native.GetCursorPos(out p);return walkPlanner.NextSafe(rect.Left,area.Left,area.Right-rect.Width,random,Settings.WalkDistanceMin*scale,Settings.WalkDistanceMax*scale,24*scale,target=>!Settings.AvoidCursor||!CursorAvoidance.Crosses(new System.Drawing.Rectangle(rect.Left,rect.Top,rect.Width,rect.Height),new System.Drawing.Point(p.X,p.Y),target,28*scale));}
  void ApplyInputOptions(){MotionSettings.Reduced=Settings.ReduceMotion;if(Settings.ReduceMotion){sprite.BeginAnimation(OpacityProperty,null);sprite.Opacity=1;hoverBar.BeginAnimation(OpacityProperty,null);toolbarScale.BeginAnimation(System.Windows.Media.ScaleTransform.ScaleXProperty,null);toolbarScale.BeginAnimation(System.Windows.Media.ScaleTransform.ScaleYProperty,null);toolbarSlide.BeginAnimation(System.Windows.Media.TranslateTransform.YProperty,null);hoverBar.Opacity=toolbarShown?1:0;toolbarScale.ScaleX=toolbarScale.ScaleY=1;toolbarSlide.Y=0;}foreach(var b in new[]{chatButton,voiceButton,notificationButton}){b.Focusable=true;b.Width=Settings.LargeTouchTargets?42:32;b.Height=Settings.LargeTouchTargets?40:32;}KeyboardNavigation.SetTabNavigation(hoverBar,KeyboardNavigationMode.Cycle);System.Windows.Automation.AutomationProperties.SetName(sprite,"琪亚娜桌宠，右键打开菜单");}
  public void FocusToolbar(){if(!Settings.HoverToolbar){Settings.HoverToolbar=true;ApplySettings();}manualHidden=false;if(!IsVisible)Show();keyboardToolbarMode=true;Native.SetMenuActivation(handle,true);Activate();Native.FocusPetForMenu(handle);SetToolbarVisible(true,false);chatButton.Focus();}
  void ToolbarKey(object sender,KeyEventArgs e){if(!keyboardToolbarMode)return;if(e.Key==Key.Escape){keyboardToolbarMode=false;Native.SetMenuActivation(handle,false);if(settingsWindow!=null)settingsWindow.Activate();e.Handled=true;}else if(e.Key==Key.Right||e.Key==Key.Left){var buttons=new[]{chatButton,voiceButton,notificationButton}.Where(b=>b.IsEnabled&&b.Visibility==Visibility.Visible).ToArray();int current=Array.FindIndex(buttons,b=>b.IsKeyboardFocused);buttons[(current+(e.Key==Key.Right?1:buttons.Length-1)+buttons.Length)%buttons.Length].Focus();e.Handled=true;}}
  readonly System.Collections.Generic.Dictionary<string,BitmapSource[]> transitionFrames=new System.Collections.Generic.Dictionary<string,BitmapSource[]>();
  void EnsureTransitions(){if(transitionFrames.ContainsKey(Settings.Skin))return;string file=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets",Settings.Skin+"-transition.png");if(!File.Exists(file)){transitionFrames[Settings.Skin]=null;return;}var atlas=new BitmapImage();atlas.BeginInit();atlas.CacheOption=BitmapCacheOption.OnLoad;atlas.UriSource=new Uri(file);atlas.EndInit();atlas.Freeze();if(atlas.PixelWidth!=768||atlas.PixelHeight!=832)throw new Exception("过渡图集尺寸错误");var cells=new BitmapSource[4];for(int i=0;i<4;i++){var cell=new CroppedBitmap(atlas,new Int32Rect(i%2*384,i/2*416,384,416));cell.Freeze();cells[i]=cell;}transitionFrames[Settings.Skin]=cells;}
  bool DrawTransition(double elapsed){if(state!="groom"&&state!="stretch")return false;EnsureAmbient();EnsureTransitions();var old=ambientFrames[Settings.Skin];var added=transitionFrames[Settings.Skin];if(old==null||added==null)return false;int frame=Settings.ReduceMotion?3:TransitionSequence.Frame(elapsed),row=state=="groom"?0:1;if(frame<0){SetFrame(0,0);return true;}int marker=300+row*4+frame;if(lastFrame!=marker){lastFrame=marker;if(frame<2)ShowSprite(added[row*2+frame],"transition",row*2+frame);else ShowSprite(old[row*2+frame-2],"ambient",row*2+frame-2);}return true;}
 }
}
