using System;using System.Linq;using System.Windows;using System.Windows.Controls;
namespace KianaPet {
 public sealed class PreferenceReviewWindow:Window {
  readonly PetWindow pet;readonly PreferenceImportInfo incoming;readonly CheckBox local=new CheckBox(),positions=new CheckBox();readonly StackPanel changes=new StackPanel();readonly TextBlock summary=new TextBlock();readonly Button apply;public string Warning{get;private set;}
  public PreferenceReviewWindow(PetWindow owner,PreferenceImportInfo info,bool includePositions){pet=owner;incoming=info;Title="导入前检查 · 桌宠偏好";Width=760;Height=680;MinWidth=540;MinHeight=420;WindowStartupLocation=WindowStartupLocation.CenterOwner;PetVisuals.Apply(this,true);Background=PetPalette.Brush(PetPalette.Background);Foreground=PetPalette.Brush(PetPalette.Ink);
   var dock=new DockPanel{Margin=new Thickness(22)};var top=new StackPanel();top.Children.Add(CompanionControls.Text("检查将要改变的设置",22));top.Children.Add(CompanionControls.Text("本机程序 "+Maintenance.Version+" · 设置包来源 "+info.Version+(info.ExportedAt.HasValue?"\n导出于 "+info.ExportedAt.Value.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss"):""),12));
   local.Content="同时导入本机配置：启动、快捷键、联动、应用名单";local.IsEnabled=info.PresentKeys.Any(PreferenceReview.LocalKeys.Contains);positions.Content="同时导入屏幕位置（坐标会适配当前屏幕）";positions.IsEnabled=info.PresentKeys.Any(PreferenceReview.PositionKeys.Contains);positions.IsChecked=includePositions&&positions.IsEnabled;foreach(var c in new[]{local,positions}){c.Foreground=Foreground;c.Margin=new Thickness(0,6,0,6);top.Children.Add(c);c.Click+=delegate{Refresh();};}
   top.Children.Add(CompanionControls.Text("默认只合并通用偏好；包内缺少的选项保留本机值。不会覆盖程序路径、显示布局记忆或连接会话。版本号与导出时间供对照，不自动判定哪台电脑的偏好更新。",12));summary.TextWrapping=TextWrapping.Wrap;summary.Margin=new Thickness(0,8,0,10);top.Children.Add(summary);DockPanel.SetDock(top,Dock.Top);dock.Children.Add(top);
   var actions=new WrapPanel{HorizontalAlignment=HorizontalAlignment.Right};actions.Children.Add(CompanionControls.Button("取消",delegate{DialogResult=false;}));apply=CompanionControls.Button("备份并应用",Apply);actions.Children.Add(apply);DockPanel.SetDock(actions,Dock.Bottom);dock.Children.Add(actions);dock.Children.Add(new ScrollViewer{Content=changes,VerticalScrollBarVisibility=ScrollBarVisibility.Auto});Content=dock;Refresh();
  }
  public Config Proposed{get{return PreferenceReview.Merge(pet.Settings,incoming,local.IsChecked==true,positions.IsChecked==true);}}
  void Refresh(){var proposed=Proposed;var rows=PreferenceReview.Differences(pet.Settings,proposed);changes.Children.Clear();int protectedCount=incoming.PresentKeys.Count(k=>PreferenceReview.LocalKeys.Contains(k)&&local.IsChecked!=true||PreferenceReview.PositionKeys.Contains(k)&&positions.IsChecked!=true);summary.Text="将修改 "+rows.Length+" 项 · 保留 "+protectedCount+" 项本机配置"+(incoming.UnknownKeys.Length>0?" · 跳过 "+incoming.UnknownKeys.Length+" 项本版本不认识的选项":"");apply.IsEnabled=rows.Length>0;apply.Content="备份并应用 "+rows.Length+" 项修改";
   foreach(var row in rows){var content=new StackPanel();content.Children.Add(CompanionControls.Text(row.Group+" · "+row.Label,14));content.Children.Add(CompanionControls.Text("当前："+Friendly(row.Key,row.Before),12));content.Children.Add(CompanionControls.Text("导入后："+Friendly(row.Key,row.After),12));changes.Children.Add(new Border{CornerRadius=new CornerRadius(PetVisuals.SurfaceRadius),BorderThickness=new Thickness(1),BorderBrush=PetPalette.Brush(PetPalette.Line),Padding=new Thickness(12),Margin=new Thickness(0,0,8,10),Child=content});}if(rows.Length==0)changes.Children.Add(CompanionControls.Text("所选范围内没有需要修改的设置。"));
  }
  string Friendly(string key,string value){if(key=="Skin"){var skin=pet.Pets.FirstOrDefault(p=>p.Id==value);return skin==null?value:skin.Name;}return value;}
  void Apply(){try{pet.Save();Warning=pet.ReplacePreferences(Proposed,true);DialogResult=true;}catch(Exception e){MessageBox.Show(this,e.Message,"设置尚未导入");}}
 }
 public sealed partial class PetWindow {
  public bool ReviewPreferenceFile(string file,bool positions){if(new System.IO.FileInfo(file).Length>65536)throw new Exception("设置文件不能超过 64 KB。");var info=PreferenceReview.Parse(System.IO.File.ReadAllText(file));var window=new PreferenceReviewWindow(this,info,positions){Owner=settingsWindow};if(window.ShowDialog()!=true)return false;RefreshSettingsWindow();if(!string.IsNullOrEmpty(window.Warning))MessageBox.Show(settingsWindow,window.Warning,"设置已导入");return true;}
 }
}
