using System;using System.Linq;using System.Reflection;using System.Collections.Generic;
namespace KianaPet {
 public sealed class PreferenceImportInfo {public Config Preferences;public string Version,Scope;public DateTime? ExportedAt;public string[] PresentKeys,UnknownKeys;}
 public sealed class PreferenceDifference {public string Key,Label,Group,Before,After;}
 public static class PreferenceReview {
  public static readonly string[] PositionKeys={"X","Y","HasPosition","MusicX","MusicY","MusicHasPosition","MusicPosition"};
  public static readonly string[] LocalKeys={"LaunchChatGPTOnStart","LaunchMusicOnStart","LinkChatGPT","BackgroundMini","RecoverHotkeyEnabled","RecoverHotkeyModifiers","RecoverHotkeyKey","QuietApps","QuietAppsEnabled","QuietForegroundOnly","RememberLayouts"};
  public static bool Local(string key){return LocalKeys.Contains(key)||PositionKeys.Contains(key);}
  public static PreferenceImportInfo Parse(string text){
   var config=PreferenceTransfer.Import(text);var root=Store.Json.DeserializeObject(text) as Dictionary<string,object>;bool package=root.ContainsKey("Product");var data=package?root["Preferences"] as Dictionary<string,object>:root;
   var keys=data.Keys.Where(k=>k!="Schema").ToArray();var p=package?Store.Json.Deserialize<PreferencePackage>(text):null;
   if(p!=null&&p.IncludedKeys!=null){if(p.IncludedKeys.Length>200||p.IncludedKeys.Any(k=>k==null))throw new Exception("设置包的选项清单无效。");keys=keys.Intersect(p.IncludedKeys).ToArray();}
   if(p!=null&&p.Scope=="common")keys=keys.Where(k=>!Local(k)).ToArray();
   var fields=typeof(Config).GetFields().Select(f=>f.Name).ToArray();return new PreferenceImportInfo{Preferences=config,Version=p==null?"旧格式 / 未记录":p.Version,Scope=p==null?"legacy":p.Scope,ExportedAt=p==null?null:p.ExportedAt,PresentKeys=keys.Intersect(fields).ToArray(),UnknownKeys=keys.Except(fields).ToArray()};
  }
  public static Config Merge(Config current,PreferenceImportInfo incoming,bool local,bool positions){var merged=PreferenceTransfer.Copy(current);foreach(var field in typeof(Config).GetFields())if(incoming.PresentKeys.Contains(field.Name)&&(!LocalKeys.Contains(field.Name)||local)&&(!PositionKeys.Contains(field.Name)||positions))field.SetValue(merged,field.GetValue(incoming.Preferences));merged=PreferenceTransfer.Copy(merged);merged.Validate();return merged;}
  public static PreferenceDifference[] Differences(Config current,Config merged){return typeof(Config).GetFields().Where(f=>f.Name!="Schema"&&Store.Json.Serialize(f.GetValue(current))!=Store.Json.Serialize(f.GetValue(merged))).Select(f=>new PreferenceDifference{Key=f.Name,Label=Label(f.Name),Group=PositionKeys.Contains(f.Name)?"屏幕位置":LocalKeys.Contains(f.Name)?"本机配置":"通用偏好",Before=Value(f.Name,f.GetValue(current)),After=Value(f.Name,f.GetValue(merged))}).OrderBy(d=>d.Group).ThenBy(d=>d.Label).ToArray();}
  static string Value(string key,object value){if(value is bool)return (bool)value?"开启":"关闭";if(value==null)return "未设置";if(value is string[])return ((string[])value).Length==0?"空":string.Join("、",(string[])value);if(value is SongMusicPreference[])return string.Join("\n",((SongMusicPreference[])value).Select(p=>(string.IsNullOrEmpty(p.Title)?p.Id:p.Title)+"："+"平时："+MusicReactions.Label(MusicReactions.SongActionSetting(p,false))+"；副歌："+MusicReactions.Label(MusicReactions.SongActionSetting(p,true))+(p.Start>=0?" · 手动区间 "+PetWindow.TimeText(p.Start)+"–"+(p.End>=0?PetWindow.TimeText(p.End):"待标记"):"")));if(value is ScenePreset[])return string.Join("\n\n",((ScenePreset[])value).Select(s=>s.Name+"\n"+string.Join("；",typeof(ScenePreset).GetFields().Where(f=>f.Name!="Name").Select(f=>Label(f.Name)+"："+Value(f.Name,f.GetValue(s))))));if(key=="RecoverHotkeyKey")return PetHotkey.KeyName(Convert.ToUInt32(value));if(key=="RecoverHotkeyModifiers")return PetHotkey.Format(Convert.ToUInt32(value),0x50).Replace(" + P","");if(key=="MusicReactionMode"||key=="MusicNormalAction"||key=="MusicChorusAction")return MusicReactions.Label((string)value);if(value is string){var v=(string)value;var map=new Dictionary<string,string>{{"icon-name","图标＋应用名"},{"icon-only","只显示图标"},{"leading-icon","左侧大图标＋右侧内容"},{"name-only","纯文字应用名"},{"below","宠物下方"},{"left","宠物左侧"},{"right","宠物右侧"},{"free","自由位置"},{"light","浅色"},{"dark","深色"},{"system","跟随系统"},{"solid","封面纯色"},{"cover-gradient","封面双色渐变"},{"background-gradient","封面与背景渐变"},{"silent","静默"},{"hide","隐藏"},{"quiet","安静陪伴"},{"lively","活泼"},{"occasional","偶尔走动"},{"custom","自定义"}};string translated;return map.TryGetValue(v,out translated)?translated:v;}return Convert.ToString(value,System.Globalization.CultureInfo.InvariantCulture);}
  public static string Label(string key){string[] pairs={"X=宠物横坐标","Y=宠物纵坐标","HasPosition=使用保存的宠物位置","MusicX=音乐栏横坐标","MusicY=音乐栏纵坐标","MusicHasPosition=使用保存的音乐栏位置","RecoverHotkeyEnabled=全局找回快捷键","RecoverHotkeyModifiers=快捷键修饰键","RecoverHotkeyKey=快捷键主键","BackgroundMini=Mini 后台模式","LinkChatGPT=ChatGPT 联动","LockPetPosition=锁定宠物位置","LockMusicPosition=锁定音乐栏位置","SmoothTransitions=平滑动作过渡","WalkProfile=走动方案","WalkSpeed=走动速度","WalkDistanceMin=最短走动距离","WalkDistanceMax=最长走动距离","WalkPauseMin=最短停留时间","WalkPauseMax=最长停留时间","QuietAppsEnabled=按应用免打扰","QuietForegroundOnly=只匹配前台应用","QuietHoursEnabled=定时免打扰","QuietApps=免打扰应用名单","QuietMode=免打扰方式","QuietStart=免打扰开始时间","QuietEnd=免打扰结束时间","TaskNoticesEnabled=本地任务通知","RememberLayouts=记住显示器布局","ResourceSaving=降低后台开销","AmbientActions=空闲互动动作","NoticeBatchSeconds=通知合并等待时间","BackupKeepCount=保留备份数量","MutedNoticeSources=静音的通知来源","MusicEnabled=显示音乐栏","MusicLyrics=显示歌词","MusicPausedCard=暂停时显示音乐栏","Gravity=自动落到屏幕底部","SleepSchedule=按作息休息","IdleSleep=空闲休息","HideFullscreen=全屏时隐藏","Bubbles=显示提示气泡","HoverToolbar=显示 ChatGPT 工具栏","Bedtime=入睡时间","WakeTime=醒来时间","IdleMinutes=空闲休息等待分钟"};foreach(var pair in pairs){int split=pair.IndexOf('=');if(pair.Substring(0,split)==key)return pair.Substring(split+1);}return EditHistory.Label(key);}
 }
}
