using System;using System.IO;using System.Linq;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using Microsoft.Win32;
namespace KianaPet {
 public sealed partial class SettingsWindow {
  void BuildPolish(TabControl tabs,Panel appearance,Panel music,Panel about){
   TitleText(appearance,"界面与互动");var theme=new ComboBox{ItemsSource=new[]{"浅色","深色","跟随系统"},SelectedIndex=Array.IndexOf(new[]{"light","dark","system"},pet.Settings.Theme),Padding=new Thickness(8)};theme.SelectionChanged+=delegate{pet.Settings.Theme=new[]{"light","dark","system"}[Math.Max(0,theme.SelectedIndex)];pet.ApplySettings();RefreshTheme();};appearance.Children.Add(theme);
   AddSlider(appearance,"工具栏大小（独立于宠物）",75,150,pet.Settings.ToolbarPercent,5,delegate(int v){pet.Settings.ToolbarPercent=v;pet.ApplySettings();});Check(appearance,"工具栏跟随音乐栏配色",pet.Settings.ToolbarFollowMusic,delegate(bool v){pet.Settings.ToolbarFollowMusic=v;pet.ApplySettings();});Note(appearance,"跟随音乐页中的纯色 / 渐变样式和配色程度。音乐栏暂时收起时仍保持配色；关闭音乐或失去连接、封面时恢复主题底色。通知角标保留蓝色、绿色等状态色。");Check(appearance,"托盘面板和外部菜单优先显示",pet.Settings.YieldToMenus,delegate(bool v){pet.Settings.YieldToMenus=v;pet.ApplySettings();});Note(appearance,"托盘隐藏图标面板或外部菜单打开时，宠物、工具栏和音乐栏统一排在面板后方，保持原位和显示状态；关闭后恢复置顶。使用面板所在层级，避免不必要地落到普通窗口后面；关闭后自动复核置顶状态。桌宠自己的菜单不受影响。");Check(appearance,"空闲时偶尔眨眼、整理头发、伸懒腰",pet.Settings.AmbientActions,delegate(bool v){pet.Settings.AmbientActions=v;pet.ApplySettings();});Note(appearance,"新增绘制动作优先用于三套 Q 版；普通版复用已有挥手和开心动作。空闲动作间隔约 35–80 秒，避免连续重复；右键也可主动触发。连续触摸会短暂防抖。");
   TitleText(music,"音乐栏尺寸");AddSlider(music,"整体大小（%）",80,150,pet.Settings.MusicScalePercent,5,delegate(int v){pet.Settings.MusicScalePercent=v;pet.ApplySettings();});AddSlider(music,"横向宽度（100% 下的逻辑像素）",200,420,pet.Settings.MusicWidth,2,delegate(int v){pet.Settings.MusicWidth=v;pet.ApplySettings();});Note(music,"整体大小同时调整文字、封面和按钮；横向宽度只改变长度。保持系统 DPI 清晰绘制，歌词开启时自动增加高度，并继续避开宠物和工具栏。");TitleText(music,"封面配色");BuildMusicColorMode(music);Check(music,"音乐栏随封面轻微变化配色",pet.Settings.MusicCoverTint,delegate(bool v){pet.Settings.MusicCoverTint=v;pet.ApplySettings();});AddSlider(music,"配色程度",0,100,pet.Settings.MusicTintStrength,5,delegate(int v){pet.Settings.MusicTintStrength=v;pet.ApplySettings();});Note(music,"0 为中性色，100 为较明显的柔和色调。仅从已加载的封面取色，不额外请求图片；歌名和按钮保持固定的高对比度前景色。切歌时平滑过渡。");
   var scenes=Page(tabs,"场景与维护");TitleText(scenes,"一键切换使用场景");var picker=new ComboBox{ItemsSource=pet.Settings.Scenes.Select(s=>s.Name).ToArray(),SelectedIndex=0,Padding=new Thickness(8)};scenes.Children.Add(picker);scenes.Children.Add(Button("应用所选场景",delegate{pet.ApplyScene(picker.SelectedIndex);},true));var name=TextRow(scenes,"保存当前设置为场景","");scenes.Children.Add(Button("保存 / 覆盖同名场景",delegate{try{pet.SaveScene(name.Text);picker.ItemsSource=pet.Settings.Scenes.Select(s=>s.Name).ToArray();picker.SelectedIndex=pet.Settings.Scenes.Length-1;}catch(Exception e){MessageBox.Show(this,e.Message,"保存场景");}},false));scenes.Children.Add(Button("删除所选场景",delegate{pet.DeleteScene(picker.SelectedIndex);picker.ItemsSource=pet.Settings.Scenes.Select(s=>s.Name).ToArray();picker.SelectedIndex=0;},false));Note(scenes,"方案包含走动节奏、音乐显示、气泡、全屏隐藏、免打扰规则开关和任务通知偏好。服装、位置、快捷键、主题及免打扰应用名单和具体时段保留。场景切换前备份偏好，方案随偏好导出。");
   TitleText(scenes,"位置记忆与后台运行");Check(scenes,"分别记住不同显示器布局的位置",pet.Settings.RememberLayouts,delegate(bool v){pet.Settings.RememberLayouts=v;pet.ApplySettings();});scenes.Children.Add(Button("清除旧显示器布局记忆",delegate{pet.ForgetDisplayLayouts();},false));Check(scenes,"降低隐藏、休息和断线时的后台开销",pet.Settings.ResourceSaving,delegate(bool v){pet.Settings.ResourceSaving=v;pet.ApplySettings();});Note(scenes,"多屏位置记忆只存本机，不随偏好迁移。隐藏时降低动画刷新率；断线后最多间隔 30 秒重试。已连接的 ChatGPT 保持两秒同步，确保后台 Mini 隐藏状态续期。恢复连接可点击“重新检测连接”。");
   TitleText(scenes,"通知节奏");Check(scenes,"普通任务完成静默，仅保留铃铛提示",pet.Settings.NoticeSilentSuccess,delegate(bool v){pet.Settings.NoticeSilentSuccess=v;pet.ApplySettings();});AddSlider(scenes,"短时间通知合并窗口（秒）",2,30,pet.Settings.NoticeBatchSeconds,1,delegate(int v){pet.Settings.NoticeBatchSeconds=v;pet.ApplySettings();});Note(scenes,"失败和等待处理会合并提醒；免打扰或隐藏期间的更新在恢复后汇总。只整理桌宠自己的提示，不改变 ChatGPT 内部通知的已读状态。");
   TitleText(scenes,"更新与恢复");scenes.Children.Add(Button("备份与缓存占用管理",pet.OpenStorageManager,false));scenes.Children.Add(Button("从完整 ZIP 更新程序…",ChooseUpdate,true));scenes.Children.Add(Button("回退到本机程序备份…",ChooseRollback,false));scenes.Children.Add(Button("单独恢复偏好备份…",RestorePreference,false));scenes.Children.Add(Button("预览 / 导出故障诊断",pet.ShowDiagnostics,false));Note(scenes,"更新前显示版本说明并校验 SHA-256，保留本机偏好，退出后自动备份程序并重启。只选择你信任来源的完整安装包；完整性校验不是发布者签名。此处没有自动下载或云同步。");string result=Path.Combine(Store.Root,"update-result.json");if(File.Exists(result))try{Note(scenes,"最近更新结果：\n"+File.ReadAllText(result));}catch{}
  }
  void AddSlider(Panel page,string label,int min,int max,int current,int tick,Action<int> save){var text=new TextBlock{Text=label+"："+current,Margin=new Thickness(0,12,0,8),TextWrapping=TextWrapping.Wrap};page.Children.Add(text);var slider=new Slider{Minimum=min,Maximum=max,Value=current,TickFrequency=tick,IsSnapToTickEnabled=true,Margin=new Thickness(0,0,5,12)};System.Windows.Automation.AutomationProperties.SetName(slider,label);slider.ValueChanged+=delegate{text.Text=label+"："+(int)slider.Value;save((int)slider.Value);};page.Children.Add(slider);}
  async void ChooseUpdate(){var picker=new OpenFileDialog{Filter="完整桌宠安装包 (*.zip)|*.zip",CheckFileExists=true};if(picker.ShowDialog(this)!=true)return;IsEnabled=false;try{var prepared=await Task.Run(()=>Maintenance.PrepareZip(picker.FileName,Path.Combine(Store.Root,"update-cache")));IsEnabled=true;ConfirmUpdate(prepared,null);}catch(Exception e){MessageBox.Show(this,e.Message,"更新包检查失败");}finally{IsEnabled=true;}}
  void ChooseRollback(){var backups=Maintenance.Backups(Store.Root);if(backups.Length==0){MessageBox.Show(this,"还没有可用的受校验程序备份。第一次更新后会自动建立。","程序回退");return;}var dialog=new Window{Background=PetPalette.Brush(PetPalette.Background),Foreground=ink,Title="选择程序备份",Owner=this,Width=520,Height=310,WindowStartupLocation=WindowStartupLocation.CenterOwner};var stack=new StackPanel{Margin=new Thickness(20)};var list=new ComboBox{ItemsSource=backups.Select(p=>Path.GetFileName(p)+" · "+Maintenance.BackupVersion(p)).ToArray(),SelectedIndex=0,Padding=new Thickness(8)};stack.Children.Add(list);Note(stack,"默认只回退程序，保留当前偏好。需要精确恢复时，可选择同时恢复当时的设置。");var settings=new CheckBox{Foreground=ink,Content="同时恢复这份备份的偏好设置",Margin=new Thickness(0,10,0,10)};stack.Children.Add(settings);stack.Children.Add(Button("检查这份备份",delegate{try{string chosen=backups[list.SelectedIndex];var prepared=Maintenance.PrepareRollback(chosen,Store.Root);string preferences=settings.IsChecked==true?Path.Combine(chosen,"settings.json"):null;if(preferences!=null&&!File.Exists(preferences))throw new Exception("这份备份没有偏好设置。");dialog.Close();ConfirmUpdate(prepared,preferences);}catch(Exception e){MessageBox.Show(this,e.Message,"无法回退");}},true));dialog.Content=stack;dialog.ShowDialog();}
  void ConfirmUpdate(PreparedUpdate prepared,string preferences){var dialog=new Window{Background=PetPalette.Brush(PetPalette.Background),Foreground=ink,Title="检查版本变化",Owner=this,Width=650,Height=570,WindowStartupLocation=WindowStartupLocation.CenterOwner};var dock=new DockPanel{Margin=new Thickness(20)};var header=new TextBlock{Text="当前 "+Maintenance.Version+" → "+prepared.Version+"\n"+(preferences==null?"保留当前偏好；程序会先备份，然后重启。":"同时恢复所选备份的偏好设置。"),TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,0,0,15)};DockPanel.SetDock(header,Dock.Top);dock.Children.Add(header);var apply=Button("备份并应用此版本",delegate{try{pet.Save();Maintenance.Launch(prepared,preferences);dialog.Close();pet.Close();}catch(Exception e){MessageBox.Show(dialog,e.Message,"更新未开始");}},true);DockPanel.SetDock(apply,Dock.Bottom);dock.Children.Add(apply);dock.Children.Add(new TextBox{Background=PetPalette.Brush(PetPalette.Background),Foreground=ink,Text=prepared.Notes,IsReadOnly=true,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Padding=new Thickness(10)});dialog.Content=dock;dialog.ShowDialog();}
  void RestorePreference(){var picker=new OpenFileDialog{Filter="偏好备份 (*.json)|*.json",InitialDirectory=Path.Combine(Store.Root,"preference-backups"),CheckFileExists=true};if(picker.ShowDialog(this)!=true)return;try{pet.ReviewPreferenceFile(picker.FileName,false);}catch(Exception e){MessageBox.Show(this,e.Message,"无法恢复偏好");}}
  public void RefreshTheme(){bool dark=PetPalette.IsDark(pet.Settings.Theme);PetPalette.Dark=dark;ink.Color=PetPalette.Ink;muted.Color=PetPalette.Muted;Background=PetPalette.Brush(PetPalette.Hex(dark?"#201F25":"#F8F6FC"));Foreground=ink;RefreshControls(this,dark);RefreshNavigationTheme();}
  void RefreshControls(DependencyObject parent,bool dark){foreach(object value in LogicalTreeHelper.GetChildren(parent)){var child=value as DependencyObject;if(child==null)continue;var check=child as CheckBox;if(check!=null)check.Foreground=ink;var box=child as TextBox;if(box!=null){box.Background=PetPalette.Brush(PetPalette.Background);box.Foreground=ink;box.BorderBrush=PetPalette.Brush(PetPalette.Line);}var button=child as Button;if(button!=null&&button.Background!=purple){button.Background=PetPalette.Brush(PetPalette.Background);button.Foreground=ink;}var combo=child as ComboBox;if(combo!=null)combo.Foreground=Brushes.Black;RefreshControls(child,dark);}}
 }
}



