using System;
using System.IO;
using System.Diagnostics;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
namespace KianaPet {
 public sealed partial class SettingsWindow:Window {
  readonly TextBlock musicStatus=new TextBlock();readonly ComboBox musicPosition=new ComboBox();bool updatingMusicPosition;readonly PetWindow pet;readonly TextBlock status=new TextBlock();readonly TextBlock sizeLabel=new TextBlock();
  readonly System.Collections.Generic.List<Button> outfitButtons=new System.Collections.Generic.List<Button>();
  readonly SolidColorBrush ink=new SolidColorBrush(Color.FromRgb(47,39,63)),muted=new SolidColorBrush(Color.FromRgb(112,103,127)),purple=new SolidColorBrush(Color.FromRgb(120,90,177));
  public SettingsWindow(PetWindow owner){pet=owner;PetVisuals.Apply(this,true);PetVisuals.InstallTooltips(this);Title="琪亚娜的陪伴设置";Width=920;Height=790;MinWidth=760;MinHeight=520;WindowStartupLocation=WindowStartupLocation.CenterScreen;Background=new SolidColorBrush(Color.FromRgb(248,246,252));FontFamily=new FontFamily("Microsoft YaHei UI");FontSize=13;Foreground=ink;
   Grid root=new Grid{Margin=new Thickness(24)};root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});root.RowDefinitions.Add(new RowDefinition());root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
   StackPanel header=new StackPanel();header.Children.Add(new TextBlock{Text="琪亚娜的陪伴设置",FontSize=25,FontWeight=FontWeights.SemiBold});header.Children.Add(new TextBlock{Text="六套衣装 · 一直在桌面陪你",Foreground=muted,Margin=new Thickness(0,6,0,20)});root.Children.Add(header);
   TabControl tabs=new TabControl{Background=Brushes.Transparent,BorderThickness=new Thickness(0)};Grid.SetRow(tabs,1);root.Children.Add(tabs);
   StackPanel appearance=Page(tabs,"外观与互动");TitleText(appearance,"今天穿哪一套？");WrapPanel outfits=new WrapPanel();foreach(PetInfo info in pet.Pets){string id=info.Id;Button b=Button(info.Name,delegate{pet.SelectSkin(id);},id==pet.Settings.Skin);b.Tag=id;outfitButtons.Add(b);b.Width=255;b.Margin=new Thickness(0,0,10,10);outfits.Children.Add(b);}appearance.Children.Add(outfits);
   TitleText(appearance,"宠物大小");sizeLabel.Text=pet.Settings.Size+" 像素（逻辑尺寸）";sizeLabel.Foreground=muted;appearance.Children.Add(sizeLabel);Slider size=new Slider{Minimum=96,Maximum=320,Value=pet.Settings.Size,TickFrequency=8,IsSnapToTickEnabled=true,Margin=new Thickness(0,10,5,12)};size.ValueChanged+=delegate{pet.Settings.Size=(int)size.Value;sizeLabel.Text=pet.Settings.Size+" 像素（逻辑尺寸）";pet.ApplySettings();};appearance.Children.Add(size);
   Check(appearance,"启用底部 ChatGPT 工具栏",pet.Settings.HoverToolbar,delegate(bool v){pet.Settings.HoverToolbar=v;pet.ApplySettings();});
   Check(appearance,"工具栏常驻（关闭后仅悬停显示）",pet.Settings.ToolbarPinned,pet.SetToolbarPinned);
   Check(appearance,"显示互动气泡",pet.Settings.Bubbles,delegate(bool v){pet.Settings.Bubbles=v;pet.ApplySettings();});
   Note(appearance,"轻点头部：摸头回应\n轻点脸部：戳脸回应\n双击：打招呼\n按住拖动：移动位置，松手后轻轻落地\n右键：换装、休息、穿透、隐藏与退出");
   StackPanel life=Page(tabs,"活动与作息");TitleText(life,"桌面活动");Check(life,"空闲时自由走动（同向两次后优先反向）",pet.Settings.Walking,delegate(bool v){pet.Settings.Walking=v;pet.ApplySettings();});Check(life,"松手后落到屏幕底部",pet.Settings.Gravity,delegate(bool v){pet.Settings.Gravity=v;pet.ApplySettings();});Check(life,"当前屏幕有全屏应用时自动隐藏",pet.Settings.HideFullscreen,delegate(bool v){pet.Settings.HideFullscreen=v;pet.ApplySettings();});
   TitleText(life,"日常作息");Check(life,"按下面的时间休息",pet.Settings.SleepSchedule,delegate(bool v){pet.Settings.SleepSchedule=v;pet.ApplySettings();});StackPanel times=new StackPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(0,7,0,8)};times.Children.Add(new TextBlock{Text="入睡",VerticalAlignment=VerticalAlignment.Center});TextBox bed=Input(pet.Settings.Bedtime);times.Children.Add(bed);times.Children.Add(new TextBlock{Text="醒来",VerticalAlignment=VerticalAlignment.Center});TextBox wake=Input(pet.Settings.WakeTime);times.Children.Add(wake);times.Children.Add(Button("保存时间",delegate{TimeSpan a,b;if(!TimeSpan.TryParse(bed.Text,out a)||!TimeSpan.TryParse(wake.Text,out b)||a.TotalHours<0||a.TotalHours>=24||b.TotalHours<0||b.TotalHours>=24){MessageBox.Show(this,"请输入 00:00 到 23:59 的时间。","时间格式");return;}pet.Settings.Bedtime=a.ToString(@"hh\:mm");pet.Settings.WakeTime=b.ToString(@"hh\:mm");pet.ApplySettings();pet.Say("作息记好啦。",3);},false));life.Children.Add(times);
   Check(life,"电脑长时间没有操作时打盹",pet.Settings.IdleSleep,delegate(bool v){pet.Settings.IdleSleep=v;pet.ApplySettings();});StackPanel idle=new StackPanel{Orientation=Orientation.Horizontal};idle.Children.Add(new TextBlock{Text="闲置分钟数",VerticalAlignment=VerticalAlignment.Center});TextBox minutes=Input(pet.Settings.IdleMinutes.ToString());idle.Children.Add(minutes);idle.Children.Add(Button("保存",delegate{int n;if(!int.TryParse(minutes.Text,out n)||n<1||n>120){MessageBox.Show(this,"请输入 1–120 分钟。","闲置时间");return;}pet.Settings.IdleMinutes=n;pet.ApplySettings();},false));life.Children.Add(idle);
   Note(life,"点击睡着的宠物会暂时唤醒。右键“醒来陪我”可陪伴 30 分钟。三套圆润 Q 版有新增的侧卧呼吸动画；普通版使用闭眼休息姿态。\n全屏退出后会自动恢复；双击托盘图标可以找回宠物，也可在“快捷键”页自定义。");
   BuildComfortPages(tabs);BuildHotkeyPage(tabs);
   StackPanel link=Page(tabs,"ChatGPT 联动");TitleText(link,"独立运行，按需联动");Check(link,"读取 ChatGPT 的任务状态",pet.Settings.LinkChatGPT,delegate(bool v){pet.Settings.LinkChatGPT=v;pet.ApplySettings();});Check(link,"Mini 后台运行（桌面只显示独立桌宠）",pet.Settings.BackgroundMini,delegate(bool v){pet.Settings.BackgroundMini=v;pet.ApplySettings();});status.TextWrapping=TextWrapping.Wrap;status.Foreground=purple;status.Margin=new Thickness(0,12,0,12);link.Children.Add(status);connectionHint.TextWrapping=TextWrapping.Wrap;connectionHint.Foreground=muted;link.Children.Add(connectionHint);link.Children.Add(Button("检查并修复联动",pet.RepairChatGPT,false));
   Note(link,"点击下方“打开 ChatGPT”后，后台模式会自动准备 Mini，收起原生宠物和闲置工具栏。桌面只显示独立桌宠，优先同步原 Mini 通知；Mini 没有角标时，补充读取主窗口已加载的本机任务状态。\n点击独立桌宠的聊天、语音或通知按钮时，按需展开原生面板；按 Esc 或离开面板焦点后收起。收起界面不会结束正在进行的语音。\n关闭后台模式或退出独立桌宠后，原 Mini 外观会恢复；异常退出时约 10 秒后自动恢复。此模式仍依赖 Mini 后台页面，不读取聊天正文；任务标题仅用于通知菜单，不写入诊断状态文件。首次准备时可能短暂看到 Mini。");
   link.Children.Add(Button("打开 ChatGPT",LaunchChatGPT,true));link.Children.Add(Button("打开运行记录目录",delegate{Process.Start("explorer.exe",Store.Root);},false));TitleText(link,"为未来预留");Note(link,"AI 对话接口已预留，当前没有接入模型、保存密钥或发送 AI 请求。后续可以增加对话服务，而不改变现有桌面功能。");
   StackPanel music=Page(tabs,"音乐");TitleText(music,"网易云音乐小卡片");Check(music,"显示音乐栏",pet.Settings.MusicEnabled,delegate(bool v){pet.Settings.MusicEnabled=v;pet.ApplySettings();});Check(music,"暂停时保留音乐卡片",pet.Settings.MusicPausedCard,delegate(bool v){pet.Settings.MusicPausedCard=v;pet.ApplySettings();});Check(music,"显示同步歌词",pet.Settings.MusicLyrics,delegate(bool v){pet.Settings.MusicLyrics=v;pet.ApplySettings();});Check(music,"音乐栏常驻（关闭后仅悬停显示）",!pet.Settings.MusicHoverOnly,pet.SetMusicPinned);TitleText(music,"音乐栏位置");musicPosition.ItemsSource=new[]{"宠物下方（不足时自动避让）","宠物左侧","宠物右侧","手动固定位置"};musicPosition.SelectedIndex=Array.IndexOf(new[]{"below","left","right","free"},pet.Settings.MusicPosition);musicPosition.Margin=new Thickness(0,0,0,8);musicPosition.Padding=new Thickness(8,5,8,5);musicPosition.SelectionChanged+=delegate{if(!updatingMusicPosition&&musicPosition.SelectedIndex>=0)pet.SetMusicPosition(new[]{"below","left","right","free"}[musicPosition.SelectedIndex]);};music.Children.Add(musicPosition);BuildDefaultMusicDock(music);Note(music,"常驻时，工具栏收起后音乐栏贴近宠物下方；工具栏出现时平滑让位。工具栏可在“外观与互动”单独设为常驻。\n按住封面或歌名拖动音乐栏，松手后固定在桌面并记住位置。自动布局和拖动结束时都会避开本桌宠的 ChatGPT 按钮栏。下方空间不足会移到侧边。悬停显示时，移入音乐栏可继续操作，离开后稍作停留再收起。");musicStatus.TextWrapping=TextWrapping.Wrap;musicStatus.Margin=new Thickness(0,12,0,12);music.Children.Add(musicStatus);music.Children.Add(Button("连接网易云音乐",pet.LaunchMusic,true));Note(music,"点击上方“连接网易云音乐”打开客户端，也可使用右键菜单 → 音乐与工具栏 → 连接网易云音乐。若已普通启动，请从网易云托盘退出；连接窗口会等待并重新启动。\n\n歌曲、歌手、暂停状态与进度来自当前播放器。按钮只在点击时控制网易云音乐。歌词默认关闭，打开后按当前歌曲 ID 向网易云请求歌词；无可用歌词时显示提示。\n\n音乐栏跟随宠物，全屏或隐藏宠物时一同隐藏。鼠标移入音乐栏时，宠物会暂停走动。客户端版本变更可能需要更新适配。客户端退出后，音乐栏自动收起。");
   StackPanel about=Page(tabs,"使用说明");TitleText(about,"琪亚娜独立桌宠 "+Maintenance.Version);Note(about,"独立的 Windows 桌宠，使用六套既有同人素材。图像按平滑采样绘制。\n\n程序与设置保存在安装时选择的运行数据目录，不依赖 ChatGPT 的私有 AppData。退出本桌宠不会关闭 ChatGPT。\n\n拖动可跨屏；自由走动与全屏隐藏以宠物所在屏幕为准。关闭“落到屏幕底部”可将宠物停在任意位置。\n\n目前支持屏幕底部活动，没有实现坐在任意应用窗口边缘。\n\n三套圆润 Q 版已补充摸头回应、悬空摆腿、侧卧呼吸，共 18 张绘制关键姿态。普通三套仍复用现有动作。");about.Children.Add(Button("打开中文说明",delegate{string p=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"README.md");if(File.Exists(p))Process.Start("notepad.exe","\""+p+"\"");},false));
   BuildTransfer(about);BuildTaskInterface(about);BuildPolish(tabs,appearance,music,about);
   StackPanel footer=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right,Margin=new Thickness(0,14,0,0)};footer.Children.Add(Button("找回宠物",pet.Recover,false));footer.Children.Add(Button("完成",Close,true));Grid.SetRow(footer,2);root.Children.Add(footer);BuildNavigation(root,tabs,header,footer);Content=root;RefreshTheme();UpdateStatus();
  }
  StackPanel Page(TabControl tabs,string name){StackPanel p=new StackPanel{Margin=new Thickness(14,18,14,10)};System.Windows.Documents.TextElement.SetForeground(p,ink);ScrollViewer sc=new ScrollViewer{Content=p,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};tabs.Items.Add(new TabItem{Header=name,Foreground=Brushes.Black,Content=sc,Padding=new Thickness(12,8,12,8)});return p;}
  void TitleText(Panel p,string text){p.Children.Add(new TextBlock{Text=text,FontSize=16,FontWeight=FontWeights.SemiBold,Margin=new Thickness(0,12,0,12)});}
  void Note(Panel p,string text){p.Children.Add(new TextBlock{Text=text,TextWrapping=TextWrapping.Wrap,Foreground=muted,LineHeight=24,Margin=new Thickness(0,9,0,10)});}
  void Check(Panel p,string text,bool initial,Action<bool> save){CheckBox c=new CheckBox{Content=text,IsChecked=initial,Margin=new Thickness(0,7,0,7)};c.Checked+=delegate{if(!syncingCommon)save(true);};c.Unchecked+=delegate{if(!syncingCommon)save(false);};p.Children.Add(c);}
  TextBox Input(string text){return new TextBox{Text=text,Width=65,Margin=new Thickness(8,0,12,0),Padding=new Thickness(5),VerticalContentAlignment=VerticalAlignment.Center};}
  Button Button(string text,Action action,bool primary){Button b=new Button{Content=text,Padding=new Thickness(14,9,14,9),Margin=new Thickness(0,5,8,5),Background=primary?purple:Brushes.White,Foreground=primary?Brushes.White:ink,BorderBrush=new SolidColorBrush(Color.FromRgb(224,216,235)),BorderThickness=new Thickness(1),Cursor=System.Windows.Input.Cursors.Hand};PetVisuals.RoundButton(b);System.Windows.Automation.AutomationProperties.SetName(b,text);b.Click+=delegate{action();};return b;}
  public void UpdateStatus(){startupStatusText.Text=pet.StartupStatus??"两个启动选项默认关闭";UpdateNavigation();RefreshMusicColorPreview();quietStatus.Text=pet.QuietStatus;connectionHint.Text=LinkHealth.Read(pet.Link.Current,pet.Settings.LinkChatGPT,DateTime.UtcNow).Summary+"\n\n"+pet.Link.Current.Hint+"\nMini："+BridgeDiagnostics.ChannelName(pet.Link.Current.MiniStatus)+" · 主窗口："+BridgeDiagnostics.ChannelName(pet.Link.Current.MainStatus)+(pet.Link.Current.LastSuccessAt.HasValue?"\n上次成功连接："+pet.Link.Current.LastSuccessAt.Value.ToLocalTime().ToString("HH:mm:ss"):"");hotkeyStatus.Text=pet.HotkeyStatus;status.Text=pet.StatusText;musicStatus.Text=pet.MusicStatus;updatingMusicPosition=true;musicPosition.SelectedIndex=Array.IndexOf(new[]{"below","left","right","free"},pet.Settings.MusicPosition);updatingMusicPosition=false;foreach(Button b in outfitButtons){bool chosen=(string)b.Tag==pet.Settings.Skin;b.Background=chosen?purple:PetPalette.Brush(PetPalette.Background);b.Foreground=chosen?Brushes.White:ink;}}
  public void Capture(string path){UpdateLayout();var bitmap=new System.Windows.Media.Imaging.RenderTargetBitmap((int)ActualWidth,(int)ActualHeight,96,96,PixelFormats.Pbgra32);bitmap.Render(this);var encoder=new System.Windows.Media.Imaging.PngBitmapEncoder();encoder.Frames.Add(System.Windows.Media.Imaging.BitmapFrame.Create(bitmap));using(var stream=File.Create(path)){encoder.Save(stream);}}
  void LaunchChatGPT(){pet.LaunchChatGPT();}
 }
}


