using System;using System.Linq;using System.Windows;using System.Windows.Controls;using System.Windows.Media;
namespace KianaPet {
 public sealed partial class SettingsWindow {
  readonly TextBlock quietStatus=new TextBlock(),connectionHint=new TextBlock();
  void BuildComfortPages(TabControl tabs){
   StackPanel page=Page(tabs,"体验");TitleText(page,"走动节奏");
   ComboBox profile=new ComboBox{ItemsSource=new[]{"安静陪伴","偶尔活动","活泼","自定义"},SelectedIndex=Array.IndexOf(new[]{"quiet","occasional","lively","custom"},pet.Settings.WalkProfile),Padding=new Thickness(8,5,8,5)};page.Children.Add(profile);
   TextBox speed=NumberRow(page,"速度（逻辑像素 / 秒，10–120）",pet.Settings.WalkSpeed),distanceMin=NumberRow(page,"最短距离（20–500）",pet.Settings.WalkDistanceMin),distanceMax=NumberRow(page,"最长距离（最短距离–600）",pet.Settings.WalkDistanceMax),pauseMin=NumberRow(page,"最短休息（秒，5–600）",pet.Settings.WalkPauseMin),pauseMax=NumberRow(page,"最长休息（秒，最短休息–900）",pet.Settings.WalkPauseMax);
   profile.SelectionChanged+=delegate{if(profile.SelectedIndex<0||profile.SelectedIndex==3)return;var c=PreferenceTransfer.Copy(pet.Settings);ComfortRules.Preset(c,new[]{"quiet","occasional","lively"}[profile.SelectedIndex]);speed.Text=c.WalkSpeed.ToString();distanceMin.Text=c.WalkDistanceMin.ToString();distanceMax.Text=c.WalkDistanceMax.ToString();pauseMin.Text=c.WalkPauseMin.ToString();pauseMax.Text=c.WalkPauseMax.ToString();};
   var feedback=new TextBlock{TextWrapping=TextWrapping.Wrap,Foreground=purple};
   page.Children.Add(Button("保存走动节奏",delegate{int a,b,c,d,e;if(!int.TryParse(speed.Text,out a)||!int.TryParse(distanceMin.Text,out b)||!int.TryParse(distanceMax.Text,out c)||!int.TryParse(pauseMin.Text,out d)||!int.TryParse(pauseMax.Text,out e)||a<10||a>120||b<20||b>500||c<b||c>600||d<5||d>600||e<d||e>900){feedback.Text="请按标注范围填写，最长值不能小于最短值。";return;}pet.Settings.WalkSpeed=a;pet.Settings.WalkDistanceMin=b;pet.Settings.WalkDistanceMax=c;pet.Settings.WalkPauseMin=d;pet.Settings.WalkPauseMax=e;var preset=PreferenceTransfer.Copy(pet.Settings);ComfortRules.Preset(preset,profile.SelectedIndex>=0&&profile.SelectedIndex<3?new[]{"quiet","occasional","lively"}[profile.SelectedIndex]:"occasional");pet.Settings.WalkProfile=preset.WalkSpeed==a&&preset.WalkDistanceMin==b&&preset.WalkDistanceMax==c&&preset.WalkPauseMin==d&&preset.WalkPauseMax==e?preset.WalkProfile:"custom";pet.ApplySettings();feedback.Text="已保存，下一次走动使用新的节奏。";},true));page.Children.Add(feedback);
   Note(page,"先在“活动与作息”开启自由走动。连续同向两次后优先反向，边缘避让优先。起跑与停下逐渐变速；不同帧率和显示缩放下保持一致的逻辑速度。");
   TitleText(page,"防误操作与动画");Check(page,"锁定宠物位置（仍可触摸，停止拖动、走动和落地）",pet.Settings.LockPetPosition,delegate(bool v){pet.Settings.LockPetPosition=v;pet.ApplySettings();});Check(page,"锁定音乐栏拖动（保留跟随与自动避让）",pet.Settings.LockMusicPosition,delegate(bool v){pet.Settings.LockMusicPosition=v;pet.ApplySettings();});Check(page,"动作切换时使用轻微淡入",pet.Settings.SmoothTransitions,delegate(bool v){pet.Settings.SmoothTransitions=v;pet.ApplySettings();});Note(page,"锁定不影响“找回宠物”和显示器断开后的自动位置修正。位置支持左侧、上方副屏的负坐标。");
   StackPanel quiet=Page(tabs,"免打扰");TitleText(quiet,"暂时安静一下");quiet.Children.Add(Button("开启 / 关闭临时免打扰",pet.ToggleQuiet,true));quietStatus.TextWrapping=TextWrapping.Wrap;quietStatus.Foreground=purple;quiet.Children.Add(quietStatus);
   ComboBox mode=new ComboBox{ItemsSource=new[]{"保持显示，停止走动与气泡","隐藏桌宠和音乐栏"},SelectedIndex=pet.Settings.QuietMode=="hide"?1:0,Padding=new Thickness(8),Margin=new Thickness(0,12,0,10)};mode.SelectionChanged+=delegate{pet.Settings.QuietMode=mode.SelectedIndex==1?"hide":"silent";pet.ApplySettings();};quiet.Children.Add(mode);
   Check(quiet,"指定应用触发免打扰",pet.Settings.QuietAppsEnabled,delegate(bool v){pet.Settings.QuietAppsEnabled=v;pet.ApplySettings();});Check(quiet,"只在指定应用处于前台时触发",pet.Settings.QuietForegroundOnly,delegate(bool v){pet.Settings.QuietForegroundOnly=v;pet.ApplySettings();});
   TextBox apps=new TextBox{Text=string.Join(Environment.NewLine,pet.Settings.QuietApps),AcceptsReturn=true,Height=82,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Padding=new Thickness(8)};quiet.Children.Add(apps);quiet.Children.Add(Button("保存应用列表",delegate{pet.Settings.QuietApps=ComfortRules.NormalizeApps(new[]{apps.Text});apps.Text=string.Join(Environment.NewLine,pet.Settings.QuietApps);pet.ApplySettings();},false));Note(quiet,"每行填一个进程名，例如 obs64.exe、Teams.exe。可从任务管理器“详细信息”查看；不填写完整路径。取消“只在前台”后，应用运行即触发，不代表已开始录制或开会。");
   Check(quiet,"每天在指定时段免打扰",pet.Settings.QuietHoursEnabled,delegate(bool v){pet.Settings.QuietHoursEnabled=v;pet.ApplySettings();});TextBox start=TextRow(quiet,"开始时间",pet.Settings.QuietStart),end=TextRow(quiet,"结束时间",pet.Settings.QuietEnd);quiet.Children.Add(Button("保存免打扰时段",delegate{TimeSpan a,b;if(!TimeSpan.TryParse(start.Text,out a)||!TimeSpan.TryParse(end.Text,out b)||a.TotalHours<0||a.TotalHours>=24||b.TotalHours<0||b.TotalHours>=24){MessageBox.Show(this,"请输入 00:00–23:59。","时间格式");return;}pet.Settings.QuietStart=a.ToString(@"hh\:mm");pet.Settings.QuietEnd=b.ToString(@"hh\:mm");pet.ApplySettings();},false));Note(quiet,"支持跨午夜。开始与结束相同时不触发。临时免打扰仅本次运行有效；规则触发期间关闭临时开关不会取消规则。全屏隐藏仍由“活动与作息”控制。");
  }
  TextBox NumberRow(Panel page,string label,int value){return TextRow(page,label,value.ToString());}
  TextBox TextRow(Panel page,string label,string value){Grid row=new Grid{Margin=new Thickness(0,7,0,4)};row.ColumnDefinitions.Add(new ColumnDefinition());row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(90)});row.Children.Add(new TextBlock{Text=label,VerticalAlignment=VerticalAlignment.Center,TextWrapping=TextWrapping.Wrap});var box=new TextBox{Text=value,Padding=new Thickness(6)};Grid.SetColumn(box,1);row.Children.Add(box);page.Children.Add(row);return box;}
  void BuildTransfer(Panel page){TitleText(page,"双设备偏好与备份");page.Children.Add(Button("导出通用偏好（适合另一台电脑）",delegate{pet.ExportPreferences(false);},false));page.Children.Add(Button("导出完整偏好备份（含本机配置）",delegate{pet.ExportPreferences(true);},false));page.Children.Add(Button("导入并预览差异…",delegate{pet.ImportPreferences(false);},true));page.Children.Add(Button("恢复默认设置",pet.ResetPreferences,false));Note(page,"导入先展示当前值与导入后值，默认保留本机启动选项、快捷键、联动方式、应用名单和位置；可单独选择导入本机配置或位置。包内没有的选项保留当前值。应用前自动备份，取消不改变设置。\n两台电脑各自安装完整新版程序，再导入通用偏好。程序路径、连接会话和显示布局记忆始终独立，不进行后台云同步。");}
  void BuildTaskInterface(Panel page){TitleText(page,"任务完成通知接口（预留）");Check(page,"显示本地任务通知",pet.Settings.TaskNoticesEnabled,delegate(bool v){pet.Settings.TaskNoticesEnabled=v;pet.ApplySettings();});page.Children.Add(Button("测试一条示例通知",pet.TestTaskNotice,false));Note(page,"接口已预留，尚未连接其他软件，也没有开放网络端口。示例通知可在宠物铃铛里查看并标记已读；重启后清空。接入约定见中文说明。");}
 }
}
