using System;using System.Linq;using System.Collections.Generic;using System.Windows;using System.Windows.Controls;using System.Windows.Controls.Primitives;using System.Windows.Input;using System.Windows.Media;using System.Windows.Data;
namespace KianaPet {
 public sealed partial class SettingsWindow {
  TabControl settingsTabs;ListBox categoryList;TextBox settingsSearch;TextBlock searchEmpty;Button undoButton;StackPanel recentPage;int recentRevision=-1;bool navigating,syncingCommon;CheckBox commonWalking,commonMusic,commonLock;
  public string ActiveCategory{get{return settingsTabs==null||settingsTabs.SelectedItem==null?"常用":Convert.ToString(((TabItem)settingsTabs.SelectedItem).Header);}}
  public string SearchQuery{get{return settingsSearch==null?"":settingsSearch.Text;}}
  void BuildNavigation(Grid root,TabControl tabs,StackPanel header,StackPanel footer){settingsTabs=tabs;
   StackPanel common=Page(tabs,"常用");TitleText(common,"常用操作");Note(common,"偏好自动保存。调整后 90 秒内可以撤销；键盘可用 Tab 切换控件，Ctrl+F 搜索。");Check(common,"空闲时自由走动",pet.Settings.Walking,delegate(bool v){pet.Settings.Walking=v;pet.ApplySettings();});Check(common,"显示音乐栏",pet.Settings.MusicEnabled,delegate(bool v){pet.Settings.MusicEnabled=v;pet.ApplySettings();});Check(common,"锁定宠物位置",pet.Settings.LockPetPosition,delegate(bool v){pet.Settings.LockPetPosition=v;pet.ApplySettings();});commonWalking=(CheckBox)common.Children[2];commonMusic=(CheckBox)common.Children[3];commonLock=(CheckBox)common.Children[4];common.Children.Add(Button("换装、大小与主题",delegate{NavigateCategory("外观与互动","");},true));common.Children.Add(Button("音乐、歌词与配色",delegate{NavigateCategory("音乐","");},false));common.Children.Add(Button("打开通知中心",pet.OpenNoticeCenter,false));common.Children.Add(Button("键盘操作桌宠工具栏",pet.FocusToolbar,false));common.Children.Add(Button("备份与缓存管理",pet.OpenStorageManager,false));var first=tabs.Items[tabs.Items.Count-1];tabs.Items.Remove(first);tabs.Items.Insert(0,first);
   recentPage=Page(tabs,"最近调整");BuildAccessibility(tabs);BuildNoticeSettings(tabs);BuildStartupPage(tabs);BuildEffectPreviewPage(tabs);
   var presenter=new FrameworkElementFactory(typeof(ContentPresenter));presenter.Name="PART_SelectedContentHost";presenter.SetValue(ContentPresenter.ContentSourceProperty,"SelectedContent");tabs.Template=new ControlTemplate(typeof(TabControl)){VisualTree=presenter};tabs.SelectedIndex=0;
   root.Children.Remove(tabs);var body=new Grid();body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(164)});body.ColumnDefinitions.Add(new ColumnDefinition());Grid.SetRow(body,1);root.Children.Add(body);
   categoryList=new ListBox{BorderThickness=new Thickness(0),Background=Brushes.Transparent,Margin=new Thickness(0,12,14,0),HorizontalContentAlignment=HorizontalAlignment.Stretch};ScrollViewer.SetHorizontalScrollBarVisibility(categoryList,ScrollBarVisibility.Disabled);body.Children.Add(categoryList);Grid.SetColumn(tabs,1);body.Children.Add(tabs);searchEmpty=new TextBlock{Text="没有找到匹配设置，试试“音乐”“快捷键”或“免打扰”。",TextWrapping=TextWrapping.Wrap,Margin=new Thickness(20),Visibility=Visibility.Collapsed,Foreground=muted};Grid.SetColumn(searchEmpty,1);body.Children.Add(searchEmpty);
   header.Children.Add(new TextBlock{Text="搜索设置（Ctrl+F）",Foreground=muted,FontSize=12,Margin=new Thickness(0,0,0,6)});settingsSearch=new TextBox{Padding=new Thickness(10,7,10,7),Margin=new Thickness(0,0,0,10),MaxLength=80};System.Windows.Automation.AutomationProperties.SetName(settingsSearch,"搜索设置");header.Children.Add(settingsSearch);settingsSearch.TextChanged+=delegate{RefreshSearch();};categoryList.SelectionChanged+=delegate{if(navigating)return;var item=categoryList.SelectedItem as ListBoxItem;if(item!=null)tabs.SelectedItem=item.Tag;};
   undoButton=Button("暂无可撤销的调整",pet.UndoLastEdit,false);footer.Children.Insert(0,undoButton);PreviewKeyDown+=delegate(object sender,KeyEventArgs e){if(e.Key==Key.F&&Keyboard.Modifiers==ModifierKeys.Control){settingsSearch.Focus();settingsSearch.SelectAll();e.Handled=true;}else if(e.Key==Key.Escape){if(settingsSearch.Text.Length>0)settingsSearch.Clear();else Close();e.Handled=true;}else if(e.Key==Key.F7){pet.FocusMusicControls();e.Handled=true;}else if(e.Key==Key.F6){pet.FocusToolbar();e.Handled=true;}};
   RefreshNavigationTheme();RefreshRecent();RefreshSearch();
  }
  public void NavigateCategory(string category,string query){if(settingsTabs==null)return;settingsSearch.Text=query??"";RefreshSearch();var item=categoryList.Items.OfType<ListBoxItem>().FirstOrDefault(x=>(string)((TabItem)x.Tag).Header==category);if(item!=null){categoryList.SelectedItem=item;categoryList.ScrollIntoView(item);((ScrollViewer)((TabItem)item.Tag).Content).ScrollToTop();}}
  static string SearchText(object value){if(value==null)return "";var label=value as TextBlock;if(label!=null)return label.Text;var header=value as HeaderedContentControl;if(header!=null)return Convert.ToString(header.Header)+" "+SearchText(header.Content);var content=value as ContentControl;if(content!=null)return SearchText(content.Content);var panel=value as Panel;if(panel!=null)return string.Join(" ",panel.Children.Cast<UIElement>().Select(SearchText));var combo=value as ComboBox;if(combo!=null&&combo.ItemsSource!=null)return string.Join(" ",combo.ItemsSource.Cast<object>().Select(Convert.ToString));if(value is string)return (string)value;return "";}
  static List<List<UIElement>> Sections(StackPanel page){var groups=new List<List<UIElement>>();foreach(UIElement element in page.Children){var text=element as TextBlock;if(groups.Count==0||text!=null&&text.FontSize>=16)groups.Add(new List<UIElement>());groups[groups.Count-1].Add(element);}return groups;}
  public static bool Matches(string haystack,string query){return (haystack??"").IndexOf((query??"").Trim(),StringComparison.OrdinalIgnoreCase)>=0;}
  void RefreshSearch(){if(categoryList==null)return;string query=settingsSearch.Text.Trim(),selected=ActiveCategory;navigating=true;categoryList.Items.Clear();foreach(TabItem tab in settingsTabs.Items){var page=(StackPanel)((ScrollViewer)tab.Content).Content;bool categoryMatch=Matches((string)tab.Header,query),any=false;foreach(var group in Sections(page)){bool show=categoryMatch||Matches(string.Join(" ",group.Select(SearchText)),query);foreach(var element in group)element.Visibility=show?Visibility.Visible:Visibility.Collapsed;any|=show;}if(any)categoryList.Items.Add(new ListBoxItem{Content=tab.Header,Tag=tab,Padding=new Thickness(11,10,11,10),Margin=new Thickness(0,2,0,2)});}var choice=categoryList.Items.OfType<ListBoxItem>().FirstOrDefault(i=>(string)((TabItem)i.Tag).Header==query)??categoryList.Items.OfType<ListBoxItem>().FirstOrDefault(i=>(string)((TabItem)i.Tag).Header==selected)??categoryList.Items.OfType<ListBoxItem>().FirstOrDefault();categoryList.SelectedItem=choice;if(choice!=null)settingsTabs.SelectedItem=choice.Tag;settingsTabs.Visibility=choice==null?Visibility.Collapsed:Visibility.Visible;searchEmpty.Visibility=choice==null?Visibility.Visible:Visibility.Collapsed;navigating=false;}
  void RefreshRecent(){if(recentPage==null||recentRevision==pet.Edits.Revision)return;recentRevision=pet.Edits.Revision;recentPage.Children.Clear();TitleText(recentPage,"最近调整");Note(recentPage,"这里记录调整过的选项，点击可以回到对应分类。记录不包含设置值；撤销只在本次运行的短时间内可用。");if(pet.Edits.Recent.Count==0)Note(recentPage,"还没有调整记录。");foreach(var entry in pet.Edits.Recent){var saved=entry;recentPage.Children.Add(Button(entry.At.ToLocalTime().ToString("MM-dd HH:mm")+"  "+entry.Label,delegate{NavigateCategory(saved.Category,"");},false));}RefreshSearch();}
  void UpdateNavigation(){syncingCommon=true;try{if(commonWalking!=null){commonWalking.IsChecked=pet.Settings.Walking;commonMusic.IsChecked=pet.Settings.MusicEnabled;commonLock.IsChecked=pet.Settings.LockPetPosition;foreach(TabItem tab in settingsTabs.Items){var page=(StackPanel)((ScrollViewer)tab.Content).Content;foreach(var check in page.Children.OfType<CheckBox>()){string text=check.Content as string;if(text=="工具栏常驻（关闭后仅悬停显示）")check.IsChecked=pet.Settings.ToolbarPinned;else if(text=="启用底部 ChatGPT 工具栏")check.IsChecked=pet.Settings.HoverToolbar;else if(text=="音乐栏常驻（关闭后仅悬停显示）")check.IsChecked=!pet.Settings.MusicHoverOnly;else if(text=="显示音乐栏")check.IsChecked=pet.Settings.MusicEnabled;else if(text!=null&&text.StartsWith("空闲时自由走动"))check.IsChecked=pet.Settings.Walking;else if(text=="锁定宠物位置")check.IsChecked=pet.Settings.LockPetPosition;}}}}finally{syncingCommon=false;}if(undoButton!=null){var entry=pet.PendingUndo;undoButton.IsEnabled=entry!=null;undoButton.Content=entry==null?"暂无可撤销的调整":"撤销："+entry.Label;undoButton.ToolTip=entry==null?"调整后 90 秒内可撤销":"撤销最近一次调整，保留当前屏幕位置";}RefreshRecent();}
  void RefreshNavigationTheme(){if(categoryList==null)return;categoryList.Foreground=ink;var style=new Style(typeof(ListBoxItem));style.Setters.Add(new Setter(Control.ForegroundProperty,ink.Clone()));style.Setters.Add(new Setter(Control.BackgroundProperty,Brushes.Transparent));var border=new FrameworkElementFactory(typeof(Border));border.SetValue(Border.CornerRadiusProperty,new CornerRadius(9));border.SetBinding(Border.BackgroundProperty,new Binding("Background"){RelativeSource=new RelativeSource(RelativeSourceMode.TemplatedParent)});border.SetBinding(Border.PaddingProperty,new Binding("Padding"){RelativeSource=new RelativeSource(RelativeSourceMode.TemplatedParent)});border.AppendChild(new FrameworkElementFactory(typeof(ContentPresenter)));style.Setters.Add(new Setter(Control.TemplateProperty,new ControlTemplate(typeof(ListBoxItem)){VisualTree=border}));var over=new Trigger{Property=UIElement.IsMouseOverProperty,Value=true};over.Setters.Add(new Setter(Control.BackgroundProperty,PetPalette.Brush(PetPalette.Dark?PetPalette.Hex("#39343F"):PetPalette.Hex("#EEEAF5"))));style.Triggers.Add(over);var selected=new Trigger{Property=ListBoxItem.IsSelectedProperty,Value=true};selected.Setters.Add(new Setter(Control.BackgroundProperty,purple.Clone()));selected.Setters.Add(new Setter(Control.ForegroundProperty,Brushes.White));style.Triggers.Add(selected);categoryList.ItemContainerStyle=style;}
  void BuildAccessibility(TabControl tabs){var page=Page(tabs,"无障碍");TitleText(page,"动态效果与操作区域");Check(page,"减少动态效果（关闭淡入、缩放和自动动作）",pet.Settings.ReduceMotion,delegate(bool v){pet.Settings.ReduceMotion=v;pet.ApplySettings();});Check(page,"使用更大的工具栏与音乐按钮触控区域",pet.Settings.LargeTouchTargets,delegate(bool v){pet.Settings.LargeTouchTargets=v;pet.ApplySettings();});Check(page,"自动走动避让鼠标，操作后稍作停留",pet.Settings.AvoidCursor,delegate(bool v){pet.Settings.AvoidCursor=v;pet.ApplySettings();});page.Children.Add(Button("进入工具栏键盘操作（F6）",pet.FocusToolbar,false));page.Children.Add(Button("键盘操作音乐栏（F7）",pet.FocusMusicControls,false));Note(page,"设置内 Ctrl+F 搜索；Tab / Shift+Tab 依次聚焦；空格或 Enter 操作按钮。工具栏可用左右方向键切换，Esc 返回；F7 进入已连接的音乐栏，Tab 选择播放按钮，Esc 返回桌宠工具栏。仅在本窗口处理这些按键，不注册全局快捷键。\n减少动态效果时，自由走动暂停、自动落地直接定位，手动拖动仍可用。图片改用静态姿态，状态和播放控制照常工作。\n支持鼠标、触控板的普通点击拖动，以及 Windows 提升为鼠标事件的单指触控；高缩放下拖动阈值按 DPI 调整。物理触屏与混合 DPI 多屏仍需实际设备复测。");}
  void BuildNoticeSettings(TabControl tabs){var page=Page(tabs,"通知中心");TitleText(page,"任务与提醒");BuildNotificationExperience(page);page.Children.Add(Button("打开任务通知中心",pet.OpenNoticeCenter,true));Note(page,"查看本次运行最近的本地任务，按来源、状态和未读筛选；可单项静音或静音整个来源。ChatGPT 已加载任务也会显示状态、标题和更新时间，点击任务可跳转；其余原生通知保留 ChatGPT 入口。\n未来适配器可以注册“打开任务”动作，只有点击按钮时才执行。当前没有接入新的外部软件，不从通知文本执行命令或链接。");}
 }
}
