using System;using System.Linq;using System.Collections.Generic;using System.Windows;using System.Windows.Controls;using System.Windows.Media;
namespace KianaPet {
 public sealed partial class SettingsWindow {
  bool syncingToolbarTheme;readonly List<Action> toolbarRefresh=new List<Action>();Border toolbarStylePreview;TextBlock toolbarStyleHint;readonly List<Button> toolbarPresetButtons=new List<Button>();
  void ThemeSave(Action action){if(syncingToolbarTheme)return;action();pet.Settings.Validate();pet.Save();pet.ApplyAppearanceForSettings();UpdateToolbarStyleSettings();}
  void ThemeChoice(Panel page,string label,string[] names,Func<int> get,Action<int> set){Note(page,label);var box=new ComboBox{ItemsSource=names,SelectedIndex=get(),Padding=new Thickness(8),Margin=new Thickness(0,0,0,8)};System.Windows.Automation.AutomationProperties.SetName(box,label);box.SelectionChanged+=delegate{if(box.SelectedIndex>=0)ThemeSave(()=>set(box.SelectedIndex));};page.Children.Add(box);toolbarRefresh.Add(()=>box.SelectedIndex=get());}
  void ThemeSlider(Panel page,string label,int min,int max,Func<int> get,Action<int> set){var slider=AddSlider(page,label,min,max,get(),1,v=>ThemeSave(()=>set(v)));toolbarRefresh.Add(()=>slider.Value=get());}
  void ThemeCheck(Panel page,string label,Func<bool> get,Action<bool> set){var check=Check(page,label,get(),v=>ThemeSave(()=>set(v)));toolbarRefresh.Add(()=>check.IsChecked=get());}
  void BuildToolbarStylePage(TabControl tabs){var page=Page(tabs,"工具栏样式");TitleText(page,"工具栏配色与材质");Note(page,"音乐栏未显示时使用独立样式；显示时可跟随配色。关闭跟随后始终使用独立样式。");
   ThemeCheck(page,"音乐栏显示时，工具栏跟随音乐栏配色",()=>pet.Settings.ToolbarFollowMusic,v=>pet.Settings.ToolbarFollowMusic=v);
   TitleText(page,"独立样式 · 音乐栏隐藏时使用");
   var choices=new Grid();choices.ColumnDefinitions.Add(new ColumnDefinition());choices.ColumnDefinitions.Add(new ColumnDefinition());var materialChoices=new StackPanel{Margin=new Thickness(0,0,10,0)};var colorChoices=new StackPanel();Grid.SetColumn(colorChoices,1);choices.Children.Add(materialChoices);choices.Children.Add(colorChoices);page.Children.Add(choices);
   ThemeChoice(materialChoices,"工具栏材质",ToolbarTheme.StyleNames,()=>Array.IndexOf(ToolbarTheme.Styles,pet.Settings.ToolbarStyle),v=>pet.Settings.ToolbarStyle=ToolbarTheme.Styles[v]);ThemeChoice(colorChoices,"工具栏颜色来源",ToolbarTheme.SourceNames,()=>Array.IndexOf(ToolbarTheme.Sources,pet.Settings.ToolbarColorSource),v=>pet.Settings.ToolbarColorSource=ToolbarTheme.Sources[v]);
   toolbarStylePreview=new Border{CornerRadius=new CornerRadius(16),Padding=new Thickness(16,10,16,10),HorizontalAlignment=HorizontalAlignment.Center,MinWidth=180,Margin=new Thickness(0,14,0,10),BorderThickness=new Thickness(.65)};page.Children.Add(toolbarStylePreview);toolbarStyleHint=new TextBlock{TextWrapping=TextWrapping.Wrap,Foreground=muted,Margin=new Thickness(0,0,0,10)};page.Children.Add(toolbarStyleHint);

   var presets=new WrapPanel{Margin=new Thickness(0,6,0,12)};for(int i=0;i<ToolbarTheme.Presets.Length;i++){int selected=i;var colors=ToolbarTheme.Presets[i].Select(PetPalette.Hex).ToArray();var b=Button(ToolbarTheme.PresetNames[i],delegate{ThemeSave(delegate{pet.Settings.ToolbarPreset=selected;pet.Settings.ToolbarColorSource="preset";if(pet.Settings.ToolbarStyle=="legacy")pet.Settings.ToolbarStyle="tricolor";});},false);b.Width=132;b.Height=39;b.Background=new LinearGradientBrush(colors[0],colors[1],30);b.Foreground=PetPalette.Brush(PetPalette.Hex("#272934"));presets.Children.Add(b);toolbarPresetButtons.Add(b);}page.Children.Add(presets);
   ThemeSlider(page,"工具栏色彩强度",0,100,()=>pet.Settings.ToolbarTint,v=>pet.Settings.ToolbarTint=v);ThemeSlider(page,"工具栏底板不透明度",15,100,()=>pet.Settings.ToolbarOpacity,v=>pet.Settings.ToolbarOpacity=v);
   var detail=Fold(page,"细节：自定义颜色、方向与动态",false);var inputs=new[]{TextRow(detail,"第一色（#RRGGBB）",pet.Settings.ToolbarColor1),TextRow(detail,"第二色（#RRGGBB）",pet.Settings.ToolbarColor2),TextRow(detail,"第三色（#RRGGBB）",pet.Settings.ToolbarColor3),TextRow(detail,"手动图标色（#RRGGBB）",pet.Settings.ToolbarIconColor),TextRow(detail,"描边色（#RRGGBB）",pet.Settings.ToolbarLineColor)};var feedback=new TextBlock{Foreground=muted,TextWrapping=TextWrapping.Wrap};
   detail.Children.Add(Button("应用自定义颜色",delegate{if(inputs.Any(x=>!ToolbarTheme.IsHex(x.Text.Trim()))){feedback.Text="请填写六位十六进制色号，例如 #A4E1FF。";return;}ThemeSave(delegate{pet.Settings.ToolbarColor1=inputs[0].Text.Trim();pet.Settings.ToolbarColor2=inputs[1].Text.Trim();pet.Settings.ToolbarColor3=inputs[2].Text.Trim();pet.Settings.ToolbarIconColor=inputs[3].Text.Trim();pet.Settings.ToolbarLineColor=inputs[4].Text.Trim();pet.Settings.ToolbarColorSource="manual";if(pet.Settings.ToolbarStyle=="legacy")pet.Settings.ToolbarStyle="tricolor";});feedback.Text="已应用；手动图标色在关闭自动深浅时生效。";},false));detail.Children.Add(feedback);
   ThemeCheck(detail,"自动选择深色 / 浅色图标",()=>pet.Settings.ToolbarAutoContrast,v=>pet.Settings.ToolbarAutoContrast=v);
   ThemeChoice(detail,"渐变方向",new[]{"从左到右","从上到下","左上 → 右下","右上 → 左下"},()=>pet.Settings.ToolbarDirection,v=>pet.Settings.ToolbarDirection=v);
   ThemeCheck(detail,"渐变缓慢流动",()=>pet.Settings.ToolbarFlow,v=>pet.Settings.ToolbarFlow=v);ThemeSlider(detail,"流动一周期（秒）",5,60,()=>pet.Settings.ToolbarFlowSeconds,v=>pet.Settings.ToolbarFlowSeconds=v);ThemeSlider(detail,"玻璃雾度（底板遮盖）",0,100,()=>pet.Settings.ToolbarGlassFog,v=>pet.Settings.ToolbarGlassFog=v);
   Note(detail,"附近背景色每秒读取工具栏附近少量屏幕像素，缓慢过渡；只在工具栏可见时读取，不保存或发送画面。音乐没有封面、背景无法读取时使用所选预设。毛玻璃使用 Windows 系统背景材质；系统不支持时保留柔和半透明渐变，系统模糊半径不能独立调节。图标保持清晰。减少动态效果时停止流动。");
   page.Children.Add(Button("恢复原有简洁工具栏",()=>ThemeSave(()=>pet.Settings.ToolbarStyle="legacy"),false));UpdateToolbarStyleSettings();
  }
  void UpdateToolbarStyleSettings(){if(toolbarStylePreview==null)return;syncingToolbarTheme=true;try{foreach(var update in toolbarRefresh)update();}finally{syncingToolbarTheme=false;}
   var c=pet.Settings;var palette=ToolbarTheme.Tinted(c,ToolbarTheme.ColorsFor(c,pet.MusicCoverForAppearance,pet.ToolbarBackgroundColors),PetPalette.Dark);toolbarStylePreview.Background=c.ToolbarStyle=="legacy"?PetPalette.Brush(PetPalette.Background):ToolbarTheme.MakeBrush(c,palette,DateTime.UtcNow.TimeOfDay.TotalSeconds);toolbarStylePreview.BorderBrush=new SolidColorBrush(PetPalette.Hex(c.ToolbarLineColor)){Opacity=.4};Color inkColor=c.ToolbarStyle=="legacy"?PetPalette.Ink:ToolbarTheme.Ink(c,palette,PetPalette.Dark);var icons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Center};foreach(string name in new[]{"chat","voice","bell"}){var icon=ToolbarIcons.Create(name,inkColor);icon.Margin=new Thickness(10,0,10,0);icons.Children.Add(icon);}toolbarStylePreview.Child=icons;
   toolbarStyleHint.Text="当前实际工具栏："+(pet.ToolbarFollowingMusic?"跟随显示中的音乐栏":"使用独立样式")+"。上方预览展示独立样式。\n"+(c.ToolbarStyle=="legacy"?"原有样式；下方独立配色在切换材质后生效。":"底板与图标配色预览；实际通知角标保持蓝、绿等语义色。")+(c.ToolbarStyle=="glass"?"\n预览展示色层；实际毛玻璃请悬停桌宠查看。"+pet.ToolbarMaterialStatus:"");
   for(int i=0;i<toolbarPresetButtons.Count;i++){var b=toolbarPresetButtons[i];var colors=ToolbarTheme.Presets[i].Select(PetPalette.Hex).ToArray();b.Background=new LinearGradientBrush(colors[0],colors[1],30);b.Foreground=PetPalette.Brush(PetPalette.Hex("#272934"));b.BorderThickness=new Thickness(c.ToolbarColorSource=="preset"&&c.ToolbarPreset==i?2:1);b.BorderBrush=c.ToolbarColorSource=="preset"&&c.ToolbarPreset==i?purple:PetPalette.Brush(PetPalette.Line);}
  }
 }
 public sealed partial class PetWindow {public void ApplyAppearanceForSettings(){toolbarThemeKey="";ApplyAppearance();UpdateToolbarTheme(clock.Elapsed.TotalSeconds);}}
}
