using System;using System.Diagnostics;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Threading;
namespace KianaPet {
 public sealed partial class SettingsWindow {
  void BuildLyricMotionSettings(Panel page){
   TitleText(page,"长歌词滚动");Note(page,"短句保持居中。按本句进度会利用当前句与下一句的时间匀速滚动，不是逐字卡拉 OK；缺少有效时间时使用往返滚动。减少动态效果时保持静态。");
   var modes=new ComboBox{ItemsSource=new[]{"往返滚动 · 到底停留后返回","单向滚动 · 到底停住，换句再开始","按本句播放进度 · 不往回","不滚动 · 超出部分省略"},SelectedIndex=Array.IndexOf(LyricMotionRules.Modes,pet.Settings.MusicLyricScroll),Padding=new Thickness(8,5,8,5),Margin=new Thickness(0,4,8,8)};page.Children.Add(modes);
   var speed=NumberRow(page,"普通滚动速度（逻辑像素／秒，15–120）",pet.Settings.MusicLyricSpeed);
   var start=LyricSecondsRow(page,"句首停留（秒，0–10）",pet.Settings.MusicLyricStartHold/1000d);
   var end=LyricSecondsRow(page,"到底后多久返回（秒，0–10，仅往返）",pet.Settings.MusicLyricEndHold/1000d);
   Note(page,"速度和句首停留用于普通往返／单向模式；按本句进度时由歌词时长决定。单向模式到末尾后一直保留，直到下一句。鼠标停在歌词上仍可查看全文。");
   var feedback=CompanionControls.Text("调整后可先看下方示例，点击保存才应用到音乐栏。",12);var sampleConfig=PreferenceTransfer.Copy(pet.Settings);
   var row=new Grid{Height=24,ClipToBounds=true,Margin=new Thickness(12,10,12,10)};var canvas=new Canvas();var text=new TextBlock{Text="沿着窗边的微光慢慢走过，把今天没说完的小故事轻轻唱给你听。",FontSize=12,Foreground=ink};var offset=new TranslateTransform();text.RenderTransform=offset;canvas.Children.Add(text);row.Children.Add(canvas);var presenter=new LyricMotionPresenter(row,text,offset);
   var card=new Border{CornerRadius=new CornerRadius(PetVisuals.SurfaceRadius),Background=PetPalette.Brush(PetPalette.Background),BorderBrush=PetPalette.Brush(PetPalette.Line),BorderThickness=new Thickness(1),MaxWidth=400,HorizontalAlignment=HorizontalAlignment.Stretch,Child=row};page.Children.Add(card);
   var clock=new Stopwatch();bool playing=true;var timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(100)};
   Func<bool> read=delegate{int n;double a,b;if(modes.SelectedIndex<0||!int.TryParse(speed.Text,out n)||n<15||n>120||!double.TryParse(start.Text,out a)||!double.TryParse(end.Text,out b)||!MusicReactions.Finite(a)||!MusicReactions.Finite(b)||a<0||a>10||b<0||b>10){feedback.Text="速度请输入15–120，停留时间请输入0–10秒。";return false;}sampleConfig.MusicLyricScroll=LyricMotionRules.Modes[modes.SelectedIndex];sampleConfig.MusicLyricSpeed=n;sampleConfig.MusicLyricStartHold=(int)Math.Round(a*1000);sampleConfig.MusicLyricEndHold=(int)Math.Round(b*1000);return true;};
   Action draw=delegate{double seconds=clock.Elapsed.TotalSeconds;presenter.Update(sampleConfig,playing,new LyricCue{Text=text.Text,Key="preview:"+(int)(seconds/14),Start=0,End=14,Position=seconds%14,SampleAt=DateTime.UtcNow},MotionSettings.Enabled);};
   var actions=new WrapPanel();var play=Button("暂停示例",delegate{playing=!playing;if(playing)clock.Start();else clock.Stop();draw();},false);play.Click+=delegate{play.Content=playing?"暂停示例":"播放示例";};actions.Children.Add(play);actions.Children.Add(Button("重新试播",delegate{if(read()){presenter.Stop();clock.Restart();playing=true;play.Content="暂停示例";draw();}},false));actions.Children.Add(Button("保存歌词滚动设置",delegate{if(!read())return;pet.Settings.MusicLyricScroll=sampleConfig.MusicLyricScroll;pet.Settings.MusicLyricSpeed=sampleConfig.MusicLyricSpeed;pet.Settings.MusicLyricStartHold=sampleConfig.MusicLyricStartHold;pet.Settings.MusicLyricEndHold=sampleConfig.MusicLyricEndHold;pet.ApplySettings();feedback.Text="已保存并应用到音乐栏；示例不会控制音乐播放器。";},true));page.Children.Add(actions);page.Children.Add(feedback);
   Action edited=delegate{end.IsEnabled=modes.SelectedIndex==0;speed.IsEnabled=start.IsEnabled=modes.SelectedIndex==0||modes.SelectedIndex==1;if(read()){clock.Restart();playing=true;play.Content="暂停示例";presenter.Stop();draw();}};
   modes.SelectionChanged+=delegate{edited();};speed.TextChanged+=delegate{edited();};start.TextChanged+=delegate{edited();};end.TextChanged+=delegate{edited();};timer.Tick+=delegate{draw();};card.IsVisibleChanged+=delegate{if(card.IsVisible){if(playing)clock.Start();timer.Start();draw();}else{timer.Stop();clock.Stop();presenter.Stop();}};Closed+=delegate{timer.Stop();clock.Stop();presenter.Stop();};end.IsEnabled=modes.SelectedIndex==0;speed.IsEnabled=start.IsEnabled=modes.SelectedIndex<2;
  }
  TextBox LyricSecondsRow(Panel page,string label,double value){var row=new Grid{Margin=new Thickness(0,3,8,3)};row.ColumnDefinitions.Add(new ColumnDefinition());row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(90)});row.Children.Add(new TextBlock{Text=label,TextWrapping=TextWrapping.Wrap,VerticalAlignment=VerticalAlignment.Center});var box=new TextBox{Text=value.ToString("0.0"),Padding=new Thickness(7,5,7,5)};Grid.SetColumn(box,1);row.Children.Add(box);page.Children.Add(row);return box;}
 }
}
