using System;using System.Linq;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;
namespace KianaPet {
 public sealed partial class SettingsWindow {
  bool sortingCategories,draggingCategory;string categoryDragName,lastCategoryOrder="";Point categoryDragStart;DateTime categoryScrollAt;ListBoxItem categoryDropItem;Button sortCategories,moveCategoryUp,moveCategoryDown,resetCategoryOrder;StackPanel categorySortTools;TextBlock categorySortHint;
  const string CategoryDragFormat="KianaPet.SettingsCategory";
  string[] CategoryOrder(){return SettingsCategoryOrder.Resolve(pet.Settings.SettingsCategoryOrder,settingsTabs.Items.Cast<TabItem>().Select(t=>(string)t.Header));}
  void BuildSidebar(DockPanel sidebar){
   var bottom=new StackPanel{Margin=new Thickness(0,8,14,0)};DockPanel.SetDock(bottom,Dock.Bottom);sidebar.Children.Add(bottom);
   sortCategories=Button("调整顺序",delegate{SetCategorySorting(!sortingCategories);},false);sortCategories.Padding=new Thickness(8,6,8,6);sortCategories.Margin=new Thickness(0);bottom.Children.Add(sortCategories);
   categorySortTools=new StackPanel{Visibility=Visibility.Collapsed};var actions=new Grid{Margin=new Thickness(0,6,0,0)};actions.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(40)});actions.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(40)});actions.ColumnDefinitions.Add(new ColumnDefinition());
   moveCategoryUp=Button("↑",delegate{MoveSelectedCategory(-1);},false);moveCategoryDown=Button("↓",delegate{MoveSelectedCategory(1);},false);Grid.SetColumn(moveCategoryDown,1);foreach(var b in new[]{moveCategoryUp,moveCategoryDown}){b.Padding=new Thickness(4,5,4,5);b.Margin=new Thickness(0,0,3,0);b.FontSize=11;actions.Children.Add(b);}moveCategoryUp.ToolTip="上移所选分类（Alt + ↑）";moveCategoryDown.ToolTip="下移所选分类（Alt + ↓）";System.Windows.Automation.AutomationProperties.SetName(moveCategoryUp,"上移所选分类");System.Windows.Automation.AutomationProperties.SetName(moveCategoryDown,"下移所选分类");categorySortTools.Children.Add(actions);
   resetCategoryOrder=Button("恢复推荐顺序",ResetCategoryOrder,false);resetCategoryOrder.FontSize=11;resetCategoryOrder.Padding=new Thickness(3,5,3,5);resetCategoryOrder.Margin=new Thickness(0);Grid.SetColumn(resetCategoryOrder,2);actions.Children.Add(resetCategoryOrder);categorySortHint=new TextBlock{Text="拖动排序 · 自动保存",Foreground=muted,FontSize=11,LineHeight=19,Margin=new Thickness(0,7,0,0)};categorySortTools.Children.Add(categorySortHint);bottom.Children.Add(categorySortTools);
   categoryList.AllowDrop=true;categoryList.PreviewMouseLeftButtonDown+=CategoryPointerDown;categoryList.PreviewMouseMove+=CategoryPointerMove;categoryList.PreviewMouseLeftButtonUp+=delegate{categoryDragName=null;};categoryList.DragOver+=CategoryDragOver;categoryList.Drop+=CategoryDrop;categoryList.DragLeave+=delegate{ClearCategoryDrop();};
   categoryList.PreviewKeyDown+=delegate(object sender,KeyEventArgs e){if(sortingCategories&&Keyboard.Modifiers==ModifierKeys.Alt&&(e.SystemKey==Key.Up||e.SystemKey==Key.Down||e.Key==Key.Up||e.Key==Key.Down)){MoveSelectedCategory(e.SystemKey==Key.Up||e.Key==Key.Up?-1:1);e.Handled=true;}};
   sidebar.Children.Add(categoryList);
  }
  void SetCategorySorting(bool value){sortingCategories=value&&string.IsNullOrWhiteSpace(SearchQuery);categoryDragName=null;ClearCategoryDrop();RefreshSearch();UpdateCategorySorting();}
  void UpdateCategorySorting(){if(sortCategories==null)return;bool searching=!string.IsNullOrWhiteSpace(SearchQuery);sortCategories.IsEnabled=!searching;sortCategories.ToolTip=searching?"清空搜索后可调整完整分类顺序":"拖动分类或使用上移、下移按钮，自动保存";sortCategories.Content=sortingCategories?"完成排序":"调整顺序";categorySortTools.Visibility=sortingCategories?Visibility.Visible:Visibility.Collapsed;int i=categoryList.SelectedIndex;moveCategoryUp.IsEnabled=i>0;moveCategoryDown.IsEnabled=i>=0&&i<categoryList.Items.Count-1;resetCategoryOrder.IsEnabled=pet.Settings.SettingsCategoryOrder.Length>0;}
  void SaveCategoryOrder(string[] order){pet.Settings.SettingsCategoryOrder=SettingsCategoryOrder.Normalize(order);pet.Save();RefreshSearch();var selected=categoryList.SelectedItem as ListBoxItem;if(selected!=null){categoryList.ScrollIntoView(selected);selected.Focus();}UpdateCategorySorting();}
  void ResetCategoryOrder(){SaveCategoryOrder(new string[0]);}
  void MoveSelectedCategory(int delta){if(!sortingCategories||!string.IsNullOrWhiteSpace(SearchQuery))return;var order=CategoryOrder();string name=ActiveCategory;int index=Array.IndexOf(order,name),target=index+delta;if(index<0||target<0||target>=order.Length)return;SaveCategoryOrder(SettingsCategoryOrder.Move(order,name,order[target],delta>0));}
  void ReorderCategory(string name,string target,bool after){if(!sortingCategories||!string.IsNullOrWhiteSpace(SearchQuery))return;var order=CategoryOrder();var next=SettingsCategoryOrder.Move(order,name,target,after);if(!next.SequenceEqual(order))SaveCategoryOrder(next);}
  ListBoxItem CategoryItem(object source){var element=source as DependencyObject;return element==null?null:ItemsControl.ContainerFromElement(categoryList,element) as ListBoxItem;}
  void CategoryPointerDown(object sender,MouseButtonEventArgs e){categoryDragName=null;if(!sortingCategories)return;var item=CategoryItem(e.OriginalSource);if(item==null)return;categoryDragName=(string)((TabItem)item.Tag).Header;categoryDragStart=e.GetPosition(categoryList);}
  void CategoryPointerMove(object sender,MouseEventArgs e){if(categoryDragName==null||draggingCategory||e.LeftButton!=MouseButtonState.Pressed)return;var point=e.GetPosition(categoryList);if(Math.Abs(point.X-categoryDragStart.X)<SystemParameters.MinimumHorizontalDragDistance&&Math.Abs(point.Y-categoryDragStart.Y)<SystemParameters.MinimumVerticalDragDistance)return;string name=categoryDragName;draggingCategory=true;try{DragDrop.DoDragDrop(categoryList,new DataObject(CategoryDragFormat,name),DragDropEffects.Move);}finally{draggingCategory=false;categoryDragName=null;ClearCategoryDrop();RefreshRecent();}e.Handled=true;}
  bool ValidCategoryDrag(DragEventArgs e){return draggingCategory&&sortingCategories&&string.IsNullOrWhiteSpace(SearchQuery)&&e.Data.GetDataPresent(CategoryDragFormat)&&Convert.ToString(e.Data.GetData(CategoryDragFormat))==categoryDragName;}
  void ClearCategoryDrop(){if(categoryDropItem!=null){categoryDropItem.BorderBrush=Brushes.Transparent;categoryDropItem=null;}}
  void CategoryDragOver(object sender,DragEventArgs e){e.Effects=DragDropEffects.None;e.Handled=true;ClearCategoryDrop();if(!ValidCategoryDrag(e))return;var item=CategoryItem(e.OriginalSource);if(item!=null){e.Effects=DragDropEffects.Move;categoryDropItem=item;item.BorderBrush=purple;item.BorderThickness=e.GetPosition(item).Y>item.ActualHeight/2?new Thickness(0,0,0,2):new Thickness(0,2,0,0);}
   if(DateTime.UtcNow-categoryScrollAt>TimeSpan.FromMilliseconds(90)){var scroll=FindCategoryScroll(categoryList);if(scroll!=null){double y=e.GetPosition(categoryList).Y;if(y<26)scroll.LineUp();else if(y>categoryList.ActualHeight-26)scroll.LineDown();}categoryScrollAt=DateTime.UtcNow;}
  }
  static ScrollViewer FindCategoryScroll(DependencyObject root){var viewer=root as ScrollViewer;if(viewer!=null)return viewer;for(int i=0;i<VisualTreeHelper.GetChildrenCount(root);i++){var found=FindCategoryScroll(VisualTreeHelper.GetChild(root,i));if(found!=null)return found;}return null;}
  void CategoryDrop(object sender,DragEventArgs e){e.Handled=true;e.Effects=DragDropEffects.None;ClearCategoryDrop();if(!ValidCategoryDrag(e))return;var item=CategoryItem(e.OriginalSource);if(item==null)return;ReorderCategory(categoryDragName,(string)((TabItem)item.Tag).Header,e.GetPosition(item).Y>item.ActualHeight/2);e.Effects=DragDropEffects.Move;}
 }
}
