using System;using System.Linq;using System.Collections.Generic;using System.Windows;using System.Windows.Controls;using System.Windows.Media;
namespace KianaPet {
 public sealed partial class SettingsWindow {
  readonly Dictionary<Expander,bool> sectionSearchState=new Dictionary<Expander,bool>();
  StackPanel Fold(Panel parent,string title,bool expanded){var body=new StackPanel{Margin=new Thickness(6,8,6,10)};var fold=new Expander{Header=title,Content=body,IsExpanded=expanded,Padding=new Thickness(12,8,12,8),Margin=new Thickness(0,5,0,6),HorizontalContentAlignment=HorizontalAlignment.Stretch};System.Windows.Automation.AutomationProperties.SetName(fold,title);parent.Children.Add(fold);return body;}
  public static IEnumerable<T> Descendants<T>(DependencyObject root) where T:DependencyObject {foreach(object obj in LogicalTreeHelper.GetChildren(root)){var child=obj as DependencyObject;if(child==null)continue;var match=child as T;if(match!=null)yield return match;foreach(var nested in Descendants<T>(child))yield return nested;}}
  void FoldSections(StackPanel page,Func<string,bool> shouldFold){var groups=Sections(page);foreach(var group in groups){var title=group.FirstOrDefault() as TextBlock;if(title==null||title.FontSize<16||!shouldFold(title.Text))continue;int index=page.Children.IndexOf(title);string label=title.Text;var body=new StackPanel{Margin=new Thickness(6,8,6,8)};foreach(var item in group){page.Children.Remove(item);if(item!=title)body.Children.Add(item);}var fold=new Expander{Header=label,Content=body,IsExpanded=false,Padding=new Thickness(12,8,12,8),Margin=new Thickness(0,5,0,6),HorizontalContentAlignment=HorizontalAlignment.Stretch};page.Children.Insert(index,fold);}}
  void ArrangeSettings(TabControl tabs){
   var music=(StackPanel)((ScrollViewer)tabs.Items.Cast<TabItem>().Single(t=>(string)t.Header=="音乐").Content).Content;
   var launch=music.Children.OfType<Button>().Single(b=>(string)b.Content=="连接网易云音乐");music.Children.Remove(launch);music.Children.Remove(musicStatus);var connect=new StackPanel();TitleText(connect,"网易云音乐连接");launch.Content="打开 / 连接网易云音乐";System.Windows.Automation.AutomationProperties.SetName(launch,"打开 / 连接网易云音乐");connect.Children.Add(launch);connect.Children.Add(musicStatus);Note(connect,"播放控制、歌曲信息与歌词共用此连接。");music.Children.Insert(0,connect);
   var help=music.Children.OfType<TextBlock>().FirstOrDefault(x=>x.Text.StartsWith("点击上方“连接网易云音乐”"));if(help!=null){music.Children.Remove(help);help.Text=help.Text.Replace("点击上方“连接网易云音乐”","点击上方“打开 / 连接网易云音乐”");Fold(connect,"连接方式与歌词说明",false).Children.Add(help);}
   var groups=Sections(music);var basic=groups.First(g=>g.FirstOrDefault() is TextBlock&&((TextBlock)g[0]).Text=="网易云音乐小卡片");int at=1;foreach(var item in basic){music.Children.Remove(item);music.Children.Insert(at++,item);}var toggles=basic.OfType<CheckBox>().ToArray();if(toggles.Length>0){int index=music.Children.IndexOf(toggles[0]);var compact=new System.Windows.Controls.Primitives.UniformGrid{Columns=2};compact.SizeChanged+=delegate{compact.Columns=compact.ActualWidth>=550?2:1;};foreach(var toggle in toggles){music.Children.Remove(toggle);compact.Children.Add(toggle);}music.Children.Insert(index,compact);}FoldSections(music,label=>label!="网易云音乐小卡片");
   var link=(StackPanel)((ScrollViewer)tabs.Items.Cast<TabItem>().Single(t=>(string)t.Header=="ChatGPT 联动").Content).Content;var open=link.Children.OfType<Button>().Single(b=>(string)b.Content=="打开 ChatGPT");var repair=link.Children.OfType<Button>().Single(b=>(string)b.Content=="检查并修复联动");link.Children.Remove(open);link.Children.Remove(repair);var actions=new WrapPanel();actions.Children.Add(open);actions.Children.Add(repair);link.Children.Insert(1,actions);link.Children.Remove(status);link.Children.Insert(2,status);
   var details=new List<UIElement>();foreach(var item in link.Children.Cast<UIElement>().ToArray()){var note=item as TextBlock;var button=item as Button;if(item==connectionHint||note!=null&&note.Text.StartsWith("点击下方")||button!=null&&(string)button.Content=="打开运行记录目录")details.Add(item);}foreach(var item in details)link.Children.Remove(item);var body=Fold(link,"连接详情与后台 Mini 说明",false);foreach(var item in details){var note=item as TextBlock;if(note!=null)note.Text=note.Text.Replace("点击下方“打开 ChatGPT”","点击上方“打开 ChatGPT”");body.Children.Add(item);}FoldSections(link,label=>label=="为未来预留");
   var appearance=(StackPanel)((ScrollViewer)tabs.Items.Cast<TabItem>().Single(t=>(string)t.Header=="外观与互动").Content).Content;appearance.Children.Insert(0,Button("工具栏配色、渐变与毛玻璃",()=>NavigateCategory("工具栏样式",""),false));
  }
  void SearchExpand(DependencyObject root,string query){foreach(var fold in Descendants<Expander>(root)){if(query.Length==0){bool old;if(sectionSearchState.TryGetValue(fold,out old)){fold.IsExpanded=old;sectionSearchState.Remove(fold);}}else if(Matches(SearchText(fold),query)){if(!sectionSearchState.ContainsKey(fold))sectionSearchState[fold]=fold.IsExpanded;fold.IsExpanded=true;}}}
 }
}
