using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;
namespace KianaPet {
 public sealed class StorageItem {public string Path,Name,Kind,Version,ProtectedReason,Signature;public long Bytes;public DateTime Changed;public bool Stable;public bool CanDelete{get{return string.IsNullOrEmpty(ProtectedReason);}}}
 public sealed class StorageDeleteResult {public List<string> Deleted=new List<string>(),Skipped=new List<string>();public long FreedBytes;}
 public static class StorageManagement {
  static readonly string[] Buckets={"managed-backups","backups","update-cache","update-jobs","setup-cache"};
  public static string Child(string root,string relative){string prefix=System.IO.Path.GetFullPath(root).TrimEnd('\\')+'\\';string path=System.IO.Path.GetFullPath(System.IO.Path.Combine(root,relative));if(!path.StartsWith(prefix,StringComparison.OrdinalIgnoreCase))throw new Exception("路径不在本机桌宠目录内。");return path;}
  static void NoLinks(string path){if((File.GetAttributes(path)&FileAttributes.ReparsePoint)!=0)throw new Exception("包含链接或重解析点，保留此项。");}
  static Tuple<long,DateTime,int> Measure(string path){NoLinks(path);if(File.Exists(path)){var f=new FileInfo(path);return Tuple.Create(f.Length,f.LastWriteTimeUtc,1);}long bytes=0;int count=0;DateTime last=Directory.GetLastWriteTimeUtc(path);var stack=new Stack<string>();stack.Push(path);while(stack.Count>0){string current=stack.Pop();NoLinks(current);count++;var directoryTime=Directory.GetLastWriteTimeUtc(current);if(directoryTime>last)last=directoryTime;foreach(string dir in Directory.GetDirectories(current)){NoLinks(dir);stack.Push(dir);}foreach(string file in Directory.GetFiles(current)){NoLinks(file);var info=new FileInfo(file);bytes+=info.Length;count++;if(info.LastWriteTimeUtc>last)last=info.LastWriteTimeUtc;}}return Tuple.Create(bytes,last,count);}
  public static long RuntimeBytes(string root){try{return Measure(Child(root,"app")).Item1;}catch{return 0;}}
  public static string Stable(string root){try{string name=File.ReadAllText(Child(root,"stable-backup.txt")).Trim();return name.Length<300?name:"";}catch{return "";}}
  public static List<StorageItem> Scan(string root,int keep,DateTime now){keep=Math.Max(1,Math.Min(10,keep));var result=new List<StorageItem>();string stable=Stable(root);foreach(string bucket in Buckets){string folder=Child(root,bucket);if(!Directory.Exists(folder))continue;NoLinks(folder);foreach(string path in Directory.GetFileSystemEntries(folder)){var row=new StorageItem{Path=path,Name=System.IO.Path.GetFileName(path),Kind=bucket,Version="",Stable=string.Equals(bucket+"/"+System.IO.Path.GetFileName(path),stable,StringComparison.OrdinalIgnoreCase)};try{var measured=Measure(path);row.Bytes=measured.Item1;row.Changed=measured.Item2;row.Signature=row.Bytes+":"+row.Changed.Ticks+":"+measured.Item3;if(bucket.Contains("backups")){row.Version=Maintenance.BackupVersion(path);if(row.Stable)row.ProtectedReason="已标记稳定版";}else if(now-row.Changed<TimeSpan.FromDays(1))row.ProtectedReason="最近 24 小时缓存，暂不清理";}catch(Exception e){row.ProtectedReason=e.Message;row.Signature="unavailable";}result.Add(row);}}
   foreach(var row in result.Where(r=>r.Kind.Contains("backups")).OrderByDescending(r=>r.Name,StringComparer.Ordinal).Take(keep))row.ProtectedReason=row.Stable?"已标记稳定版":"保留最近 "+keep+" 份备份";return result.OrderBy(r=>r.Kind).ThenByDescending(r=>r.Name).ToList();}
  public static void MarkStable(string root,StorageItem item){using(var gate=new FileStream(Child(root,"maintenance.lock"),FileMode.OpenOrCreate,FileAccess.ReadWrite,FileShare.None)){string parent=System.IO.Path.GetDirectoryName(System.IO.Path.GetFullPath(item.Path));if(!string.Equals(parent,Child(root,"managed-backups"),StringComparison.OrdinalIgnoreCase))throw new Exception("只有带运行清单的程序备份可标记为稳定版。");NoLinks(parent);Measure(item.Path);Maintenance.VerifyRuntime(System.IO.Path.Combine(item.Path,"app"));File.WriteAllText(Child(root,"stable-backup.txt"),"managed-backups/"+System.IO.Path.GetFileName(item.Path));}}
  public static StorageDeleteResult DeleteSelected(string root,IEnumerable<StorageItem> selected,int keep){var result=new StorageDeleteResult();using(var gate=new FileStream(Child(root,"maintenance.lock"),FileMode.OpenOrCreate,FileAccess.ReadWrite,FileShare.None)){
    foreach(var requested in selected){var current=Scan(root,keep,DateTime.UtcNow).FirstOrDefault(r=>string.Equals(r.Path,requested.Path,StringComparison.OrdinalIgnoreCase));if(current==null||!current.CanDelete||current.Signature!=requested.Signature){result.Skipped.Add(requested.Name+"：已变化或受到保护");continue;}string expectedParent=Child(root,current.Kind);if(!string.Equals(System.IO.Path.GetDirectoryName(System.IO.Path.GetFullPath(current.Path)),expectedParent,StringComparison.OrdinalIgnoreCase))throw new Exception("拒绝清理范围外的路径。");Child(root,current.Kind+"/"+current.Name);NoLinks(expectedParent);Measure(current.Path);try{if(Directory.Exists(current.Path))Directory.Delete(current.Path,true);else File.Delete(current.Path);result.Deleted.Add(current.Name);result.FreedBytes+=current.Bytes;}catch(Exception e){result.Skipped.Add(current.Name+"："+e.Message);}}
   }return result;}
  public static string Size(long bytes){return bytes>=1073741824?(bytes/1073741824d).ToString("0.00")+" GB":bytes>=1048576?(bytes/1048576d).ToString("0.0")+" MB":bytes>=1024?(bytes/1024d).ToString("0.0")+" KB":bytes+" B";}
 }
 public sealed class StorageWindow:Window {
  readonly PetWindow pet;readonly StackPanel rows=new StackPanel();readonly TextBlock summary=CompanionControls.Text("");readonly List<Tuple<CheckBox,StorageItem>> choices=new List<Tuple<CheckBox,StorageItem>>();bool busy;
  public StorageWindow(PetWindow owner){pet=owner;Title="琪亚娜 · 备份与缓存";Width=740;Height=700;MinWidth=520;MinHeight=460;FontFamily=new FontFamily("Microsoft YaHei UI");Background=PetPalette.Brush(PetPalette.Background);Foreground=PetPalette.Brush(PetPalette.Ink);WindowStartupLocation=WindowStartupLocation.CenterScreen;var root=new DockPanel{Margin=new Thickness(22)};var top=new StackPanel();top.Children.Add(CompanionControls.Text("备份与缓存管理",22));top.Children.Add(summary);var keepRow=new WrapPanel();keepRow.Children.Add(CompanionControls.Text("保留最近的程序备份份数："));var keep=new ComboBox{ItemsSource=Enumerable.Range(1,10),SelectedItem=pet.Settings.BackupKeepCount,Padding=new Thickness(8),Margin=new Thickness(8,0,0,0)};keep.SelectionChanged+=delegate{pet.Settings.BackupKeepCount=(int)keep.SelectedItem;pet.ApplySettings();Refresh();};keepRow.Children.Add(keep);top.Children.Add(keepRow);top.Children.Add(CompanionControls.Text("稳定版始终保留。缓存至少放置 24 小时；当前程序、配置、素材及联动会话不在清理范围。",12));var actions=new WrapPanel();actions.Children.Add(CompanionControls.Button("重新扫描",Refresh));actions.Children.Add(CompanionControls.Button("选择建议清理项",delegate{foreach(var row in choices)row.Item1.IsChecked=row.Item2.CanDelete;}));actions.Children.Add(CompanionControls.Button("永久删除所选…",Delete));top.Children.Add(actions);DockPanel.SetDock(top,Dock.Top);root.Children.Add(top);root.Children.Add(new ScrollViewer{Content=rows,VerticalScrollBarVisibility=ScrollBarVisibility.Auto});Content=root;Loaded+=delegate{Refresh();};PreviewKeyDown+=delegate(object s,System.Windows.Input.KeyEventArgs e){if(e.Key==System.Windows.Input.Key.Escape){Close();e.Handled=true;}};}
  async void Refresh(){if(busy)return;busy=true;try{summary.Text="正在读取占用情况…";var found=await Task.Run(()=>StorageManagement.Scan(Store.Root,pet.Settings.BackupKeepCount,DateTime.UtcNow));long runtime=await Task.Run(()=>StorageManagement.RuntimeBytes(Store.Root));if(!IsLoaded)return;rows.Children.Clear();choices.Clear();summary.Text="当前程序与素材 "+StorageManagement.Size(runtime)+" · 管理目录 "+StorageManagement.Size(found.Sum(r=>r.Bytes))+" · 可清理 "+StorageManagement.Size(found.Where(r=>r.CanDelete).Sum(r=>r.Bytes));foreach(var item in found){var saved=item;var panel=new StackPanel{Margin=new Thickness(0,10,0,10)};var check=new CheckBox{Content=item.Kind+" / "+item.Name+"  "+StorageManagement.Size(item.Bytes),Foreground=PetPalette.Brush(PetPalette.Ink),IsEnabled=item.CanDelete,Margin=new Thickness(0,4,0,4)};choices.Add(Tuple.Create(check,item));panel.Children.Add(check);panel.Children.Add(CompanionControls.Text((item.Version.Length>0?"版本 "+item.Version+" · ":"")+(item.CanDelete?"可清理":item.ProtectedReason),12));if(item.Kind=="managed-backups")panel.Children.Add(CompanionControls.Button(item.Stable?"当前稳定版":"标记为稳定版",delegate{try{StorageManagement.MarkStable(Store.Root,saved);Refresh();}catch(Exception e){MessageBox.Show(this,e.Message,"无法标记");}}));rows.Children.Add(panel);}if(found.Count==0)rows.Children.Add(CompanionControls.Text("当前没有可管理的备份或缓存。"));}catch(Exception e){summary.Text="扫描未完成："+e.Message;}finally{busy=false;}}
  async void Delete(){if(busy)return;var selected=choices.Where(r=>r.Item1.IsChecked==true&&r.Item2.CanDelete).Select(r=>r.Item2).ToArray();if(selected.Length==0)return;string preview=string.Join("\n",selected.Take(8).Select(r=>r.Kind+"/"+r.Name))+(selected.Length>8?"\n……":"");if(MessageBox.Show(this,"永久删除 "+selected.Length+" 项，共 "+StorageManagement.Size(selected.Sum(r=>r.Bytes))+"？此操作不能撤销。\n\n"+preview,"确认清理",MessageBoxButton.YesNo,MessageBoxImage.Question)!=MessageBoxResult.Yes)return;busy=true;try{var result=await Task.Run(()=>StorageManagement.DeleteSelected(Store.Root,selected,pet.Settings.BackupKeepCount));MessageBox.Show(this,"已删除 "+result.Deleted.Count+" 项，释放 "+StorageManagement.Size(result.FreedBytes)+(result.Skipped.Count>0?"\n保留项：\n"+string.Join("\n",result.Skipped):""),"清理结果");}catch(Exception e){MessageBox.Show(this,"未完成清理："+e.Message,"清理失败");}finally{busy=false;Refresh();}}
 }
 public sealed partial class PetWindow {
  StorageWindow storageWindow;
  public void OpenStorageManager(){if(storageWindow!=null){storageWindow.Activate();return;}storageWindow=new StorageWindow(this);storageWindow.Closed+=delegate{storageWindow=null;};storageWindow.Show();}
 }
}
