using System;using System.Windows;using System.Windows.Controls;using System.Windows.Data;using System.Windows.Media;
namespace KianaPet {
 public static class PetVisuals {
  public static readonly FontFamily Font=new FontFamily("Microsoft YaHei UI");public const double SurfaceRadius=12,ControlRadius=8;public const int ShowMs=180,HideMs=140;
  public static void Apply(FrameworkElement element,bool opaque){element.UseLayoutRounding=true;element.SnapsToDevicePixels=true;TextOptions.SetTextFormattingMode(element,TextFormattingMode.Display);TextOptions.SetTextHintingMode(element,TextHintingMode.Fixed);TextOptions.SetTextRenderingMode(element,opaque?TextRenderingMode.ClearType:TextRenderingMode.Grayscale);var control=element as Control;if(control!=null)control.FontFamily=Font;}
  public static void InstallTooltips(FrameworkElement root){var style=new Style(typeof(ToolTip));style.Setters.Add(new Setter(Control.FontFamilyProperty,Font));style.Setters.Add(new Setter(Control.FontSizeProperty,12d));style.Setters.Add(new Setter(Control.PaddingProperty,new Thickness(10,7,10,7)));style.Setters.Add(new Setter(FrameworkElement.MaxWidthProperty,340d));style.Setters.Add(new Setter(FrameworkElement.UseLayoutRoundingProperty,true));style.Setters.Add(new Setter(UIElement.SnapsToDevicePixelsProperty,true));style.Setters.Add(new Setter(TextOptions.TextFormattingModeProperty,TextFormattingMode.Display));style.Setters.Add(new Setter(Control.BackgroundProperty,PetPalette.Brush(PetPalette.Background)));style.Setters.Add(new Setter(Control.ForegroundProperty,PetPalette.Brush(PetPalette.Ink)));style.Setters.Add(new Setter(Control.BorderBrushProperty,PetPalette.Brush(PetPalette.Line)));var border=new FrameworkElementFactory(typeof(Border));border.SetValue(Border.CornerRadiusProperty,new CornerRadius(ControlRadius));border.SetValue(Border.BorderThicknessProperty,new Thickness(1));foreach(var pair in new[]{new{Property=Border.BackgroundProperty,Name="Background"},new{Property=Border.BorderBrushProperty,Name="BorderBrush"},new{Property=Border.PaddingProperty,Name="Padding"}})border.SetBinding(pair.Property,new Binding(pair.Name){RelativeSource=new RelativeSource(RelativeSourceMode.TemplatedParent)});var content=new FrameworkElementFactory(typeof(ContentPresenter));border.AppendChild(content);style.Setters.Add(new Setter(Control.TemplateProperty,new ControlTemplate(typeof(ToolTip)){VisualTree=border}));root.Resources[typeof(ToolTip)]=style;}
  public static void RoundButton(Button button){var border=new FrameworkElementFactory(typeof(Border));border.SetValue(Border.CornerRadiusProperty,new CornerRadius(ControlRadius));foreach(var pair in new[]{new{Property=Border.BackgroundProperty,Name="Background"},new{Property=Border.BorderBrushProperty,Name="BorderBrush"},new{Property=Border.BorderThicknessProperty,Name="BorderThickness"},new{Property=Border.PaddingProperty,Name="Padding"}})border.SetBinding(pair.Property,new Binding(pair.Name){RelativeSource=new RelativeSource(RelativeSourceMode.TemplatedParent)});var content=new FrameworkElementFactory(typeof(ContentPresenter));content.SetValue(FrameworkElement.HorizontalAlignmentProperty,HorizontalAlignment.Center);content.SetValue(FrameworkElement.VerticalAlignmentProperty,VerticalAlignment.Center);border.AppendChild(content);var template=new ControlTemplate(typeof(Button)){VisualTree=border};var disabled=new Trigger{Property=UIElement.IsEnabledProperty,Value=false};disabled.Setters.Add(new Setter(UIElement.OpacityProperty,.45));template.Triggers.Add(disabled);button.Template=template;Apply(button,true);}
 }
}
