using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Controls.Primitives;using System.Windows.Input;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Threading;using KianaPet;
class NotificationPreviewTests {
 static readonly List<string> checks=new List<string>();static void Check(bool value,string name){if(!value)throw new Exception(name);checks.Add(name);}static object Field(object value,string name){return value.GetType().GetField(name,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(value);}static object Call(object value,string name,params object[] args){return value.GetType().GetMethod(name,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(value,args);}
 static void Capture(FrameworkElement element,string name,int dpi){element.UpdateLayout();var b=new RenderTargetBitmap((int)Math.Ceiling(element.ActualWidth*dpi/96d),(int)Math.Ceiling(element.ActualHeight*dpi/96d),dpi,dpi,PixelFormats.Pbgra32);var drawing=new DrawingVisual();using(var dc=drawing.RenderOpen()){dc.DrawRectangle(new VisualBrush(element),null,new Rect(0,0,element.ActualWidth,element.ActualHeight));}b.Render(drawing);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(b));using(var f=File.Create(Path.Combine(Store.Root,name+".png")))encoder.Save(f);}
 [STAThread]static int Main(string[] args){Store.Root=args[0];Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false,NoticeSound=false,ToolbarPinned=true});var app=new Application{ShutdownMode=ShutdownMode.OnLastWindowClose};var pet=new PetWindow(true);bool passed=false;
 pet.Loaded+=async delegate{try{await Task.Delay(1100);((DispatcherTimer)Field(pet,"animation")).Stop();var settings=app.Windows.OfType<SettingsWindow>().Single();settings.NavigateCategory("场景与维护","仓库更新");Capture(settings,"repository-settings",144);settings.Close();
  var now=DateTime.UtcNow;pet.Settings.LinkChatGPT=true;pet.Link.Current=new BridgeState{Connected=true,AppOpen=true,CanNotifications=true,NotificationSource="main",State="running",NotificationCount=5,At=now,LastSuccessAt=now,Notices=Enumerable.Range(0,5).Select(i=>new BridgeNotice{Id="task-"+i,Title=i==0?"等待确认 · 琪亚娜桌宠更新方案":"桌宠通知浮窗与音乐联动优化 · 示例任务 "+i,State=i==0?"waiting":i<3?"running":"review",UpdatedAt=now.AddSeconds(-i)}).ToArray()};
  int invoked=0;pet.TaskNotices.RegisterAction("构建","open",delegate{invoked++;});pet.TaskNotices.Publish(new TaskNotice{Source="构建",TaskId="local",Title="本机源码构建完成",Status="succeeded",ActionId="open"});Call(pet,"UpdateToolbar",0d);var bell=(Button)Field(pet,"notificationButton");bell.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(220);
  var preview=(NoticePreview)Field(pet,"noticePreview");Check(preview.IsOpen&&preview.Pinned,"首次点击打开并固定速览");Check(!app.Windows.OfType<NoticeCenter>().Any(),"首次点击不打开完整通知中心");Check(preview.VisibleTaskCount==1&&pet.Settings.NoticePreviewWidth==420,"默认单条手机通知式横幅");
  var banner=(FrameworkElement)preview.Child;banner.UpdateLayout();Check(banner.ActualWidth==420&&banner.ActualHeight<95,"默认横幅宽高比例细长");foreach(int dpi in new[]{96,144,192})Capture(banner,"phone-banner-"+dpi,dpi);PetPalette.Dark=true;preview.Refresh();Capture(banner,"phone-banner-dark",144);PetPalette.Dark=false;
  pet.Settings.NoticePreviewCount=4;preview.Refresh();await Task.Delay(80);Check(preview.VisibleTaskCount==4,"可展示四条精简横幅");Check(NoticePreviewRows.Read(pet)[0].State=="waiting","需要处理任务优先");Check(pet.TaskNotices.Unread==1,"打开预览不标记已读");
  var cards=(Dictionary<string,QuickNoticeCard>)Field(preview,"cards");var card=cards["gpt:task-1"];pet.Link.Current.Notices[1].Title="任务标题持续更新但保留按钮与焦点";preview.Refresh();Check(ReferenceEquals(card,cards["gpt:task-1"]),"轮询复用任务卡片");
  foreach(int dpi in new[]{96,144,192})Capture((FrameworkElement)preview.Child,"notice-preview-light-"+dpi,dpi);
  PetPalette.Dark=true;preview.Refresh();Capture((FrameworkElement)preview.Child,"notice-preview-dark",144);PetPalette.Dark=false;
  pet.Link.Current=LinkResilience.KeepLast(new BridgeState{AppOpen=true,Code="timeout"},pet.Link.Current,DateTime.UtcNow,30);preview.Refresh();Check(cards.Values.Where(c=>c.Row.ChatGPT).All(c=>!c.Open.IsEnabled&&c.Row.Stale),"短暂断线保留任务并禁用跳转");Check(cards.Values.Where(c=>c.Row.ChatGPT).All(c=>((TextBlock)Field(c,"state")).Text.Contains("待同步")),"断线状态直接标在任务行");
  pet.Settings.LinkChatGPT=false;preview.Refresh();Check(preview.VisibleTaskCount==1,"停用联动后仅保留本地任务");var local=cards.Values.Single();local.Open.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(invoked==1&&pet.TaskNotices.Unread==0,"快捷打开执行注册动作并已读");
  pet.TaskNotices.Publish(new TaskNotice{Source="构建",TaskId="other",Title="等待操作",Status="waiting"});preview.Refresh();cards.Values.Single(c=>c.Row.Id=="other").Read.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(pet.TaskNotices.Unread==0,"单条已读生效");
  // The same non-blocking outside-click listener used by pet menus is wired to dismiss.
  var outside=Field(preview,"outside");Check(outside!=null,"浮窗打开时注册外部点击监听");((Action)Field(outside,"dismiss"))();Check(!preview.IsOpen&&!((DispatcherTimer)Field(preview,"timer")).IsEnabled&&Field(preview,"outside")==null,"外部点击收起并释放监听和计时器");
  pet.ShowNoticePreview(false);await Task.Delay(100);Check(!preview.Pinned,"悬停模式不固定浮窗");((DispatcherTimer)Field(preview,"timer")).Stop();typeof(NoticePreview).GetField("leaveAt",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(preview,DateTime.UtcNow.AddSeconds(-2));
  preview.Dismiss();pet.ShowNoticePreview(true);var close=(Button)Field(preview,"closeButton");close.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(!preview.IsOpen,"关闭按钮可收起");pet.ShowNoticePreview(true);((Button)Field(preview,"center")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(80);Check(!preview.IsOpen&&app.Windows.OfType<NoticeCenter>().Count()==1,"第二级入口打开完整中心并收起浮窗");app.Windows.OfType<NoticeCenter>().Single().Close();
  pet.ShowNoticePreview(true);pet.Settings.HoverToolbar=false;Call(pet,"UpdateToolbar",0d);Check(!preview.IsOpen,"关闭工具栏同步收起浮窗");
  pet.Settings.HoverToolbar=true;pet.Settings.LinkChatGPT=true;pet.Link.Current=new BridgeState{Connected=true,CanNotifications=true,NotificationSource="mini",NotificationCount=3,State="running",At=DateTime.UtcNow,LastSuccessAt=DateTime.UtcNow};pet.ShowNoticePreview(true);preview.Refresh();Check(((TextBlock)Field(preview,"summary")).Text.Contains("来源暂未提供标题"),"仅有原生数量时不编造任务内容");Check(((Button)Field(preview,"native")).IsEnabled,"无标题活动仍可进入原生通知");
  var child=(FrameworkElement)preview.Child;child.RaiseEvent(new KeyEventArgs(Keyboard.PrimaryDevice,PresentationSource.FromVisual(child),Environment.TickCount,Key.Escape){RoutedEvent=Keyboard.PreviewKeyDownEvent});Check(!preview.IsOpen,"Esc 收起固定浮窗");
  pet.ShowNoticePreview(false);Call(pet,"OpenToolbarNotifications");Check(preview.Pinned,"悬停展开后的首次点击固定而非跳转");Call(pet,"OpenToolbarNotifications");Check(!preview.IsOpen,"再次点击铃铛可收起");
  pet.Settings.NoticePreviewHover=false;bell.RaiseEvent(new MouseEventArgs(Mouse.PrimaryDevice,Environment.TickCount){RoutedEvent=Mouse.MouseEnterEvent});Check(!((DispatcherTimer)Field(pet,"noticeHoverTimer")).IsEnabled,"关闭悬停后不会启动自动预览计时器");
  var oldConfig=Store.Json.Deserialize<Config>("{\"Schema\":1,\"Size\":176}");Check(oldConfig.NoticePreviewWidth==420&&oldConfig.NoticePreviewCount==1,"旧设置自动获得紧凑横幅默认值");var custom=new Config{NoticePreviewFollowMusic=true,NoticePreviewWidth=510,NoticePreviewCount=3,NoticePreviewHover=false};var imported=PreferenceTransfer.Import(PreferenceTransfer.Export(custom,false));Check(imported.NoticePreviewWidth==510&&imported.NoticePreviewCount==3&&imported.NoticePreviewFollowMusic&&!imported.NoticePreviewHover,"浮窗偏好可导出导入");custom.NoticePreviewWidth=9999;custom.NoticePreviewCount=0;custom.Validate();Check(custom.NoticePreviewWidth==560&&custom.NoticePreviewCount==1,"导入的越界尺寸和条数被限制");
  string unchanged=File.ReadAllText(Path.Combine(Store.Root,"settings.json"));var originalBridge=pet.Link.Current;string originalNotices=Store.Json.Serialize(pet.TaskNotices.Snapshot());pet.Settings.NoticePreviewCount=1;
  foreach(string state in new[]{"running","succeeded","waiting","failed","stale","multiple"}){pet.ShowNoticeTest(state);Check(preview.IsTest&&preview.IsOpen&&cards.Values.All(c=>!c.Open.IsEnabled),"测试状态可显示且不能操作真实任务："+state);Check(!((Button)Field(preview,"center")).IsEnabled,"测试不跳转真实通知中心："+state);}
  Check(ReferenceEquals(originalBridge,pet.Link.Current)&&originalNotices==Store.Json.Serialize(pet.TaskNotices.Snapshot()),"所有模拟状态不污染通知和联动");Check(unchanged==File.ReadAllText(Path.Combine(Store.Root,"settings.json")),"显示测试不修改偏好文件");
  pet.ShowNoticeTest("running");await Task.Delay(200);Capture((FrameworkElement)preview.Child,"minimal-banner",144);Check(typeof(QuickNoticeCard).GetField("time",BindingFlags.NonPublic|BindingFlags.Instance)==null&&typeof(NoticePreview).GetField("heading",BindingFlags.NonPublic|BindingFlags.Instance)==null,"横幅不再包含通知标题和更新时间控件");Check(((Button)Field(preview,"center")).Content is Image,"完整通知中心使用图标按钮");
  // Supply an in-memory cover; no music network access or real playback commands.
  MotionSettings.Reduced=true;pet.Settings.MusicEnabled=true;pet.Settings.NoticePreviewFollowMusic=true;pet.Settings.MusicTintMode="cover-gradient";pet.Settings.MusicTintStrength=100;pet.Music.Current=new MusicState{Connected=true,Id="fixture",Cover="fixture-cover",At=DateTime.UtcNow};var library=Field(pet,"musicLibrary");library.GetType().GetField("id",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(library,"id:fixture");library.GetType().GetField("coverUrl",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(library,"fixture-cover");var art=BitmapSource.Create(2,1,96,96,PixelFormats.Bgra32,null,new byte[]{80,120,240,255,230,160,90,255},8);art.Freeze();library.GetType().GetProperty("Cover").SetValue(library,art,null);preview.Refresh();var surface=(Border)Field(preview,"surface");var expected=new Border();new MusicSurfaceAppearance().Apply(expected,art,pet.Settings,true);Check(surface.Background is LinearGradientBrush&&((LinearGradientBrush)surface.Background).GradientStops[0].Color==((LinearGradientBrush)expected.Background).GradientStops[0].Color,"通知横幅与音乐栏使用相同渐变和浓度");Capture((FrameworkElement)preview.Child,"minimal-banner-music",144);pet.Settings.NoticePreviewFollowMusic=false;preview.Refresh();Check(surface.Background is SolidColorBrush&&((SolidColorBrush)surface.Background).Color==PetPalette.Background,"关闭跟随音乐配色恢复主题色");pet.Settings.NoticePreviewFollowMusic=true;pet.Music.Current.At=DateTime.UtcNow.AddSeconds(-20);preview.Refresh();Check(surface.Background is SolidColorBrush,"过期音乐状态不保留封面配色");pet.Settings.MusicEnabled=false;MotionSettings.Reduced=false;
  pet.ShowNoticePreview(true);Check(!preview.IsTest&&cards.Values.All(c=>!c.Row.Key.StartsWith("test:")),"返回铃铛后恢复真实通知");preview.Dismiss();
  pet.Settings.MusicDefaultPosition="left";pet.Settings.MusicPosition="free";pet.Settings.MusicHasPosition=true;pet.Settings.LockMusicPosition=true;pet.ResetMusicPosition();Check(pet.Settings.MusicPosition=="left"&&!pet.Settings.MusicHasPosition&&pet.Settings.LockMusicPosition,"恢复默认停靠退出自由坐标但保留拖动锁定偏好");foreach(string pos in new[]{"below","left","right"}){pet.RestoreMusicDock(pos);Check(pet.Settings.MusicPosition==pos&&!pet.Settings.MusicHasPosition,"可直接恢复停靠："+pos);}Check(Store.Load().MusicPosition=="right","恢复停靠位置保存到本机设置");var dock=new Config{MusicDefaultPosition="invalid"};dock.Validate();Check(dock.MusicDefaultPosition=="below","默认停靠位置无效时回到下方");
  pet.Settings.NoticePreviewCount=1;pet.Settings.MusicEnabled=false;pet.Settings.NoticePreviewWidth=420;pet.ShowNoticeTest("running");await Task.Delay(200);var comparisons=new StackPanel{Width=444,Background=Brushes.White};string[] labels={"图标＋应用名","只显示图标","左侧大图标＋右侧内容","纯文字应用名"};int styleIndex=0;
  foreach(string style in NoticeSourceIcons.Styles){pet.Settings.NoticeSourceStyle=style;preview.Refresh();await Task.Delay(60);var c=cards.Values.Single();var small=(Image)Field(c,"inlineIcon");var large=(Image)Field(c,"leadingIcon");string label=((TextBlock)Field(c,"state")).Text;Check(label.Contains("测试")&&label.Contains("进行中"),"每种样式保留测试与任务状态："+style);Check(label.Contains("ChatGPT")== (style=="icon-name"||style=="name-only"),"应用名显隐符合所选样式："+style);Check((large.Visibility==Visibility.Visible)==(style=="leading-icon")&&(small.Visibility==Visibility.Visible)==(style=="icon-name"||style=="icon-only"),"图标布局符合所选样式："+style);Check(small.ToolTip.ToString().Contains("ChatGPT")&&large.Source!=null,"隐藏名称时图标仍可识别来源："+style);Capture((FrameworkElement)preview.Child,"source-style-"+style,144);
   comparisons.Children.Add(new TextBlock{Text=labels[styleIndex++],Margin=new Thickness(12,8,0,0),FontFamily=PetVisuals.Font,FontSize=12,Foreground=Brushes.DimGray});var bitmap=new BitmapImage();bitmap.BeginInit();bitmap.CacheOption=BitmapCacheOption.OnLoad;bitmap.UriSource=new Uri(Path.Combine(Store.Root,"source-style-"+style+".png"));bitmap.EndInit();comparisons.Children.Add(new Image{Source=bitmap,Width=420,Margin=new Thickness(12,0,12,0)});
  }
  comparisons.Measure(new Size(444,double.PositiveInfinity));comparisons.Arrange(new Rect(comparisons.DesiredSize));Capture(comparisons,"source-style-comparison",144);
  pet.Settings.NoticeSourceStyle="leading-icon";PetPalette.Dark=true;preview.Refresh();await Task.Delay(380);Capture((FrameworkElement)preview.Child,"source-style-dark",192);PetPalette.Dark=false;pet.Settings.NoticeSourceStyle="icon-name";preview.Refresh();Check(NoticeSourceIcons.Resolve("unknown",false,false)!=null&&NoticeSourceIcons.Resolve("unknown",false,true).IsFrozen,"未知来源有稳定的深浅色备用图标");NoticeSourceIcons.Register("fixture-icon",art);Check(NoticeSourceIcons.Resolve("fixture-icon",false,false) is BitmapSource,"未来来源可注册对应图标");var pref=new Config{NoticeSourceStyle="leading-icon"};Check(PreferenceTransfer.Import(PreferenceTransfer.Export(pref,false)).NoticeSourceStyle=="leading-icon","标识样式可随偏好迁移");pref.NoticeSourceStyle="invalid";pref.Validate();Check(pref.NoticeSourceStyle=="icon-name","无效旧配置回退到图标加应用名");preview.Dismiss();
  // Per-machine repository bindings never enter Config/portable preferences.
  string fake=Path.Combine(Store.Root,"repo with spaces");Directory.CreateDirectory(Path.Combine(fake,".git"));Directory.CreateDirectory(Path.Combine(fake,"scripts"));Directory.CreateDirectory(Path.Combine(fake,"source"));File.WriteAllText(Path.Combine(fake,"scripts","Repository-Bootstrap.ps1"),"");File.WriteAllText(Path.Combine(fake,"source","Program.cs"),"");RepositoryUpdate.Bind(fake,Store.Root);Check(RepositoryUpdate.Find(Store.Root)==fake,"可绑定独立磁盘或含空格仓库路径");var command=RepositoryUpdate.Command(fake,Store.Root,true);Check(command.Arguments.Contains("-Mode update")&&command.Arguments.Contains("-InstallRoot \""+Store.Root+"\"")&&command.Arguments.Contains("-KeepOpen"),"按钮传递当前安装目录并保留进度窗口");Check(RepositoryUpdate.Command(fake,Store.Root,false).Arguments.Contains("-Mode build"),"构建按钮不拉取");Check(!RepositoryUpdate.Valid(Store.Root),"拒绝非仓库目录");passed=true;
 }catch(Exception e){Store.Atomic("error.json",new{error=e.ToString()});}finally{Store.Atomic("notification-preview-tests.json",new{passed,checks});foreach(var w in app.Windows.Cast<Window>().Where(w=>w!=pet).ToArray())w.Close();pet.Close();}};app.Run(pet);return passed?0:1;}
}
