using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Controls.Primitives;using System.Windows.Input;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Threading;using KianaPet;
class NotificationPreviewTests {
 static readonly List<string> checks=new List<string>();static void Check(bool value,string name){if(!value)throw new Exception(name);checks.Add(name);}static object Field(object value,string name){return value.GetType().GetField(name,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(value);}static object Call(object value,string name,params object[] args){return value.GetType().GetMethod(name,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(value,args);}
 static void Capture(FrameworkElement element,string name,int dpi){element.UpdateLayout();var b=new RenderTargetBitmap((int)Math.Ceiling(element.ActualWidth*dpi/96d),(int)Math.Ceiling(element.ActualHeight*dpi/96d),dpi,dpi,PixelFormats.Pbgra32);var drawing=new DrawingVisual();using(var dc=drawing.RenderOpen()){dc.DrawRectangle(new VisualBrush(element),null,new Rect(0,0,element.ActualWidth,element.ActualHeight));}b.Render(drawing);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(b));using(var f=File.Create(Path.Combine(Store.Root,name+".png")))encoder.Save(f);}
 [STAThread]static int Main(string[] args){Store.Root=args[0];Store.Save(new Config{Walking=false,Gravity=false,LinkChatGPT=false,MusicEnabled=false,SleepSchedule=false,IdleSleep=false,HideFullscreen=false,NoticeSound=false,ToolbarPinned=true});var app=new Application{ShutdownMode=ShutdownMode.OnLastWindowClose};var pet=new PetWindow(true);bool passed=false;
 pet.Loaded+=async delegate{try{await Task.Delay(1100);((DispatcherTimer)Field(pet,"animation")).Stop();var settings=app.Windows.OfType<SettingsWindow>().Single();settings.NavigateCategory("场景与维护","仓库更新");Capture(settings,"repository-settings",144);settings.Close();
  var now=DateTime.UtcNow;pet.Settings.LinkChatGPT=true;pet.Link.Current=new BridgeState{Connected=true,AppOpen=true,CanNotifications=true,NotificationSource="main",State="running",NotificationCount=5,At=now,LastSuccessAt=now,Notices=Enumerable.Range(0,5).Select(i=>new BridgeNotice{Id="task-"+i,Title=i==0?"等待确认 · 琪亚娜桌宠更新方案":"桌宠通知浮窗与音乐联动优化 · 示例任务 "+i,State=i==0?"waiting":i<3?"running":"review",UpdatedAt=now.AddSeconds(-i)}).ToArray()};
  int invoked=0;pet.TaskNotices.RegisterAction("构建","open",delegate{invoked++;});pet.TaskNotices.Publish(new TaskNotice{Source="构建",TaskId="local",Title="本机源码构建完成",Status="succeeded",ActionId="open"});Call(pet,"UpdateToolbar",0d);var bell=(Button)Field(pet,"notificationButton");bell.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(220);
  var preview=(NoticePreview)Field(pet,"noticePreview");Check(preview.IsOpen&&preview.Pinned,"首次点击打开并固定速览");Check(!app.Windows.OfType<NoticeCenter>().Any(),"首次点击不打开完整通知中心");Check(preview.VisibleTaskCount==1&&pet.Settings.NoticePreviewCompact&&pet.Settings.NoticePreviewWidth==420,"默认单条手机通知式横幅");
  var banner=(FrameworkElement)preview.Child;banner.UpdateLayout();Check(banner.ActualWidth==420&&banner.ActualHeight<210,"默认横幅宽高比例细长");foreach(int dpi in new[]{96,144,192})Capture(banner,"phone-banner-"+dpi,dpi);PetPalette.Dark=true;preview.Refresh();Capture(banner,"phone-banner-dark",144);PetPalette.Dark=false;
  pet.Settings.NoticePreviewCount=4;pet.Settings.NoticePreviewCompact=false;preview.Refresh();await Task.Delay(80);Check(preview.VisibleTaskCount==4,"可切换四条舒展卡片");Check(NoticePreviewRows.Read(pet)[0].State=="waiting","需要处理任务优先");Check(pet.TaskNotices.Unread==1,"打开预览不标记已读");
  var cards=(Dictionary<string,QuickNoticeCard>)Field(preview,"cards");var card=cards["gpt:task-1"];pet.Link.Current.Notices[1].Title="任务标题持续更新但保留按钮与焦点";preview.Refresh();Check(ReferenceEquals(card,cards["gpt:task-1"]),"轮询复用任务卡片");
  foreach(int dpi in new[]{96,144,192})Capture((FrameworkElement)preview.Child,"notice-preview-light-"+dpi,dpi);
  PetPalette.Dark=true;preview.Refresh();Capture((FrameworkElement)preview.Child,"notice-preview-dark",144);PetPalette.Dark=false;
  pet.Link.Current=LinkResilience.KeepLast(new BridgeState{AppOpen=true,Code="timeout"},pet.Link.Current,DateTime.UtcNow,30);preview.Refresh();Check(cards.Values.Where(c=>c.Row.ChatGPT).All(c=>!c.Open.IsEnabled&&c.Row.Stale),"短暂断线保留任务并禁用跳转");Check(((TextBlock)Field(preview,"hint")).Text.Contains("保留上次状态"),"断线说明清楚显示");
  pet.Settings.LinkChatGPT=false;preview.Refresh();Check(preview.VisibleTaskCount==1,"停用联动后仅保留本地任务");var local=cards.Values.Single();local.Open.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(invoked==1&&pet.TaskNotices.Unread==0,"快捷打开执行注册动作并已读");
  pet.TaskNotices.Publish(new TaskNotice{Source="构建",TaskId="other",Title="等待操作",Status="waiting"});preview.Refresh();cards.Values.Single(c=>c.Row.Id=="other").Read.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(pet.TaskNotices.Unread==0,"单条已读生效");
  // The same non-blocking outside-click listener used by pet menus is wired to dismiss.
  var outside=Field(preview,"outside");Check(outside!=null,"浮窗打开时注册外部点击监听");((Action)Field(outside,"dismiss"))();Check(!preview.IsOpen&&!((DispatcherTimer)Field(preview,"timer")).IsEnabled&&Field(preview,"outside")==null,"外部点击收起并释放监听和计时器");
  pet.ShowNoticePreview(false);await Task.Delay(100);Check(!preview.Pinned,"悬停模式不固定浮窗");((DispatcherTimer)Field(preview,"timer")).Stop();typeof(NoticePreview).GetField("leaveAt",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(preview,DateTime.UtcNow.AddSeconds(-2));
  preview.Dismiss();pet.ShowNoticePreview(true);var close=(Button)Field(preview,"closeButton");close.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(!preview.IsOpen,"关闭按钮可收起");pet.ShowNoticePreview(true);((Button)Field(preview,"center")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(80);Check(!preview.IsOpen&&app.Windows.OfType<NoticeCenter>().Count()==1,"第二级入口打开完整中心并收起浮窗");app.Windows.OfType<NoticeCenter>().Single().Close();
  pet.ShowNoticePreview(true);pet.Settings.HoverToolbar=false;Call(pet,"UpdateToolbar",0d);Check(!preview.IsOpen,"关闭工具栏同步收起浮窗");
  pet.Settings.HoverToolbar=true;pet.Settings.LinkChatGPT=true;pet.Link.Current=new BridgeState{Connected=true,CanNotifications=true,NotificationSource="mini",NotificationCount=3,State="running",At=DateTime.UtcNow,LastSuccessAt=DateTime.UtcNow};pet.ShowNoticePreview(true);preview.Refresh();Check(((TextBlock)Field(preview,"summary")).Text.Contains("来源暂未提供标题"),"仅有原生数量时不编造任务内容");Check(((Button)Field(preview,"native")).IsEnabled,"无标题活动仍可进入原生通知");
  var child=(FrameworkElement)preview.Child;child.RaiseEvent(new KeyEventArgs(Keyboard.PrimaryDevice,PresentationSource.FromVisual(child),Environment.TickCount,Key.Escape){RoutedEvent=Keyboard.PreviewKeyDownEvent});Check(!preview.IsOpen,"Esc 收起固定浮窗");
  pet.ShowNoticePreview(false);Call(pet,"OpenToolbarNotifications");Check(preview.Pinned,"悬停展开后的首次点击固定而非跳转");Call(pet,"OpenToolbarNotifications");Check(!preview.IsOpen,"再次点击铃铛可收起");
  pet.Settings.NoticePreviewHover=false;bell.RaiseEvent(new MouseEventArgs(Mouse.PrimaryDevice,Environment.TickCount){RoutedEvent=Mouse.MouseEnterEvent});Check(!((DispatcherTimer)Field(pet,"noticeHoverTimer")).IsEnabled,"关闭悬停后不会启动自动预览计时器");
  var oldConfig=Store.Json.Deserialize<Config>("{\"Schema\":1,\"Size\":176}");Check(oldConfig.NoticePreviewCompact&&oldConfig.NoticePreviewWidth==420&&oldConfig.NoticePreviewCount==1,"旧设置自动获得紧凑横幅默认值");var custom=new Config{NoticePreviewCompact=false,NoticePreviewWidth=510,NoticePreviewCount=3,NoticePreviewHover=false};var imported=PreferenceTransfer.Import(PreferenceTransfer.Export(custom,false));Check(imported.NoticePreviewWidth==510&&imported.NoticePreviewCount==3&&!imported.NoticePreviewCompact&&!imported.NoticePreviewHover,"浮窗偏好可导出导入");custom.NoticePreviewWidth=9999;custom.NoticePreviewCount=0;custom.Validate();Check(custom.NoticePreviewWidth==560&&custom.NoticePreviewCount==1,"导入的越界尺寸和条数被限制");
  // Per-machine repository bindings never enter Config/portable preferences.
  string fake=Path.Combine(Store.Root,"repo with spaces");Directory.CreateDirectory(Path.Combine(fake,".git"));Directory.CreateDirectory(Path.Combine(fake,"scripts"));Directory.CreateDirectory(Path.Combine(fake,"source"));File.WriteAllText(Path.Combine(fake,"scripts","Repository-Bootstrap.ps1"),"");File.WriteAllText(Path.Combine(fake,"source","Program.cs"),"");RepositoryUpdate.Bind(fake,Store.Root);Check(RepositoryUpdate.Find(Store.Root)==fake,"可绑定独立磁盘或含空格仓库路径");var command=RepositoryUpdate.Command(fake,Store.Root,true);Check(command.Arguments.Contains("-Mode update")&&command.Arguments.Contains("-InstallRoot \""+Store.Root+"\"")&&command.Arguments.Contains("-KeepOpen"),"按钮传递当前安装目录并保留进度窗口");Check(RepositoryUpdate.Command(fake,Store.Root,false).Arguments.Contains("-Mode build"),"构建按钮不拉取");Check(!RepositoryUpdate.Valid(Store.Root),"拒绝非仓库目录");passed=true;
 }catch(Exception e){Store.Atomic("error.json",new{error=e.ToString()});}finally{Store.Atomic("notification-preview-tests.json",new{passed,checks});foreach(var w in app.Windows.Cast<Window>().Where(w=>w!=pet).ToArray())w.Close();pet.Close();}};app.Run(pet);return passed?0:1;}
}
